### ISSUE TITLE
Heatmap shows aliasing artifacts when data is dense

### ISSUE THREAD

**Issue by hellochar** [plotly/plotly.js#1018]
I'm trying to render heatmaps with many thousands of points, such that there could be more than one point per screen pixel -- see:

http://codepen.io/hellochar/pen/vXdXkK 

Try zooming and notice how datapoints appear and then disappear depending on the specific zoom. I'd prefer if the visualization stayed consistent and showed the correct data at all zoom levels. Any ideas?

Thanks,
Xiaohan Zhang

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
