### ISSUE TITLE
support `rangemode="symmetric"`

### ISSUE THREAD

**Issue by ssfrr** [plotly/plotly.js#1022]
I sometimes want to make a graph where zero is in the middle, but I still want to use `autorange` rather then setting the range manually. Could there be a `rangemode` value of "symmetric" that would set the range to be `[-x, x]` where `x = max(abs(max(data), min(data)))`?

**Comment by etpinard** [comment]
Yeah, that would be nice.

Thanks for writing in!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
