### ISSUE TITLE
Cannot download as image in IE10

### ISSUE THREAD

**Issue by HenryKeen** [plotly/plotly.js#1060]
When downloading an image in IE10, it does not download and the following error is thrown:
"Object doesn't support property or method 'isView'"

The console breaks on the line:

`ArrayBuffer.IsView(t);`
https://github.com/plotly/plotly.js/blob/de6a183ca5d40e597bf224a4a0f7a069adf3f44a/src/lib/is_array.js#L15

I'm assuming I need a typedarray polyfill so I've tried a few, but none of them define the ArrayBuffer.isView function. I tried with the [typedarray polyfill by plotly](https://github.com/plotly/plotly.js/blob/master/dist/extras/typedarray.min.js) in this repo.

I'm not sure whether the error is a red-herring but either way it's not downloading the image file.

Any help would be greatly appreciated. Thanks!

**Comment by etpinard** [comment]
Thanks for writing in.

Looks like that particular console error is indeed caused by a lack-of-typed-array-support issue. You might want to look at https://github.com/plotly/plotly.js/issues/315 for the details on how to include the typed array polyfill.

That said, I very much doubt that client-side image download work in IE10 as they are currently broken on IE11 (ref https://github.com/plotly/plotly.js/issues/699).

**Comment by HenryKeen** [comment]
Thanks for your quick response. That makes perfect sense, I'll disable the download button in IE10/IE11 for now then.
