### ISSUE TITLE
CheatSheet error

### ISSUE THREAD

**Issue by FWirtz** [plotly/plotly.js#1106]
Hey

I just started using plot.ly JS by downloading the [Cheat Sheet](https://images.plot.ly/plotly-documentation/images/plotly_js_cheat_sheet.pdf) and ran into some trouble:

Under _3. A Hello World Figure_ it uses the variable `myDiv` twice in the js part, whereas the second occurence should obviously be `data` instead (see below).

I can't really find the cheatsheet code here in the repo, can you guys point me to the location (**so I can propose a PR**) or is it not on GitHub?
***
Code:
```
myDiv = document.getElementById('myDiv');
myDiv = { x: [ 1, 2, 3, 4, 5 ], y: [ 1, 2, 4, 8, 16 ] }; //bad line here, should be "data"
trace = [ data ]; //otherwise, this line wont work
(...)
```

**Comment by etpinard** [comment]
cc @cldougl @ellecj

**Comment by cldougl** [comment]
Hi @FWirtz -- thanks for pointing that out! 
I've fixed it because we don't have the cheat sheet code in our repo. In the future, if you see an issue with the documentation/examples the code can typically be found here:  [documentation repo](https://github.com/plotly/documentation/tree/source-design-merge) and it would be really awesome if you're interested in making a pr to fix it!!
