### ISSUE TITLE
Data-referenced layout images should contribute to autorange calculations

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1111]
as discovered by @alexcjohnson in https://github.com/plotly/plotly.js/pull/1110#discussion_r86576948

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/2704

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
