### ISSUE TITLE
Restyling a subset of points changes default color

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1113]
http://codepen.io/cpsievert/pen/YpzBqv

**Comment by etpinard** [comment]
That's the expected behavior. See [here](https://github.com/plotly/plotly.js/blob/8745a22e42933b48b85ae05c7daf46bc20e7726c/src/components/colorscale/make_color_scale_func.js#L69-L72).

Color array items that are non-numeric and invalid colors string (e.g. `undefined` in your example) are drawn as [`#444`](https://github.com/plotly/plotly.js/blob/master/src/components/color/attributes.js#L26).

Is the current that surprising?

**Comment by cpsievert** [comment]
Ah, I see, it is a bit surprising to me. Something about that syntax made me think you could restyle particular marks without side-effects...

**Comment by cpsievert** [comment]
On a related note, I also find this behavior surprising http://codepen.io/cpsievert/pen/dOyryr

**Comment by etpinard** [comment]
... and I'm surprised that you forgot about this restyle [q](https://github.com/plotly/plotly.js/issues/167)-[u](https://github.com/plotly/plotly.js/issues/748)-[i](https://github.com/plotly/plotly.js/issues/144#issuecomment-167864117)-[r](https://github.com/plotly/plotly.js/issues/654)-[k](https://github.com/plotly/plotly.js/issues/247)

```js
Plotly.restyle(gd, {'marker.color': [["red", "blue"]]});
```

is what you want I believe.

**Comment by cpsievert** [comment]
Thanks. The biggest reason for opening this ticket was because I wasn’t sure how to get `restyle()` to do what I wanted, but this comment fixes that
