### ISSUE TITLE
Heatmap annotation is slow.

### ISSUE THREAD

**Issue by colinfang** [plotly/plotly.js#1115]
Demo http://codepen.io/anon/pen/MbwWrO

I have a heatmap with 7 x 5 grids. It takes 200ms to do a relayout of annotations of 35 values. (2 sec if there are 350 texts).

Is there any way to speed it up?

**Comment by rreusser** [comment]
@colinfang Here's a version using a text trace instead of annotations that's visually indistinguishable but takes closer to 75-80 ms (for me) to draw the first time. After that, using animate (which now has a fast path for [text trace updates without a relayout](https://github.com/plotly/plotly.js/pull/1011)) then takes about 20-25ms (likely faster cpu time, but it's deferred to a requestAnimationFrame so perhaps it's not busy the whole time).

http://codepen.io/rsreusser/pen/zorZZL?editors=0011

It's a workaround, but maybe that helps! Of course if a corresponding heatmap redraw is required, then it may still just require a redraw. An ongoing goal is to create more of these fast paths via animate, but heatmaps aren't a top priority for this.

**Comment by etpinard** [comment]
Adding `hoverinfo: 'skip'` the scatter trace would make it even more indistinguishable from the `annotations` version.

**Comment by colinfang** [comment]
Thank you, it is indeed faster.
