### ISSUE TITLE
Carpet plots

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1179]
![image](https://cloud.githubusercontent.com/assets/6675409/20497237/6e3b14f4-aff6-11e6-9fd0-5aba929b9c5f.png)

References:

- https://www.mathworks.com/matlabcentral/fileexchange/40831-carpet-plot-toolkit/content/CarpetPlots/carpet.m
- https://en.wikipedia.org/wiki/Carpet_plot

**Comment by rreusser** [comment]
One challenge for this approach: contour lines. We need hash lines along a contour line in order to represent inequalities, which means we need to be able to construct continuous contour lines. [simplicial-complex-contour](https://github.com/mikolalysenko/simplicial-complex-contour), unless I'm wrong, needs triangle geometry in 2D and returns contour segments in cell order rather than as continuous lines.

Imagine a quad which we need to split into triangles in order to get contours. 

```
c ------- d
|  \      |
|    \    |
|      \  |
a ------- b
```

The first choice is a-b-c and b-d-c. When there's high frequency detail, this doesn't do so well:

<img width="211" alt="screen shot 2016-11-24 at 15 44 52" src="https://cloud.githubusercontent.com/assets/572717/20609717/facc9dc0-b25d-11e6-8195-550367170ebb.png">

a-d-c and a-b-d obviously gives similar results:

<img width="209" alt="screen shot 2016-11-24 at 15 44 40" src="https://cloud.githubusercontent.com/assets/572717/20609730/18e31898-b25e-11e6-9200-0d2c6f01e35c.png">

A switching function that minimizes the angle between the normals (imagining the data projecting into the third dimension) is better but not great:

<img width="205" alt="screen shot 2016-11-24 at 15 45 39" src="https://cloud.githubusercontent.com/assets/572717/20609734/33ae915c-b25e-11e6-8257-8286c64506be.png">

Okay, so next I tried splitting it into *four* triangles by taking the centroid of the coordinates and data.

```
c ------- d
| \     / |
|    O    |
| /     \ |
a ------- b
```

<img width="187" alt="screen shot 2016-11-24 at 15 43 34" src="https://cloud.githubusercontent.com/assets/572717/20609781/e22f6670-b25e-11e6-89b2-859883e34745.png">

This basically just adds a lot more noise to the contours since it's all based on linear interpolation. It does get the topology pretty good though. So at @alexcjohnson's suggestion, I filtered out the center points *after* using them to construct the geometry. Yay. This seems to work well:

<img width="203" alt="screen shot 2016-11-24 at 15 43 53" src="https://cloud.githubusercontent.com/assets/572717/20609775/d33d396c-b25e-11e6-93f4-f03e33e0346a.png">

Nothing will get it perfect when there's heavy aliasing, but this is at least way better 😄 

Current prototype at: http://rickyreusser.com/demos/carpet/

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/1595
