### ISSUE TITLE
Vertical box plots in inverted order by default

### ISSUE THREAD

**Issue by smalesys** [plotly/plotly.js#1187]
Hello,

Not really an issue here but i noticed that when you have vertical boxplots such as [here](http://codepen.io/anon/pen/JbNomX), the first to appear in the graph is actually the last one in the data array, while the legend still have the correct order.

It's not that hard to get the desired behaviour, but don't you think it would be more logical to display the boxes, from top to bottom, in the same order that in the data array by default?

**Comment by etpinard** [comment]
> but don't you think it would be more logical to display the boxes, from top to bottom,

Maybe? What do order graphing libraries do?

**Comment by zbjornson** [comment]
Agree, it's much easier to read when the bars and the legend are in the same order.

Same goes for horizontal, grouped bar charts, which are currently reversed: http://codepen.io/anon/pen/eBWdoO

> What do order graphing libraries do?

Mathematica has them in the same order:
![image](https://cloud.githubusercontent.com/assets/469365/20539876/94b8c2c4-b0ab-11e6-9eef-9dee50f80048.png)

Excel: same order:
![image](https://cloud.githubusercontent.com/assets/469365/20540088/83d8679c-b0ac-11e6-84d9-741d08f004a3.png)

**Comment by etpinard** [comment]
Thanks for the screenshots @zbjornson !

Maybe the issue here is with the `legend.traceorder` default - which feels like a less intrusive _smart default_ than reordering the `y` coordinates.

For example, for `barmode: 'stack'` bar charts, we currently make sure to reversed the trace ordering in the legend (see logic [here](https://github.com/plotly/plotly.js/blob/c13093282e9824d7e61db4a43b4c4a8bf17368fd/src/components/legend/defaults.js#L40)). Extending this to horizontal box and bar charts sounds like a good idea. 

Unfortunately, this is a breaking change. The best we can do is implement this in [`v2`](https://github.com/plotly/plotly.js/issues/420).

**Comment by zbjornson** [comment]
@smalesys I see you closed this, but is there a place where this is tracked as a request for v2 (since that's the earliest that it can be fixed)?
