### ISSUE TITLE
Support animation looping "out of the box"

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#1209]
Support more developer friendly workflow for looping animations. This has come up a couple times in other discussions as looping as a variety of use cases.

**Comment by rreusser** [comment]
Sounds good. I think carpet plots will have to take priority at the moment, but I'll figure out how to make this happen.

**Comment by spencerlawrence36** [comment]
This is a good idea- did it anything come out of it?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
