### ISSUE TITLE
Plotly.addFrames should manipulate by name/group

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1222]
For consistency with `Plotly.addTraces`, `addFrames` manipulates frames by integer index. This was a bad choice and requires digging into internal plotly data in order to sort things out. Instead there should be an interface for manipulating by name. The two choices:

- override the existing functions. it's slightly ugly to differentiate between numbers and strings in JS since `1 == '1'`, but there's probably a way to accomplish it.
- a new interface and steer people away from the current frame-related API methods

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
