### ISSUE TITLE
Set a strange timezone for image test container

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1228]
Just to make sure our tests aren't dependent on the old, local-timezone-dependent date range format (and some of them definitely still are!)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
