### ISSUE TITLE
Re-look-up slider position when the options change

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1234]
Imagine slider steps `1, 2, 3, 4, 5`. `3` is active. Step `2` is removed. You were on the third step, now you're on the second. Since we track active by index, the slider no longer reflects the correct state.

#1233 partially addressed similar concerns so that nothing breaks, but fixing this would be a nice cosmetic addition. The only downside is whether it means a full scan on every update, which starts to feel like one more straw on the camel's back with full scans on every update.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
