### ISSUE TITLE
Make sure updatemenus work when options are changed

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1235]
Sliders failed a bunch when @bpostlethwaite manipulated the options because the input events were using *closure* data that had been created before manual internal manipulation of slider steps had occurred. The simple fix is to fe-fetch the steps/buttons inside user input callbacks. #1233 fixed this for sliders. Need to:

- [ ] investigate whether it's a problem for updatemenus
- [ ] fix it if so
- [ ] apply a nice addition like #1234 to make it even better

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
