### ISSUE TITLE
canonical way to handle rapidly updating data?

### ISSUE THREAD

**Issue by mg1075** [plotly/plotly.js#1238]
I've tried to investigate some of the github issues and cannot find a definitive answer on the best way to handle data updates for a graph. (I could very well be missing an existing answer.)

1. If high volume data is coming in at a rapid rate (i.e., worst case scenario), what is the recommended way to update the graph?

2. Does the way you update a graph depend on the type of graph where the data is changing? 
Meaning, are certain update methods exclusive to certain graph types?

3. Do certain graph types not have an update method, and you simply have to redraw the whole thing?

4. Is there a _good_ example of how a graph should be updated? (I am surprised there is not an example on the plot.ly site.)

**Comment by rldotai** [comment]
That's weird, I could have sworn there was an example somewhere under the Function Reference.

The thing to use is `Plotly.extendTraces(gd, traces, indices, maxPoints)`. 
Search through the code in the repository if you want a more detailed explanation, or check the information available from [the community site](https://community.plot.ly)

[There are a few questions similar to yours on the community site](https://community.plot.ly/t/what-is-the-most-performant-way-to-update-a-graph-with-new-data/639)

[Here's a simple example](http://codepen.io/anon/pen/vgGogG?editors=1011)

In my experience this seems to be the fastest way to add new data; depending on your use case you might want to use the GL versions of the various charts (e.g., 'scattergl` instead of `scatter`).
They mostly work well ([except for a weird bug](https://github.com/plotly/plotly.js/issues/1298)) and are substantially less resource intensive.

**Comment by etpinard** [comment]
Closing. Work on https://github.com/plotly/plotly.js/issues/2358 will start in the coming days.
