### ISSUE TITLE
World calendars open items

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1241]
A couple of things that came up in #1220 that would be nice to add:

- [ ] support `dtick='Y<n>'` (for years) like we do `'M<n>'` for months. For the regular Gregorian calendar this doesn't matter, as a year is always 12 months, but for other calendars we currently hack in year ticks by assuming that if `n` is a multiple of 12 the user really meant years because that's what they do for the Gregorian calendar. We should just make explicit year ticks. Perhaps it would be nice to make other units too, like day (if we ever put back in timezones the right way, we will need this to handle 23 and 25-hour days), hour, minute (shoot, *that* should have gotten the capital M for consistency. oops), second, though the latter ones are for convenience only. See https://github.com/plotly/plotly.js/pull/1220#discussion_r91010748

- [ ] support year to date and month to date range selectors with non-Gregorian calendars. See https://github.com/plotly/plotly.js/pull/1220#discussion_r91010269

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
