### ISSUE TITLE
Zero-sized scatter markers

### ISSUE THREAD

**Issue by macleginn** [plotly/plotly.js#1270]
The reference for scatter markers states that the size property should be a “number greater than or equal to 0”, which means that I can have a zero-sized marker. However, when I enter `size: 0` in the `marker` properties I get standard-sized markers: http://fiddle.jshell.net/uax3eju6/2/

**Comment by etpinard** [comment]
Thanks for the headsup! The line in question is [here](https://github.com/plotly/plotly.js/blob/1ef50b91e97e3bfc53a856329649c858e7f0d9ec/src/components/drawing/index.js#L208-L209).

I'm not sure if changing that fallback should be considered a bug fix or a backward incompatible change and would have to wait for v2.

In any case, changing the scatter `mode` to `lines` should get you the desired result.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
