### ISSUE TITLE
Click-drag zooming does not trigger a plotly_relayout event for 'scattergl'

### ISSUE THREAD

**Issue by halfs13** [plotly/plotly.js#134]
As shown in this [JSfiddle](https://jsfiddle.net/halfs13/rdp64q7g/2/), for `type: 'scatter'` using the click-drag zoom triggers the event; for `type: 'scattergl'` doing the same does not trigger the event.

**Comment by etpinard** [comment]
You're correct. Zooming in on a `scattergl` graph does not emit `plotly_relayout`.

@halfs13 Zooming in on gl and svg graphs work differently at the moment. 

In svg, zooming modifies the `xaxis` and `yaxis` ranges to selection box and redraw the graph with the help of `Plotly.relayout`.

In gl, that operation would take much longer to perform; we try to shortcut most of the drawing logic. In other words, zooming does not call `Plotly.relayout`.

We could still emit a `plotly_relayout` event when zooming on a gl graph so that users could use hook in custom functionality, but wouldn't that be an abuse of language?

We could solve the problem by adding a `plotly_zoom` event to be emitted on both svg and gl zooms.

**Comment by halfs13** [comment]
`plotly_zoom` would be very helpful. And either the same event or something similar to trigger when panning using the pan tool.

**Comment by kevintc** [comment]
+1, I just stumbled on this issue, I'm trying to implement a callback when the user zooms on a scattergl graph and couldn't make it work. I understand why now :)

Is there any news regarding this implementation ? (either plotly_relayout or plotly_zoom would be nice). Is there any callback available when using scattergl ?

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/466
