### ISSUE TITLE
Add support for non-common (x|y)ref / a(x|y)ref combinations

### ISSUE THREAD

**Issue by SemmZemm** [plotly/plotly.js#1362]
When setting the ayref value of the annotation to "y" (the only available axis) ay is still considered to be in pixels. 

[Example on codepen](http://codepen.io/anon/pen/rjZJEp)

Clearly, ay=50 is enterpreted neither as the absolute value, nor as the relative offset, but as the value in pixels.

**Comment by etpinard** [comment]
`(x|y)ref` / `a(x|y)ref` combinations that don't have a common axis aren't support. See logic [here](https://github.com/plotly/plotly.js/blob/master/src/components/annotations/annotation_defaults.js#L66-L71) for more detail.

So, to get the `ayref` you want, you'll need to set `yref` to `'y'`.

----

I'll change the issue to reflect a feature request.

**Comment by SemmZemm** [comment]
Since @etpinard marked this as a feature, would it be possible to add support for a(x|y)ref="paper"?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
