### ISSUE TITLE
Fractional milliseconds in time series are not handled correctly. 

### ISSUE THREAD

**Issue by SemmZemm** [plotly/plotly.js#1363]
Hi, 

When I'm using scatter chart to display time series with fractional milliseconds, the fractional part is not displayed correctly. Multiple samples become one, this looks strange, for sure it's not the user expects to see on high resolution. The problem persists in all versions of plotly.js since 1.21.0. Version 1.20.5 doesn't have this problem.

Example on jsfiddle: 
[1.20.5 (expected behaviour)](https://jsfiddle.net/c1kt3r82/143/)
[1.23.0 (issue is reproduced)](https://jsfiddle.net/c1kt3r82/144/)

**Comment by etpinard** [comment]
@alexcjohnson can you comment on this?

I suspect this is a side-effect of https://github.com/plotly/plotly.js/pull/1194.

**Comment by alexcjohnson** [comment]
Yes, definitely a bug, we're clipping fractional msec because we go through native JS dates [here](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/set_convert.js#L98) and native dates do not support fractional milliseconds. Should be a fairly easy fix.

@SemmZemm - we'll fix this, but it's highly recommended to use date strings instead of millisecond numbers. If you do this, it works fine, and as a side benefit your plots will be portable across timezones.

**Comment by hidai** [comment]
@alexcjohnson, you mentioned that the precision is 100 microseconds now in [this thread](https://github.com/plotly/plotly.js/issues/420#issuecomment-293149923).
Isn't it possible to close this issue?

**Comment by alexcjohnson** [comment]
@hidai I'm afraid this bug is still open. 100 microseconds resolution works when you use date strings, but the issue here is when you provide the data as epoch milliseconds, and that still drops to 1 millisecond resolution.
