### ISSUE TITLE
Trace hover information is not related to the good trace

### ISSUE THREAD

**Issue by felixveysseyre** [plotly/plotly.js#1367]
Hello,

I am using Plotly.js (latest version) in order to plot some data generated by the [MATLAB-Online library.](https://github.com/plotly/MATLAB-Online)
For a given dataset, the label displaying the trace value is not the correct one.

I have created a [JSFiddle](https://jsfiddle.net/78cfm9de/1/) demonstrating the error.

On the example, if my mouse is at (x, y) = (-0.5, 0.45), the cursor is over the green trace but the information are displayed for the blue trace:

![capture d ecran 2017-02-09 a 13 24 55](https://cloud.githubusercontent.com/assets/4909259/22783239/353d96d6-eecb-11e6-9e42-adaa53db0b8c.png)

Thanks,

**Comment by rreusser** [comment]
By default, the [hovermode](https://plot.ly/javascript/reference/#layout-hovermode) compares multiple data points that align vertically. That doesn't catch points here since the x-coordinates are numerical and never align to within tolerance. You can set `hovermode: 'closest'` in the layout or click the icon in the corner to hover over the closest point.

<img width="340" alt="screen shot 2017-02-09 at 09 33 20" src="https://cloud.githubusercontent.com/assets/572717/22787599/dc81dfcc-eeaa-11e6-8f1f-ce86dd91d811.png">

**Comment by felixveysseyre** [comment]
@rreusser 

Thanks a lot for your answer, it solved my problem !

**Comment by rreusser** [comment]
Awesome! In the future https://community.plot.ly/ can be a good place to ask question before filing a bug report, though I'll admit some things can be a bit surprising. 😄
