### ISSUE TITLE
`showspikes` is broken on surface traces

### ISSUE THREAD

**Issue by jdugge** [plotly/plotly.js#1406]
When hovering over a surface plot, Plot.ly displays guide lines ("hover guides"?) that highlight all lines of equal x, y, or z values:

![image](https://cloud.githubusercontent.com/assets/2399255/23222657/ea0fa088-f928-11e6-93a4-30bb39e055c7.png)

[Codepen](http://codepen.io/anon/pen/qrWpRE)

We found that the z hover guides can sometimes be confusing rather than helpful, and in many cases they aren't needed for highlighting the position.

I haven't been able to find a way to disable the hover guides. Would it be possible to add a boolean for switching them off for each axis, similar to `showspikes` and `spikesides`?

**Comment by etpinard** [comment]
Nice catch. `spikesides` is working as it should (the spikes don't extend on the axis walls) when turned on. But, `showspikes` is indeed broken for `surface` traces (but is working perfectly fine for `scatter3d` traces as far as I know)

Thanks very much for this report!

**Comment by etpinard** [comment]
OK @jdugge `showspikes` doesn't remove the hover guides on surface traces by design. Sorry about the confusion.

To remove them you'll need to set 

```js
contours: {
  x: { highlight: false },
  y: { highlight: false },
  z: { highlight: false }
}
```

in your surface trace object. See example http://codepen.io/etpinard/pen/peoajB

----

I think it's fairly easy to realized that this is all very confusing so perhaps we should _merge_ the surface contour highlight and the spikes behavior into once attribute in [v2](https://github.com/plotly/plotly.js/issues/420)?

**Comment by jdugge** [comment]
Ah, amazing, that's it! Thanks, I completely missed that option. I guess because of the visual similarity to the spikes and spikesides, I didn't even consider looking in the options for the `surface` plot.

Maybe instead of merging contour highlights and spikes into a single attribute, a note in the documentation linking the two topics would already be enough?

**Comment by etpinard** [comment]
> a note in the documentation linking the two topics would already be enough

Good idea. Will be done in https://github.com/plotly/documentation/issues/702

Thanks again for the report!
