### ISSUE TITLE
Use editContainerArray for arrays in traces too

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1412]
#1403 standardizes the behavior of editing all the container arrays in `layout` - to the way it used to work just in annotations, plus a bunch of cleanup to make it more robust. We should extend this to container arrays in `data` as well.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
