### ISSUE TITLE
Alignment of horizontal grid lines and tick text is off

### ISSUE THREAD

**Issue by Kilian** [plotly/plotly.js#1434]
Visually, the tick text and the horizontal gridlines are not vertically centered, which makes the axis look slightly-off. This is already noticeable in the [line chart demos](https://plot.ly/javascript/line-charts/):
![selection_012](https://cloud.githubusercontent.com/assets/41970/23499707/7b3f63ae-ff2d-11e6-92a5-01a98fc7b2f6.png)

If you zoom in on this image, you can see it more clearly:

![selection_013](https://cloud.githubusercontent.com/assets/41970/23499750/acd3241e-ff2d-11e6-9616-31fcbd93c91c.png)

**What I would expect** is vertical alignment of the tick text (regardless of font-size) with the grid lines. In the above example, the ticks would need to be moved _2px_ up to get the following alignment (left: new position, right: overlayed on current position):

![selection_014](https://cloud.githubusercontent.com/assets/41970/23499846/0ec1aeb6-ff2e-11e6-8964-219a51778701.png) ![selection_015](https://cloud.githubusercontent.com/assets/41970/23499856/19f40a90-ff2e-11e6-8695-6d9812dbe434.png)

**Comment by etpinard** [comment]
I suspect that off-center offset is on purpose. Though it would be nice to add an axis attribute (e.g. `yaxis.ticktextoffset`) to make this configurable.

**Comment by alexcjohnson** [comment]
I don't think it's on purpose; I know that for log axes we fiddle with the positioning of individual labels (particularly to keep the small 9 from interfering with the bigger 10^n) but I suspect for linear it's just us making a poor approximation to avoid having to calculate bounding boxes individually for each tick label. I'd be happy to consider this a bug.

That said there *are* use cases for offsetting the labels - but perhaps this would be best handled as an anchor (top/middle/bottom, or left/center/right for x axes) rather than a pixel offset?

Like this Vox chart:
![screen_shot_2015-01-14_at_11 34 49_am 0](https://cloud.githubusercontent.com/assets/2678795/23520569/925fd07a-ff49-11e6-89b0-a1247992a143.png)

**Comment by alexcjohnson** [comment]
Closed by #1854

**Comment by FinnFrotscher** [comment]
<img width="883" alt="screen shot 2017-09-08 at 19 55 05" src="https://user-images.githubusercontent.com/11148454/30224624-bf69d6f8-94cf-11e7-87b8-8719be105cae.png">
i have the same issue.

**Comment by alexcjohnson** [comment]
@FinnFrotscher this issue was about alignment of tick labels with their own gridlines - which to my eye looks good in the image you posted... perhaps you're concerned about the ranges of your two y axes being mismatched? Like https://github.com/plotly/plotly.js/issues/1962 perhaps? Can you clarify what you're interested in?

**Comment by FinnFrotscher** [comment]
I am refering to the horizontal alignment of the barchart and linechart. 
the 0-line of the line is higher then the 0-line of the bars.

<img width="799" alt="screen shot 2017-09-08 at 20 19 06" src="https://user-images.githubusercontent.com/11148454/30225501-fe86aa48-94d2-11e7-8e30-091c98bcafa5.png">

**Comment by etpinard** [comment]
@FinnFrotscher see https://github.com/plotly/plotly.js/issues/1775#issuecomment-309035652 for explanations.

**Comment by alexcjohnson** [comment]
> I am refering to the horizontal alignment of the barchart and linechart. the 0-line of the line is higher then the 0-line of the bars.

That's a separate issue. You have two autoranged axes, one with bars (so it doesn't pad the axis past zero unless you have negative bars) and one with a line (so it always pads the axis vertically). If you want the right-side axis to behave like the left, you can do something like `yaxis2: {rangemode: 'tozero'}` which forces the axis autorange to reach down to zero, but also won't go past it unless there's actually negative data.

**Comment by FinnFrotscher** [comment]
thank you, my issue is resolved. sorry for posting it in the wrong issue.
