### ISSUE TITLE
Editable text should stop being edited on other interactions

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1437]
Discovered when fiddling with the legend for #1432 - if you make a plot in `{editable: true}` mode and click on some element that's editable as text (legend text, plot title, axis title, axis end), it becomes a text entry you can type in. But it doesn't go away nearly as easily as it should. As far as I can tell currently you need to either accept a new value with `<enter>`, cancel with `<esc>`, click on a different text-edit field, or click somewhere that has no interactions at all (like the outer border of the plot). But if you click or drag anywhere that has another interaction, the text entry sticks around - even if it's no longer where it should be, like if you drag the legend out from under it!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
