### ISSUE TITLE
Strange behaviour for connectgaps

### ISSUE THREAD

**Issue by CyberPK** [plotly/plotly.js#1454]
Look at http://codepen.io/anon/pen/LWxByB

Reading at https://plot.ly/javascript/reference/#scatter-connectgaps i was expecting a gaps at x=3 for the trace2. If you look at the trace1, the gap for x=3 is present, only because followed (or preceded) by a point with null value.

**Comment by rreusser** [comment]
I think you may have misinterpreted a gap as a discontinuity in the spacing of values. Plotly doesn't make assumptions about the spacing of data. A gap refers to the presence of a null value in either of the arrays.

To clarify slightly, trace 1 does not have a gap at x=3 since there is no x=3. There's a gap at the third pair in the arrays which is `(4, null)`. Since a value in that pair is null, the result is a gap that goes from the preceding point (`(2, 15)`) to the succeeding point (`(5, 17)`).

**Comment by CyberPK** [comment]
reading https://plot.ly/javascript/reference/#scatter-connectgaps a gaps is "{nan} or missing values". For this reason I was expecting that connectgaps=false would not connect points if there is a discontinuity.

Anyway, if you think this is the right behaviour, can you point me to the right solution to make the line not connected in case of discontinuity? Obviously with plotly setting, without cycling the entire dataset in search of discontinuity and manually adding a null value.

Thank you

**Comment by etpinard** [comment]
@CyberPK thanks for bringing this potential confusion to our attention.

> can you point me to the right solution to make the line not connected in case of discontinuity?

This discussion should take place on https://community.plot.ly/ so that other users can benefit from it. You may open a new ticket there.

Thanks for using plotly.js :+1:
