### ISSUE TITLE
ticklen in proportion rather than pixel format (feature request)

### ISSUE THREAD

**Issue by alanocallaghan** [plotly/plotly.js#1458]
Currently the ticklen parameter for axes takes pixels only. If it were possible to have this be a proportion of the window or plot, that would be helpful for dynamic sizing particularly using the R API.

**Comment by talgalili** [comment]
BUMP, It would be great if someone could have a look at this.
Thanks!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
