### ISSUE TITLE
bar chart is not properly setting the X axis values

### ISSUE THREAD

**Issue by rolandjitsu** [plotly/plotly.js#1485]
It seems that the bar chart plot has some issues. I made a [pen](http://codepen.io/rolandjitsu/pen/NpaJJO) to illustrate the issue. If you look at the data provided to the plot and what it renders on the **x** axis, you can see the discrepancies.

I'm not sure if the data provided is wrong, but I'd expect all the strings in `{x: [...]}` to be rendered as labels on the **x** axis, though it seems to only render 3 of them and it thinks that the entire **x** axis is a number scale.

**Comment by etpinard** [comment]
Ha I found the problem. Since you have a few numeric strings in your x data, our axis [auto-type](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axis_autotype.js) routine thinks that your data is numeric and linear (that's `xaxis.type: 'linear'`) meaning that it essentially skips the non-numeric items in your `x` arrays. This is why your graph only shows the 1,2,3 coordinates. It's worth stressing, plotly.js treats numeric strings (e.g. "3") and numbers (e.g. `3`) the same - which differs from other libraries where `"3"` can be considered a category.

So, to fix the problem, simply set `xaxis.type: 'category` in layout: http://codepen.io/etpinard/pen/oZogaq

--- 

But perhaps this example points at a problem in the auto-type routine, your `x` arrays have more categories then numeric strings. We [currently](https://github.com/plotly/plotly.js/blob/388287b09dd88634b9603a8599321ad73d95c352/src/plots/cartesian/axis_autotype.js#L58) require twice as many categories as numbers for an axis to be autotyped as `categories`. Maybe we should reduce that requirement? Unfortunately, _fixing_ this requirement would be backward incompatible and so would have to wait for `v2`.

**Comment by rolandjitsu** [comment]
@etpinard yes, that seems to be the issue and your suggestion fixes that. I hope this requirement will change in `v2` as you mentioned it.

Thanks for the help 👍

**Comment by giuliodasois** [comment]
Might be of some interest (5 May 2020). I'm using plotly version 4.6.0. I have the same problem (barchart is not setting the xaxis.ticks properly). And your solution still works fine. Thank you!
fig.update_xaxes (
  type: 'category' 
)
