### ISSUE TITLE
Incompatibility with React-Native

### ISSUE THREAD

**Issue by TomPridham** [plotly/plotly.js#1512]
Plotly is incompatible with React-Native. Trying `const Plotly = require('plotly.js/lib/core')` in a React Native project results in a `Can't find variable: document` error.

**Comment by rreusser** [comment]
React Native uses a JS engine but without any web api (the DOM, in particular), so that there simply *isn't* a web `document`. Anything that feels like the DOM is really just RN controlling the native layer via a [native bridge](https://facebook.github.io/react-native/docs/native-modules-ios.html). I wouldn't say it's *impossible*, but I would think getting all the DOM and SVG-like machinery in place for plotly to work in plain RN would probably be a project on the scale of plotly or RN itself.

A potential workaround though is using a [WebView](http://facebook.github.io/react-native/releases/0.42/docs/webview.html#webview) component. You would need to set up a [standalone static html document](http://facebook.github.io/react-native/releases/0.42/docs/webview.html#source) that includes all of plotly bundled as well as any code necessary to [receive messages](http://facebook.github.io/react-native/releases/0.42/docs/webview.html#onmessage) passed from the containing WebView component to the inner WebView context and control it via the Plotly API. A place to start would be the [react-plotlyjs](https://github.com/benjeffery/react-plotlyjs) module. You would need to add a layer of indirection to rewrite [plotly API calls](https://github.com/benjeffery/react-plotlyjs/blob/master/src/PlotlyComponent.js#L37) as *messages* which are then received and executed within the webview. On the plus side it's all be serializable json, so it should be very possible.

I haven't kept current, so I can't promise the webview's JS engine is as modern as iOS Safari's, for one, so unfortunately I can't promise this will work. A place to start though would just be dumping a html-wrapped, bundled plotly script into a webview to see what happens.

**Comment by rreusser** [comment]
Thanks for bringing up the idea, but if it's okay, I'll close this since there's no official support planned.

**Comment by TomPridham** [comment]
That's fine. I wasn't able to find anything and figured I would ask. Thanks!

**Comment by danderson00** [comment]
It's worth mentioning that the scope of work shouldn't be epic. Given that Plotly is built on D3, and D3 can just generate SVG paths, these can be fed to the react native ART library to render the SVG. There are a [few](https://medium.com/the-react-native-log/animated-charts-in-react-native-using-d3-and-art-21cd9ccf6c58) [articles](http://hswolff.com/blog/react-native-art-and-d3/) that describe the approach.

I've enjoyed using Plotly, the time it takes to produce awesome charts is very low, but I'm fairly committed to the react native approach and can't commit the time to making Plotly work. react native is exploding in popularity, don't miss the bus!
