### ISSUE TITLE
BUG: After a 'pan' restyle function doesn't color points

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1526]
Using the plotly codepen for 'click and double-click event'
http://codepen.io/plotly/pen/WoZOdq

If you click a point, it restyles the point colors. But if you 'pan' the plot and then click the point, it doesn't restyle. Only after reseting the plot does it show the point with the new color
![pan then restyle bug](https://cloud.githubusercontent.com/assets/6043499/24473026/1fba6372-1485-11e7-87e6-d1ee3c71c27c.gif)

**Comment by etpinard** [comment]
Ok interesting. Thanks for reporting. This is probably related to https://github.com/plotly/plotly.js/pull/1488 in which your restyle call doesn't trigger a per-pt `recalc`.

By restyling only `marker.color` instead of the whole `marker` container, things are appear to be working correctly: http://codepen.io/etpinard/pen/ZempLG

**Comment by etpinard** [comment]
will be fixed in https://github.com/plotly/plotly.js/pull/1536
