### ISSUE TITLE
broken transpose attribute

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#1558]
`transpose: true` doesn't seem to work for heatmaps/contours 
example: http://codepen.io/plotly/pen/728bb39cd7e9d856729ab3b83bf6834d

**Comment by alexcjohnson** [comment]
wait, @cldougl your `z` matrix is symmetric - so there's no difference when you transpose it. If I make it asymmetric it *does* change on transpose.

![screen shot 2017-04-06 at 12 19 59 am](https://cloud.githubusercontent.com/assets/2678795/24737724/d504011e-1a5e-11e7-9eb0-4da70db7a33a.png)

Perhaps the confusion arises because the heatmap shows up upside-down from the matrix? ie row 0 is on the bottom, but the columns still go left-to-right. So the transpose axis is NE/SW rather than the normal NW/SE.

**Comment by cldougl** [comment]
ahh thanks @alexcjohnson!
Rather than the NE/SW axis - I think the confusion was stemming because I started in the workspace and was trying to rotate 90 degrees w/ the the transpose attribute: 

<img width="625" alt="screen shot 2017-04-06 at 8 54 28 am" src="https://cloud.githubusercontent.com/assets/2789078/24755163/22edad60-1aa7-11e7-965e-87e51211a7a4.png">
I see that `transpose:true` does transpose the matrix, but is it correct to associate that transposition with a 90 degree rotation?

**Comment by alexcjohnson** [comment]
Right, it's really not a rotation, we should change that wording. One whole diagonal is unchanged, and the rest of the matrix is reflected about that diagonal. And it has period 2 to get back to where you start, not period 4 as a 90-degree rotation would.

**Comment by cldougl** [comment]
yep-- agreed, I'll make a little issue just to update that wording.
