### ISSUE TITLE
Images with a data URI source don't render in webkit-based browsers

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1571]
E.g., Safari, RStudio viewer:

http://codepen.io/cpsievert/pen/dvBZae

**Comment by rreusser** [comment]
Must have something to do with the way it loads it. For reference: http://codepen.io/rsreusser/pen/BWgJXQ

**Comment by etpinard** [comment]
Are there any errors in popping out in the console? If so, can you share a screenshot?

**Comment by cpsievert** [comment]
Yep, `Cross-origin image load denied by Cross-Origin Resource Sharing policy.`

**Comment by etpinard** [comment]
Possible solution http://stackoverflow.com/a/31667722/4068492

Would someone with access to Safari like to give this a shot?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
