### ISSUE TITLE
Highlight region when part of carpet axis is inverted

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1637]
See: https://github.com/plotly/plotly.js/pull/1625

It should be fairly obvious when the carpet axis is partially inverted, but I think it would be a good option to make it *very* obvious when the plot should not be used for interpretation. I propose two flags:

- `showinverted: true | false`
- `invertedcolor`

When true, a carpet axis with inverted sections will look like this:

<img width="351" alt="screen_shot_2017-04-27_at_14 48 32_720" src="https://cloud.githubusercontent.com/assets/572717/25542469/c206818a-2c20-11e7-8bac-526683322f6c.png">

This much is implemented; it just needs a bit of additional tweaking to ensure nothing is shaded when a valid axis is simply flipped. Note that it is *not* possible, generally speaking, to shade the multi-valued region itself without a significant amount of work since that region isn't encircled by the carpet axis boundary.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
