### ISSUE TITLE
Allow specification of lineheight in font objects [feature request]

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1661]
It would be useful to be able to specify the height of each line (break) in annotations/titles/scatter text etc.

As @etpinard mentioned, this might be best specified via `font.height` (or maybe `font.lineheight`)

I suppose this may lead to conflicts with `annotations[i].height`, but we could just have the latter override the former?

https://codepen.io/cpsievert/pen/wdyQxX

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
