### ISSUE TITLE
Add a way to specify height/width of annotation's bounding box

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1670]
More specifically, I'd like a way for the surrounding textbox to be independent of annotation[i].textangle, like this:

![screen shot 2017-05-10 at 6 44 21 pm](https://cloud.githubusercontent.com/assets/1365941/25926397/9c4d72a8-35b4-11e7-9fd9-dadbd3d9f3ce.png)

https://codepen.io/cpsievert/pen/eWMOWy

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
