### ISSUE TITLE
Fit for Scatter(line,poly,exp)?

### ISSUE THREAD

**Issue by r1z1a** [plotly/plotly.js#1677]
I was looking at the Scatter plot to have a best fit line, and it seems there is no way to do it without making a separate data set, and plotting an extra trace.

From https://plot.ly/python/#statistics can see there is some types of fits. 
Can this be done in plotly.js? Will there be something like this available at some point? 
Is the scatter plot line only for connecting the points in order they come?

**Comment by etpinard** [comment]
You can try looking for another library to compute the fit line and pipe the result into a plotly.js trace.

https://github.com/Tom-Alexander/regression-js looks interested but I haven't tried it myself.

Since, we probably most likely won't incorporate fitting into the library itself (a plugin though would be nice). I'll close this issue.

Thanks for writing in :beers:
