### ISSUE TITLE
Find better solution to "TOBESTRIPPED" dummy string in toSVG to handle quoted style attributes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1697]
See https://codepen.io/etpinard/pen/vmzpPy?editors=1010 and https://github.com/plotly/plotly.js/pull/1694#pullrequestreview-38774918

**Comment by etpinard** [comment]
Suggestions from @dy, use:

- https://www.npmjs.com/package/split-string-words, or
- maybe https://www.npmjs.com/package/balanced-match

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
