### ISSUE TITLE
Dependency Mapbox-gl requires outdated package

### ISSUE THREAD

**Issue by g4challenge** [plotly/plotly.js#1714]
The package requires an outdated node-zlib-backports package, which could easily be solved by changing:

`"mapbox-gl": "^0.22.0",`

to

`"mapbox-gl": "^0.37.0",`

Could anyone test if this results in breaking changes, as for my use case it worked flawlessly.

**Comment by etpinard** [comment]
Yep it's breaking our tests, see https://github.com/plotly/plotly.js/pull/1543

**Comment by eddies** [comment]
I came here via 

* #1745 (Unable to install on npm 5.0.0), which refers to 
  * #1714 (Dependency Mapbox-gl requires outdated package), which refers to 
    * #1543 (Scattermapbox BADNUM + mapbox-gl@0.33.1), which was replaced by
    * #1564 (Scattermapbox BADNUM (w/o upgrading mapbox-gl)), which has been merged

#1543 indicates that "mapbox-gl@0.33.1 does not get along with the nw.js version we use in our image test container" and "I couldn't update mapbox-gl to their latest version (v0.34.0) because that version is currently broken in browserified bundles and that patch hasn't been published yet."

But that comment was written 1 April and mapbox/mapbox-gl-js#4486 AFAIK was included in [v0.35.0](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#0350-april-7-2017).

So...is there still blocker for this? I'm not familiar with how you're testing with nw.js to try and replicate on my end.

**Comment by etpinard** [comment]
Thanks @eddies for writing in. By quickly looking at the `mapbox-gl` changelog, I don't anything that would fix its issues with the (old) `nw.js` version we use to run our image tests. So, I doubt that bumping `mapbox-gl` to `v0.35.0` would fix our issues.

>  I'm not familiar with how you're testing with nw.js to try and replicate on my end.

If you're down to try, reading through [this](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md) and [this](https://github.com/plotly/plotly.js/blob/master/test/image/README.md) should be enough to get you started. 

---

Now that `npm@5` is the npm's `latest` version, issue https://github.com/plotly/plotly.js/issues/1745 becomes very problematic for us. We're planning on improving our image test runner in the coming months, but that might be too long of a wait. I'm thinking we should fork `mapbox-gl` and publish it as `@plotly/mapbox-gl` on npm in such a way that `npm@5` does not complain when installing.

**Comment by simoneb** [comment]
I'm not sure I'm seeing the same issue but installing plotly seems to require serveral mapbox packages from github that don't exist. Any known solution to this?

**Comment by jeberst** [comment]
Since this older version of mapbox-gl is a dependency, it might be better to make a copy of it somewhere the package managers can reference.

**Comment by simoneb** [comment]
Especially because npm is wasting lots of time trying to resolve those dependencies, and in CI scenarios it's less than ideal
