### ISSUE TITLE
in version 1.4 onclick event broken

### ISSUE THREAD

**Issue by arnaudcol** [plotly/plotly.js#173]

**Comment by etpinard** [comment]
Bug confirmed (for all trace but pies, it looks like). Working on a fix now.

**Comment by etpinard** [comment]
Click events are working in `v1.3.1` http://cdn.plot.ly/plotly-1.3.1.min.js

**Comment by etpinard** [comment]
@alexcjohnson commenting out [fx.unhover](https://github.com/plotly/plotly.js/compare/v1.3.1...master#diff-c3362661b0796b176be95487fa368e39R1380) in the dragBox definition makes click events work again. 

Why did you put this in https://github.com/plotly/plotly.js/commit/b1a1c24b37ed6040ca6345ba88b118dc18968cfb ?

**Comment by etpinard** [comment]
Right. We need to clear the hover labels when starting a selection. Let's see if there's a way to make that happen on click events.

**Comment by alexcjohnson** [comment]
Ah, nuts.
> Right. We need to clear the hover labels when starting a selection.

bingo. It's nice there because that clears hover labels on ANY drag event... select, zoom, pan... but I guess the solution would be to wait until `dragged` is `true` (which gets plugged into `gd._dragged`, though at this point that's only used within the `fx.dragElement` closure so could and should be ditched in favor of a local var). I suppose either we could say hover effects should always clear when you're dragging, no matter what it is you're dragging... then we could put the `fx.unhover` call right there in `fx.dragElement` next to [`gd._dragged = true;`](https://github.com/plotly/plotly.js/blob/b1a1c24b37ed6040ca6345ba88b118dc18968cfb/src/plots/cartesian/graph_interact.js#L2038). If you don't feel comfortable with that in all cases, we could add an `options.draggedFn` (these should really be called `options.onDragged` etc shouldn't they...) to be called there.

**Comment by etpinard** [comment]
> I suppose either we could say hover effects should always clear when you're dragging, no matter what it is you're dragging...

@alexcjohnson Could you give me examples of *things that can be dragged* ?

**Comment by alexcjohnson** [comment]
```
dhcp159:plotlyjs alex$ ag dragElement
src/components/annotations/index.js
586:                Plotly.Fx.dragElement({
644:            Plotly.Fx.dragElement({

src/components/colorbar/draw.js
458:            Plotly.Fx.dragElement({

src/components/legend/index.js
531:        Plotly.Fx.dragElement({

src/plots/cartesian/graph_interact.js
1412:    fx.dragElement(dragOptions);
1992:fx.dragElement = function(options) {
```

**Comment by alexcjohnson** [comment]
I think [this](https://github.com/plotly/plotly.js/commit/026e16e3dba3a5829ac54c76daf0f955a45ae79f#commitcomment-15382678) is OK - `fx.unhover` works fine when there's no hover to begin with, and in all of those cases if for whatever reason there DID happen to be some hovertext that didn't get cleared, it would be nice to do so!

**Comment by etpinard** [comment]
@alexcjohnson thanks.

I'd vote for clearing all hover effects upon dragged. I don't see the need to add logic for annotations, legend and colorbar dragging - at least for now.
