### ISSUE TITLE
Don't make a request for geo topojson layers when no layers are visible

### ISSUE THREAD

**Issue by collioud** [plotly/plotly.js#1754]
Hello,

I noticed that when creating a scatter geo plot, the file [https://cdn.plot.ly/world_110m.json](https://cdn.plot.ly/world_110m.json) seem to be automatically requested.

Is there an option to block this call, since I mostly plot sky maps (no need for continents, etc.) ?

Thanks!
Arnaud

**Comment by etpinard** [comment]
> I mostly plot sky maps

Well that's not what `scattegeo` was designed to do. 

Maybe we should add a `scattersky` trace type :laughing:

**Comment by collioud** [comment]
☺ why not?

More seriously, it is similar to plot positions on Earth and sky positions: Right Ascension is longitude and Declination is latitude. I can provide a codepen if you are interested...

Cheers

**Comment by etpinard** [comment]
> I can provide a codepen if you are interested...

Sure, that would be nice :smile: 

----

More seriously, we could add a clause so that this [block](https://github.com/plotly/plotly.js/blob/bc0e06d280be748200870da28bf48180ef5f100b/src/plots/geo/geo.js#L129-L156) is skipped when all the geo `show*` attributes are set to `false`.

This won't be a priority for us for the foreseeable future, but we'll review community PR (maybe from you, if up for a challenge) that implement this feature.

**Comment by collioud** [comment]
Here is a codepen example:
[https://codepen.io/anon/pen/MoWobY?editors=0010](https://codepen.io/anon/pen/MoWobY?editors=0010)

I have no experience in preparing PR, so if I write this one, I will need some help...
