### ISSUE TITLE
Discrete colorscales for heatmaps

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1785]
I was reading https://www.vox.com/policy-and-politics/2017/6/13/15792276/trump-obamacare-map and got annoyed by the colorbar:

![screen shot 2017-06-14 at 12 32 50 am](https://user-images.githubusercontent.com/2678795/27115492-0a8b8396-5099-11e7-984a-d166a140fae6.png)

Is "2" grey or light blue? Totally ambiguous. They need to move the labels to the middle of the corresponding color swatch. Ironically the Trump administration map, which the article so painstakingly picked apart, made it much clearer what each color means.

But I realized that, while we make discrete colorbars for contour maps (though in that case you really *do* want to place the label the boundary, and that's what we do), we actually don't have this ability with heatmaps and choropleths, we can only do continuous gradations for these types. We should support that, and perhaps even default to it when the data values are discrete like this.

**Comment by etpinard** [comment]
Referencing another down-the-road colorscale improvement https://github.com/plotly/plotly.js/issues/1747

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
