### ISSUE TITLE
Add touch event support for lasso/select drag modes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1790]
related to https://github.com/plotly/plotly.js/issues/480 and https://github.com/plotly/plotly.js/issues/1098 but of higher priority.

There a few complications that I can think of:

- Right now, _touch_ on mobile is sorta like a mousemove on desktop: it activates hover. So how would we distinguish between hover, click and select? Maybe under `layout.dragmode: 'lasso' // or 'select'` hover labels & hover/click event would be turned off on mobile and leaving only selections on _touch_.

It might be nice to review what other interactive graphing libraries out there are doing before going at it.

@dfcreative would you be interested in looking at this?

cc @jackparmer

**Comment by dfcreative** [comment]
@etpinard sure, I will have a look

**Comment by dfcreative** [comment]
@etpinard currently we don't have a toolbar on mobiles, because it shows on hover. Probably we should test if it is mobile to show toolbar always, right? Or is there an option already to make it always visible?

**Comment by dfcreative** [comment]
WIP https://github.com/dfcreative/plotly.js/tree/select-touch

**Comment by dfcreative** [comment]
@etpinard we have a problem [here](https://github.com/dfcreative/plotly.js/blob/select-touch/src/components/dragelement/index.js#L94). Turns out touch interactions cannot `touchstart` on one element and then continue `touchmove` on another element, they require to be continuous. But we create `dragcover` here once we captured mouse down.

Possible solutions

* create dragcover in select/lasso mode for mobile
* ignore dragcover and bind touch interactions to `document`

**Comment by etpinard** [comment]
> create dragcover in select/lasso mode for mobile

Creating a mobile-specific dragcover sounds like the way to go.

**Comment by dfcreative** [comment]
@etpinard should be fixed in https://github.com/plotly/plotly.js/pull/1804

**Comment by jackparmer** [comment]
Another win for crossfilter 🎉  https://github.com/plotly/plotly.js/issues/1316
