### ISSUE TITLE
Feature request: Delete all traces

### ISSUE THREAD

**Issue by NathanJAdams** [plotly/plotly.js#1838]
Situation: A variable length array of traces in a graph which all need to be removed and replaced with a new array of traces.

Current solution: Keeping track of the number of traces, then creating an array of indices every time the traces change and calling deleteTraces(graphDiv, indices) with it.

Ideal solution: What I'd love to be able to do is call deleteTraces(graphDiv) without an indices parameter which would delete all the traces. Currently it throws an error saying that the indices need to be an integer or an array of integers.

Would it be possible to add functionality to delete all the traces either like this or in some other way?

Side-note...great library btw!

**Comment by etpinard** [comment]
That's an interesting idea. It would be a breaking change though, so if we choose to forward with it, we'll have to wait to [`v2`](https://github.com/plotly/plotly.js/issues/420).

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
