### ISSUE TITLE
Possible bug with animating with a slider

### ISSUE THREAD

**Issue by DanielSBrown** [plotly/plotly.js#1839]
I am working with the feature of animating data with a slider (https://plot.ly/javascript/animations/#animating-with-a-slider). When working with it, I noticed a strange bug. When I use some data, at runtime one of my frames will be overwritten. For example, I am trying to animate three frames to have a data point move around. It works the first time around, but when I try to restart the cycle, it will no longer return to the first point. Example of the bug is found here: https://jsfiddle.net/nvr4b6ok/3/

In order to figure out what was going on or if it was my problem, I made a hardcoded object that would be equivalent to the one used in the previous JSFiddle link. This one, while equivalent in every way, does not reproduce the bug. Example found here: https://jsfiddle.net/y562yozy/

I made a third JSFiddle link that had variables for the generated frames vs. the hard-coded frames, and I show that their JSON.stingify'd versions of them are equivalent. I do that by logging their equivalency to the console. Here is the JSFiddle link: https://jsfiddle.net/32xqccah/

Additional Information: Sometimes, when I am examining the objects at runtime, the generated data object will have its first frame (the one that is not shown in subsequent animations) be overwritten with the final frame.

**Comment by rreusser** [comment]
It's a known issue that it does currently mutate the input. That's not usually a problem, but the results can be a bit surprising if the initial data and data for a particular frame are the same object (I think that's the case where this arises). The best solution to this problem is to simply clone the input. That should break the reference and prevent the original from getting overwritten.

Animation handles a lot of different use-cases so that mutating `data` was a compromise in order to avoid excessive cloning of input data. In particular, some animations are ephemeral with frames computed live, displayed, and thrown away, while others just have a fixed set of precomputed frames. One way to think of it is that what's called a "frame" could be slightly more precisely called a "changeset".

The obvious solution would be to have plotly clone the data internally, but we decided it was to avoid *always* applying that since it could require lots of extra allocation.

Apologies if the thoughts here are a bit scattered, but long story short: 1. you're right; I really don't like this behavior, 2. cloning your input object should solve it, and 3. I'll open up a ticket with what I think is maybe a good (but nontrivial) long-term solution (stateless toggleable frames)

**Comment by DanielSBrown** [comment]
Ahh, I see. I made a deep copy of the object and low and behold, your solution worked perfectly! Thank you for your help. I am new to issues on github, should I close this now as resolved or keep it open for Plotly to see and consider?

**Comment by rreusser** [comment]
Glad to hear it! This is probably the biggest gotcha to animations, IMO. The other one is `redraw: true | false` that controls whether the plot is redrawn from scratch or whether (for scatter plots only, currently) it's just a fast d3 update. With sliders, that can make the experience much more pleasant.

I've opened up #1841 to discuss a deeper solution to this issue, so maybe we can consider this one closed. 👍

**Comment by DanielSBrown** [comment]
Thanks again! Will do.
