### ISSUE TITLE
onHover on a point sharing the same x-value

### ISSUE THREAD

**Issue by atemysemicolon** [plotly/plotly.js#1840]
I am displaying a straight line, with different y values, but all x=0. I can't seem to select (the onHover marker text) a point except the lowermost or the uppermost one. I am coming from plotly python, but I am assuming the bug/feature is  on the js side of things.

**Comment by rreusser** [comment]
You might want `hovermode: 'closest'` in the layout, but it's hard to debug without a reproducible example. Also, https://community.plot.ly/ is probably the best place to ask questions so that everyone can benefit from an archived answer. Hope maybe that helps!

**Comment by etpinard** [comment]
Setting `hovermode` to `'closest'` is what you want to do here.

Arguably, even for some cartesian charts, `hovermode` should default to `'closest'` (as opposed to `'x'` or `'y'` as currently). I think this would make the most sense when all `scatter` traces have array `marker.size`. But otherwise, it might be a case of _too much magic_. This might be worth discussing in the [`v2`](https://github.com/plotly/plotly.js/issues/420) ticket.

Closing.
