### ISSUE TITLE
Per-axis separators attribute

### ISSUE THREAD

**Issue by ndabAP** [plotly/plotly.js#1842]
```javascript
var trace = {
  x: ['2000-01-30', '2000-01-31'],
  y: [1.5, 1.7],
  type: 'scatter' 
};

var data = [trace];

var layout = {
  xaxis: {
    type: 'date',
  },
  yaxis: {
    tickformat: ',.'
  },
};

Plotly.plot('myDiv', data, layout);
```
Last two axis labels are wrong and the comma format isn't applied. The problem doesn't occur when setting `layout.separators = ',.'`.

https://codepen.io/anon/pen/LLmWpm

**Comment by etpinard** [comment]
What _should_ it do? It's not obvious to me from reading the [docs](https://github.com/d3/d3-format/blob/master/README.md#locale_format).

You might be looking for [`layout.separator`](https://plot.ly/javascript/reference/#layout-separators) attribute.

**Comment by ndabAP** [comment]
@etpinard, last two axis labels should be 1,65 and 1,7 not 000000 ...

What if my x axis values should be comma decimal and my y axis should be dot decimal notation? E. G.:

x: 1.5, 1.7
y: 2.1, 2.5

should be displayed as

x: 1,5, 1,1
y: 2.1, 2.5

Is this possible?

**Comment by etpinard** [comment]
> Is this possible?

Yes, using `layout.separtors` as in https://codepen.io/etpinard/pen/awKoBP?editors=0010

**Comment by ndabAP** [comment]
@etpinard, thanks for your answer. But it seems that it is not possible to set the separators independently per axis, e. g.  `yaxis2` has a different separator than `yaxis`. Is this correct?

**Comment by etpinard** [comment]
> But it seems that it is not possible to set the separators independently per axis, e. g. yaxis2 has a different separator than yaxis. Is this correct?

That's correct. `layout.separators` is a global setting and there's no corresponding per-axis attribute.

Can I ask? Why do you different separator styles on different axes?

**Comment by ndabAP** [comment]
> Why do you different separator styles on different axes?

Sure. The user within my application can choose their column format which can be a comma or a dot decimal notation. They can upload data and visualize it. Maybe one source of the data has dot, another comma decimal notation. Either way, the user can choose their format.

**Comment by etpinard** [comment]
> Maybe one source of the data has dot, another comma decimal notation.

Hmm. But `layout.seperators` is meant to control the output format of those numbers on the graph. Wouldn't you want that to be consistent?

**Comment by ndabAP** [comment]
> Wouldn't you want that to be consistent?

I can't make this decision. I let the user decide that. Also it's just the output, not the actual number. Maybe the user can't modify the data before he imports it into my application.

**Comment by etpinard** [comment]
Ok. Well, we _could_ add attributes `xaxis.separtors` and `yaxis.separators` that would either inherit from `layout.separators` or be set individually. I'll change the issue title accordingly.

This won't be a high priority item for the foreseeable future, so don't expect it getting implementing anytime soon, unless you're willing to make a PR to this repo.

**Comment by ndabAP** [comment]
Sounds great!

**Comment by alexcjohnson** [comment]
Also, similar to calendars #1220 - if your users are providing this data as *text*, not numbers, we currently only support parsing with `'.'` as the decimal separator. If we need to support other text formats (which may be independent of how you want to display the data in tick & hover labels) we'll need separators as a *trace* property too.

**Comment by alexcjohnson** [comment]
Coming back to this in the context of #2207 and my comment that we may consider removing `separators` altogether in v2 https://github.com/plotly/plotly.js/issues/420#issuecomment-352099689 and supporting only `config.locale`:

@ndabAP seems like you're concerned with interpreting numeric strings being passed into your system with different separators - potentially several different formats within the same graph? In principle this isn't even just per-axis OR per-trace, but per-data-array - so we'd need something like `trace.xseparators` and `trace.marker.line.widthseparators` etc etc... which makes me think that this doesn't really belong in plotly.js but at a higher level of application logic (ie sanitize the data before passing it to plotly.js) - kind of like how we don't accept dates in any string form besides (potentially truncated) ISO 8601 format.

And then as far as display (tick and hover labels) - even if we *did* support parsing different arrays within a plot differently, I think we want a single *display* format throughout the plot - whether based on `layout.separators` or `config.locale` - otherwise we're just inviting confusion.

**Comment by etpinard** [comment]
This ticket most likely won't be implemented. Closing.

https://github.com/plotly/plotly.js/issues/1842#issuecomment-352105362 sums up our current state-of-mind on the topic.
