### ISSUE TITLE
scattergl click event not fired when dragmode is 'select'

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1870]
see this example and change the plot type from 'scatter' to 'scattergl' and you'll see that plotly_click event is not fired when in selection tool

https://codepen.io/plotly/pen/Obxbdv

although it does work on svg 'scatter' plot

**Comment by SillyLily0** [comment]
..probably somehow related to this issue: using scatterGL, the default dragmode is set to 'zoom', hence plotly_click events are fired, everything works fine, then I change dragmode to lasso by clicking the lasso icon in the toolbar, dragmode changes to 'lasso', everythings works as expected, plotly_selected is fired instead of 'plotly_click'. However, I would expect to untoggle the lasso mode by again clicking the lasso toolbar icon but it doesn't. In fact, checking the gl2d code it looks like there is no difference between toggling the incon on or off. Would be nice, if untoggling the lasso icon would set the dragmode back to default. Do you agree or am I missing something?

**Comment by etpinard** [comment]
> I would expect to untoggle the lasso mode by again clicking the lasso toolbar icon but it doesn't.

That's true for all a subplot types, gl or not. To return back to the default click on the `pan` button:

![peek 2017-09-18 09-47](https://user-images.githubusercontent.com/6675409/30545408-8006b1ea-9c57-11e7-8ba0-f3482fe94567.gif)

**Comment by SillyLily0** [comment]
Oh, ok I see. Thanks for pointing that out etpinard.

**Comment by etpinard** [comment]
This will be fixed by @dfcreative 's regl-based `scattergl` work.

@dfcreative would you mind adding a test case in this [suite](https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/gl2d_click_test.js#L456) to lock down `plotly_click` event behavior under `dragmode: 'select'`?

**Comment by dfcreative** [comment]
https://github.com/plotly/plotly.js/commit/091883ca4b9acb720e667d35bec3d7f0b669e428 adds test of `plotly_click` in lasso/select modes.

**Comment by etpinard** [comment]
that's now in https://github.com/plotly/plotly.js/pull/2258
