### ISSUE TITLE
Implement cliponaxis false for scattergeo

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1880]
Like https://github.com/plotly/plotly.js/pull/1861, but for `scattergeo`.

This will be a little bit work as `scattergeo` does not reuse `scatter/plot.js`.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
