### ISSUE TITLE
zooming behavior scaling open items

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1899]
#761 got some of our plot elements to scale correctly during a dynamic zoom, and #1897 extends this a bit further, but there are still a few items that stretch in this process and then jump to the new size later:

- errorbar caps: their stroke is correct, but their lengths are not. Presumably what's needed is a 1D version of `Drawing.setPointScale` (or just calling it with one of the dimensions set to 1) - see https://github.com/plotly/plotly.js/pull/1897#discussion_r128278824
- contour labels - this is a bit tricky, see https://github.com/plotly/plotly.js/pull/1897#issuecomment-316426194 - but we could do something anyway. Perhaps we scale them down but not up?
- bar text - see https://github.com/plotly/plotly.js/pull/1897#discussion_r128285494

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/2625 

when implementing items in the checklist, please have performance in mind, zoom scale can be very costly.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
