### ISSUE TITLE
Plotly and MathJax issue in Jupyter Notebooks

### ISSUE THREAD

**Issue by parsonsk** [plotly/plotly.js#1937]
I created a Jupyter Notebook with an (offline) Plotly plot embedded. When downloaded as HTML and viewed in a browser, the LaTeX equation is not converted by MathJax about 50% of the time that the page is loaded. A demo is attached which when loaded will display the equation correctly about 50% of the time. Tried in Safari, FF and Chrome (Chrome seems a bit more reliable, but not 100%). Removing the Plotly loading code causes the equation to always load correctly, so it looks like there is some kind of conflict. When the equation is not displayed, I can see that jax.js and fontdata.js are not loaded.
[PlotlyMathJaxIssueDemo.html.zip](https://github.com/plotly/plotly.js/files/1205854/PlotlyMathJaxIssueDemo.html.zip)

**Comment by rreusser** [comment]
Possibly related to https://github.com/plotly/plotly.py/issues/515 ?

At any rate sounds like a [plotly.py](https://github.com/plotly/plotly.py/issues?utf8=%E2%9C%93&q=mathjax) issue. If it's alright, I'll close this since there's nothing to be done about it in `plotly.js` but definitely sounds like an issue appropriate for the python bug tracker.
