### ISSUE TITLE
How to add a custom chart?

### ISSUE THREAD

**Issue by bitmega** [plotly/plotly.js#1954]
Hi,

I am looking for extending plotly to use in my application. It requires many custom behaviors and perhaps special drawing which is not supported by current chart types. Do you know how I can achieve that? I looked into the source code and I found that maybe I need to add a new trace and register it in with the Plotly. Is that correct? 

Any help will be appreciated.

Thanks in advance!

**Comment by etpinard** [comment]
Looking at a PR that adds a new trace type would be good place to start https://github.com/plotly/plotly.js/pull/1834

**Comment by rreusser** [comment]
@bitmega A *very* brief summary of how a plot is computed and displayed:

- supplyDefaults is run first (and semi-frequently) to sanitize inputs. This is generally very easy and there are lots of examples in all the traces.
- Unnecessary side note on `supplyDefaults`: attributes that aren't used (like marker size when only lines are displayed) should just be deleted. That's why most of the routines tend to have quite a bit of logic in supplyDefaults. If that doesn't matter to you, you can probably ignore that and simplify things somewhat.
- supplyDefaults should coerce pass data arrays through, but it should never iterate over the *content* of data arrays. That would make it slow. It should be fast. 🐎 
- `calc.js` is where the trace should do data computation that doesn't need to happen every time the plot is drawn. For example, when you pan or zoom with the cursor, only `plot` is re-executed. `supplyDefaults` and `calc` are *not*.
- `plot.js` is (obviously) where all the SVG magic happens.
- If your trace could live on a cartesian axis, you might be able to get a lot of bells and whistles for free by specifying the [basePlotModule](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/index.js#L36).

Ternary plots are probably actually a really good place to look. They piggyback on some of the cartesian plot code and almost entirely use scatter trace machinery for drawing lines. [The plot method of scatterternary](https://github.com/plotly/plotly.js/blob/master/src/traces/scatterternary/plot.js#L34) is extremely short because basically all it does is pass data to the regular scatter plot code.

Would love to hear how it goes!

**Comment by etpinard** [comment]
Closing this ticket as it won't lead to a PR.

@bitmega if you have any others questions, feel free to ask them on https://community.plot.ly/
