### ISSUE TITLE
Shape type 'path' SVG causes TypeError: Cannot read property 'append' of undefined

### ISSUE THREAD

**Issue by acats-dkolev** [plotly/plotly.js#1974]
Upgrading Plotly.js from v.1.24 to v.1.30 resulted in
	Failed: TypeError: Cannot read property 'append' of undefined
	at drawShape (plotly.js:120051)
	when SVG type 'path' Shape is used

To reproduce use the plotly-1.24.0.min.js library - the SVG shape shows.
Switch to plotly-1.30.0.min.js - TypeError: Cannot read property 'append' of undefined is thrown

https://codepen.io/dkolev8/pen/VzVywM

I found out that the last Plotly.js version that works with this SVG shape is v.1.24.1 
Looks like the breaking changes are introduced in [v.1.24.2](https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#1242----2017-03-10)

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by etpinard** [comment]
Wait. What browser are you using?

**Comment by etpinard** [comment]
Ha I see, your codepen imports `1.24.1`. Confirmed.

**Comment by acats-dkolev** [comment]
Browser chrome://version/ report:
Google Chrome | 60.0.3112.101 (Official Build) (64-bit) (cohort: Stable)

Similar error in Firefox  55.0.3 (32-bit) TypeError: shapeLayer is undefined
Thanks

**Comment by alexcjohnson** [comment]
1-line fix - I'll get it.

**Comment by alexcjohnson** [comment]
The issue is not with the type of shape, it's adding a shape to an overlaying axis. Thanks for the report!

Side note @acats-dkolev - I notice you're using milliseconds for the path coordinates. That will work, but it's fragile - it will shift if you change timezones. Better is to use date strings like you do in the `rect`, the only complication is that if there's a time part you need to separate with an underscore instead of a space, like:
`path: "M 2016-09-30_12:34:56.78 1.524 H 2016-10-14 V 1.303 Z"`
