### ISSUE TITLE
`gl3d_multi_scene` mock is throwing WebGL rendering warnings

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1976]
See http://rickyreusser.com/plotly-mock-viewer/#gl3d_multi-scene

![image](https://user-images.githubusercontent.com/6675409/29903341-608fb80a-8dd1-11e7-808a-1e0e2c0915f5.png)

in Chrome `60.0.3112.113` on Ubuntu 16.04.

**Comment by rreusser** [comment]
Same on OSX + Chrome.

**Comment by etpinard** [comment]
cc @archmoj

**Comment by etpinard** [comment]
updated link: https://rreusser.github.io/plotly-mock-viewer/#gl3d_multi-scene

**Comment by archmoj** [comment]
Good call @etpinard! 
This one is definitely related to gl-scatter3d and I believe it happens when the line mode is enabled and has only one point which produce 0 lines! So I need to fix gl-scatter3d there.
But my observation here is that one could use `mode:'markers'` to remove the warnings on this mock.
Also I observed that if we use `mode:'text'` instead we get similar warnings on master branch. But using the fix for issue #704 those warnings would be removed.
