### ISSUE TITLE
Error Bar "color" array.

### ISSUE THREAD

**Issue by efaden** [plotly/plotly.js#1985]
It would be nice if the color field of error_y/error_x also accepted an array like the marker->color field.  Right now I can have a custom marker for the hover, but it is impossible to highlight the error bars as well.

**Comment by alexcjohnson** [comment]
Right, there are a few error bar attributes that would be nice to support as `arrayOk` - `color`, but also `width` and `thickness`. For that matter, it would be nice to make `value` and `valueminus` support `arrayOk` and get rid of `array` and `arrayminus` but that may need to wait for v2 - https://github.com/plotly/plotly.js/issues/420#issuecomment-327266480

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
