### ISSUE TITLE
Requesting a way to validate input data

### ISSUE THREAD

**Issue by phxnsharp** [plotly/plotly.js#1998]
In #598 a Plotly.validate() call was added to validate the structure of the input data. This is a fantastic step forward.

This issue is to request further validation of the input data itself. For example, if you provide arrays for x and y data that do not match in length, Plotly will just silently ignore the values from the longer array. 

In our usage, we are very risk adverse to "bad data with no error" cases. Obviously having empty or NaN values should be supported per design. The specific case of the input arrays being different length, though, indicates that something has gone awry.

https://jsfiddle.net/fn4cmnqo/

**Comment by etpinard** [comment]
Very interesting suggestion. Thanks @phxnsharp

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
