### ISSUE TITLE
OHLC calculations are off on category axes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2004]
See https://codepen.io/plotly/pen/KXwaMR

cc @cldougl

**Comment by alexcjohnson** [comment]
oof, I hate to say it but I'm not sure we have a good way to do this within the current framework. You simply can't have data points on a category axis that don't point to exact categories. So the options I see are:
- build some sort of shim into scatter to allow shifting points away from their data values (cf #299)
- build a hook to allow transforms to alter `gd.calcdata` after it's been created
- rebuild OHLC as a native trace without transforms
Am I missing some simpler option?

**Comment by cldougl** [comment]
This issue originally came up from someone trying to workaround a scenario similar to https://github.com/plotly/plotly.js/issues/1382 and remove gaps caused by weekends/missing dates. Not setting x (to use default linear coordinates) and then using `ticktext` works well as a workaround to using `category`.
