### ISSUE TITLE
Sankey hover text placement

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2014]
@alexcjohnson noticed a hover placement issue with Sankey - here the 633 appears on top of the white box instead of inside it. Not sure if it's a JSON construction issue or a Plotly.js issue.

![image](https://user-images.githubusercontent.com/1865834/30574500-5d0e73dc-9cc8-11e7-803b-d577e8f65488.png)

The wapo hover text can also go off into the ether and does not always seem to point at the selected line:

![image](https://user-images.githubusercontent.com/1865834/30574529-88e96ec6-9cc8-11e7-81ff-748bd5144dc4.png)

Both of these examples are from https://medium.com/@plotlygraphs/4-interactive-sankey-diagram-made-in-python-3057b9ee8616

/cc @monfera @alishobeiri

**Comment by monfera** [comment]
Looks like the out-of-box number happens on items that show a `Source:` and a `Target:` line, but no title above it, as on the above example, because the few items with a `label` are fine:
![image](https://user-images.githubusercontent.com/1548516/30584156-2e9abaf4-9d29-11e7-8377-45ccaa9984f6.png)

This codepen example also has links both with and without `label`, and both render fine:

![image](https://user-images.githubusercontent.com/1548516/30584366-c6364cd4-9d29-11e7-8c79-18b0f925372d.png)

![image](https://user-images.githubusercontent.com/1548516/30584334-b29b323e-9d29-11e7-9ed2-1974db25b694.png)

I'll look at how the data is different here.

**Comment by monfera** [comment]
Reopening to be able to link the other fix (closing only when that's done too)

**Comment by monfera** [comment]
@alexcjohnson the only remaining problem is the sometimes misplaced tooltip, seen when the browser window [here](https://plot.ly/~alishobeiri/1367.embed) is wide and `div.svg-container` gets a `margin: auto`, as inlined style. Any quick thought on where this `auto` is coming from? I copied `data` and `layout` and I didn't get that. I can look it up if it'd take time.

**Comment by monfera** [comment]
Added an effective [fix](https://github.com/plotly/plotly.js/pull/2027), and, depending on the answer I'd need to add an appropriate test. It looks like our [guideline](https://plot.ly/javascript/responsive-fluid-layout/) on fluid layout tampers with the `gd` `margin` rather than the `paperdiv` (=== `div.svg-container`) margin.

**Comment by monfera** [comment]
With the above last PR (thanks @alexcjohnson for the review) I think the two problems reported in this issue, and a third one I ran into (node became invisible if `value` was comparatively low), and a fourth one surfaced by the preceding item (reworking node/link pixel alignment as the small mismatch looked off when the node was very small) are taken care of and merged into `master`.

**Comment by monfera** [comment]
As discussed with @alexcjohnson we're closing these issues as fixed by the linked four PRs.
