### ISSUE TITLE
Need help with plotly.js fill area

### ISSUE THREAD

**Issue by mantabernd** [plotly/plotly.js#2033]
Hello,

I got a graph from -135 ... +20 and want to fill the ploted area to the maximum value of my graph.
Unfortunately the fill ends at zero and not at +20.

How to change my layout to plot the whole graph till "the end" and not to zero?

trace1 and trace4 are the traces with the fills.

![plotly2](https://user-images.githubusercontent.com/30231556/30786472-7570556e-a176-11e7-907c-23a76a7eda71.PNG)

            var trace1 = {
					x: xvals,
					y: yvals,
					mode: 'scatter',
					fillcolor: 'rgba(51, 122, 183, 0.5)',
					fill: 'tonextx',
					
				};
		var trace2 = {
					x: markerx,
					y: markery,
					mode: 'markers'
				};
		var trace3 = {
					x: VuIndB,
					y: VuOutdB,
					mode: 'markers'
				};
		var trace4 = {
					x: x_back,
					y: y_back,
					mode: 'none',
					fill: 'tonextx',
					fillcolor: 'rgba(51, 122, 183, 0.3)'
				};
		var dataplot = [trace1,trace2,trace3,trace4];
		var layout = {
					xaxis: {zeroline: false, range: [-135, 20], gridcolor: 'grey', tickcolor: 'white', linecolor: 'white', color: 'white'},
					yaxis: {zeroline: false, range: [-135, 20], gridcolor: 'grey', tickcolor: 'white', linecolor: 'white', color: 'white'},
					margin: {l: 30, t: 20, b: 30, r: 10},
					showlegend: false,
					plot_bgcolor: '#3f3f3f',
					paper_bgcolor: '#3f3f3f'
				};

Thanks for your help!
Regards
Bernhard

**Comment by etpinard** [comment]
@mantabernd would you mind reposting your question on https://community.plot.ly/ ?

As mentioned in our contributing guidelines, Github issues are reserved _for bug reports and feature requests only_. Why you might ask? Because on https://community.plot.ly/ other users can benefit from answers plotly.js maintainers or other plotly.js user give in the long run - as opposed to here where resolved issues are closed. You can think of Github issues for this project as a TODO for devs **not** a Q&A forum.

Thanks.
