### ISSUE TITLE
Add way to customize geo base layer ordering

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2042]
See https://github.com/plotly/plotly.js/pull/2030#discussion_r140511424 ideally with an API somewhat similar to cartesian https://github.com/plotly/plotly.js/pull/1871 and ternary https://github.com/plotly/plotly.js/pull/1952 `layer`.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
