### ISSUE TITLE
Consider and possibly put in place a common, unified scroller solution

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#2054]
This ticket is a spinoff of the [`table` PR](https://github.com/plotly/plotly.js/pull/2052).

`plotly.js` now has three different scrollers, each supporting specific features that the others may not cover. The use cases and constraints should be collected to see if, meeting the tightest constraints in each area, a common implementation could support all, and future scrolling items.

Relevant thread starts:

- https://github.com/plotly/plotly.js/pull/2052#discussion_r142418972
- https://github.com/plotly/plotly.js/pull/1834#issuecomment-313729498
- https://github.com/plotly/plotly.js/pull/1834#issuecomment-317541477
- https://github.com/plotly/plotly.js/pull/2052#discussion_r142476943 (from "One more note")

**Comment by monfera** [comment]
Self-assigning to keep tabs on it

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
