### ISSUE TITLE
Spline interpolation for line charts and scatter plots is limited and distorts data

### ISSUE THREAD

**Issue by Animus451** [plotly/plotly.js#2085]
Currently, the spline technique that is employed for line charts and scatter plots seems to be some form of non-monotonic polynomial regression. Whatever method is used to generate the spline often distorts the data set to which the curve is being fit. (See below) The graph below shows false extrema as a result of the spline.
![innacurate splining](https://user-images.githubusercontent.com/22042681/31510962-34368190-af54-11e7-815d-ed66dfbad888.png)
While this kind of spline may work for some situations, a more generally useful spline would be a monotonic polynomial regression. This specifically prevents distorted representations of extrema.

Note: A similar issue has been opened here: https://github.com/plotly/plotly.js/issues/993

**Comment by rreusser** [comment]
It's actually 2D catmull-rom splines. That means there's no favored independent variable or axis. Which in turn means, I guess, monotonic _with respect to what_? Which then means this would probably take the form of `shape: 'spline' | 'monotonicx' | 'monotonicy'` Paths are computed for use [here](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/plot.js#L218-L241) and step paths (perhaps most similar to this case) are computed [here](https://github.com/plotly/plotly.js/blob/master/src/components/drawing/index.js#L547-L577). It would then be a matter of computing a monotonic path (in screen coordinates, I believe). The math is [here](https://en.wikipedia.org/wiki/Monotone_cubic_interpolation). It certainly seems reasonable and perhaps not even that difficult, though I don't believe it's currently on the radar. A PR would be gladly accepted though. Glad to help out, otherwise those are my thoughts on what it would take.

**Comment by alexcjohnson** [comment]
Thanks for pointing to #993 - it is indeed a duplicate, lets keep the discussion contained over there.
