### ISSUE TITLE
Ability to style download image for chart

### ISSUE THREAD

**Issue by AlexVvx** [plotly/plotly.js#2098]
Hi, what do you think about adding ability to style downloaded image differently, then original chart? E.g. margins, borders - update appearance of chart exported to image.

**Comment by etpinard** [comment]
See https://codepen.io/etpinard/pen/BwvENX?editors=0010

Since https://github.com/plotly/plotly.js/pull/1939 released in `1.30.0`, `Plotly.downloadImage` and `Plotly.toImage` accept `{"data":[], "layout":{}}` objects as well as graph div as first argument.

So one could extend a graph's data and/or layout before calling `Plotly.downloadImage` to apply custom download styles to a graph. I don't see the need to add a _style_ option to `Plotly.toImage`.

**Comment by AlexVvx** [comment]
Sounds good. A couple of questions:
- does it mean, that arguments list probably won't change and it's ok to use {data, layout, config} ?
- _snapshotInProgress probably won't work. It's possible to update it manually in your app code, but is it ok to use property with underscore, since it supposed to be used internally?

**Comment by etpinard** [comment]
> does it mean, that arguments list probably won't change and it's ok to use {data, layout, config} ?

The [api](https://github.com/plotly/plotly.js/blob/master/src/plot_api/to_image.js#L75-L84) is the following, so yes isn't the same as `newPlot`.

> _snapshotInProgress probably won't work

I don't know what that is. Is probably always a bad idea to rely on `_` properties.

**Comment by AlexVvx** [comment]
_snapshotInProgress - from plotly.js/src/snapshot/download.js, 
true - if snapshotting already in progress, will cancel next download process when first one is not finished
false - if not in progress

**Comment by etpinard** [comment]
It should.

Alright, I'm closing this thing as it won't result in a PR of any sort. Please use https://community.plot.ly/ if you have other questions of the likes.
