### ISSUE TITLE
Boxplot outlier color for other boxpoint options 

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#2112]
I noticed that in boxplots we can only color outlier points when the box options `'boxpoints'` option is set to `'suspectedoutliers' `

I would like to be able to color outlier points when the options is set to `'all'` or `'outliers'`

Also, this wasn't obvious to me from the documentation, I recommend that it should be pointed out in the boxplot.marker.outliercolor description

**Comment by alexcjohnson** [comment]
Good idea, and you're absolutely right that the docs are unclear (or perhaps just plain wrong 🙈 ) on this point.

Just to be clear though: you can already set the point color different from the box color by using both `marker.color` and `line.color`, but it's only when `boxpoints = 'suspectedoutliers'` that you can have two different colors for the sample points: one for the suspected outliers (less than 3 interquartile ranges from 1Q or 3Q), another for the full outliers (farther out).

In principle it would be nice to be able to:
- separately color *all three groups* differently: non-outliers, suspected outliers, full outliers
- alter other pieces of their styles - size, symbol, opacity...

I suspect this means we should ditch `marker.[line.]outlercolor` and `marker.line.outlierwidth` and just make two new containers that provide everything in `marker`, one for full outliers and another for suspected outliers (only used if `boxpoints = 'suspectedoutliers'`, otherwise these get styled like outliers). Can these just be `marker`, `outliers`, and `suspectedoutliers`?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
