### ISSUE TITLE
plotly.js aggregations by N columns

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2123]
Here for example I've already grouped air pollution measurements by state name, now I would like to get an average over all counties by year:

![image](https://user-images.githubusercontent.com/1865834/32033246-85b80e00-b9d9-11e7-80ae-056497e4909c.png)

![image](https://user-images.githubusercontent.com/1865834/32033278-b7cf33e6-b9d9-11e7-9bb2-e50bf85ef0a4.png)

cc @alexcjohnson

**Comment by alexcjohnson** [comment]
This should work the same way as SQL `GROUP BY COL1, COL2, COL3, ...` - gives one output row per unique combination of values in all N columns.

To be clear, this is an extension of a single `aggregate` transform, and is not possible through chaining N `aggregate` transforms - in fact it's kind of the opposite effect, as adding more columns to one `aggregate` transform generates *more* output rows, whereas chaining can only give *fewer* output rows.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
