### ISSUE TITLE
Add `Axes.tickText` variant tailored to pixel-level detail

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2137]
From @alexcjohnson 's https://github.com/plotly/plotly.js/commit/bc6bc025ce3717c3e640f43eb71dd3ab2f719e01#commitcomment-25310521

> hmm, this is a little tricky... it's giving the v labels more digits than they warrant. Axes.hoverLabelText calls Axes.tickText with 'hover' mode. This whole machinery is getting awfully contorted at this point, but 'hover' mode gives several more digits than you need to distinguish pixels, as it's meant to label data points precisely without going overboard. But regular Axes.tickText might have too few digits to distinguish pixels. This is really a new use case - though if we put continuous labels on lines it will show up again there. I'm OK leaving it as is for now, but lets make an issue to clean up this machinery and provide a tickText variant tailored to pixel-level detail.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
