### ISSUE TITLE
Make Lib.nestedProperty an npm module of its own

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2138]
So that users and plotly.js consumer projects can use it!

The tricky part will be to factor out the _core_ nested property logic from the plotly.js-specific parts (namely [`plot_api/container_array_match.js`](https://github.com/plotly/plotly.js/blob/81ddaca1016218aa749ebf0d78fc9021d3bb73ea/src/lib/nested_property.js#L15)).

Wrapping `nestedProperty` in a constructor should do the trick. For example, `plotly.js/src/lib/nested_property.js` could become:

```js
var NestedProperty = require('@plotly/nested-property');
var containerArrayMatch = require('../plot_api/container_array_match');

module.exports = new NestedProperty({containerArrayMatch: containerArrayMatch});
```

cc @bpostlethwaite @alexcjohnson

**Comment by alexcjohnson** [comment]
@etpinard sounds great! The only change I'd suggest is instead of `containerArrayMatch`, factor out `isDeletable` - there's more plotly.js-specific logic in there than just `containerArrayMatch`. That said, this logic is fairly obtuse and always makes me wonder how much would really be lost if we ditched it or at least simplified it...

**Comment by etpinard** [comment]
Probably not going to happen in the near future. Closing.
