### ISSUE TITLE
SVG container DIV much larger than actual graph

### ISSUE THREAD

**Issue by pascalpas** [plotly/plotly.js#216]
There seems to be a lot of unneeded whitespace for some of my graphs (but not all), where the SVG container is the actual specified height, but the graph itself is much smaller.
![schermafbeelding 2016-01-26 om 10 13 29](https://cloud.githubusercontent.com/assets/8132276/12576830/bb252e0c-c416-11e5-9b5e-7fc752fe7594.png)

Why doesn't it fill the specified height?

**Comment by etpinard** [comment]
No. plotly.js adds margin separating your graph's axes from the container div.

See `layout.margin` for more details: https://github.com/plotly/plotly.js/blob/master/src/plots/layout_attributes.js#L75-L103

**Comment by etpinard** [comment]
For future questions of the likes, please note that:

> Note that GitHub issues are reserved for bug reports and feature requests only.
Implementation questions should be asked on Stack Overflow (tagged [`plotly`](https://stackoverflow.com/questions/tagged/plotly)) or on community.plot.ly (tagged [`plotly-js`](http://community.plot.ly/c/plotly-js)).

More info in the [contributing guidelines](https://github.com/plotly/plotly.js/blob/a66dc667e85e90f7ffb0fd933651910ac4656237/CONTRIBUTING.md#opening-issues).

**Comment by fresheneesz** [comment]
@etpinard I think this was appropriate as a bug. While this may be an intended feature by whoever designed it, its confusing and unexpected to users (including me). If I want a margin, I would want to create that explicitly myself in my own styles. There's no need for this margin to be there by default.

I recommend this be reopened with the goal of dicussing removing that margin by default.

**Comment by etpinard** [comment]
I see your point that the behaviour might be _confusing_. 

But, if the graph (i.e. the what's inside the axes) is meant to cover the whole div then there would be no room for the axis titles. Wouldn't that be even more _confusing_?

**Comment by fresheneesz** [comment]
@etpinard It should know whether or not there are axis titles and how large the area needs to accommodate them, right? Then you don't need custom margining, you just fit it to the space available. Any keys, titles, etc should be given just enough space, and margins can then be left to CSS rather than a plotly configuration.

**Comment by etpinard** [comment]
> extra margins can then be left to CSS rather than a plotly configuration.

plotly.js isn't meant to be used with CSS. The own source of truth is the `data` / `layout` JSON-serializable schema.


> It should know whether or not there are axis titles and how large the area needs to accommodate them, right?

Agree. We could do a better job in our auto-margin algorithm so that e.g. it considers visible axis titles to determine the needed padding. That said, it's not obvious to me how _fix_ in a backward compatible way.

**Comment by fresheneesz** [comment]
@etpinard 

"plotly.js isn't meant to be used with CSS."

I mean, whatever container contains the plotly graph could have css margins.

"it's not obvious to me how fix in a backward compatible way."

Why make it backwards compatible? I see there's a version 2 coming up. A non-backwards compatible change could be put there. Also, its unlikely that the change will mess anyone up, since its only removing unneeded margin. Anyone relying on the margins will likely be setting explicit ones themselves I would imagine.

**Comment by etpinard** [comment]
> Why make it backwards compatible? I see there's a version 2 coming up.

Good point. 

Would you mind if I change this issue's title to something like _Improve auto-margin routine_ ?

**Comment by fresheneesz** [comment]
@etpinard Please do! Note this isn't my issue ( @pascalpas ), I've just co-opted it as relevant to the discussion I wanted to have.

**Comment by fresheneesz** [comment]
Hmm, I'm also noticing that resizing a plot doesn't take into account margins or padding, and so doesn't size properly if those exist.

**Comment by etpinard** [comment]
@fresheneesz 

Would you mind sharing a reproducible example?

**Comment by fresheneesz** [comment]
Here's an example. Replace the padding with either margin or a border to get the same effect: scrollbars. Remove any border, margin, or padding on .a and you're fine

```
<body>
<div id="container"></div>
</body>

<style type="text/css">
    #container {
        width: 400px;
        overflow:auto;
    }
    .a {
        display: inline-block;
        width: 100%;
        /*border: 1px solid green;*/
        /*margin:10px;*/
        padding:10px;
    }
</style>

<script src="plotly-latest.min.js" charset="utf-8"></script>
<script>

    var a = document.createElement('div')
    a.classList.add("a")

    var x = [1, 2, 3, 4, 5, 6]
    var y = [1, 2, 4, 8, 6, 1]

    Plotly.newPlot(a, [{x: x,y: y,type: 'scatter'}], {
        title: "Some Title",
        xaxis: {
            title:"X axis", range: [4, 5.1]
        },
        yaxis: {
            title:"Y axis"
        },
        margin: {
            b:40,l:40,r:5,t:30
        }
    })

    document.getElementById("container").appendChild(a)
    Plotly.Plots.resize(a)
</script>
```
