### ISSUE TITLE
Range values for the "date" type are passed as String in plotly_relayout callback

### ISSUE THREAD

**Issue by mperrando** [plotly/plotly.js#2176]
These values should be passed with a more appropriate format (i.e. ms form epoch time or Date objects).

This is a real problem when the user needs needs to perform calculations: the conversion to ms or Date is not trivial (see https://stackoverflow.com/questions/6427204/date-parsing-in-javascript-is-different-between-safari-and-chrome).

Here is explained the current behaviour

https://github.com/plotly/plotly.js/blob/1dbaea521d701ca4bd82cbfca5c13760183e8aa5/src/plots/cartesian/set_convert.js#L208

https://github.com/plotly/plotly.js/blob/1dbaea521d701ca4bd82cbfca5c13760183e8aa5/src/plots/cartesian/set_convert.js#L44

Plotly accepts, for the date type, Date objects, and this should IMO be the preferred type for this data type when Plotly send it back to the user.

Here 

https://github.com/plotly/plotly.js/blob/4c9458b2c421fcf84fc6032091a3c152c2ebae67/src/lib/dates.js#L84

and here

https://github.com/plotly/plotly.js/blob/4c9458b2c421fcf84fc6032091a3c152c2ebae67/src/lib/dates.js#L231

you can see that the conversion towards ms accepts both Date and String, while the conversion from ms returns a String and not a sane data type. Can't understand why, it seems just evil to me, but I have not studied all the Plotly lib! :)

Possible solutions:

* change the behaviour of the library so that the "r" and "d" type for date values is always Date, but strings are also accepted as input as it is now (dangerous, could break currently correct code);
* expose the dateTime2ms (I have not been able to reach it from inside the event callback function, is there a simple way of doing this, please tell me and I am fine!);
* along with range values, pass also all the r2X functions, so that the user can be convert range values to another format.

Anything, but please, save me from the craziness of manipulating dates as strings! :)

Thank you.

**Comment by alexcjohnson** [comment]
Strings are, for better or worse, the preferred format for dates in plotly.js. There are a couple of reasons for this:
- We do not, at present, support time zones. All datetimes are treated as UTC but for backward compatibility we do a bunch of gymnastics to convert `Date` objects and epoch ms to the UTC time that *looks* the same as the local time indicated by the given input. This, however, is not portable across time zones so is discouraged (note that `Date` is not a JSON data type).
- We can support *a little* more precision with our own string-to-number conversion than js allows with its `Date` objects. Doesn't get all the way to nanoseconds that some folks would like but it helps in some cases.
- World calendar support

> along with range values, pass also all the r2X functions, so that the user can be convert range values to another format.

True, these are available directly in the event data for hover and click events, but not for relayout. Since relayout events might not even relate to axes, it's a little hard to figure out when to include them. You can get the conversions fairly easily though from `graphDiv._fullLayout.xaxis.r2c` etc. @mperrando does that work for you?

**Comment by mperrando** [comment]
Thank you @alexcjohnson! Great suggestion!

Now another problem rises. The conversion from datetime (string) to ms does not take into account that the string is specified in local time, but it treats it as a UTC date.

This introduces a time offset that is equal to the local time zone offset (see image below).

![mappa sir di test 2017-11-28 09-59-04](https://user-images.githubusercontent.com/525572/33311010-d561df1c-d423-11e7-8aff-685f18572eea.png)

So, when you pass this value back to the layout command, the resulting graph results shifted in time.

This is the date hell I was referring :) 

Do you think it is the case to open a new ticket about this?

Thank you.

**Comment by mperrando** [comment]
Thank you @alexcjohnson.

**Comment by jhvanderven** [comment]
Late into this discussion.

I noticed that react-plotly.js(^2.6.0) still changes the range types from Date to string. This causes an extra rerender in my case, so I now pass them in as correctly formatted strings. 

Is it better for performance to pass in the data points as strings too?
