### ISSUE TITLE
scatter3d marker size has different meanings when specified as a single value vs as an array.

### ISSUE THREAD

**Issue by ksze** [plotly/plotly.js#2185]
When using Scatter3D, the marker size has very different meanings when specified as a single value vs when specified as an array.

To reproduce:
1. Visit this codepen: https://codepen.io/k_sze/pen/MOqZpY
2. In the codepen console, run `restyle1()` and `restyle2()`;
3. Watch the points getting very different sizes.

`restyle1()` specifies the sizes of the markers as an array filled with the integer 12;
`restyle2()` specifies the sizes of the markers as a single value of 12.

**Comment by etpinard** [comment]
Ha good catch. Those array-item values should be multiplied by 2 [here](https://github.com/plotly/plotly.js/blob/629f7a04a3d8b864c7617c42c25232be950e4714/src/traces/scatter3d/convert.js#L220).

Fixing this old (pre-open-source) bug would arguably _break_ many existing graphs. So I think it would be best to wait for v2, unless someone can convince us otherwise.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
