### ISSUE TITLE
Using Plotly.restyle sometimes changes the order of the datasets

### ISSUE THREAD

**Issue by Leprosy** [plotly/plotly.js#2192]
Hi...I have this script to update the style of the first dataset:

```javascript
Plotly.newPlot('graph', [{
  mode: 'lines',
  line: {
    color: '#0f0'
  },
  name: "first",
  y: [1, 2, 1, 3]
}, {
  mode: 'lines',
  y: [1, 2, 3, 4],
  line: {
    color: '#f00'
  }
}]).then(function(obj) {
  Plotly.restyle(obj, {line: {color: "#000"}}, 0)
  Plotly.restyle(obj, {fill: "tozeroy"}, 0)
  //Plotly.restyle(obj, {fill: "tonexty"}, 0)
})
```

I've noticed that when the `restyle` method is used to change the `tonexty` value of the `fill` attribute in the style object, changes the order of the datasets. Is there a way to prevent this? Using this example, when the value is `tozeroy`, the order is mantained.

**Comment by alexcjohnson** [comment]
The tonext fills (and some other conditions like stacked bars) automatically set the layout property `legend.traceorder` to `reversed` so that in the most common case, the legend items show up in the order the traces appear on the plot. But you can revert this by adding `legend: {traceorder: 'normal'}` to your layout.

**Comment by alexcjohnson** [comment]
BTW just because I notice it in your post - your line:
`Plotly.restyle(obj, {line: {color: "#000"}}, 0)`
is probably better written:
`Plotly.restyle(obj, {'line.color': "#000"}, 0)`
The former will overwrite the whole `line` object, so will clear other properties (`line.width`, `line.dash`, `line.shape`) that might have been set previously. The latter will ONLY change `line.color`.

**Comment by Leprosy** [comment]
Great, thanks!
