### ISSUE TITLE
autosize: true still keeps previously set width and height

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#2198]
try this codepen: https://codepen.io/veraz/pen/QOPQJJ
try removing width and height -> plot resizes to fit screen maximally, 
keep width and height, plot doesn't resize even if autosize is set to true.

**Comment by antoinerg** [comment]
@VeraZab According to the doc, this is the expected behavior. `autosize` will only work if `width` and `height` are unspecified.

@alexcjohnson Should we change thhis behavior and make `autosize: true` prevail over `width` and `height`? If not, I would close this issue!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
