### ISSUE TITLE
Feature request: Configure double-click time interval

### ISSUE THREAD

**Issue by pynklu** [plotly/plotly.js#2206]
Would it be possible to configure the double-click time interval.
I'm getting some reports from users that doubleclicking on a label to select a single trace/group of traces is too difficult.

**Comment by alexcjohnson** [comment]
Sounds reasonable, probably as a `config` parameter rather than `layout`. I've always wished browsers would let you query the system's doubleclick time so you could match how the user has configured their own environment...

Probably not something we'll get to very soon, but it should be pretty easy and we'd be happy to review a PR about it 😉

**Comment by sagar3047** [comment]
Hi,
We are using plotly js library for 3D visualizations . We are facing an issue with double click on the scatter plot(type : scatter) after they are zoomed in.

After zooming in to scatter plots(click & drag) , subsequent **double click** to restore the image to original size(default zoom level) is quite flaky. The issue being that the double click time interval is too low & hence the zoom restore does not work reliably.
Would be great to have the issue resolved for us . Any news from plotly side on taking up the issue.

Regards,
Sagar.

**Comment by pynklu** [comment]
Any movement on this? :-)
