### ISSUE TITLE
Allow setting hoverformat for lat, lon, and text values in maps

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2214]
Similar to https://github.com/plotly/plotly.js/issues/1383, but for mapbox-gl and D3 maps:

![image](https://user-images.githubusercontent.com/1865834/34131159-7b589a74-e418-11e7-9a7a-4fd0c84c096a.png)

**Comment by etpinard** [comment]
Now doable using `hovertemplate` e.g: https://codepen.io/etpinard/pen/oVMLMm

Not sure it's worth adding something an attribute similar to [`zhoverformat`](https://plot.ly/javascript/reference/#heatmap-zhoverformat) for `lon` and `lat` formatting.

**Comment by jackparmer** [comment]
wow, very cool!

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/2618 - which is also "doable" using `hovertemplate` w/o needing an extra attribute. 

We'll need to discuss how much we want to "solve" everything using `hovertemplate` or adding more hover-label-content-related attribute is still the way to go.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
