### ISSUE TITLE
Better autoranging for carpet plots

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2289]
Currently the container axes for carpet plots are autoranged with a [fixed percentage buffer](https://github.com/plotly/plotly.js/blob/2db87078f1f3f831a8df6fd8ae55da21bf093c8d/src/traces/carpet/calc.js#L69-L77) around all edges of the carpet area. But for large carpets this is too much, and for small carpets too little - titles can get clipped - see eg [cheaterslope.png](https://github.com/plotly/plotly.js/blob/0c7d20ef662c77784d98fb94dce5bc95ef74d94f/test/image/baselines/cheaterslope.png) which isn't even autoranged, it's manually ranged more generously, but the titles are *still* cut off.

Figuring out a better autorange than this would require sizing and calculating positions for the text upfront, then using that to pad the containing axes.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
