### ISSUE TITLE
restyle of marker opacity not working for scattergl 

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2299]
https://codepen.io/cpsievert/pen/Rxzzzz

cc @dfcreative

**Comment by alexcjohnson** [comment]
Interestingly `Plotly.restyle(gd, {"marker.opacity": 0.1});` seems to work fine, as does the `trace.opacity` attribute on the initial draw - it's just `Plotly.restyle(gd, {"opacity": 0.1});` that fails.

@dfcreative you probably just have to explicitly define `opacity` in `scattergl/attributes`, like we do in eg [`surface/attributes`](https://github.com/plotly/plotly.js/blob/f48d03ec5da0219419faac55366646479931d65d/src/traces/surface/attributes.js#L226) so you can get `editType: 'calc'` instead of `editType: 'style'` that you get from the base [opacity attribute](https://github.com/plotly/plotly.js/blob/f48d03ec5da0219419faac55366646479931d65d/src/plots/attributes.js#L55). And assuming that fixes it, take a quick spin through the rest of those base attributes and see if anything else is broken the same way.

**Comment by etpinard** [comment]
Better yet, maybe we could make [`ScatterGl.style`](https://github.com/plotly/plotly.js/blob/fdf20cb46bd9224ee70be4a3a78b39d6046a6142/src/traces/scattergl/index.js#L1214-L1221) handle trace opacity updates.

**Comment by dfcreative** [comment]
@alexcjohnson thank, fixed in https://github.com/plotly/plotly.js/pull/2311/commits/a9d387aa14d3e2ade6768bcd2bbc20dcc22782b3. Making `ScatterGl.style`to do options recalculation (that is required to update opacity, since resulting opacity depends on trace.opacity, marker.opacity and color alpha) would be unnecessary complexity and mostly duplication.

**Comment by etpinard** [comment]
fixed in https://github.com/plotly/plotly.js/pull/2311
