### ISSUE TITLE
Bug: Titles not being shown

### ISSUE THREAD

**Issue by LarryMartell** [plotly/plotly.js#2301]
The new version fixed the heat and contour map bugs, but a new bug was introduced. The titles on plots are not being show. Here are 2 codepens that show this:

Version 1.31.2 titles work: https://codepen.io/LarryMartell/pen/BYBaXB
Version 1.33.1 titles do not work: https://codepen.io/LarryMartell/pen/WMebeQ?editors=1000

**Comment by alexcjohnson** [comment]
Thanks for the codepen examples! Looks like you're referring to the titles for `xaxis3` and `xaxis5` being ignored? I'm afraid this is an intentional result of #2227 - you don't reference these axes with any traces, and as of that change we simply stop creating any subplots for axes that don't have any data (or other components like annotations or shapes) referencing them; with no subplots, we don't create any titles, ticks, or tick labels either.

If you're using these axes just to get labels positioned where you want them, can you make them with annotations instead? Those should actually be quite a bit easier to use (and more flexible) for this purpose anyway. Something like:
```js
var layout = {
    ...
    annotations: [{
        text: 'By Radius',
        xref: 'paper',
        yref: 'paper',
        xanchor: 'center',
        yanchor: 'bottom',
        x: 0.875,
        y: 1.01,
        showarrow: false,
        font: {size: 14}
    }]
};
```

**Comment by LarryMartell** [comment]
Thanks I was able achieve what I need using the annotations.

**Comment by alexcjohnson** [comment]
OK great. Sorry for the trouble, I didn't realize anyone was using axes this way...

**Comment by LarryMartell** [comment]
Not sure why I did it this way - probably did not know about annotations. Thanks for the pointer.
