### ISSUE TITLE
plotly_relayout event only emits xaxis or yaxis if only adjusting those axes

### ISSUE THREAD

**Issue by jwkvam** [plotly/plotly.js#2330]
Hello, I'm not sure if this is a bug or my misunderstanding in documentation.

In the [docs](https://plot.ly/javascript/plotlyjs-events/#update-data) it says the following will be returned.
```
// plotly_relayout update: Cartesian
//// Upon resizing plot:
{
 xaxis.range[0]: ,
 xaxis.range[1]: ,
 yaxis.range[0]: ,
 yaxis.range[1]:
}
//// Upon autosizing plot:
{
 xaxis.autorange: true,
 yaxis.autorange: true
})
```
In this [jsfiddle](https://jsfiddle.net/2tw1bnzn/6/) I output the data from the relayout event. If you adjust the yaxis only you get something like:
```
{"yaxis.range[0]":3.0540691192865106,"yaxis.range[1]":4.258082497212931}
```
It similarly happens if you adjust the xaxis only. Based on the docs I was expecting to receive both yaxis.range and xaxis.range.

I'm mainly wondering if this is intentional. If so I will store the xaxis and yaxis info in my application so I have both if an event like this happens. Thanks for your attention!

**Comment by alexcjohnson** [comment]
Yes, this is intentional. Thanks for pointing it out, we'll clarify this in the docs. The event data for `restyle` and `relayout` events shows exactly what was sent to `Plotly.restyle`/`Plotly.relayout` - that is, only the quantities we directly changed. Anything we didn't change (in your case, the xaxis range) will not show up, nor will anything that changed *indirectly* as a result (for example, when `yaxis.range` changes, `yaxis.autorange` is automatically set to `false` but this is not reported in the event data either).

**Comment by jwkvam** [comment]
Thank you! I will close.
