### ISSUE TITLE
Mapbox select doesn't update with scrollzoom

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2343]
If you scrollzoom on a Mapbox map with a selection, the selection box (or lasso) does not update its size after zooming:

![image](https://user-images.githubusercontent.com/1865834/35892610-1c9cdeaa-0b78-11e8-8940-8172657d438b.png)

**Comment by etpinard** [comment]
Same goes for all subplot types.

Maybe we should just clear the selection region on scroll (not the selected points of course).

**Comment by etpinard** [comment]
Ok this is actually a little different for cartesian subplots. My mistake.

 Starting from https://codepen.io/etpinard/pen/xYRqOj?editors=0010 we get:

![peek 2018-02-07 11-45](https://user-images.githubusercontent.com/6675409/35928981-6f5ef22a-0bfc-11e8-8b05-74ce44e17c0b.gif)

that is the select box does not clear on scroll zoom (just like on mapbox subplots) but does clear on scroll end. The cartesian behavior is _little bit_ better but still not right.

I still think clearing the select box on scroll start for all subplot types would be the cleanest way to fix this bug. But thinking about https://github.com/plotly/plotly.js/issues/1851, we might have to come up with something more powerful. We can't just describe select box and lasso path in data coordinates (e.g. like data-ref annotations) because on non-cartesian subplot select box and lasso paths are allowed to extend pass the subplot's plot area e.g. for polar:

![peek 2018-02-07 11-52](https://user-images.githubusercontent.com/6675409/35929382-60fbce6e-0bfd-11e8-85f6-8bbac2ea93c4.gif)

**Comment by alexcjohnson** [comment]
> I still think clearing the select box on scroll start for all subplot types would be the cleanest way to fix this bug.

👍 

> But thinking about #1851, we might have to come up with something more powerful. We can't just describe select box and lasso path in data coordinates (e.g. like data-ref annotations) because on non-cartesian subplot select box and lasso paths are allowed to extend pass the subplot's plot area 

As part of #1851 we could consider making the selection outline persist through scroll/zoom *for cartesian subplots* but I don't feel like that's a particularly valuable addition, and as you point out it won't work for other subplot types. Extending past the plot area is one issue, though in principle we could sort that out by using the natural extension of the data<->px mapping. But a bigger problem is that for some subplot types - polar and geo at least - a rectangle is no longer necessarily a rectangle after you zoom, straight lines are no longer straight. So even if you were able to properly transform the selection region into one with curved boundaries, we wouldn't be able to use the same UI to modify the region afterward.
