### ISSUE TITLE
error bars: add symmetric: true to _fullData when type is 'sqrt'

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#2359]
The editor's controls rely on gd._fullData to display widgets.
For error bars, when we're setting type to 'sqrt', gd._fullData no longer contains the `symmetric` key.

Since error bars type 'sqrt' is only applicable to symmetric error bars, correct? Would it be possible to include a `symmetric: true` to _fullData?

We want to avoid putting exceptions code into the editor for things like this.

Here's a codepen: https://codepen.io/veraz/pen/bLRdVb

**Comment by alexcjohnson** [comment]
`type: 'sqrt'` doesn't use the `symmetric` attribute, so it should not be part of `_fullData`. I guess ideally we'd design the attributes so that missing (`undefined`) is falsy - which in this case would mean using an attribute `asymmetric` instead of `symmetric`... perhaps we should make that change in v2, but for v1 would it be too much to ask to treat `symmetric=undefined` like `symmetric=true`?
