### ISSUE TITLE
scattergl issues with opacity and clustering

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2374]
![screen shot 2018-02-15 at 2 13 04 pm](https://user-images.githubusercontent.com/2678795/36276031-999c3e80-125a-11e8-9f3a-347e57905baa.png)

See https://codepen.io/alexcjohnson/pen/OQOMmp - two issues are apparent here:
- Color and opacity stop being assigned properly after 4K points. Occasional points beyond this get the right color, but most get some random constant. Note that this problem doesn't happen if you remove opacity, see #1909.
- I asked for 20K points, the clustering algo is removing way too many of them.

cc @dfcreative @etpinard

**Comment by dfcreative** [comment]
* 20K points was an edge case of detecting pixel size only by width, fixed in https://github.com/dfcreative/regl-scatter2d/commit/9133a03700ee9e63c7185b39838d3670c4a7daca#diff-168726dbe96b3ce427e7fedce31bb0bcL375.
* 4096 colors limit - that takes a separate effort. We cannot easily increase palette texture size, that linearly affects performance, and for say 4096×4096 colors initial load will be extra ~150ms or more (if not 500ms). As for color quantization - it needs a separate package for efficient decomposing voronoi diagram, as described [here](https://en.wikipedia.org/wiki/Color_quantization). Because basically for every new data point with unknown color we have to find nearest cluster, and making such search for 10k points or more is inefficient.

**Comment by dfcreative** [comment]
@alexcjohnson should be fixed with #2377 
![image](https://user-images.githubusercontent.com/300067/36326675-ed9f9a70-1329-11e8-8e91-7de3f680b9c4.png)

**Comment by etpinard** [comment]
fixed by https://github.com/plotly/plotly.js/pull/2377
