### ISSUE TITLE
uneven arrays in parcoords

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2405]
Currently if you pass uneven arrays to parcoords, everything gets truncated to the shortest array. In #2399 I tweaked it a little bit to drop length-0 `dimensions[i].values` arrays, and it's *probably* fine to continue truncating to the shortest non-empty `values` array. But for correspondence with other trace types, it seems like `line.color` should not be able to omit points, but instead should pick a default color for latter points - black perhaps, or white if you're on a dark background?

See https://github.com/plotly/plotly.js/pull/2399#discussion_r170634399

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
