### ISSUE TITLE
Uncaught error when user zoom (by mouse) or click on graph layer

### ISSUE THREAD

**Issue by skyandrd** [plotly/plotly.js#2438]
Hello. A bug can be reproduced here https://codepen.io/skyandrd/pen/oERddp

When I click (or double click) on the graphics or select it with the mouse to zoom in, the browser console displays an error:
index.html:1 Uncaught (in promise) undefined
Promise.then (async)
update @ plotly-latest.js:127424

**Comment by etpinard** [comment]
Hmm. I can't reproduce.

Could you share a videocast of the interactions that induce the uncaught error(s) to help us out?

**Comment by alexcjohnson** [comment]
I see that error - draw a zoombox and hold it for a couple of seconds, such that a few of these `Plotly.update` calls happen from the `setTimeout`. It's an intentional `Promise.reject` [here](https://github.com/plotly/plotly.js/blob/3bff26f7ef21c8ca43122e86214d268f57b77418/src/plot_api/plot_api.js#L146) added way back in https://github.com/plotly/plotly.js/pull/226. We bail out of redrawing the plot at that point because there's an interaction ongoing, and I guess the returned `Promise` is rejected as a signal to the user that this happened. It's not clear to me that this is a problem though, or if it is a problem what the solution should look like.

**Comment by iMaximal** [comment]
Same problem :-(

**Comment by skyandrd** [comment]
@etpinard The screencast is attached [https://drive.google.com/open?id=1TEm_GefV4OXFsg8uvL_LlHayyaQLOodU](url)

**Comment by etpinard** [comment]
Related https://github.com/plotly/plotly.js/issues/2382

**Comment by etpinard** [comment]
Merged into https://github.com/plotly/plotly.js/issues/3305
