### ISSUE TITLE
idiosyncrasies in horizontal bar chart hover with a line

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2463]
(forwarding on from the dash community forum: https://community.plot.ly/t/hover-showing-wrong-labels-in-barchart-scatter-graph/8867/4)

https://plot.ly/~Ireneg555/4/#plot

Example:
![horizontal hover](https://user-images.githubusercontent.com/1280389/37184819-4bec4772-230b-11e8-83c5-9162ff4c0bb9.gif)

User noticed a few things:
- Hover switches back and forth from bar to line unpredictably
- User can't hover over the second bar ("cables")

**Comment by alexcjohnson** [comment]
Man, we should just make `closest` the default hovermode - see also #778. But also I guess in this case `compare` should still be able to be `y` (like it is with just a horizontal bar chart), not `x` like I guess it reverts to when you add the scatter trace.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
