### ISSUE TITLE
Corrupt toolbar

### ISSUE THREAD

**Issue by dwjp** [plotly/plotly.js#2476]
See the second plot here: https://dashboard.hpc.unimelb.edu.au/status/ (screenshot below for posterity). Result is same in Firefox and Chrome.

![screen shot 2018-03-15 at 11 22 25 am](https://user-images.githubusercontent.com/5535606/37437808-40192126-2843-11e8-8c71-34ce838a3d7f.png)

Apologies this isn't in a self-contained example, can do if underlying issue isn't immediately obvious. 

I gather this is an issue with the styles inherited from my university's stylesheet, and that perhaps plotly.js should be overriding something extra to avoid this?

**Comment by alexcjohnson** [comment]
Seems like the culprit is `uom.css` -> `.uomcontent svg { width: 100%; }`
You've got `.uomcontent` wrapping the entire contents of the page, meaning you've reset the defaults for all `<svg>` elements on the page. The first plot is immune because it's in an iframe.

I suppose we could use our own (more targeted) css to re-reset this attribute, but it seems like a losing battle for us to try and reset *every* attribute that might come up. Any way you can handle that on your end, something like `.uomcontent .plotly svg { width: auto; }`?

**Comment by dwjp** [comment]
Thanks @alexcjohnson 

Yes, I have my own stylesheet after the 'official' one which I can use to override, and that works with the attribute you suggested.

I don't have a good sense for just how many attributes might need to be reset to make this bulletproof, hopefully this particular case is rare enough that this issue will put others on the right track.
