### ISSUE TITLE
Tools (e.g. select) should not execute on contextmenu

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#248]
All tools (e.g. select) have their click handler invoked when right-clicking.

**Comment by etpinard** [comment]
Can I ask you why?

**Comment by joshua-gould** [comment]
I'd like to create a custom popup menu on right-click (contextmenu event)

**Comment by etpinard** [comment]
@joshua-gould I labelled this issue with the `community` tag meaning that the no plotly.js team member will dedicate time to it, but PR are welcomed to address this issue.

**Comment by AlexVvx** [comment]
Hi, guys. I pulled pr about context menu. When {rightClick: false} is in options, then 'contextmenu' event will be fired on element and default browser menu prevented. Please take a look at https://github.com/AlexVvx/plotly.js/pull/1/files

**Comment by alexcjohnson** [comment]
@AlexVvx interesting, thanks for the PR! I wonder though if there isn't a simpler solution - we probably don't really want to trigger `dragelement` if you right click no matter what. Can we just look at `e.button` and/or `e.buttons` and bail out of `onStart` if it's not a left-click? If we do that, your own `contextmenu` event handler should pick up the event, right?

I haven't looked at browser support of the button attributes - note that we target IE9+ in addition to current versions of Chrome, FF, Edge, and Safari.

Touch interactions are an interesting case, you generally get `contextmenu` on a long press there, right? But might this already work correctly, since in touch environments we don't create a `coverSlip` at all (which I'm assuming is what interferes with the expected `contextMenu` on desktop)?

**Comment by AlexVvx** [comment]
Sounds good, applied changes in [new pr](https://github.com/AlexVvx/plotly.js/pull/2)

**Comment by alexcjohnson** [comment]
closed by @AlexVvx in https://github.com/plotly/plotly.js/pull/2087
