### ISSUE TITLE
Sankey nodes overlap by default

### ISSUE THREAD

**Issue by rahulsindc** [plotly/plotly.js#2480]
Hi there,

As you can see [here](https://rahulsindc.github.io/BF-visualisations/funding.sankey.html), a relatively simply sankey will often end up with nodes overlapping with other nodes, and the outgoing flows stacked as well. The code generating this diagram can be found [here](https://github.com/rahulsindc/BF-visualisations/blob/master/funding.sankey.html)

Is there a reason this is happening?

Thanks!
R

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by rahulsindc** [comment]
Update: It appears to be browser-specific; Chrome 65 has this issue, but the diagram renders property on Safari 11 (both on Mac OS 10.13 High Sierra)

**Comment by alexcjohnson** [comment]
And yet a different result in FF (image is Chrome / FF / Safari):
![screen shot 2018-04-29 at 1 18 54 pm](https://user-images.githubusercontent.com/2678795/39409159-11f51828-4bb0-11e8-810b-d5c6a6445929.png)

Here it is as a pared-down codepen https://codepen.io/alexcjohnson/pen/NMdMbE?editors=1010
Even in Safari it's not quite right - there is no overlap at least, but there's a net upward shift from left to right that should not be there.

**Comment by alexcjohnson** [comment]
Update: the issue here is with a link with `value: 0` (element 5 in this graph's `link.value` array, that leads to node 15 having zero size). If I replace that with anything positive the layout is fixed. The zero results in a `NaN` in the node list, and I suspect the breakage and the browser-dependence of the problem have to do with strange handling of `NaN` in `Array.sort` or the like.

Obviously we need to prevent a zero (or otherwise invalid) `value` from breaking things, but the question then is, what *should* this do? Should we delete it completely? Draw it as a very thin node & link (labeled as size zero)?

Negative or non-numeric values I feel confident we should ignore, but I feel like there may be cases you still want a zero-size node to show up. Thoughts?
