### ISSUE TITLE
Fuzz testing inputs

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2491]
We may be able to flush out some obscure bugs by doing some fuzz-testing on our input JSON. https://en.wikipedia.org/wiki/American_fuzzy_lop_(fuzzer) is an impressive piece of software which has been used to automatically discover a number of bugs in various open source libraries. There exists a few different attempts at porting this approach to Javascript, notably https://github.com/connor4312/js-fuzz and we might be able to leverage these to find novel test cases.

As a starting point, I would be interested in finding pairs of inputs `X_in` and `Y_in` such that, in pseudocode:

```javascript
clearDiv();
X_out1 = Plotly.react(X_in);
Y_out1 = Plotly.react(Y_in); 
X_out2 = Plotly.react(X_in);
X_out1 != X_out2;
```

We could also try to flush out some cases of sequences of `Plotly.update()` pairs which are intended to do and undo changes to ensure that they are undone correctly.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
