### ISSUE TITLE
Plotly.react sequence and subplot bgcolor

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2509]
The following Pen shows a simple pair of calls to `Plotly.react` which causes the `plot_bgcolor` to be applied to the gridlines of one of the subplots instead of its background: https://codepen.io/nicolaskruchten/pen/QmQXMK

**Comment by alexcjohnson** [comment]
Alright, this one isn't as bad as it looks... the grid actually *is* supposed to be this color (which is a slightly darkened version of the red background), since we blend `plot_bgcolor` with the default line color in order to avoid unnecessary opacity. The problem is just that we're not creating the right background rect for the new subplot.

**Comment by alexcjohnson** [comment]
And yes, happens with relayout as well:
```js
Plotly.newPlot(gd,
  [{x:[1],y:[2]},{x:[3],y:[4],xaxis:'x2',yaxis:'y2'}],
  {xaxis2:{overlaying:'x'},yaxis2:{overlaying:'y'},plot_bgcolor:'red'}
)
Plotly.relayout(gd,{
  'xaxis.domain':[0, 0.4],
  'xaxis2.domain':[0.6,1],
  'xaxis2.overlaying':null
})
```
