### ISSUE TITLE
plot-schema axis regex doesn't include `x1`

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2519]
In the new plotly.py PR (https://github.com/plotly/plotly.py/pull/942), we're using the plot schema for validation. The current regex for axes keys is
```
"layout": {
    "layoutAttributes": {
        ...
        "xaxis": {
              "anchor": {
                    ...
                    "valType": "enumerated",
                    "values": [
                        "free",
                        "/^x([2-9]|[1-9][0-9]+)?$/",
                        "/^y([2-9]|[1-9][0-9]+)?$/"
                    ]
              },
         },
    },
}
```

which doesn't support `x1`. The plotly.py library uses `x1` in `make_subplots` and other places as an alternative to `x`.

**Comment by alexcjohnson** [comment]
`x1` is not really accepted by plotly.js - it's generally converted to `x`, though I wouldn't say with any confidence that *every* place you can use an axis reference will make this conversion. Likewise (and this I *can* say confidently) if you pass in a layout with `xaxis1` it will be renamed to `xaxis`.

Would it be possible for plotly.py to force `x` instead of `x1` as well, either by automatically converting like we do here or simply not accepting `x1`?

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/2007

**Comment by etpinard** [comment]
I wouldn't be opposed to start to officially accept `'x1'` axis id and `'xaxis1'` axis names in plotly.js as long as we make it clear in our docs that `'x(axis)1'` refers to the same axis as `'x(axis)'`. 

We'll need to clear up what happens when `xaxis` and `xaxis1` are present in the layout. I'd say ignoring `xaxis1` in that case would suffice. We should also make `Plotly.validate` log something whenever `xaxis` and `xaxis1` are used in the same layout.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
