### ISSUE TITLE
Scattergl boxpoints on box plots?

### ISSUE THREAD

**Issue by yniknafs** [plotly/plotly.js#2534]
Sorry to hammer you again with a boxplot-related issue. I was curious how difficult it would be to employ a scattergl-like functionality to the boxpoints of the boxplot. Not sure if you are using an additional scatter trace under the hood for this? I am currently making some box plots with ~20k points, and rendering all boxpoints is prohibitively slow. Rendering just outliers works, but not ideal. I know I can add a scatter layer on top, but getting jitter to work with that will be mayhem, probably (see [#299](https://github.com/plotly/plotly.js/issues/299)).

[Attempt I found on one of the issue threads here.](https://codepen.io/yniknafs/pen/KoGjGr)

**Comment by yniknafs** [comment]
No problem. Thanks for the response. Makes sense that its low priority, figured it was worth asking if it would have been easy to plug in some underlying functionality used for scattergl. Thanks for everything you've done. plotly.js is really awesome.

**Comment by nils-fl** [comment]
Hi, I was wondering if this was ever implemented? I am trying to work with >1M points.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
