### ISSUE TITLE
Improve axis `mirror: 'allticks'` - to show multiple ticks/labels for the same axis

### ISSUE THREAD

**Issue by finger563** [plotly/plotly.js#2539]
Context:
I have multiple plots that I want to interact with that each have different y axes, but I want them synchronized on their x axes.  Right now the best way I know how to do this with plotly.js is to have them be subplots which shrare a single x-axis - but this means that each subplot does not have axis ticks or labels - which will only be shown on the "primary" xaxis.

Ideally I want them to link together for interaction (panning / zooming) but remain distinct.

How i want it to look (labels on all x-axes) but these are subplots which do not share x-axes and therefore do not interact together:
![image](https://user-images.githubusercontent.com/213467/38514469-e88d2f7a-3bf6-11e8-8d53-1ae4836949cc.png)

How it looks when they share the same x-axis (and therefore interactivity):
![image](https://user-images.githubusercontent.com/213467/38514521-0f07d0ce-3bf7-11e8-8a4c-e0ce89b2f8e1.png)

Is there something I'm missing that will let me synchronize the x-axes across multiple subplots? or a way to have each subplot xaxis have the labels?

**Comment by alexcjohnson** [comment]
Right, there's no way to replicate the tick labels and title across multiple subplots. Once we implement https://github.com/plotly/plotly.js/issues/1549 that will be one way to do it, though that would be kind of heavy, both in terms of having to specify all the config multiple times and probably in terms of performance.

Better would be for us to make some options within the one axis to replicate its tick labels and/or title. It can also be nice to show labels both top and bottom, if you have a single especially-large subplot.

Supposedly we already have this for the tick *marks* using `{ticks: 'inside', mirror: 'allticks'}` but a) you're not using tick marks here so that wouldn't help you, and b) `'allticks'` doesn't seem to work ATM - so I'll give this issue a `bug` label to remind us to fix that (though it's probably been broken for a while so it doesn't seem many people care about this...)

**Comment by karlicoss** [comment]
I think I've managed to achieve this by explicitly setting the `showticklabels` attribute:

```python
    N = len(plots)
    figg = make_subplots(
        rows=N,
        cols=1,
        shared_xaxes=True,
        **kwargs,
    )
    for i in range(N):
        xaxis_name = 'xaxis' if i == 0 else f'xaxis{i + 1}'
        getattr(figg.layout, xaxis_name).showticklabels = True
```

I get simultaneous zooming and tick labels displayed under each subplot

**Comment by HendrikRoehm** [comment]
The solution suggested by karlicoss did not work for me in javascript. However, I found another hack: add a css text-shadow to the xaxis svg container via css. For example adding two copies of the xaxis labels:
```
.xaxislayer-above {
     text-shadow: 0 -262px, 0 -490px;
}
```
This should not harm the performance, but the offset has to be computed manually.

**Comment by rpanai** [comment]
> ```python
> for i in range(N):
>         xaxis_name = 'xaxis' if i == 0 else f'xaxis{i + 1}'
>         getattr(figg.layout, xaxis_name).showticklabels = True
> ```

you could avoid `getattr` using

```python
for i in range(N):
        xaxis_name = 'xaxis' if i == 0 else f'xaxis{i + 1}'
        figg.layout[yaxis_name].showticklabels = True
```

**Comment by pablomadoery** [comment]
fig.update_xaxes(showticklabels=True) will show xticks for all subplots.
put it after making all subplots.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
