### ISSUE TITLE
Implement 'style' editType for scattergl and splom traces

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2553]
Currently, scattergl and splom traces have to go through `editType: 'calc'` pathway to update style attributes. We should open up a new pathway to for things like `marker.color` and `line.width` that doesn't have to go through all the data type conversion done in the `calc` step.

**Comment by etpinard** [comment]
Splom part done in https://github.com/plotly/plotly.js/pull/3057

Shouldn't be too hard to implement this for `scattergl` now.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
