### ISSUE TITLE
Pass DOM event to "plotly_click" event for 3D plots

### ISSUE THREAD

**Issue by gfpeltier** [plotly/plotly.js#2565]
I would like to be able to determine if a user clicks on a 3D surface plot with the right mouse button. It would be nice to get the same information passed to plotly_click events for cartesian plots.

Is there a version where this was possible? I noticed this was implemented in #1505 but am unsure if it ever worked for 3D plot types.

**Comment by kirsan31** [comment]
Yea was totally surprised today when got, that there are no `event` in `plotly_click` with `scatter3d`.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
