### ISSUE TITLE
500k point ScatterGL: unselected points don't fade on second selection

### ISSUE THREAD

**Issue by jmmease** [plotly/plotly.js#2586]
### Overview
When displaing a scattergl trace with a large number of points (> 500k), the second time the selection tool is used the unselected points don't fade into the background.

### To reproduce:
1) Run the following codepen (scattergl with 500k points): https://codepen.io/anon/pen/zjoWpO

2) Perform lasso selection
![screen shot 2018-04-27 at 12 46 05 pm](https://user-images.githubusercontent.com/15064365/39374566-3bf889fe-4a19-11e8-878d-df8bb7914722.png)

Note that unselected points fade into the background as expeccted

3) Double click to clear selection

4) Perform lasso selection again:
![screen shot 2018-04-27 at 12 46 19 pm](https://user-images.githubusercontent.com/15064365/39374569-440b3894-4a19-11e8-8983-fc9f76a6b2a8.png)

Note that now there is no contrast between selected and unselected points

### Comments
 - This doesn't seem to happen with 10k points
 - plotly.js version: 1.36.1
 - Chrome version: Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by etpinard** [comment]
@dy any ideas?

**Comment by dy** [comment]
Oh, unfortunately that is regl issue, demanding it insert `regl._refresh()` here and there. I tried to nail it couple of times, to no success, since it requires some complex shader setup. Btw inserting `regl._refresh` affects drawing performance ~6 times for a thousand of rendering passes, which might be a case for `regl-splom` or multitrace plots.

**Comment by etpinard** [comment]
@dy did you file a bug report to regl about this?
