### ISSUE TITLE
Legends lose state on Plotly.react update

### ISSUE THREAD

**Issue by tropys** [plotly/plotly.js#2608]
When using Plotly.react to update a plot with legends, after an update the legend loses its state and any toggled traces show up again. 

Codepen:  https://codepen.io/steph_curried/pen/Qrgxyz
Hide a trace by clicking its legend and wait for react to be called.

**Comment by alexcjohnson** [comment]
The issue here is that hiding the trace via legend updates (mutates) that trace in `data`, and when you rebuild the state for the new `Plotly.react` call you're discarding that update.

Typically what we do in cases like this is build the new state for `Plotly.react` as a modified version of the old state (in `gd.data` and `gd.layout`, which should in fact be the objects you previously passed in to `Plotly.plot` or `Plotly.react`) so that any user-initiated changes in that state - others include zooming in, changing `layout.hovermode` or `layout.dragmode` - will be incorporated in the new state. But to resolve *just* the legend-set visibility issue, you could include it explicitly like https://codepen.io/alexcjohnson/pen/gzRZQR

**Comment by etpinard** [comment]
This issue appears resolved. Can we close this?

**Comment by alexcjohnson** [comment]
Yes, I think so. @tropys feel free to reopen if I'm missing something, or to discuss strategies for using `Plotly.react` effectively you may find https://community.plot.ly/ more helpful.
