### ISSUE TITLE
Replace "dataScale" hack in 3D subplots

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2646]
From https://github.com/plotly/plotly.js/pull/2641#discussion_r189329872

We should spend some time replacing this `dataScale` hack. This thing was added to make date axes work properly in 3D. Timestamps don't fit in a Float32Array, so we can't just convert the datestrings to timestamps, but we do this better in `scattergl`, where we use Float64Array or split the data into two Float32Arrays when not supported.

Fixing this should improve autorange results and make incorporating upcoming gl-vis components much easier!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
