### ISSUE TITLE
SciPy 2018 Paper Review

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#2648]
Hi All,
     I've submitted the first draft of my paper for SciPy 2018 on bringing ipywidgets support to plotly.py.
scipy-conference/scipy_proceedings#395 (Current PDF is attached to main description).

There is a fair amount of material here on Plotly.js under the "Plotly.js Overview" section, and I wanted to give you all a chance to look it over during the review process. 

Feel free to close this issue if you're fine with what's there, or if you don't care to review it!
Thanks

**Comment by jmmease** [comment]
Thanks for the feedback @alexcjohnson! The snippets are supposed to be JSON (or JavaScript code in the case of the Plotly.js command arguments). I'll make everything consistent with double-quoted keys and double quoted strings so it's valid JSON.

No, ``Plotly.react`` isn't being used in the new version.  All of the Python mutation operations are converted into ``relayout``, ``restyle``, ``update``, ``addTraces``, ``moveTraces``, ``deleteTraces``, or ``animate`` commands (Figures 5 and 6 from the paper).  Part of the reason for this is that the architecture predates ``react``, the rest of the reason is that I don't want to send the full figure state from Python to JavaScript when only a subset of the properties have changed.  By mapping everything to the commands above we only need to serialize the args for the individual command, which is generally smaller than the full figure state.

**Comment by etpinard** [comment]
OK if we close this @jonmmease ?

**Comment by jonmmease** [comment]
Yes. The paper was actually merged yesterday. Thanks!

**Comment by etpinard** [comment]
> The paper was actually merged yesterday.

Great news :tada:
