### ISSUE TITLE
Draw() & update() fails to draw traces when first trace y property consists of nulls

### ISSUE THREAD

**Issue by GlennMatthys** [plotly/plotly.js#2661]
Reproduction link (newPlot): https://jsfiddle.net/n1teax2o/2/
Reproduction link (update): https://jsfiddle.net/703a5bnf/1/

Observed behavior: When drawing two or more traces, and the first trace's y property is all nulls, no traces are drawn even if subsequent traces do not have nulls in their y property.

Expected behavior: Traces that don't have nulls in their y property are drawn correctly.

As a side note, the intention of this graph in particular is to only draw markers where (x, y) !== null and not draw markers where (x, y) === null. End result like this:

![image](https://user-images.githubusercontent.com/31989842/40482574-92574f46-5f55-11e8-9386-6de0b90c5f37.png)

**Comment by alexcjohnson** [comment]
Thanks for the clear reproductions @GlennMatthys! The issue here is that we only look at the first trace to automatically determine the axis type - if you add `yaxis: {type: 'category'}` to your `layout` it works as you expect (unless you were hoping for trace 0 to still contribute a category - if you want that you'll need a different solution like `yaxis.categoryarray`, or use numbers for the y data along with `ticktext`/`tickvals`).

I suppose we could look at subsequent traces for the axis autotype if the first trace is empty like this... sure, I'll slap a `bug` label on this and at some point we'll try that.

**Comment by GlennMatthys** [comment]
Perhaps just documenting this is enough. I solved it in my code by detecting whether the array consists of all nulls (I was already looping through all the source values anyway) and then replacing the y property with an empty array (saves some memory too). That seems to make Plotly skip over to the next non-empty array to automatically determine axis type, is that the intended behavior?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
