### ISSUE TITLE
Selection box stays after panning

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#2669]
I see an issue when I draw a selection box on the points on a scattergl plot, and then I pan.
 
After I select a range of points and then I use the modifier key 'alt-select' (to subract) or 'shift-select' (to add) I can see the previously drawn selection box and it has not moved even though the plot has shifted range. 

EXAMPLE:
http://recordit.co/Z6r2ZPUMoo

Also, I can't find documentation about the modifier key 'add-select' or 'subtract-selection' tools. 
Is there a dragmode: 'select-add' or a way to programmatically use these dragmodes?

**Comment by etpinard** [comment]
Ha. Nice catch @destradafilm thanks for the report.

This bug is similar to https://github.com/plotly/plotly.js/issues/2667 (the optimizations of https://github.com/plotly/plotly.js/commit/bb022818e7fe6c2c808ad440a633558398853325 are likely to blame) but will require another patch.

I'll try to squeeze that one in before 1.38.1 .
