### ISSUE TITLE
gl3d hover labels get clipped to the scene

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2695]
They should be able to overflow the scene like other subplot types do. gl3d:

![screen shot 2018-06-05 at 3 29 06 pm](https://user-images.githubusercontent.com/2678795/40998260-3d0ee902-68d5-11e8-82d1-ac3cdfe81f5c.png)

vs eg cartesian:

![screen shot 2018-06-05 at 3 30 12 pm](https://user-images.githubusercontent.com/2678795/40998305-6853281c-68d5-11e8-8a6d-48b8d39b144f.png)

**Comment by etpinard** [comment]
Thanks for pointing this out. We still draw hover labels in a per-3d-scene `<svg>` container. 

We should draw those in `<g.hoverlayer>`.

**Comment by etpinard** [comment]
w

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
