### ISSUE TITLE
Separate tool-tip with text for candlestick feed (high,low,open,close) value.

### ISSUE THREAD

**Issue by md-nasir** [plotly/plotly.js#2706]
I have a problem when I want to display candlestick hoverinfo in separate tool-tip.
I want to show hoverinfo(high,low,open,close) with separated tool-tip like the image bellow.
![accept hover text](https://user-images.githubusercontent.com/28702419/41077271-7fc35978-6a37-11e8-8523-7c04e9bc4627.PNG)
But I confirm by asking a question on plotly community that's plotly.js support candlestick hoverinfo(high,low,open,close) in one tool-tip  like the image bellow.
![Supported hover info](https://user-images.githubusercontent.com/28702419/41077306-c3b9cbe4-6a37-11e8-83f2-348916b95a27.png)
Reference : https://community.plot.ly/t/is-it-possible-to-show-separate-tooltip-with-text-for-candlestick-feed-high-low-open-close-value/10724?u=nasirfardoush

**Comment by alexcjohnson** [comment]
Seems reasonable - perhaps even just change to 4 separate tooltips as you suggest, rather than making this configurable. This is already basically what we do for box plots:
![screen shot 2018-06-07 at 10 10 36 am](https://user-images.githubusercontent.com/2678795/41105185-157f2afc-6a3b-11e8-9553-1ef83fd19150.png)
Could make a great first PR if you're looking to get involved - look at how [box hover](https://github.com/plotly/plotly.js/blob/95c88e686601a7c3fa109d6f87c91be0c1b5a667/src/traces/box/hover.js#L48) works and fit something similar into [OHLC hover](https://github.com/plotly/plotly.js/blob/master/src/traces/ohlc/hover.js) (which is shared by candlestick)
