### ISSUE TITLE
plotly_click and plotly_doubleclick don't register on parcoords charts

### ISSUE THREAD

**Issue by DDunc** [plotly/plotly.js#2716]
Reproduced with example forked from the docs on Firefox 60.0.1 and Chrome 66.0.3359.181:  https://codepen.io/anon/pen/eKgYPg?editors=1010

If plotly_click/doubleclick events not working on some types of charts or settings is currently the expected behavior, it would be very helpful to add that somewhere in the docs, thanks!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
