### ISSUE TITLE
Time Axis is not correct

### ISSUE THREAD

**Issue by guitar9** [plotly/plotly.js#2720]
When I use time Axis the left tick is not visible (first picture). Or when i use hour the 0.00 hour or the date (i dont know)  is not visible. (second Picture) At the thrird picture eversthing is okay. This  problem is everytime in the same date range. I use chrome and firefox
My Version:     "plotly.js": "^1.38.2"

![github1](https://user-images.githubusercontent.com/25721108/41232293-32232390-6d86-11e8-9bdd-2860cb149c50.png)
![github2](https://user-images.githubusercontent.com/25721108/41232294-323c4bf4-6d86-11e8-84c5-aed0fd29326e.png)
![github3](https://user-images.githubusercontent.com/25721108/41232295-325749c2-6d86-11e8-8a5d-8bc6178b3a0a.png)

**Comment by alexcjohnson** [comment]
@guitar9 can you make a codepen or other reproducible example? If you're seeing this in a complex page you can pull your figure data out using `Plotly.Plots.graphJson(gd)` then paste it into a codepen. Thanks!

**Comment by guitar9** [comment]
What  is gd?

**Comment by alexcjohnson** [comment]
Right, sorry, that's one we haven't officially documented but it's useful in cases like this. `gd` is "graph div", the DOM element you rendered your plot into. If you just have one Plotly plot on the page you can do `gd = document.querySelector('.js-plotly-plot')`

**Comment by guitar9** [comment]
How can i use this data to create a new Plot?

**Comment by alexcjohnson** [comment]
Thanks for trying it standalone in codepen. The fact that it works there certainly implies either a problem with the build process you're using - though that looks fine to me and usually problems there manifest themselves earlier than this - or an interaction with something else on the page.

Looks to me like the problem is with the class `.line` we apply to multiline SVG text `<tspan>` elements. All the single-line labels appear as they should, all the multiline labels disappear. Is it possible you can find the style rule that's hiding (or moving?) these elements, and make it more specific? I suppose if all else fails you could override it with your own super-specific-to-plotly rule like:

`.js-plotly-plot .plotly tspan.line { reset whatever's being mucked up }`

but it would be much better (more robust and maintainable) to narrow the original rule if possible.

**Comment by guitar9** [comment]
that was the problem.
I have overriden the class .line.
Can be closed.
