### ISSUE TITLE
transforms[0].groups in aggregation targets

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2726]
If I add two transforms to a trace: a group-by and an aggregate, then `_fullData` contains an extra element in the aggregate transform's aggregation list with a target of `transforms[0].groups` which doesn't seem to serve any purpose.

/cc @alexcjohnson

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
