### ISSUE TITLE
Scatter3d projection should work with lines too

### ISSUE THREAD

**Issue by ischurov** [plotly/plotly.js#273]
It seems that currently `Scatter3D` `projection` option doesn't work with `lines` mode, only with markers. I believe it should work with `lines` too.

See [example](http://nbviewer.jupyter.org/url/schurov.com/Projection%20in%20Scatter3D.ipynb) for details.

**Comment by kewi4** [comment]
Is this feature in plan?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
