### ISSUE TITLE
Respect sizemode='area' when marker.size is a constant

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2735]
When `marker.size` is a constant, `marker.sizemode` is currently silently ignored (i.e., it's always set to diameter, regardless of whether the user specified `marker.sizemode='area'`):

https://codepen.io/cpsievert/pen/zazXgw

At the very least I think this should generate a warning/message. IMO the behavior should change at some point so that `marker.sizemode='area'` is respected, regardless of whether `marker.size` is a number or an array -- perhaps an item to add to https://github.com/plotly/plotly.js/issues/420?

**Comment by etpinard** [comment]
> At the very least I think this should generate a warning/message.

Plotly.validate can do that for you: https://codepen.io/etpinard/pen/zazQNP?editors=0010

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
