### ISSUE TITLE
Option to translate graph title in plotly

### ISSUE THREAD

**Issue by gFaro** [plotly/plotly.js#2741]
There seems to be no way to translate graph title texts in plotly.js.

I tried to include my text in the language dictionary but this did not work. I noticed that for the default translations, you guys did something like _(gd, 'text'). Is there a way to make this functionality available in for custom text translations.

**Comment by alexcjohnson** [comment]
Interesting... we had only considered the built-in text of the library to be in scope for translation, I suppose it would be possible to allow translation of the contents of the plot as well. Might even be possible to build this into `svg_text_utils` so it gets applied uniformly with minimal footprint. @etpinard thoughts?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
