### ISSUE TITLE
Streamtube open items

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2781]
Follow-up of https://github.com/plotly/plotly.js/pull/2658

- [ ] investigate `gl3d_streamtube-first` _pinched sausage links_ problems (see https://github.com/plotly/plotly.js/pull/2658#issuecomment-402277291 for more info) and more generally improve tube generation beyond data-limits. This one should probably be considered a bug; it might deserve an issue of its own.
- [ ] add way to "stop" tubes that overlap (more info in https://github.com/plotly/plotly.js/pull/2658#issuecomment-395486321)
- [ ] add `sizemode` with values `'scaled'` (the default and current behavior), `'absolute'` (similar to cones) and `'fixed'` to plot stream _lines_.
- [ ] perhaps add ways to tweak automatic starting positions with some other attributes that might be nice to collect all in a sub-container.

cc @kig @alexcjohnson

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
