### ISSUE TITLE
start zooming outside of boundary

### ISSUE THREAD

**Issue by wangyueming** [plotly/plotly.js#2817]
My client has complained for half a year that he can not start zooming outside of boundary. When he puts his left button of the mouse down outside of boundary, he can not initial a zooming.

Is it possible?
![26755cbd-8fb9-4f4f-8677-8c6aac7928c4](https://user-images.githubusercontent.com/10303419/42732054-4c08709a-884c-11e8-9d4a-cb8985549e05.png)

**Comment by alexcjohnson** [comment]
It's hard to see this working, because we use the area just outside the plot for other interactions. In your example the exact starting point of your "this direction not possible" arrow is unused, but on the other three sides, where there's an axis, a click-and-drag will pan just that axis (if you start near the middle) or change just one end of that axis range (if you start near either end). If you put an axis on top as well, then all sides serve as the starting point of another interaction.

In addition, a click-and-drag starting from just outside any corner of the plot will change the corresponding end of all axes. So if the reason your client wants to start outside the plot is that their goal is, for example, to preserve the coordinates in the upper left corner while zooming the lower right, perhaps dragging the lower right corner would suit their needs?

**Comment by etpinard** [comment]
This ticket probably won't result in a PR. Closing.
