### ISSUE TITLE
Parallel plots: Add an api to show/hide lines in parcoords plots

### ISSUE THREAD

**Issue by siakouchine** [plotly/plotly.js#2820]
Hello,
as I mentioned in https://community.plot.ly/t/is-it-possible-to-hide-lines-in-parallel-coordinates-plot/10311, it would be very useful to add the possibility for parallel coordinates plots to allow hiding/showing lines that share the same color. 
Interactively, from a discrete colorbar, "Hide all but this" when the user "double-clicks" on a color, would be a plus.
Thanks.

**Comment by archmoj** [comment]
Instead of display/hide `boolean` a feature similar to `opacityscale` (which is available in `volume` trace) may be of interest here.

**Comment by etpinard** [comment]
> Instead of display/hide `boolean` a feature similar to `opacityscale` (which is available in `volume` trace) may be of interest here.

+1

**Comment by siakouchine** [comment]
Very good idea.
+1

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
