### ISSUE TITLE
Color by a numeric array in groupby styles is broken

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2886]
This works:
```js
Plotly.newPlot(gd,[{
  x: [1,2,3,4,5,6],
  y: [1,2,3,4,5,6],
  mode: 'markers' ,
  transforms: [{
    type: 'groupby',
    groups: [1,2,1,2,1,2],
    styles: [{target: 2, value: {marker: {color: ['red', 'black', 'red']}}}]
  }]
}])
```

But replace the color array with numbers and it fails
```js
Plotly.newPlot(gd,[{
  x: [1,2,3,4,5,6],
  y: [1,2,3,4,5,6],
  mode: 'markers' ,
  transforms: [{
    type: 'groupby',
    groups: [1,2,1,2,1,2],
    styles: [{target: 2, value: {marker: {color: [1, 2, 3]}}}]
  }]
}])

Uncaught TypeError: Cannot read property 'autocolorscale' of undefined
    at calc (calc.js:98)
```
https://codepen.io/alexcjohnson/pen/JBeoEy?editors=0010
cc @nicolaskruchten

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
