### ISSUE TITLE
Bold text shifts slightly to the left when "right" aligned inside the cell - specific to Firefox

### ISSUE THREAD

**Issue by priyatharsan** [plotly/plotly.js#2943]
Here is a codepen example: https://codepen.io/priyatharsan/pen/JaGPxO

Please note that this issue is specific to: Firefox browser. The text string seems to create a whitespace at the end of the string when bolded. Here is a screenshot: 
![2](https://user-images.githubusercontent.com/25846124/44597880-25c36080-a79f-11e8-961b-3fe651d8a581.JPG)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
