### ISSUE TITLE
feature request - Axis Tick Label length

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#2975]
We have 'namelength' option for the 'hoverlabel' obj but it would be ideal to have the option to abbreviate the axis tick labels the same way with a similar option. 

I'm currently adding ticktext & tickvals but then it changes the tickmode to 'array'
I like the way tickmode: 'auto' handles the auto hiding/showing of ticklabels depending on the height/width of the plot. 

So if all I want to do is abbreviate (add ellipses), it will be better to use the option to set a ticklabel length for each axis.

example:
```
xaxis: 
   ticknamelength: <int> (integer or array of integers greater than or equal to -1)

*default: -1 (shows the whole  "label")
```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
