### ISSUE TITLE
scattergl doesn't draw error bars with negative lower bounds on log axes

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3009]
as can be seen from this codepen https://codepen.io/antoinerg/pen/vzrayY

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
