### ISSUE TITLE
displaying left aligned and right aligned data in hover items

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3010]
Somewhat related to #3007. The ability to better display left aligned and right aligned data like this:

![capture d ecran 2018-09-13 a 22 07 08](https://user-images.githubusercontent.com/1280389/45525562-8859bc00-b7a1-11e8-9b84-42cb830274c4.png)

Example taken from https://www.nytimes.com/interactive/2016/04/29/upshot/money-race-and-success-how-your-school-district-compares.html

**Comment by etpinard** [comment]
Related to https://github.com/plotly/plotly.js/issues/2342 also.

**Comment by etpinard** [comment]
Related to https://github.com/plotly/plotly.js/issues/1882 as well.

**Comment by etpinard** [comment]
Attributes for vertical alignment in hover labels would be nice also, from @alexcjohnson's https://github.com/plotly/plotly.js/issues/3442#issuecomment-455603144 

> But an attribute to switch that to middle-aligned or bottom-aligned would be great to add at some point.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
