### ISSUE TITLE
Feature Request: Geo: Scope: Oceania

### ISSUE THREAD

**Issue by jianqing-shi** [plotly/plotly.js#3036]
As I am working on a project using Bubble Maps, I need to make a zoom on Oceania.

But surprisingly, it seems that geo.scope doesn't  know what is this "Oceania" thing. 

Could you add this feature? So that all the continents are supported in this libarary, that could be awesome.

Many Thanks.

**Comment by etpinard** [comment]
If you want to make a PR to https://github.com/etpinard/sane-topojson adding a scope to this [list](https://github.com/etpinard/sane-topojson/blob/3efc5797df570fc7143a121d0ca9903defb8a8d5/config.json#L6-L65), we'll accept it.

**Comment by etpinard** [comment]
Update: https://github.com/etpinard/sane-topojson/pull/10#issuecomment-493460253

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
