### ISSUE TITLE
Styling portions of a trace

### ISSUE THREAD

**Issue by prakriti-p** [plotly/plotly.js#3045]
Hi,

Wondering if there is currently a direct or indirect way to apply styles (e.g. “line: {dash: ‘dot’}”) to a segment/portion/region of a trace or data series, as is done here: 

http://c3js.org/samples/simple_regions.html

**Comment by etpinard** [comment]
Interesting idea. Thanks for bringing this up.

We should probably merge this along with https://github.com/plotly/plotly.js/issues/147

**Comment by prakriti-p** [comment]
Hi Étienne Tétreault-Pinard,

Great to hear that. Can you tell me what could be the probable ETA on this?

I have a task that needs to be delivered early next week. Is there any indirect way of doing this?

Thanks so much!

**Comment by etpinard** [comment]
> I have a task that needs to be delivered early next week.

This won't happen before next week, no.



> Is there any indirect way of doing this?

I would use multiple traces.

**Comment by nitramwin** [comment]
I'd like to show my support for such a feature in the future. Applying styling features like line color and line width to the trace would be really great.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
