### ISSUE TITLE
Misalignment of horizontal box/violin hover labels

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3050]
Split out of @alexcjohnson 's  https://github.com/plotly/plotly.js/issues/2970#issuecomment-424499773

----------

The misalignment in the original multi-plot codepen https://codepen.io/kotwgarnku/pen/gdxaPN when you set the first plot to `closest` is still there (and yes, the codepen is now using 1.41.3). To be clear, I'm talking about how eg the "min" label is not pointing to the "min" value, but to where that value would be according to the bottom plot. There also seems to be a problem with the overlap avoidance algorithm when one of the labels is too long and gets flipped to the top - it's putting them out of order and then stretching them across each other.
![screen shot 2018-09-25 at 4 52 23 pm](https://user-images.githubusercontent.com/2678795/46042585-c0d39100-c0e3-11e8-94e2-17769f507abb.png)

**Comment by alexcjohnson** [comment]
In fact, flipped labels shouldn't try to avoid each other at all, since they *can't* overlap. Top and bottom labels should go through the avoidance algorithm separately, or even better (in case of hover invoked externally, that needn't produce labels with any particular alignment, and for centered labels, which we use when neither side has enough room) we could make a new algorithm that's aware of the full 2D extent of each label. That applies to regular unrotated labels too, left- and right-side labels need not avoid each other.

Also especially labels that get pushed to the left look ugly (self-crossing label outline) and it's hard to tell what's pointing where:
![screen shot 2018-09-25 at 5 26 18 pm](https://user-images.githubusercontent.com/2678795/46044284-56711f80-c0e8-11e8-880b-04feb505fde1.png)
Perhaps we can shift some of the labels vertically - in this image, we could push min and q3 down so the rotated edge of their boxes align with the rotated edge of the median box perhaps?

**Comment by etpinard** [comment]
More examples from https://github.com/plotly/plotly.js/issues/3389:

- https://plot.ly/~nicolaskruchten/252
- https://plot.ly/~nicolaskruchten/254
