### ISSUE TITLE
locationmode: 'usa-state-names'

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3054]
I'm making a choropleth and my data has the USA state names, not their abreviations. New York, not NY. In order to graph this data, I have to translate this data to abbreviations, it'd be nice if I didn't have to do that.

**Comment by Elderado-C** [comment]
Hello, how will you go about this to convert State Names to abbreviations

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
