### ISSUE TITLE
Template issues

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3055]
- [ ] Parcoords line colors not updating with `template` and `react`. The line should be blue but it’s still hotpink: https://codepen.io/chriddyp/pen/EeQoGE
- [x] I couldn’t get the carpet grid colors to update. I might be doing something wrong here with the API though: https://codepen.io/chriddyp/pen/BOYJGy **Fixed in:** #3095
- [x] Similarly I couldn’t get the radar grid lines to updates: https://codepen.io/chriddyp/pen/qMxpJy **Fixed in:** https://github.com/plotly/plotly.js/pull/3092

**Comment by etpinard** [comment]
Potentially related to: https://github.com/plotly/plotly.js/issues/3032

**Comment by etpinard** [comment]
Some info:

Parcoords line colors: 

The template propagate fine during `react`, the problem happens during the parcoords update. We can replicate this bug using `restyle` and `relayout`: https://codepen.io/etpinard/pen/YJVrKm

-----------

Carpet grid colors:

No bug here (I think). You' need to include `startlinecolor` and `endlinecolor` or `color` in your template: e.g. https://codepen.io/etpinard/pen/ZqKXOo?editors=1010

-----------

Polar grid lines:

This line:

https://github.com/plotly/plotly.js/blob/5c4094fc49e910da953b80b06f14e44332afd223/src/plots/polar/layout_defaults.js#L52-L56

is off. In fact, we _do_ need to propagate the template so that the attributes that use [`coerce2`](https://github.com/plotly/plotly.js/blob/5c4094fc49e910da953b80b06f14e44332afd223/src/plots/cartesian/line_grid_defaults.js#L30-L32) can reach into `_template`. This should be an easy fix, PR incoming.

**Comment by jonmmease** [comment]
So I've been able to get the carpet grid colors working in the carpet trace directly, but they don't seem to be coming through from the `data` portion of the template.

https://codepen.io/jonmmease/pen/NOjyya

Does my template `data` specification here look right?

**Comment by etpinard** [comment]
Good :eye: @jonmmease , fixed in https://github.com/plotly/plotly.js/pull/3095

**Comment by etpinard** [comment]
All the "real" template issues listed here have been resolved. 

The parcoords problems are now in -> https://github.com/plotly/plotly.js/issues/3101

Closing.
