### ISSUE TITLE
Make parcoords coexist with other regl-based traces

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3069]
Mostly a follow-up for https://github.com/plotly/plotly.js/pull/3067, where we should incorporate the parcoords "render" step in the `redrawReglTraces` subroutine to make cartesian/polar drag and selection work on graphs with parcoord subplots.

**Comment by etpinard** [comment]
cc @archmoj related to what we discussed yesterday.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
