### ISSUE TITLE
Contour showlines has no effect if contours.coloring != "fill"

### ISSUE THREAD

**Issue by martin-drozdik** [plotly/plotly.js#3080]
From the [documentation](https://plot.ly/python/reference/#contour-contours-showlines):

> showlines (boolean) 
> default: True 
> Determines whether or not the contour lines are drawn. Has an effect only if `contours.coloring` is set to "fill".

I think it would be nice if this restriction was lifted. Otherwise it prevents the user from creating beautiful plots like:

![newplot 2](https://user-images.githubusercontent.com/11381175/42320525-ed9e5748-8055-11e8-971a-37d33ea3bce0.png)

A workaround I use now is:

`line={'color':'rgba(0,0,0,0.0)'}`

But this is neither readable, nor efficient.

You can find the reproducible example in this repo:

https://github.com/martin-drozdik/logit-distribution/blob/80d3f4e4d25ec51524dc79020b89dfc34d9a2476/main.js#L97

There are two branches:

  1. master, where the current behavior is shown
  2. workaround, where I set the contours to transparent instead of using the `showlines: false`

**Comment by alexcjohnson** [comment]
Is `type: 'contour', coloring: 'heatmap', showlines: false`
different from `type: 'heatmap', zsmooth: 'best'`?

Anyway that's the reason we do not allow that combination of settings, because then there are actually no contours, so it's equivalent to a heatmap and therefore best to avoid the extra overhead of generating contours.

**Comment by etpinard** [comment]
Looks like this issue was resolved by https://github.com/plotly/plotly.js/issues/3080#issuecomment-427358030

Closing.
