### ISSUE TITLE
Drawing heatmaps with non-rectangular domain is very slow

### ISSUE THREAD

**Issue by martin-drozdik** [plotly/plotly.js#3081]
I made a repository to illustrate this issue:

https://github.com/martin-drozdik/logit-distribution

Checkout branch master and simply drag the slider left and right. You will see that the re-drawing of a heatmap with triangular domain takes about 500ms on my humble notebook.

I did some profiling and most of the time is spent on the `findEmpties` function.

For comparison, check out the `rectangular` branch which is much faster.

**Comment by etpinard** [comment]
Codepen version: https://codepen.io/etpinard/pen/VEjRRw?editors=1010

Thanks for the report.

**Comment by martin-drozdik** [comment]
Actually, I found that a workaround to a[ different problem
](https://github.com/plotly/plotly.js/issues/3080#issuecomment-427358030) that was suggested to me by your colleague solves the problem.

You just have to change the type of the graph from contour to heatmap:

```
type: 'contour', coloring: 'heatmap', showlines: false
different from type: 'heatmap', zsmooth: 'best'
```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
