### ISSUE TITLE
Cannot set colorscale in template for some trace types

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3100]
In working on developing templates for plotly.py I've found that I'm not able to set the colorscale and colorbar properties in the template for some trace types.

This works as I expect for the `heatmap` trace type. The defualt colorscale of Viridis and the colorbar tick properties are both applied.
Pen: https://codepen.io/jonmmease/pen/mzMeMW
```javascript
var trace1 = {
  type: 'heatmap',
  z: [[1, 2, 3], [4, 5, 6]],
};

var data = [ trace1 ];

var layout = {
  template: {
    data: {
      heatmap: [{
        colorscale: 'Viridis',
        colorbar: {
          ticks: 'inside',
          ticklen: 10,
          tickcolor: 'white'
        }
      }],
    }
  }
};

Plotly.newPlot('myDiv', data, layout);
```
![newplot-1](https://user-images.githubusercontent.com/15064365/46864559-c40b9400-cde8-11e8-835b-5be4b4e42d01.png)

But it does not work for the `scatter.marker` colorscale and colorbar.
Pen: https://codepen.io/jonmmease/pen/LgjpQG
```javascript
var trace1 = {
  type: 'scatter',
  y: [1, 2, 3],
  marker: {
    size: 20,
    color: [1, 2, 3],
    showscale: true
  },
  mode: 'markers'
};

var data = [ trace1 ];

var layout = {
  template: {
    data: {
      scatter: [{
        marker: {
          symbol: 'square',
          colorscale: 'Viridis',
          colorbar: {
            ticks: 'inside',
            ticklen: 10,
            tickcolor: 'white'
          } 
        }
      }],
    }
  }
};

Plotly.newPlot('myDiv', data, layout);
```

Note that `scatter.marker.symbol` is being picked up from the template, so I'm pretty sure the template specification is correct, but let me know if I'm missing something.

I've noticed this same behavior for other colorscales and colorbars, and I can work through an exhaustive list later today if that's helpful.  Thanks!

**Comment by etpinard** [comment]
Thanks for the report @jonmmease !

The colorscale part can be "fixed" by adding `marker.autocolorscale: false` to the template as in https://codepen.io/etpinard/pen/XxaRyB, I'm not sure if this is the desired behavior though. Perhaps we could improve the logic here:

https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/components/colorscale/defaults.js#L43-L46

where `autocolorscale` would default to `false` if a valid colorscale template is set.

As for the colorbar part, the problem comes from the colorbar defaults call:

https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/components/colorscale/defaults.js#L62

where `containerOut` is `fullData[i]` for heatmap, but is `fullData[i].marker` for scatter and other marker colorscales. Colorbar templates propagate correctly (using [`Template.newContainer`](https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/components/colorbar/defaults.js#L23))  from `fullData[i]`, but **not** from marker containers. Adding

![image](https://user-images.githubusercontent.com/6675409/46880073-b3254780-ce15-11e8-9c0f-9d3aa6738c56.png)


should be enough to fix this, but we should look for other situations where supply-defaults subroutines are called with trace sub-containers.

**Comment by etpinard** [comment]
Thanks for pointing out the relayout issue @jonmmease (-> in https://codepen.io/etpinard/pen/gBqqgo)

I'm afraid that it points to a bigger problem though. At the moment, colorscales are mutating in the input traces and thus rely on an 'implied edit' (listed [here](https://github.com/plotly/plotly.js/blob/aea6b8d796d367c3930da9753a8b9151e10cd5d8/src/components/colorscale/attributes.js#L162)) during `Plotly.relayout`. This 'implied edit' clears the `colorscale` value out of the input trace before calling `Plots.supplyDefaults` making calls like `relayout(gd, 'marker.colorscale', 'Viridis')` work as expected.

Now there are many more attributes (e.g. `cmin`/`cmax`, `contours.*` to name a few) with 'implied edits' which currently won't work with `relayout(gd, 'template', {/* */})`.

I'm not sure what the best way forward is. To stop mutating in things in input traces would solve the issue, or do something similar to the new histogram autobin logic, but those are fairly big projects. There might be an easier solution.

In the meantime, using `relayout` to update template might not be the best idea.

**Comment by jonmmease** [comment]
Thanks for the background @etpinard,

Would `react` handle this case better, or would the same issues arise?  It would be a bit of a project, but I think plotly.py's `FigureWidget` could eventually move to using `react` instead of `restyle`/`relayout`/`update`.

But in the meantime, a lot of the template information does come through well when switching templates using `relayout` and I think it's a pretty useful way to explore themes.  So I'd like to leave it in place for plotly.py 3.4 and just have the caveat that some template updates require the figure to be re-rendered.

**Comment by etpinard** [comment]
> Would `react` handle this case better, or would the same issues arise? I

No unfortunately. Only `newPlot` will behave correctly on `layout.template` edits.
