### ISSUE TITLE
Missing error_[x/y].valuesrc attribute

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3107]
IIRC, all "array-like" attributes (e.g. `x`), that need a grid reference on plotly cloud have a corresponding "src" attribute in the schema (e.g., `xsrc`), but there doesn't appear to be one for `error_[x/y].value` (which excepts arrays). Is there a reason why `error_[x/y].valuesrc` doesn't exist? If it's added to the schema, it should automatically fix these (and other related) errors -- https://plot.ly/r/error-bars/

**Comment by etpinard** [comment]
In fact, `value` is not `arrayOk` at the moment: 

https://github.com/plotly/plotly.js/blob/7ae6fd68533d6489e3161cdbdfe2a44217f530e1/src/components/errorbars/attributes.js#L68-L80

so that's why `error_[x/y].valuesrc` doesn't exist. You have to use `array` ([example](https://rreusser.github.io/plotly-mock-viewer/#error_bar_asymmetric_array)) and `error_[x/y].arraysrc` should indeed exist.

Related: https://github.com/plotly/plotly.js/issues/1985

----------

On a related topic @cpsievert, can I ask why you are using `*src` attributes from the schema?

They don't do anything in plotly.js proper, they erroneously show up on the [reference](https://plot.ly/javascript/reference/) pages, and should probably get :hocho: So if you find them useful, please tell us!

**Comment by cpsievert** [comment]
> In fact, value is not arrayOk at the moment...so that's why error_[x/y].valuesrc doesn't exist.

Huh, it's really weird that arrays passed to value seem to 'work' locally with the R package. Maybe I'll just request that the documentation be changed to use `array` instead of `value`.

> On a related topic @cpsievert, can I ask why you are using *src attributes from the schema? 

I use those to check which attributes need a grid reference when uploading to plotly cloud -- it would be a bummer to see them go (also, IIRC, I borrowed that logic from the python library)

**Comment by jonmmease** [comment]
The Python library uses them to hold the `id` of grid columns for use with plot.ly

We don't need separate `*src` attributes in the schema, but we need some way of identifying which properties can be properly associated with columns of data (i.e. which properties are valid encoding channels for a data frame).

@nicolaskruchten what does the RCE use as a source of truth for which properties can be associated with grid columns?

**Comment by nicolaskruchten** [comment]
The RCE is all hardcoded ;)

**Comment by etpinard** [comment]
> it would be a bummer to see them go

... and I guess implementing this logic in r/python

https://github.com/plotly/plotly.js/blob/36d9fb4ad341510823e6e25cb9202867ac94a94a/src/plot_api/plot_schema.js#L604-L615

would be less-than-ideal? If that's the case, we could add a meta key in schema to all the attribute linked to cloud columns instead of adding new (dummy) attributes.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
