### ISSUE TITLE
Parameter for max marker size

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3129]
Right now we have `sizeref` but I think it would make sense to have the option to set `maxsize` as well, not in a threshold sense like we do for minimum, but for scaling. We'd likely need a new `scalemode` thing to switch between `sizeref` and `maxsize` but that's life in the fast lane.

**Comment by etpinard** [comment]
Essentially covered in https://github.com/plotly/plotly.js/pull/2318 which stalls when we could come to an agreement about the API.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
