### ISSUE TITLE
Should the 'send to cloud' option be disabled by default?

### ISSUE THREAD

**Issue by th0ma5w** [plotly/plotly.js#316]
The CDN hosted version of the library includes the toolbar link to immediately copy the data elsewhere. It would be nice to use the CDN version without this seemingly insecure option that can be clicked accidentally. There does not seem to be a way to disable this option. The Codepen examples all use a custom build and not the CDN version, so this issue is not apparent on the examples.

Alternatively, perhaps hosting can be done at CDNJS or Google if this button is a condition of the cost of the CDN hosting.

**Comment by etpinard** [comment]
Please search http://community.plot.ly/c/plotly-js for the answer.

**Comment by th0ma5w** [comment]
Okay cool! I found http://community.plot.ly/t/plotly-privacy-policy/303 which denotes how to disable this functionality. I will break out the security, privacy, and sales funnel issues into separate issues since they are not resolved by the community. Thanks again, I didn't even think to check the forum!

**Comment by etpinard** [comment]
@th0ma5w issues

- https://github.com/plotly/plotly.js/issues/318
- https://github.com/plotly/plotly.js/issues/317
- https://github.com/plotly/plotly.js/issues/319

are all valid concerns. Thanks for reporting.

That said, from the perspective of this repo, they are all related to the same feature, So I merged the above three issues in this one. I hope you don't mind.

**Comment by th0ma5w** [comment]
Nope, don't mind. I thought perhaps there could be work on where the link points to to address some of these things individually? Anyway, makes sense to have it here too. Plotly is so very wonderful and a powerful addition to the JS landscape. I can 100% see when the system was proprietary that the public sharing features were an integral part to the service, and even an absolutely wonderful idea for the concept of open data. Unfortunately not all data is open, and not all people immediately get some of the implications, at least in my opinion. I shared the library with some colleagues and afterwards noticed the button. I can of course tell them how to disable it, no big deal, but I wondered about the risk to the greater audience that may consume Plotly charts. Thanks for your work and putting up with my drama :P If I was a little more versed in the code base I could offer a commit. Perhaps it could just be a simple addition to the dictionary/map on the main object? Thank you so much!!

**Comment by etpinard** [comment]
> Unfortunately not all data is open, and not all people immediately get some of the implications, at least in my opinion.

That's a very good point. I personally agree with you. But Plotly isn't my company, so I can't guarantee an outcome for this issue nor any short-term action.

At the moment, the workaround of least-friction is:

```js
// include the call below once per page:
Plotly.setPlotConfig({
  modeBarButtonsToRemove: ['sendDataToCloud']
});

// then all subsequent 
Plotly.plot('graph', data, layout);

// won't show the send data to cloud mode bar button
```

**Comment by nicolaskruchten** [comment]
A few updates on the status quo as of today, which differs somewhat from March 2016 when this issue was opened:

* The button in question is present in the modebar by default, and upon mouseover says "Edit in Chart Studio".
* When this button is clicked, the user's browser sends (over HTTPS) the chart specification to Plotly's Chart Studio Cloud, which then returns a prepopulated version of our chart editor available at https://plot.ly/create but this data is not persisted anywhere during this operation
* The user can then edit the chart as desired, and has the option of saving to Plotly's servers, but this is a multi-click affair wherein the user must:
    1. have or create a Chart Studio Cloud account;
    2. log in or already be logged into said account;
    3. confirm the public/private settings on the plot being saved
* All of our documentation including CodePens uses the same CDN-hosted library as we distribute elsewhere and has this button available by default, so this is just as apparent in the examples as it is in regular use
* Disabling this button is now even simpler than when @etpinard posted above, it can be done inline with plot creation: `Plotly.newPlot('divId', data, layout, {modeBarButtonsToRemove: ['sendDataToCloud']})`
* Because this issue is sometimes linked to alongside rhetorical questions like "I wonder if Plotly will ever take privacy and security seriously", I should add that Plotly does take both of these issues very seriously: among other industry-standard measures, we have an active [security vulnerability bounty program](https://help.plot.ly/security/)

**Comment by alexcjohnson** [comment]
What we've been insisting on primarily is backward compatibility. This was originally linked to the v2.0 milestone, in recognition that we would like to change it but doing so can be considered a breaking change.

That said, in addition to the changes @nicolaskruchten points out above, plotly.js and its ecosystem have evolved in ways that both mitigate some of the original reasons to want this functionality, and strengthen the argument for removing it. So on balance we've become comfortable that the benefits of making this change in a minor release override our concerns about it being a breaking change. Scheduling it for inclusion in 1.43.

**Comment by nicolaskruchten** [comment]
(1.43.0 is out now out, so this button is gone by default on the CDN version)

**Comment by soerendip** [comment]
And how can we get it back? Cannot find a description anywhere.

**Comment by nicolaskruchten** [comment]
you can set the `showEditInChartStudio ` option to `true` in `config`: https://plotly.com/javascript/configuration-options/#display-edit-in-chart-studio-modebar-button

**Comment by soerendip** [comment]
And with plotly.py ? I tried finding it.

**Comment by nicolaskruchten** [comment]
The same options work for Python, which you can pass in as documented here: https://plotly.com/python/configuration-options/
