### ISSUE TITLE
Support for color/size arrays in [x-y]axis.tickfont

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3204]
So that you can have a different color/size for each tick on a given axis.

Needed for `ggplotly()` support in https://github.com/ropensci/plotly/issues/1328 (should be added to that milestone)

**Comment by alexcjohnson** [comment]
In principle possible with pseudo-html in `ticktext` - see eg https://rreusser.github.io/plotly-mock-viewer/#axes_enumerated_ticks

I suppose it would be possible to make `tickfont` components accept arrays when you're using a tick array though, might have some advantages...

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
