### ISSUE TITLE
Responsive Update Menu

### ISSUE THREAD

**Issue by Sjnjerak** [plotly/plotly.js#3208]
One of the things I really appreciate with Plotly is the responsiveness of the charts (i.e. that they self-adjust to the size of the window in which they are viewed). However, this responsiveness does not seem to extend to the update menus. This can get problematic, as an update menu that is appropriately sized/positions for a large window might end up looking disproportioned or even partially occluding the chart in a smaller window. Is there anyway to add a setting so that the update menus scale with chart?

Thank you!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
