### ISSUE TITLE
Charts with subplots and zoom/reset order

### ISSUE THREAD

**Issue by markzolotoy** [plotly/plotly.js#3209]
I have a chart with a few subplots. Here is an example: https://codepen.io/plotly/pen/4b6f9ca3e9c1e8d5e5ac32061dd68418
The problem with it is if I zoom into the first trace and then double click on the bottom subplot to reset the zoom the original trace that the zoom was applied to is not resetting. I consider that a problem because a user might not remember nor he has to remember the zooming order he has performed so far.

Thanks

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by etpinard** [comment]
Actually, this is the desired behavior.

I guess we could a `doubleClick` config option to handle such scenarios. In the meantime, I would suggest listening to `plotly_doubleclick` event to create your own handler.

**Comment by markzolotoy** [comment]
I see, thanks. What's confusing is that it does reset the original trace, but no to its initial state.

**Comment by alexcjohnson** [comment]
I guess the confusion here comes from the fact that it's not really subplots that have (auto or explicit) ranges, it's each individual  x or y axis. But double clicking on the subplot is a kind of shorthand for "autorange all the axes on this subplot." So in that example, double clicking on the bottom subplot affects the top subplot, but only because they share the x axis.

There's an "Autoscale" button in the mode bar, and that will autorange every axis on the plot. I suppose as @etpinard says we *could* make a config option to have double click anywhere do that as well, though that strikes me as trading one potential confusion for another.

**Comment by markzolotoy** [comment]
We are running preventive analytics using Plotly charts. Usually one chart consists of two traces: Actual and Predicted. Then a user can bring more traces and I am using subplots for that. It's critical to the user to be able to analyse the same time region while zooming in. He might go back and forth many times and it's going to be inconvenient to memorize zooming order.

**Comment by alexcjohnson** [comment]
OK, if you don't find the Autoscale button sufficient, then per @etpinard's suggestion - 
```js
gd.on('plotly_doubleclick', function(e) {
  Plotly.relayout(gd,{'allaxes.autorange':true});
});
```
will make doubleclick anywhere autorange the whole plot.

**Comment by markzolotoy** [comment]
Since I am not using Modebar I will go with an event listener. Thanks for the help.

**Comment by etpinard** [comment]
Looks like this got resolved. Closing.
