### ISSUE TITLE
Histogram + groupby transform bug

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3216]
See https://codepen.io/alexcjohnson/pen/bQdeyB?editors=1010

Actually there are two bugs here.
- Hover seems to only show unique y values (groups 4, 5, 6 have y: 1 here but they aren't shown):
![screen shot 2018-11-05 at 3 45 09 pm](https://user-images.githubusercontent.com/2678795/48025659-0e471300-e112-11e8-818c-a613744ec580.png)
- Sometimes - seems like it's when there's an empty bin but data later in the trace - we get an error thrown. Here's hovering on column 4 on the same plot using a dev bundle:
```js
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.makeEventData (helpers.js:133) // components/fx/helpers.js
    at _hover (hover.js:665)
    at hover.js:75
    at exec (throttle.js:48)
    at Object.throttle (throttle.js:57)
    at Object.hover (hover.js:72)
    at SVGRectElement.maindrag.onmousemove (graph_interact.js:67)
```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
