### ISSUE TITLE
Scattergl traces with multiple colors set sometimes incorrectly format points in other scattergl traces

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3232]
see https://codepen.io/alexcjohnson/pen/JeXOGX?editors=1010

The large point above the line should be orange (as it is in the legend) but it ends up blue, taking its color from the previous trace.

Fiddling around with the settings, there seem to be various ways to trigger or avoid this behavior. See also https://codepen.io/donolingerPHX/pen/qQZdxE?editors=1010

Seems to have come in with v1.36.0 - perhaps #2499?

**Comment by etpinard** [comment]
> Seems to have come in with v1.36.0

Good eye, both codepens work with v1.35.2:
- https://codepen.io/etpinard/pen/MzeJyL?editors=1010
- https://codepen.io/etpinard/pen/eQzgza?editors=1010

In both cases, the options computed in `scattergl/convert.js` appear correct:

![image](https://user-images.githubusercontent.com/6675409/48271186-c2de7e80-e409-11e8-82a0-b8bc9276e1d4.png)

![image](https://user-images.githubusercontent.com/6675409/48271241-eacde200-e409-11e8-9c38-0b9c3a0f0dd8.png)

looking at `[1].color`.

--------

>  perhaps #2499?

Yeah good eye, but maybe changes to `regl-scatter2d` that accommodate splom traces in https://github.com/plotly/plotly.js/pull/2505 are to blame too.

**Comment by etpinard** [comment]
Ah this line

https://github.com/gl-vis/regl-scatter2d/blob/8e68ee211dd7e8c2892e55eb392271994046cd00/scatter.js#L46

seems problematic.

**Comment by etpinard** [comment]
Here's my attempt:  https://github.com/plotly/plotly.js/compare/scattergl-maxColors-4096 which uses https://github.com/plotly/plotly.js/compare/scattergl-maxColors-4096 - but unfortunately breaks the `gl2d_scatter-color-clustering` mock.

**Comment by etpinard** [comment]
Well, 255 colors is for sure not enough. Looks like we could theoretically reach 16384 with just one WebGL texture. @archmoj would you be interested in looking at this further?

**Comment by archmoj** [comment]
Interesting. Let me have a look.

**Comment by dy** [comment]
Hey guys can we possibly create a problematic test case in regl-scatter2d mocks (after we merge https://github.com/gl-vis/regl-scatter2d/pull/15)?

`maxColors=255` there is wrong, in fact that is 256 colors. But that is not the point - for the case when the trace has more than 255 colors regl-scatter2d just puts all of them into an attribute buffer directly, so all of the trace colors get displayed, none of them lost. That does not even cause memory overhead, because if we want to use big texture with color palette (more than 256x256), we have to use two Uint16s pointers for color id, but that is the same as single Uint32 color value, therefore having a long buffer with colors directly is valid solution.

The issue seems to be something different.
