### ISSUE TITLE
Some Partial Bundles Cause Bar Charts to Render as Line

### ISSUE THREAD

**Issue by irv075** [plotly/plotly.js#3278]
Using the plotly-basic partial along with any of either geo, gl2d, gl3d or mapbox partials causes bar charts to be rendered as a line chart.

Example here:
https://codepen.io/irv075/pen/YRaXdg

However, finance or cartesian partials do not cause this issue.

**Comment by etpinard** [comment]
Ah, that's not how partial bundles were designed to work, unfortunately. Partial bundles are **not** composable. When you include two partial bundles in separate `<script>` the "second" partial bundle with override the `window.Plotly` global from the "first" one.

It would be possible to make a version of partial bundles that would _extend_ (instead of _override_) one another, but at present, that would defeat the main (in my mind) purpose of using partial bundles: that is include less bytes in your app - as many (many) lines of code would be duplicated. 

For example, the current `plotly-basic` is `257.2kB` and `plotly-gl3d` is `414kB` which together are almost equal the size of the main plotly.js bundle.

What I recommend doing instead: build you own "custom" bundle `require`'ing all the trace modules you need, as described [here](https://github.com/plotly/plotly.js#modules). You may also want to read our [`BUILDING.md`](https://github.com/plotly/plotly.js/blob/master/BUILDING.md).

**Comment by irv075** [comment]
Understood, thanks for the info
