### ISSUE TITLE
Unable to have uneven tick values for color-bar of contour

### ISSUE THREAD

**Issue by poldz123** [plotly/plotly.js#3287]
During contour the color-bar's color scale cannot be set to specific color but instead depends on the zmax or zmin which is I guess it is fine, but when having an uneven tick-values for the colorbar is not possible? This is bad when having a logarithmic axis, which will result for the tick texts to overlap when the tick-values are: `1,2,4,8,10,100,1000, 10000`

I would like to have this kind of layout to the color-bar more like a static-colorbar:

![screen shot 2018-11-22 at 3 22 18 pm](https://user-images.githubusercontent.com/4010507/48961966-6457eb00-ef47-11e8-84af-9cdb92ae332f.png)

As you can see, even if it is un-even, it still have specific color and specific range for each tick marks. So the tick-bar are even but its corresponding values are un-even.

**Comment by poldz123** [comment]
Is there any alternative to have a static value on the color bar instead of plotly deciding the ranges?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
