### ISSUE TITLE
Hyperbolic segments of surface traces within 3d scenes using log axis may not be interpolated properly at the center 

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3312]
Please refer to [this demo](https://codepen.io/MojtabaSamimi/pen/GwPzOR).

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
