### ISSUE TITLE
Sankey: Trace-wide minimum link width

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3319]
Add the ability to specify that no link in the diagram can be narrower than X pixels. This is useful with per-component colorscales, so trace components get expanded to a visible size, and you evaluate its weight according to color.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
