### ISSUE TITLE
Sankey: Column to column node move interaction

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3320]
Currently you can't drag a node from one column to another - you can drag a node sideways but it won't stay there. I think the only reason that sidewise motion is allowed is so you can reorder nodes in a column by dragging one around a different one - if you drag across it you'll push it. The final node needs to be part of the state.

**Comment by antoinerg** [comment]
As @nicolaskruchten pointed out, this should part should work in conjunction with `uirevision`.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
