### ISSUE TITLE
Hovertext dynamic text color should be black/white

### ISSUE THREAD

**Issue by dpmccabe** [plotly/plotly.js#3338]
From the JS scatter plot example:
https://codepen.io/plotly/pen/LVMRMO
<img width="640" alt="screen shot 2018-12-14 at 4 51 27 pm" src="https://user-images.githubusercontent.com/527578/50029376-867ddf80-ffc0-11e8-9408-b578e30e3bfa.png">

When you don't specify a text color on hovertext labels, plotly will set it based on the background color of the label. For dark background labels, the text color is `#ffffff`. For light background labels, the text color is `#444444`. I'm probably not the only person who finds that gray-on-orange label to be very hard to read. The text should really be `#000000`, both for symmetry and because it would be more readable.

I can't seem to find a way to change the text color for only the light background labels. In this case, I think it would be reasonable just to change the default.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
