### ISSUE TITLE
3D axis lines & tick labels may sometimes be rendered over webgl surfaces

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3346]
Using CI to create images and in some perspective views or depending on OS (as @alexcjohnson experienced on Mac) the axis lines may draw over the webgl surfaces. Although [this demo](https://codepen.io/MojtabaSamimi/pen/NeRrgQ?editors=0010) works fine (on Ubuntu) the image below made using CI illustrated parts of the object interior as if it was located below the xy plane!  
![gl3d_parametric_surface_data_precision](https://user-images.githubusercontent.com/33888540/50125560-758ad380-0237-11e9-8110-c8ec43e894d3.png)

**Comment by alexcjohnson** [comment]
Tick labels also sometimes flicker above/below the data

**Comment by antoinerg** [comment]
@alexcjohnson Should I just prune those for now?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
