### ISSUE TITLE
"Uncaught container is not an object" after layout is sent to newPlot

### ISSUE THREAD

**Issue by poldz123** [plotly/plotly.js#3350]
When editing the layout object after it was sent it to `Plotly.newPlot`, it causes an error log `Uncaught container is not an object`.

Seems only for non-objects that causes it:

```
var layout = {
  title: "title",
  margin: {
      l: 30,
      r: 50,
      t: 30,
      b: 10
    }
};

Plotly.newPlot('contourDiv', data, layout, {displayModeBar: false});
console.log(layout)
layout.margin = {} -> It works
layout.title = "edit title" -> Causes the error
Plotly.update('contourDiv', data, layout)
```

Before version `1.43.0` the above code works.

https://codepen.io/poldz123/pen/pqNBzj?editors=0010

**Comment by etpinard** [comment]
This must be a side-effect of https://github.com/plotly/plotly.js/pull/3276 - where we deprecated `layout.title` and replaced it with `layout.title.text`.

More generally, if you (1)  `newPlot` (2) mutate data/layout (3) update the graph, you should be using `Plotly.react` at step (3) instead of `Plotly.update`. Passing whole data/layout objects to `update` will always result in the slowest possible update path - whereas `react` will attempt to find the faster update path possible.

Oh well, we should still try to fix this thing.

**Comment by etpinard** [comment]
also note that 

```js
var layout = {
  title: "title",
  margin: {l: 30, r: 50, t: 30, b: 10}
};

var data = [{
  y: [1, 2, 1]
}]

Plotly.newPlot('graph', data, layout, {displayModeBar: false});
console.log(layout)
layout.margin = {}
layout.title.text = "edit title"
Plotly.update('graph', data, layout)
```

works as expected.

**Comment by etpinard** [comment]
as well as:

```js
var layout = {
  title: "title",
  margin: {l: 30, r: 50, t: 30, b: 10}
};

var data = [{
  y: [1, 2, 1]
}]

Plotly.newPlot('graph', data, layout, {displayModeBar: false});
console.log(layout);
layout.margin = {};
layout.title = "edit title";
Plotly.react('graph', data, layout)
```

**Comment by poldz123** [comment]
@etpinard Ended up with the react instead, not seeing any changes on performance. Well, it does not matter. Closing this thread.
