### ISSUE TITLE
Add support for transforms on multicategory axes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3363]
Follow-up issue from https://github.com/plotly/plotly.js/pull/3300

**Comment by MrQubo** [comment]
I think this cannot be done without rewriting hell of a code.
Correctly describing `x` and `y` attributes in [src/traces/scatter/attributes.js](https://github.com/plotly/plotly.js/blob/c91f88b0f6f41bdfda46ecf28be06bf534d993c0/src/traces/scatter/attributes.js) would probably be sufficient for transforms to work with multicategory axes.
But those attributes sometimes can be `data_array`s and sometimes can be arrays of `data_array`s and I think that current format doesn't allow us to describe this dual nature of those attributes.
In my opinion we should rewrite multicategory axes itself and instead of reusing `x` and `y` attributes add new attributes, like `multix` and `multiy` and use a data format similar to `dimensions` attribute in parcats.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
