### ISSUE TITLE
Passive event listener error on mobile on drag

### ISSUE THREAD

**Issue by athenatan** [plotly/plotly.js#3371]
Hi,
I got this error from trying to scroll on bar chart surface (on mobile platforms).
`Unable to preventDefault inside passive event listener due to target being treated as passive.`
Also, this makes the hover doesn't work as well.
How to fix this ?
Thank you.

**Comment by etpinard** [comment]
Could you share a the "data" / "layout" you used to generate the graph in question? Thank you.

**Comment by autukill** [comment]
Test with Chrome's Device Mode:
- https://plot.ly/javascript/line-and-scatter/
- [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

![passive event](https://user-images.githubusercontent.com/5186639/50556618-4c2d7580-0d16-11e9-85a6-19e7035fad9d.png)

**Comment by etpinard** [comment]
Thanks @autukill
