### ISSUE TITLE
histogram2dsurface

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3391]
It would be really nice to have a 3d surface equivalent of `histogram2dcontour`... Right now for matrix data we have `heatmap`, `contour` and `surface` but for densities we're missing the 3d case :)

In principle this is mostly remixing existing code...

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
