### ISSUE TITLE
better dticks default when switching from auto to linear tickmode

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#3395]
https://codepen.io/veraz/pen/VqQQGj?editors=0010
also maybe related: https://github.com/plotly/streambed/issues/11864

**Comment by VeraZab** [comment]
I tried reproducing https://github.com/plotly/streambed/issues/11864, but even just using newPlot, then react to change tickmode from 'auto' to 'linear' does not seem to be working

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
