### ISSUE TITLE
small domain does not display correctly.

### ISSUE THREAD

**Issue by slfan2013** [plotly/plotly.js#3403]
In this [codepen][1], the first attempt on `Plotly.newPlot` is not working.

I have two Y-axes. The bottom has a domain of `[0,0.5]`, while the second has the `plot_layout.yaxis2.domain` = `[0.945, 0.95]`. However, the second Y-axis will overlap the whole plot. I expected it only covers the top 94.5% to 95%. I don’t know why this does not work. If I simply change the domain to `[0.94, 0.95]` covering top 94% to 95%, it suddenly worked. Why does this happen?

  [1]: https://codepen.io/anon/pen/wRmQLN

**Comment by alexcjohnson** [comment]
That's because of the `0.01` on this line:

https://github.com/plotly/plotly.js/blob/364cdec83e862e076ab02400b814ed9566777351/src/plots/cartesian/position_defaults.js#L75

which is mainly there to prevent zero- or negative-size domains, but we gave it a small buffer to cover "almost zero" or rounding errors. We can certainly decrease that buffer to `0.0001` or something, but I'm curious what use you have for such a small axis?

**Comment by slfan2013** [comment]
And I cannot find the `0.01` buffer in the [CDN](https://cdn.plot.ly/plotly-latest.min.js?_ga=2.267415053.260800222.1546541663-1721469137.1545016128)?

**Comment by alexcjohnson** [comment]
> Why do you want to avoid "almost zero" values?

I think we wanted to avoid errors if we round some size to zero and end up making invalid svg elements. Perhaps we should take the height or width into account, and refuse any domain smaller than 1px.

> And I cannot find the 0.01 buffer in the CDN?

It's going to be hard to find something like that in minified code, but since you're seeing this effect I'm quite sure it's there somewhere!

**Comment by alexcjohnson** [comment]
I’ll leave the issue open, as it probably would be good to tighten up this limit.

**Comment by archmoj** [comment]
@slfan2013 Just opened a pull request to possibly help your research porject. In the meantime you may want to try the source used in [this demo](https://codepen.io/MojtabaSamimi/pen/dwmBpX) or one of the two on the lines below:
"https://22828-45646037-gh.circle-artifacts.com/0/plotly.js" 
"https://22828-45646037-gh.circle-artifacts.com/0/plotly.min.js"
