### ISSUE TITLE
Making scrollbar always visible

### ISSUE THREAD

**Issue by anikets43** [plotly/plotly.js#3412]
Feature Request:
When using table with scrolls, the scroll bar is by default set to be visible on hover.
It would be good to have a config so we can always make the scrollbar visible.

Not sure if this if applicable to other trace types. But I'm facing this with Table.

Similar to CSS - there could be 3 possibilities - onhover, always, never ?

![scroll2](https://user-images.githubusercontent.com/7136799/50764114-c40c1a80-1297-11e9-8efa-ae01050eab62.gif)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
