### ISSUE TITLE
URL Encoding Bugs when dealing with already encoded URLs

### ISSUE THREAD

**Issue by tedivm** [plotly/plotly.js#3449]
Plotly seems to be doing some weird things with character encoding that results in unexpected behavior.

Take the URL `/projects/Project #1` as an example. The only way to use that character in a URL is to escape it, turning it into `/projects/Project %231`- or, if we're encoding everything, `/projects/Project%20%231`. 

Unfortunately when presented with that URL Plotly decides to encode the center `%` sign (but only that one, it ignores the `%20`), turning it into `/projects/Project%20%25231`

This makes it impossible to actually use the `#` sign in URLs related to Plotly.

[Codepen Example](https://codepen.io/tedivm/pen/xmoMYY)

Ideally there would be an option for Plotly to take the URL *as is*.

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
