### ISSUE TITLE
[Feature-Request] Allow SVG overflowing

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#3454]
Hello everyone.
It would be awesome if we could have SVG overflow with a simple setting so this doesn't happen:
![grafik](https://user-images.githubusercontent.com/6761196/51529289-b084b600-1e38-11e9-8ebf-27863e0085ee.png)
Visible overflow for SVG can be achieved like this, I think: https://codepen.io/AmeliaBR/pen/wJRbBO

What do you guys think? Or did I miss a setting for this?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
