### ISSUE TITLE
ScatterGL broken with coordinate near floating point limit

### ISSUE THREAD

**Issue by mscotch1** [plotly/plotly.js#3476]
See https://codepen.io/anon/pen/zevwQg

Traces drawn with the `type: 'scattergl'` property have an issue drawing points with coordinates on the order of the max value for a 32-bit floating point number (~3.402823e+38).

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by etpinard** [comment]
@archmoj wanna take a :eye: at this?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
