### ISSUE TITLE
Ternary density contours

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3503]
We should add a new trace type analogous to `histogram2dcontours` for ternary axes. Basically this https://github.com/plotly/plotly.py/pull/1413 should be native ;)

**Comment by alexcjohnson** [comment]
First we need triplet (Delaunay triangulated) contours (mentioned in #3166), then this would be easy to add.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
