### ISSUE TITLE
Funnel charts

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3504]
Funnel charts are kind of interesting because they're kind of like stacked bar charts, with variable width bars, often with sloping sides, which makes for the potential for double-encoding. A standard stacked bar chart has each segment with the same width, and the height of the segment encodes the datum. On the other extreme you can have bars where each are the same height, and the width encodes the datum, like this: https://www.amcharts.com/demos/funnel-chart/

In both of those cases, the area is proportional to the datum. If you start sloping the sides, then the area no longer matches the datum and it's just the height: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/funnel/

So we could maybe add some options to `bar` to make the version without sloping sides, but it may make more sense to create a new trace type here. We'll want some special legend and color handling, as well as some computations for hovertemplate like 'percentage of total' and 'percentage difference with previous stage' etc.

**Comment by alexcjohnson** [comment]
I really dislike the version where the whole side is sloped - I get that this makes the analogy to an actual funnel clearer, but it makes the data value highly ambiguous. But connecting bars with a sloping region in the gap, like the amcharts example does, strikes me as really cool, and would be a nice addition to regular bar charts too. This came up recently, I can't seem to find it now, but it's a great effect for stacked bars with some sort of stack sorting, because it shows you when two series change order in the stack.

At that point it would be fairly easy to imagine this just as another attribute to a bar chart to shift it to symmetric about the size-axis origin, but perhaps enough of the default attributes should change that it's worth making a trace type for it (and just use the bar code to render it)

**Comment by alexcjohnson** [comment]
Oh I was thinking of this not as stacked at all, but a single trace of horizontal bars of equal height. That's how the amcharts example does it, and it shows you all the relevant information clearly: the total starting size, the size and amount lost at each stage, and it's intuitive that each stage is a subset of the previous stage.

The way that highcharts example shows it, where the vertical size of each segment is different, strikes me as totally inappropriate. Yes, it shows you the size at each stage (at least if you can figure out how to interpret the sloping sides), but the total stack size is completely meaningless and there's no way to visually see what's lost at each stage.

**Comment by nicolaskruchten** [comment]
OK, so the a pie-like thing makes sense, if we want to be able to let people have different colours for each stage. I actually think that separate legend items per stage could be problematic if we allow click-to-hide :)

**Comment by alexcjohnson** [comment]
Related potential use for a bar trace positioned symmetrically about the origin of the size axis: check out the "neutral" trace here https://peltiertech.com/charting-survey-results/:

![screen shot 2019-02-01 at 2 27 12 pm](https://user-images.githubusercontent.com/2678795/52145204-5cdf4d00-262e-11e9-9ad3-8c33b239cbf0.png)

The final piece we'd need to make this plot I guess is an attr to say "stack this trace on the negative side" for the "hate" and "dislike" traces. Or perhaps that would happen automatically if "neutral" is the third trace in the stack but it has an attribute saying "position this trace symmetrically"?

**Comment by nicolaskruchten** [comment]
So what can we converge on in terms of an API here? The key question in my mind is: is this pie-like in the sense that one funnel = one trace? Or bar-like in the sense that one funnel stage = one trace?

In general I feel like this is quite pie-like, even perhaps to the point of not actually rendering axes etc.

**Comment by alexcjohnson** [comment]
Definitely one funnel = one trace. I'm not sure it has any practical implications but to my mind it's much more like horizontal bars than pie. Perhaps we don't draw them by default, but I certainly think we want it drawn on cartesian axes, so that you can overlay it with other traces matching at least the category axis, and probably so you can stack funnels like https://stackoverflow.com/questions/45421748/making-a-stacked-funnel-chart-in-excel
![screen shot 2019-02-04 at 10 37 50 am](https://user-images.githubusercontent.com/2678795/52219477-b59b2980-286a-11e9-823d-e3ccffd82858.png)

**Comment by nicolaskruchten** [comment]
Ok for one funnel per trace. It’s very common to want each bar a different color however (much more than to segment each bar like in the image above) so I would want built in support for this, like in pie.

**Comment by nicolaskruchten** [comment]
* new trace type
* bar-length encoding only, no variable width
* no neck.
* ability to center the thing
* no negative values
* accepts stacking, grouping, overlaying
* x, y (cartesian subplots) with magic to hide the grids 
* ability to display on-plot and/or in hover the "percentage of first" and "percentage of previous"
* connecting lines
* ability to hover on connecting area to see delta in hover
* ability place delta% text on the intermediate area

**Comment by chriddyp** [comment]
- in addition to the delta% (from one stage to the next), it seems like many of the charts have percentages based off the value (value / total)

![image](https://user-images.githubusercontent.com/1280389/54840245-929dcb00-4c9a-11e9-9825-40ecfdbf6fb2.png)

**Comment by nicolaskruchten** [comment]
Yep, that's 

> * ability to display on-plot and/or in hover the "percentage of first" and "percentage of previous"

**Comment by nicolaskruchten** [comment]
ah no, sorry, percentage of total... hm

**Comment by nicolaskruchten** [comment]
So that's interesting: I guess there are two ways of seeing funnel charts.

It's either "each step contains a subset of the previous step" meaning each unit appears in N stages. Or it's "each step contains a unit in its current position" meaning each unit is accounted for in one stage at a time.

**Comment by nicolaskruchten** [comment]
Note that at the moment we're not considering building the ability to make the above chart with the sloping sides, as it's very ambiguous/incorrect to encode something with height while you're narrowing the width. @chriddyp do you think it's very important to support this kind of thing with a constant slope?

**Comment by alexcjohnson** [comment]
Right, I guess that's like "here's what's in our sales funnel right now" in which case "total" does have a real meaning, it's the sum of all deals the team is working on. But there's also no need that successive stages must decrease in size - averaged over time they would, but that's not necessarily true in one snapshot because they refer to different items.

**Comment by nicolaskruchten** [comment]
OK, so after chatting with @chriddyp I think we should actually do something fairly different from what we (enjoyably!) discussed last Thursday. I'm now seeing funnel traces as trapezoid-shaped area-encoded pie traces rather than a specialization of bar charts. Should be easier to implement actually, just lift all the non-circular aspects of the `pie` API.

**Comment by alexcjohnson** [comment]
The pie analogy works for the snapshot case but I don’t see how it handles the successive parts of a whole case. Want to elaborate on the API you’re imagining?

**Comment by nicolaskruchten** [comment]
(still discussing with @chriddyp actually, but basically we would not support the successive parts of whole case if we went pie-like, @alexcjohnson )

**Comment by nicolaskruchten** [comment]
OK, discussion concluded... original plan still stands.

Let's add one more bullet though:

* a flag to enable sloping sides on the bars like this, such that the bars are still length-encoded to the midpoint, and area-encoded, AND we have sloped sides

![image](https://user-images.githubusercontent.com/203523/55025584-918cd680-4fd7-11e9-8ec7-d1fa5303e0f9.png)

**Comment by nicolaskruchten** [comment]
If we wanted a pie-like funnel we could create a second `funnel_area` trace type or something.

**Comment by antoinerg** [comment]
> If we wanted a pie-like funnel we could create a second `funnel_area` trace type or something.

Isn't a pie-like funnel a `sunburst` trace? Pretty cool example: https://bl.ocks.org/kerryrodden/7090426

**Comment by nicolaskruchten** [comment]
> Isn't a pie-like funnel a sunburst ?

Not really: I meant in the sense of "parts of whole"

**Comment by alexcjohnson** [comment]
FYI in whatever program produced that example, the value is encoded in the max width, not the area. Look what happens when you overlay the two sides:
<img width="411" alt="Screen Shot 2019-03-26 at 6 10 38 PM" src="https://user-images.githubusercontent.com/2678795/55036996-a7f45b80-4ff2-11e9-8627-d505351013ab.png">

In fact I think if you area-encode with constant thickness, you're forced into strange situations like a boundary line bigger than the one above despite the same or smaller value. Consider a step 100-100-100-50-50-50, there's an extra degree of freedom (you could make the 100's look better if the 50's look worse) but I think you'll always get stuff like this (grey is the midpoint to show value encoding):
<img width="257" alt="Screen Shot 2019-03-26 at 6 34 22 PM" src="https://user-images.githubusercontent.com/2678795/55038012-e7707700-4ff5-11e9-9a5c-9b052f622532.png">

**Comment by nicolaskruchten** [comment]
Surely there is a stable optimum such that all points along the edge are connected with minimum internal angles, that doesn’t look nearly as jagged as your thing above.

**Comment by nicolaskruchten** [comment]
Maybe not though... I see that two equally sized adjacent bars causes a problem.

**Comment by alexcjohnson** [comment]
Yeah my example is ridiculous, but that's the point, I really don't think you can do better. There's only one extra degree of freedom so if you make the 100s look better the 50s look worse, and vice versa.

Using the max width is visually appealing because the last bar is straight so the overall chart looks like a physical funnel, but interpretation is bizarre, you have to read it as something like "at this stage we have value Y but then in the next stage it's going to drop to Z."

Could we get away with sloped connectors between rectangular data bars, like the amcharts example? That way the stage values and inter-stage reductions are separate visual elements and it's all very clear what's what.

I suppose another option that might make more intuitive sense would be to encode the value in the *minimum* width of the trapezoid. That way you can read each stage fairly naturally as "at this stage we reduced from value X (the previous stage) to value Y (this stage). So looking at that one trapezoid you can see the two key metrics for the stage: the remaining value and what was lost getting there. The disadvantage though is people who are used to the dumb but more common max-width encoding would be disoriented.

**Comment by nicolaskruchten** [comment]
Right. OK let' stick with normal rectangular bars and rely on diagonal connectors to make things look funnel-y.

**Comment by archmoj** [comment]
In respect to conversation above, this thing appear to be quite similar to `bar`.
I also like a `pie` variation of it. But that would become another creature. 
What about the colouring options? `Markers` + `Lines` + `Colorscale`?

**Comment by nicolaskruchten** [comment]
OK so let's focus on the `bar` version now and leave out anything `pie`-like.

Yes, we will need to be able to specify the marker as a bar: color, length, line-width, line-color etc. We will also need to be able to specify the connector-lines and connector-fill, as well as the bar gap and width etc. (similar to waterfall in a way). Orientation as well.

**Comment by archmoj** [comment]
OK. I started [this branch](https://github.com/plotly/plotly.js/compare/funnel-draft) simply to figure out few options.
Please search for the `attributes.js` & `layout_attributes.js` files there.
In contrast to `waterfall` and `bar` there is no `base` attribute in the API but it should be computed internally to align the center of bars on the middle axis.
We could possibly default the graphs to be displayed horizontally.
It looks we may support `stack`, `group`, `overlay` & `relative` as `funnelmode`.
Also having `funnelgap` & `funnelgroupgap` is the other question.
There could be only one `marker` container similar to `bar`.
OK if `colorscale` is supported in the first iteration?
I think drawing lines similar to `waterfall` between bars plus not filling the space between connectors is a good idea.

**Comment by nicolaskruchten** [comment]
Update: we'll do two trace types here... `funnel` (bar-like) *and* `funnelarea` (pie-like)

**Comment by archmoj** [comment]
`funnelarea` is kind of cool as they might be a third one in 3D `funnelvolume`...

**Comment by archmoj** [comment]
Here is a new [codepen](https://codepen.io/MojtabaSamimi/pen/EJbXNo?editors=0010) for bar-like funnel charts from this branch: https://github.com/plotly/plotly.js/compare/funnel-proto.

**Comment by nicolaskruchten** [comment]
Very nice! I would remove connector.mode: I think we should support only "between"

**Comment by archmoj** [comment]
What about negative sizes? For the moment one could pass negative sizes and the connectors intersect. But in that case (& if we want to support them then) we may need another color container...

**Comment by nicolaskruchten** [comment]
See above: we said “no negative values”... doesn’t make sense semantically in a funnel.

**Comment by alexcjohnson** [comment]
FWIW `pie` simply ignores negatives, but here the space still has to exist. Shall we simply treat them as zero values?

**Comment by archmoj** [comment]
Thanks @alexcjohnson for the pointer to `pie`.
The negative values are now treated as bad input numbers i.e. `BADNUM` during `calc` step. 
Updated [codepen](https://codepen.io/MojtabaSamimi/pen/jRazNP?editors=0010).

**Comment by nicolaskruchten** [comment]
For both `funnel` and `funnelarea` we should have fairly robust `textinfo` options (see also #3777) so as to be able to display computed values on-chart.

Note that I think that for `funnel` we should leave the percentages out of the hoverlabel by default and have `hoverinfo`/`textinfo` support for percentage-of-first AND percentage-of-total and then let the user choose. (for `funnelarea` obviously we will support percentage-of-total also).

For `funnelarea` shape control, I propose that the length of the top of the funnel be sized according to the domain, and then we can have a single attr for "length of bottom as fraction of top". thoughts?

**Comment by archmoj** [comment]
[New funnel prototype](https://codepen.io/MojtabaSamimi/pen/oOdmrX?editors=0010) with `textinfo` and `textposition` default to `auto`. Connector `mode` is no longer needed since the `spanning` mode is dropped and the only connector mode is `between`.

**Comment by archmoj** [comment]
[updated funnel prototype](https://codepen.io/MojtabaSamimi/pen/MRqPQb?editors=0010) with auto hide axis when there are only funnels visible in data.

**Comment by etpinard** [comment]
@archmoj looking good - which branch is that on?

**Comment by archmoj** [comment]
@etpinard thanks for looking at it. That is on https://github.com/plotly/plotly.js/tree/funnel-finalist

**Comment by archmoj** [comment]
[Second prototype of the day](https://codepen.io/MojtabaSamimi/pen/rbZgJm?editors=0010) now it is possible to center the inside text using `insidetextcenter`: `true`.
I am not a fan of defaulting it to true considering `overaly` & `group` modes.

**Comment by archmoj** [comment]
[New prototype](https://codepen.io/MojtabaSamimi/pen/VNVvPg?editors=0010) with filled in-between areas i.e. thanks to @nicolaskruchten feedback.

**Comment by nicolaskruchten** [comment]
Oh yeah, so nice! can we default the text to not rotate like it does? i.e. stay horizontal?

**Comment by nicolaskruchten** [comment]
For textinfo: I think we need to distinguish between "percentage of total" and "percentage of previous" and allow people to specify both/either/neither.

**Comment by alexcjohnson** [comment]
> distinguish between "percentage of total" and "percentage of previous"

Perhaps also "percentage of first", like [this one](https://exceldashboardschool.com/sales-funnel-chart/)?
![Screen Shot 2019-04-24 at 3 50 14 PM](https://user-images.githubusercontent.com/2678795/56689277-b80e6200-66a8-11e9-91b2-e4f6b66d8fce.png)

**Comment by archmoj** [comment]
@nicolaskruchten Good point related to `textinfo`. Instead of "total" which refers to the first value in data, could we use "initial" for example: `initial percent` & `delta percent` if 'spaces' are allowed for flags?
And what about hover?

**Comment by alexcjohnson** [comment]
> "total" which refers to the first value in data

or to the sum of all values...

**Comment by archmoj** [comment]
> > "total" which refers to the first value in data
> 
> or to the sum of all values...

Yes that can make sense too. So should we have all the 3 rather similar to `waterfall` and [this PR](https://github.com/plotly/plotly.js/pull/3790)?

**Comment by nicolaskruchten** [comment]
Right I forgot pct of first of course

**Comment by nicolaskruchten** [comment]
And yes this should be available to hoverinfo AND hovertemplate please

**Comment by archmoj** [comment]
Here is [the updated prototype](https://codepen.io/MojtabaSamimi/pen/WWYOeb?editors=0010) which displays those 3 ratios.

**Comment by archmoj** [comment]
And this the development branch: https://github.com/plotly/plotly.js/compare/fix3777-textinfo-waterfall-fin...funnel-new-proto .

**Comment by archmoj** [comment]
[Updated prototype](https://codepen.io/MojtabaSamimi/pen/EJGvWG?editors=0010) with `cliponaxis: false` & other fixes.
Also in the `textinfo` the percent description is not printed when only one of the percentage flags are used.

**Comment by etpinard** [comment]
@archmoj I gave your https://github.com/plotly/plotly.js/compare/fix3777-textinfo-waterfall-fin...funnel-new-proto a first look. It's looking pretty good!

I only noticed two "major" things:

- the `axis.visible` logic https://github.com/plotly/plotly.js/compare/fix3777-textinfo-waterfall-fin...funnel-new-proto#commitcomment-33322847
- `textinfo` formatting using `Axes.tickText` (which also applies to https://github.com/plotly/plotly.js/pull/3790/) https://github.com/plotly/plotly.js/compare/fix3777-textinfo-waterfall-fin...funnel-new-proto#commitcomment-33323818

Once these are addressed, please PR away :rocket: The other comments are _minor_.

**Comment by holassan** [comment]
text to not rotate like it does? i.e. stay horizontal,
