### ISSUE TITLE
IE11 - Vertical modebar doesn't wrap button when height is small

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3540]
Because IE11 has bugs when using `flexbox` columns, vertical mode bars do not span multiple columns as it should when figure height is small:
![screenshot_2019-02-12_20-06-14](https://user-images.githubusercontent.com/301546/52681302-5e035a80-2f09-11e9-8bd9-d641b2b00a49.png)

**Comment by etpinard** [comment]
Another argument (cc https://github.com/plotly/plotly.js/issues/3471#issuecomment-460443544) for rewriting modebar rendering in pure SVG.

**Comment by yemling** [comment]
Is there any fix for this yet? The vertical modebar looks great in everything except IE. Anyone know of a workaround?

**Comment by antoinerg** [comment]
@yemling There is no simple fix: it would involve rewriting the mode bar in pure SVG. It's really unfortunate that IE11 does not implement `flexbox` properly...

I'll give it a shot when nothing more urgent is on my plate.

**Comment by yemling** [comment]
Thanks @antoinerg , sorry to be a bother. I'd contribute if I could, but I'm not as clever as you guys. :)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
