### ISSUE TITLE
matches with animations

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3562]
The following pen is super long, sorry, but it shows animations with matched X axes where x1 has a fixed range. The matching appears broken :(

https://codepen.io/nicolaskruchten/pen/gqJoOJ?editors=0010

**Comment by etpinard** [comment]
Is this a requirement for 1.45.0?

**Comment by nicolaskruchten** [comment]
We can push it out of scope for 1.45.0 but without it, `px` will have to be released without animations, so fixing it will be at the top of the 1.45.1 pile :)

**Comment by etpinard** [comment]
I wouldn't call that a bug fix, so all right let's make this part of 1.45.0.

**Comment by etpinard** [comment]
The "animation" in https://codepen.io/nicolaskruchten/pen/gqJoOJ?editors=0010 seems to work ok when using the correct bundle and setting all the x-axis to `type: 'log'`:

- https://codepen.io/etpinard/pen/KJLJJr

and things work ok when unsetting `xaxis.type` as well:

https://codepen.io/etpinard/pen/Gzazzv

Even "axes" transitions on matching axes seem to work ok:

https://codepen.io/etpinard/pen/vbwPBZ?editors=1010

---

Now, maybe having

```
layout = {
  xaxis: {type: 'log'},
  xaxis2: {matches: 'x'}
}
```

should infer that `xaxis2.type` is `'log'`? I'd vote no, but I could be convinced otherwise.

**Comment by nicolaskruchten** [comment]
Ahhh interesting. Would you be surprised if I voted the other way from you? I could be convinced otherwise also though :)

**Comment by etpinard** [comment]
My main argument is: "that how is works right now for `scaleanchor`", where trying to constraint axes of different types (you can add config option `logging: 2` to see those warnings in the console) results in this message:

https://github.com/plotly/plotly.js/blob/b5663aa958cb57edbd08c19040e178c16cebe628/src/plots/cartesian/constraints.js#L87-L91

**Comment by etpinard** [comment]
@nicolaskruchten Anything here still blocking for 1.45.0? Can we close this ticket?

**Comment by nicolaskruchten** [comment]
Can close
