### ISSUE TITLE
Weird issue when restyling bar 'orientation'

### ISSUE THREAD

**Issue by aleburato** [plotly/plotly.js#358]
If you restyle a bar plot and specify its orientation while restyling, the plot becomes empty, even if you use the default orientation ("v"). If before restyling you already specified the orientation (in newPlot), the issue won't occur.

See:

http://codepen.io/aleburato/pen/LNLExv?editors=0010

**Comment by mdtusz** [comment]
Thanks for reporting this - confirmed as a bug.

**Comment by etpinard** [comment]
cc @alexcjohnson and https://github.com/plotly/plotly.js/pull/1999

**Comment by PPPW** [comment]
In the example, the bar's orientation is vertical, it seems I can't change it to horizontal:

Plotly.restyle('myDiv', 'orientation', 'h');

The above doesn't work. Is there any way to flip x/y for bar (and stacked bar) plot? Thanks!

**Comment by PPPW** [comment]
Dear @alexcjohnson ,
Thanks for your reply! It seems now it won't look weird, I guess that's why this issue is closed, but I still don't know how to **flip x/y** for bar (and stacked bar) plot, e.g.:

https://codepen.io/anon/pen/gGMrrx?editors=0010

Restyling to 'v' or 'h' does nothing. 
Is there any way to flip x/y for bar (and stacked bar) plot? Thanks!

**Comment by etpinard** [comment]
@PPPW the issue is fixed on `master`, but we haven't made a new release yet nor have we updated the `latest` CDN link. Please be patient.
