### ISSUE TITLE
Axes title overlaps other Axes with multi-axis charts

### ISSUE THREAD

**Issue by MPursche** [plotly/plotly.js#3629]
Hello,

I have found a bug when using multiple axes in a scatterplot. The title of an axis sometimes overlaps another axis when the chart is resized. I'm trying to create a chart with four y-axes: two on the left and two on the right.
My chart setup can be found here: [Codepen Example](https://codepen.io/mpursche/pen/ywzZdr)
The layout works if the chart is wide enough but if the window is resized and the chart is smaller the axes title may overlap another axes. I tried to work around the issue using the axis position, but this does not work for responsive charts as the position is in relative coordinates.
I would expect the placement algorithm for the axis to consider the title and add margins if necessary.

Title don't overlap if chart is wide enough:
![Screenshot_20190312_120906](https://user-images.githubusercontent.com/5239962/54196162-e4876980-44c0-11e9-8d07-0c71e3794782.png)
Titles overlap if chart is too narrow:
![Screenshot_20190312_120928](https://user-images.githubusercontent.com/5239962/54196163-e4876980-44c0-11e9-895e-c6194d2131e6.png)

Greetings
Marcel

**Comment by antoinerg** [comment]
Thank you @MPursche for reporting this issue!

**Comment by etpinard** [comment]
This is the expected behavior (for now). We don't attempt to smartly position axes titles based on the position of other graph components. 

Related:

- https://github.com/plotly/plotly.js/issues/2575
- https://github.com/plotly/plotly.js/issues/1199

We should probably merge this tickets together. Adding something like `axis.title.position: 'auto'` could potential help for _fixing_ this problem.

Tagging as `feature`.

**Comment by etpinard** [comment]
One more: https://github.com/plotly/plotly.js/issues/3505

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
