### ISSUE TITLE
barmode: "stack relative" as alias for "relative"

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3650]
I’d like to make a case for adding “stack relative” as an alias for “relative” as I feel the latter is not sufficiently discoverable and leads people to use “stack” which can hide data from them and is thus dangerous in my view

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
