### ISSUE TITLE
Feature: let layout.colorway accept a colorscale

### ISSUE THREAD

**Issue by anch2150** [plotly/plotly.js#3657]
Currently layout.colorway accepts a list of pre-defined hex format colors. It would be nice to be able to specify a color scale instead, and let plotly generate the colors for each trace or pie sector.

Suppose there are three traces and a color scale `0rgb(0,0,0)1(rgb(255,255,255)`. The desired colors of trace 1 to 3 should be `0: rgb(0,0,0), 0.5: rgb(127, 127, 127), 1: rgb(255, 255, 255)`.

Not sure if a similar feature has already been implemented. At the moment I do it via a custom function. However, it can be tricky if the data is retrieved async, as the # of traces is unknown.

**Comment by tamersalama** [comment]
potential work around (if the number of `traces` is known)
```
        cScale= d3.scaleSequential().domain([0, traces.length-1]).interpolator(d3.interpolateRdBu)
        colors = traces.map((t, idx) => cScale(idx))
   
      //then assign colors to layout.colorway
```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
