### ISSUE TITLE
js-yaml (prior to 3.13.0) security vulnerability

### ISSUE THREAD

**Issue by yuanstanley** [plotly/plotly.js#3664]
Looks like js-yaml 3.12.1, which my security scan says Plotly depends on, has a Denial of Service security vulnerability. A yarn why seems to indicate that it's coming from plotly.js -> mapbox-gl -> gray-matter.

Info on the js-yaml security vulnerability - https://www.npmjs.com/advisories/788

**Comment by k-sai-kiranmayee** [comment]
@etpinard Even if I upgraded _plotly.js_ to 1.48.1 but still could see the vulnerability, might be because of the inner libraries, it is still showing the js-yaml's version as 3.12.0
![image](https://user-images.githubusercontent.com/36036544/58882423-d6c93500-86f9-11e9-9444-72339b8d267f.png)
![image](https://user-images.githubusercontent.com/36036544/58882411-cca73680-86f9-11e9-90c5-3063524915cc.png)

Could you please have a look.

**Comment by etpinard** [comment]
We're listing js-yaml as:

https://github.com/plotly/plotly.js/blob/7a1ed7ba3d4d098440a3a60fbe6237cc75d649d9/package-lock.json#L6473-L6488

Could you tell how you're installing plotly.js?

**Comment by k-sai-kiranmayee** [comment]
@etpinard I'm installing it through _**npm install plotly.js**_.
