### ISSUE TITLE
Shared autobin for overlaid histograms

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3749]
For `px` we need some new attrs to get `histogram`s to share autobin logic even when in `overlay` mode (they currently do so in the other modes by default).

Ref #3515

**Comment by etpinard** [comment]
Similar to https://github.com/plotly/plotly.js/issues/3515#issuecomment-488074466:

- Should `bingroup` for overlaid histograms only work for traces on the same bin axis and across matching axes?

Furthermore, what does `bingroup` mean for graphs with `barmode` other than `'overlay'`? Should we even coerce `bingroup` for non-overlay barmodes? Or, should we allow users to place stacked/grouped  histograms on the same (or matching) binning axis in different binning groups using `bingroup`?

**Comment by alexcjohnson** [comment]
How about we just force `bingroup` to match within a stack/group? ie have it inherit from the first trace in the group that sets a `bingroup`. That way you could choose to have a stack overlaid by another single trace, or another stack/group on a stacked or matching subplot, all sharing bin settings.

**Comment by etpinard** [comment]
> How about we just force `bingroup` to match within a stack/group?

Yep, that sounds about right. With this and https://github.com/plotly/plotly.js/issues/3515#issuecomment-488079313 , we'll have a pretty robust `bingroup` behavior.

**Comment by nicolaskruchten** [comment]
> How about we just force bingroup to match within a stack/group? 

Not sure what the implications of that are... can you unpack please?

**Comment by alexcjohnson** [comment]
It wouldn't make sense to have incompatible bins within a single stack or group - you need to have matching position values, and we already do force this in the stacking/grouping code. Since that's exactly what we're talking about here, but extending this forcing to other traces that aren't otherwise known to need compatible positions, we might as well make this correspondence explicit: instead of inferring that a set of traces need to be forced into compatible positions based on their stacking or grouping, it becomes a 2-step process. (1) infer that these traces need to have the same `bingroup` (2) use that `bingroup` (along with any other traces we've put into the same group) to force compatible positions.

**Comment by nicolaskruchten** [comment]
But.... this issue is about overlaid histograms, not grouped or stacked ones, right?

I'm having trouble seeing what the API implications are here. I was expecting some new attr that I could set somewhere that said "share bins" that would kick in if the bars are overlaid.

**Comment by alexcjohnson** [comment]
With `alignmentgroup` and `offsetgroup` you can have all of those together - a single histogram overlaying a stack or a group, or multiple stacks... also need to consider multiple subplots, stacked or otherwise, and the desire to share binning across these. So yes, the simple case would be several overlaid histograms but there's a lot more you can imagine doing with bin groups.

**Comment by nicolaskruchten** [comment]
Oh I see. ok then. Still curious what the final API would look like  :)

**Comment by nicolaskruchten** [comment]
For e.g. the simple case of two histograms that are currently overlaid.

**Comment by etpinard** [comment]
> Still curious what the final API would look like :)
> For e.g. the simple case of two histograms that are currently overlaid.

```js
Plotly.newPlot(gd, [{
  type: 'histogram',
  x: [1,1,2,3,3,4],
  opacity: 0.8,
  bingroup: '1'
}, {
  type: 'histogram',
  x: [2,4,4,1,2,3],
  opacity: 0.8,
  bingroup: '1'
}], {
  barmode: 'overlay'
})
```

that looks like:

![image](https://user-images.githubusercontent.com/6675409/56993053-6c0c6300-6b69-11e9-9ea6-a8d33b554ab9.png)

with bins `{size: 1, start: 0.5, end: 4.5}`

**Comment by nicolaskruchten** [comment]
Ah ok this makes sense. Too many stack/alignment/bin-group possibilities for my pre-coffee brain to think about though :)

**Comment by nicolaskruchten** [comment]
does it make sense to do #3614 first?

**Comment by etpinard** [comment]
> does it make sense to do #3614 first?

I'm starting to think that, yes maybe we should get `stackgroup` in there in 1.48.0
