### ISSUE TITLE
Bug: Resize on hidden graph divs causes Error

### ISSUE THREAD

**Issue by ford04** [plotly/plotly.js#3866]
Discussion: https://community.plot.ly/t/dynamically-change-responsive-layout/23002
Repo sample: https://codesandbox.io/s/9qy1p1k8jy

Error:
```
Error: Resize must be passed a displayed plot div element.
    at eval (plotly-basic.js:59636)
    at new Promise (<anonymous>)
    at Object.plots.resize (plotly-basic.js:59629)
    at gd._responsiveChartHandler (plotly-basic.js:41558)
```

**Comment by etpinard** [comment]
Thanks for posting!

Here's the problematic block:

https://github.com/plotly/plotly.js/blob/9340f2608b3a2710e91878923ac5aaa3ca9a1fd0/src/plots/plots.js#L84-L86

Rejecting the promise when calling `Plotly.Plots.resize(gd)` seems fine, but perhaps we could catch it in

https://github.com/plotly/plotly.js/blob/9340f2608b3a2710e91878923ac5aaa3ca9a1fd0/src/plot_api/plot_api.js#L187

so that graphs with `{responsize: true`} don't results in a bunch of somewhat unhelpful error logs.

@antoinerg I'd be interesting in hearing your thoughts on this.

**Comment by antoinerg** [comment]
You will indeed get this error if plots are not removed with `Plotly.purge`.

@etpinard We could definitely catch the error in the responsive handler and then remove the event listener if the `div` element is not in the DOM anymore.

**Comment by antoinerg** [comment]
Updated comment https://github.com/plotly/plotly.js/issues/3866#issuecomment-492758466 above :arrow_up:

**Comment by etpinard** [comment]
Let's try to squeeze this one in `v1.49.0`

**Comment by antoinerg** [comment]
@etpinard I guess we have two options here:

1- Ignore all rejected promises
```javascript
gd._responsiveChartHandler = function() { Plots.resize(gd).catch(Lib.noop); };
```
2- Do not call resize if div is hidden
```javascript
gd._responsiveChartHandler = function() { if(!isHidden(gd)) Plots.resize(gd); }; 
```
