### ISSUE TITLE
OBJ export options for 3D traces

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4000]
It may potentially be useful for Plotly users to have options for exporting geometry generated by Plotly's `isosurface` and `volume` engine to [OBJ format](https://en.wikipedia.org/wiki/Wavefront_.obj_file).
The graphs then could be easily ported to [CAD/CAM software](https://en.wikipedia.org/wiki/Computer-aided_design), [AR/VR applications](https://en.wikipedia.org/wiki/Virtual_reality) as well as game engines e.g. [Unity](https://en.wikipedia.org/wiki/Unity_(game_engine)).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
