### ISSUE TITLE
Mosaic plot

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4020]
Placeholder issue for this kind of trace. See also #4019 for the two-level Marimekko variant and #1038 for the general-purpose treemap variant.

For the purposes of keeping our issues straight, a mosaic plot _looks like_ a more-than-two-level Marimekko plot or a more-than-two-level slice-and-dice treemap. It is used to visualize contigency tables with inputs that look a lot like `parcats` (i.e. rows of cases with dimensional columns and values therein):

![image](https://user-images.githubusercontent.com/203523/60721836-31260300-9efd-11e9-9b95-3e52840f79ca.png)

**Comment by eddy-geek** [comment]
someone went to the trouble of creating one with manual positioning of rectangle shapes : https://plotly.com/~octogrid/1089/titanic-passengers-mosaic-chart/#plot
... but the magic for placement is missing.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
