### ISSUE TITLE
Strange slider behaviour with null values

### ISSUE THREAD

**Issue by Jorgeewa** [plotly/plotly.js#4092]
I am experiencing really weird behaviour with plot types 'heatmap' with frames and sliders added on to it. When I have some frames with only null values and I move from the very first frame to the last, there is weird alignment behaviour as can be seen in this pen: https://codepen.io/JorgeJavasScripter/pen/jgmoxa. Specifically if you move from Round 1 to round 4 you will notice this. I think it is a css bug or something. How can I resolve this issue?

**Comment by etpinard** [comment]
Here's a working example: https://codepen.io/etpinard/pen/zgdGgM?editors=0010

In your codepen, you're setting `layout.margin.r` to `50` which isn't enough to fit the colorbar. So under `Round 3` and `Round 4` the alignment the right margin gets bumped to make the colorbar fit. Switching to `Round 2` and `Round 1`, the colorbar isn't displayed (as both heatmaps have no valid entries) meaning the plot-area can take up to `margin.l: 50` causing the misalignment.

The easier way to fix the problem (see my codepen above) is to set `layout.margin.r` a to big enough value so that the plot-area has the same width with and w/o a colorbar.

**Comment by Jorgeewa** [comment]
Gotcha. I think I can play around with it to see what values works best for my project.
