### ISSUE TITLE
shift-select should include points in selected points

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#4095]
If I make a new boxplot with some points in `selectedpoints` list and I 'shift-select' to add more points to selection it doesnt include the points I have originally marked as selected. It just selects it as if I did a normal 'select' ,  not 'shift-select'

screenrecording example:
https://www.screencast.com/t/HX9cbkLcE3

codepen:
https://www.screencast.com/t/HX9cbkLcE3

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
