### ISSUE TITLE
Cannot plot heatmapGL subplots

### ISSUE THREAD

**Issue by ANuttinck** [plotly/plotly.js#4135]
Trying to plot heatmapGL subplots throws the following error whereas it works with heatmap.

```
> Uncaught TypeError: Cannot read property 'x' of undefined
>     at handlePositionDefaults (plotly-latest.js:127420)
>     at Object.supplyLayoutDefaults (plotly-latest.js:127205)
>     at Object.exports.supplyLayoutDefaults (plotly-latest.js:133299)
>     at Object.plots.supplyLayoutModuleDefaults (plotly-latest.js:140100)
>     at Object.plots.supplyDefaults (plotly-latest.js:138929)
>     at Object.plot (plotly-latest.js:112517)
>     at Object.newPlot (plotly-latest.js:113020)
>     at test_heatmapgl.html:33
```

[Codepen](https://codepen.io/anuttinck/pen/RXGJvB)

(It works if you replace "heatmapgl" by "heatmap" in data[0].type and data[1].type or if you plot only one heatmapgl.)

The issue seems to be due to the fact that grid._axisMap is not instantiated because the function that should do it - contentDefaults(layoutIn, LayoutOut) - is not called.
Indeed, this function is called only if layoutOut._has('cartesian') is true but the basePlotModule is "gl2d".

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by chetan51** [comment]
I'm encountering this issue too!

**Comment by archmoj** [comment]
Encountered a different issue with `heatmapgl` on this [codepen](https://codepen.io/MojtabaSamimi/pen/xxxEXXx?editors=0010).

**Comment by yearnaudov** [comment]
Just ran into the same problem. Any workarounds ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
