### ISSUE TITLE
rangemode is ignored if there is no data

### ISSUE THREAD

**Issue by DaanyWaay** [plotly/plotly.js#4137]
https://codepen.io/pen/eYOdNVV

**Comment by etpinard** [comment]
related: https://github.com/plotly/plotly.js/issues/3487

**Comment by etpinard** [comment]
Here's a bit more info on the topic.

Traces with data arrays with `length=0` are considered as if they were `visible:false`. These `visible:false` traces skip the calc step, so they don't get their `_extremes` stashes filled and `getAutorange` [exits early](https://github.com/plotly/plotly.js/blob/5f25eafb96b356b724b45e3a87bd09cb4b2b5cb3/src/plots/cartesian/autorange.js#L62-L64). This means that even though axis `autorange` gets coerced to `true`, we end up plotting the dflt range:

https://github.com/plotly/plotly.js/blob/5f25eafb96b356b724b45e3a87bd09cb4b2b5cb3/src/plots/cartesian/set_convert.js#L394-L396

https://github.com/plotly/plotly.js/blob/5f25eafb96b356b724b45e3a87bd09cb4b2b5cb3/src/plots/cartesian/constants.js#L59-L61

So, I'm thinking we could easily add something like:

```js
        if(ax.rangemode === 'tozero' || ax.rangemode === 'nonnegative') {
            dflt[0] = 0;
        }
```

to `ax.cleanRange` so that the range dflt would be `[0, 6]` for x-axes and `[0, 4]` for y-axes when `rangemode` is set to `'tozero'` or `'nonnegative'`. 

That said, maybe instead we implement https://github.com/plotly/plotly.js/issues/400 and have users solve this problem by setting `xaxis.range` or `yaxis.range` to `[0]`.

**Comment by alexcjohnson** [comment]
> `dflt[0] = 0;`

sounds right to me. this is somewhat independent of #400 for eg. entirely negative axes with `tozero` or reversed ranges.
