### ISSUE TITLE
[BUG] HeatMap wrong Transpose Z

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4138]
**Dear Devs,**
https://plot.ly/javascript/reference/#heatmap-transpose
 z transpose for heat map is not working correctly. 

**CodePen transpose=false :** 
https://codepen.io/mafar/pen/bGbwjgr

**CodePen transpose=true:** 
https://codepen.io/mafar/pen/YzKGOwx

**Image comparison:**
![image](https://user-images.githubusercontent.com/4101480/63337326-a6a33280-c2f5-11e9-84bd-6d43a38cbb2c.png)

**Comment by etpinard** [comment]
Granted, it might not be what you're expecting, but this is the expected behavior (unfortunately):

your `z` values

```
var zValues = [
  [0.00, 0.00, 0.75, 0.75, 0.00],
  [0.00, 0.00, 0.75, 0.75, 0.00],
  [0.75, 0.75, 0.75, 0.75, 0.75],
  [0.00, 0.00, 0.00, 0.75, 0.00]
];
```


are plotted as

```
[
  [0.00, 0.00, 0.75, 0.00],
  [0.00, 0.00, 0,75, 0.00],
  [0.75, 0.75, 0.75, 0.00],
  [0.75, 0.75, 0.75, 0.75],
  [0.00, 0.00, 0.75, 0.00]
]
```

but since you set and 5 `x` coordinates and 4 `y` coordinates, the transposed `z[4]` is omitted.

In brief, setting `transpose: true` in a `heatmap` trace only acts on the `z` 2d array, not on the (x, y) coordinates nor on the annotations.

**Comment by mafar** [comment]
Ok thankx. Would be helpful to others if behaviour is documented .
Closing it...
