### ISSUE TITLE
Inverted axes matching

### ISSUE THREAD

**Issue by jackh726** [plotly/plotly.js#4187]
This was previously discussed in https://github.com/plotly/plotly.js/issues/1549#issuecomment-456838212
> One more question: What if you want two axes to match but inverted? I'm thinking of things like x/y match but you want the diagonal to go NW-to-SE... or the population pyramid, with male on one side and female on the other, which you _can_ do with a single axis and positive/negative data, but that requires fudging the data (negating one set) and with two axes you could put the labels in the middle without overlapping the data... Perhaps we could support this with `scaleratio: -1`?

I'm finding myself wanting this feature, but as far as I can tell, it isn't implemented yet. Specifically, I need it for x/y match with the NW-to-SE diagonal (for zooming onto squares (not physical, but data-based) on the diagonal). As noted, I can fudge the data to be on the NW/SE diagonal, but zooming isn't correct.

As noted above, one possible way to support this would be `scaleratio: -1`. Would that physically constrain the axes too? If so, I think that's less than ideal. One other option would to maybe add a `matchesreversed` option, which is identical to matches, except inverted. Or allow specifying an axes to `matches` like `x-reversed` (or similar).

Related, but not the same: https://github.com/plotly/plotly.js/issues/3539

**Comment by FRYoussef** [comment]
Hi, any progress with this?

I have two scatter plots, one of them with an inverted axis. 
I need to match both y axes in order to share the same range between them, but 'matches' property doesn't consider whether you reverse an axis.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
