### ISSUE TITLE
There is no support for React Native

### ISSUE THREAD

**Issue by morampudibabu** [plotly/plotly.js#4195]
I have used Plotly for Web application, and I have thought of implement same in the mobile application too, which is built by React Native. But Plotly - There is no support for React native.

**Comment by yinshurman** [comment]
+1 for React Native support

**Comment by iliazlobin** [comment]
Looks like there is support, check out [an expo showroom](showroom)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
