### ISSUE TITLE
Hoverlabel clipping should occur with 0 or tight margins

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4221]
Right now it's possible for various plot elements to clip when `margin` is set to 0, for example the hoverlabel on the axis in `hovermode: closest`

![image](https://user-images.githubusercontent.com/203523/65695617-d9072480-e045-11e9-876a-dc26300d68cc.png)

**Comment by nicolaskruchten** [comment]
This also happens in the horizontal case: 

![image](https://user-images.githubusercontent.com/203523/65696275-ecff5600-e046-11e9-942f-0abe0363cee6.png)

**Comment by nicolaskruchten** [comment]
Related #3607

**Comment by etpinard** [comment]
What would be the best solution here?

1) should we fit the hover label into viewport, and then possibly tweak the tip shape?
1) should we truncate the hover label text and add ellipses? 

---

I'd vote for 1), but please let me know if you disagree or have a better solution in mind.

**Comment by nicolaskruchten** [comment]
When the axis is perpendicular to the edge (second screenshot) then just moving the hoverlabel such that it fits would work I think. When the axis is parallel to the edge (first screenshot) I think ellipses will be needed? hard to imagine what else we can do in this case.

**Comment by etpinard** [comment]
Might be nice to explore solutions to https://github.com/plotly/plotly.js/issues/3985 at the same time as this ticket.

**Comment by etpinard** [comment]
Here's a first attempt:

https://github.com/plotly/plotly.js/compare/common-label-overlaps

-------

Under `hovermode: 'x'`, the common hover label (i.e. the one on top of the x axis) is constrained into the viewport while the hover label arrow appear on the left or right edge.

https://codepen.io/etpinard/pen/NWWpPmq

![Peek 2019-10-22 14-48](https://user-images.githubusercontent.com/6675409/67319439-f8755e00-f4da-11e9-94eb-dd34c75554b8.gif)

----

Under `hovermode: 'y'`, the common hover label for `side:'left'` y axes has its text shifted to the right so that its beginning is visible and then clipped so that it doesn't overlap the hover label arrow.

https://codepen.io/etpinard/pen/LYYWEvr

![Peek 2019-10-22 14-51](https://user-images.githubusercontent.com/6675409/67319776-615cd600-f4db-11e9-8af7-a1189f81b4c3.gif)

**Comment by nicolaskruchten** [comment]
Re https://codepen.io/etpinard/pen/NWWpPmq the hoverlabels look great but the axis label is pretty clipped ;P

**Comment by nicolaskruchten** [comment]
Re https://codepen.io/etpinard/pen/LYYWEvr when I set automargin there's still a tiny bit of clipping on the "Way longer" one.

**Comment by etpinard** [comment]
`automargin: true` versions:

- https://codepen.io/etpinard/pen/RwwpPLb
- https://codepen.io/etpinard/pen/GRRWJMg

**Comment by etpinard** [comment]
> the hoverlabels look great but the axis label is pretty clipped

Yes, it was much easier to show the new behaviour w/o setting `automargin: true`



> Re https://codepen.io/etpinard/pen/LYYWEvr when I set automargin there's still a tiny bit of clipping on the "Way longer" one.

Where?

![Peek 2019-10-22 15-21](https://user-images.githubusercontent.com/6675409/67322839-a2ef8000-f4df-11e9-838b-3ec134c26a12.gif)

taken off https://codepen.io/etpinard/pen/GRRWJMg

**Comment by nicolaskruchten** [comment]
Here's what it looks like in Chrome/MacOS on your pen:

![image](https://user-images.githubusercontent.com/203523/67335138-1ab9ac80-f4d8-11e9-8cf7-a4d3a6d9766e.png)

**Comment by etpinard** [comment]
> Here's what it looks like in Chrome/MacOS on your pen:

Ok, that's odd. How does it look like w/o `automargin: true` e.g. using https://codepen.io/etpinard/pen/LYYWEvr ?

**Comment by nicolaskruchten** [comment]
Looks fine there.
