### ISSUE TITLE
How do you suppress the already registered console.log for trace libs?

### ISSUE THREAD

**Issue by chickendinosaur** [plotly/plotly.js#426]
So I am working in a component environment using reactjs at work of course and I want each charting page component to be able to register which trace types it depends on but by doing that each page that using one of the same type I get a "bar already registered" for example. Any way to suppress this or different way to registered modules differently that I am not doing?

**Comment by etpinard** [comment]
> I am working in a component environment using reactjs at work of course and I want each charting page component to be able to register which trace types it depends on

Nice.

> Any way to suppress this or different way to registered modules differently that I am not doing?

Not at the moment, unfortunately.

Maybe we could add an option flag e.g. `hideWarnings: true` to `Plotly.register` that would suppress those `console.log`s. 

@mdtusz thoughts?

**Comment by mdtusz** [comment]
Something like that would be good to add (hint hint @chickendinosaur if you're up to it). Otherwise, the temporary/DIY route is to check `Plotly.Plots.modules` for the existence of the plot type you are trying to register.

I'd be ok with just removing the warning entirely as well - there's no real consequence of trying when something is already registered, but I suppose it is nice to see that unnecessary calls are being made.

**Comment by etpinard** [comment]
resolved in `v1.13.0` by PR https://github.com/plotly/plotly.js/pull/590
