### ISSUE TITLE
texttemplate vs hovertemplate

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4263]
This pen https://codepen.io/nicolaskruchten/pen/YzzXwdL shows some differences between `texttemplate` and `hovertemplate`, specifically that `%{y}` in `texttemplate` doesn't seem to pick up the formatting from the `yaxis` ticklabels the way `hovertemplate` does.

**Comment by etpinard** [comment]
Looking at https://github.com/plotly/plotly.js/pull/4071, I found:

- https://github.com/plotly/plotly.js/pull/4071#discussion_r306809541
- https://github.com/plotly/plotly.js/pull/4071#pullrequestreview-278047084

that discussed similar things, but nothing on axis attributes having an effect on the default `texttemplate` output - @antoinerg do you remember discussing this?

--------

I'd call this bug, axis `tickformat`, `tickprefix` and `ticksuffix` should be considered in `texttemplate`. Internally, this means using [`Axes.tickText`](https://github.com/plotly/plotly.js/blob/25fe1c929672461e0b915a737134f6a975edf8f8/src/plots/cartesian/axes.js#L956-L1022) everywhere.

**Comment by antoinerg** [comment]
Mmm... that is unfortunate indeed. The code path a value takes before reaching `texttemplate` and `hovertemplate` is a bit different hence the difference. We should aim to close the gap. 

> I'd call this bug, axis `tickformat`, `tickprefix` and `ticksuffix` should be considered in `texttemplate`. Internally, this means using [`Axes.tickText`](https://github.com/plotly/plotly.js/blob/25fe1c929672461e0b915a737134f6a975edf8f8/src/plots/cartesian/axes.js#L956-L1022) everywhere.

I agree that the default values should contain those 3 `tick` properties.

**Comment by nicolaskruchten** [comment]
Is there any case for not declaring absolutely that they should always be equal, not just with those three properties but all properties?

**Comment by nicolaskruchten** [comment]
I seem to recall discussing this, yes.

**Comment by nicolaskruchten** [comment]
All in all this is a wicked feature already :)

**Comment by etpinard** [comment]
@antoinerg I think I found a fix for this issue - ok if I assign myself this one?

**Comment by antoinerg** [comment]
> @antoinerg I think I found a fix for this issue - ok if I assign myself this one?

Sure go ahead :) Thanks for taking this on

**Comment by etpinard** [comment]
I probably won't have the time to make a PR to fix this bug for all traces that support `texttemplate` before my vacation, so here's some info I gathered about this problem.

---------

There are currently four different `texttemplate` "pathways" used currently:

- bar, funnel and waterfall traces format labels and call `Lib.texttemplateString` inside `bar/plot.js`
- pie/funnelarea and sunburst/treemap format labels and call `Lib.texttemplateString` from their `formatSliceLabel` routine
- scatter, scattercarpet, scatterpolar, scatterternary and scattergeo call `Drawing.textPointStyle` via `Scatter.styleText`
- scatter3d, scattergl, scatterpolargl and scattermapbox call `Lib.texttemplateString` in their "convert" step

---------

Fixing this bug here for bar, funnel and waterfall traces is relatively easy: we simply need to copy the `labelLabel` and `valueLabel` formatted values 

https://github.com/plotly/plotly.js/blob/fbfadbeaa304110ba3173e84d3e6573c07b0f41f/src/traces/bar/plot.js#L595

https://github.com/plotly/plotly.js/blob/fbfadbeaa304110ba3173e84d3e6573c07b0f41f/src/traces/bar/plot.js#L601

to `xLabel` and `yLabel` depending on the orientation. 

----

pie, funnelarea, sunburst and treemap appear unaffected by this bug. Their `texttemplate` formatting appears equivalent to their `hovertemplate` formatting.

---

All the `scatter*` traces appear affected, example: https://codepen.io/etpinard/pen/pooWyMg

To fix the `scatter` case, we'll need to pass `xLabel` and `yLabel` to `Lib.texttemplateString` as formatted by `Axes.tickText` similarly to how we fill in `xLabel` and `yLabel` during hover. 

https://github.com/plotly/plotly.js/blob/fbfadbeaa304110ba3173e84d3e6573c07b0f41f/src/components/fx/hover.js#L1424

https://github.com/plotly/plotly.js/blob/fbfadbeaa304110ba3173e84d3e6573c07b0f41f/src/components/fx/hover.js#L1428

(note that `Axes.hoverLabelText` calls `Axes.tickText` internally)

To fix the `scatterternary` case, we'll need to pass `aLabel`, `bLabel` and `cLabel`

https://github.com/plotly/plotly.js/blob/fbfadbeaa304110ba3173e84d3e6573c07b0f41f/src/traces/scatterternary/hover.js#L52-L54

For the `scattergeo`, `lonLabel` and `latLabel`

https://github.com/plotly/plotly.js/blob/fbfadbeaa304110ba3173e84d3e6573c07b0f41f/src/traces/scattergeo/hover.js#L67-L68

... and so on.

In brief, the logic here in `Drawing.textPointStyle`

https://github.com/plotly/plotly.js/blob/fbfadbeaa304110ba3173e84d3e6573c07b0f41f/src/components/drawing/index.js#L705-L709

is not sufficient.

---

Now, if we agree that the default `texttemplate` formatting should be the same as the default `hovertemplate` formatting everywhere (i.e. with the same number precision), we should probably start thinking about ways to reuse the same coordinate-to-label formatting functions for both hover and `texttemplate` formatting.

I'm thinking either adding a new trace module method (e.g. `_module._formatCoords`) or add format functions to the trace's corresponding `fullData[i]` objects e.g. during `supplyDefaults` 

```js
// in scatterternary/defaults.js
trace._aFormatFn = function(cdi) { return Axes.tickText(ternary.aaxis, cdi.a, 'hover').text; };
```

With a bit more work, perhaps we could even generalise `_module.eventData` so that it also formats the coordinates. 

Oh well, having all the per-trace coordinate formatting logic in one place should be a big win.

**Comment by nicolaskruchten** [comment]
OK to bump to 1.52

**Comment by etpinard** [comment]
> OK to bump to 1.52

Sure, but this can be done in a 1.51.x patch release also.
