### ISSUE TITLE
Add support for custom geojson polygons in choropleth traces

### ISSUE THREAD

**Issue by geraldo** [plotly/plotly.js#4267]
[Locationmode](https://plot.ly/javascript/reference/#scattergeo-locationmode) right now only accepts these 3 options: "ISO-3" | "USA-states" | "country names"

I want to make choropleth maps for different countries on provinces level, as equivalent to _locationmode: "USA-states"_. Instead of defining a new _locationmode_ for every country, like "BRA-states" or "ESP-states" maybe it would be better to define a new generic one calles "province" and afterwards define the country using _locations_ option.

**Comment by etpinard** [comment]
Our current topojson files (built in https://github.com/etpinard/sane-topojson using [Natural Earth data](http://www.naturalearthdata.com/)) contain:

- (only) USA states for the 110m resolution
- USA, Brazil and Australian states + Canadian provinces at 50m

The "full" subunit lists are available [here](https://github.com/etpinard/sane-topojson/blob/d92e1fc7bc1d709b55b9bbb33bd5c398e25bfe24/test/assets.js#L160-L177).

------

In general, we can't use a single `locationmode` value for all these subunits because they have overlapping values. For example, `'WA'` means both Washington state and Western Australia.

-----

I suspect what you're _really_ looking for is either:

- Add topojson for the 10m resolution to have subunits from more countries available to choropleth traces. We would consider doing only for scoped geo maps, as at the 110m resolution rendering would be too slow (in SVG at least)
- To provide your own "subunit" topojson (or geojson) in choropleth traces, similar how `choroplethmapbox` [does it](https://github.com/plotly/plotly.js/blob/c8a9f8ae8a8389e357c2afbada1ec0b7a2c4259a/src/traces/choroplethmapbox/attributes.js#L44-L54).

**Comment by etpinard** [comment]
@nicolaskruchten I suspect you're looking for us to implement

> * To provide your own "subunit" topojson (or geojson) in choropleth traces, similar how `choroplethmapbox` [does it](https://github.com/plotly/plotly.js/blob/c8a9f8ae8a8389e357c2afbada1ec0b7a2c4259a/src/traces/choroplethmapbox/attributes.js#L44-L54).

item here?

**Comment by nicolaskruchten** [comment]
Yup. TopoJSON optional for now but basically the same API as we did for mapbox would be great, plus some automatic bounding box logic

**Comment by geraldo** [comment]
> - To provide your own "subunit" topojson (or geojson) in choropleth traces, similar how choroplethmapbox does it.

Yes, that's what I'm looking for. The first option also would be nice, but actually it's not hard to make (or find) topojson files for different countries.

Thanks for translating my description into a proper feature request.

**Comment by etpinard** [comment]
Here's my WIP branch: 

- https://github.com/plotly/plotly.js/compare/locationmode-geojson-id

where a new `locatiionmode` value is added in choropleth and scattergeo traces called `'geojson-id'` and where much of the corresponding choroplethmapbox logic is reused.

----

Now regarding 

> plus some automatic bounding box logic

This is essentially the `geo` subplot version of https://github.com/plotly/plotly.js/issues/3434. To me, it makes more sense to implement this at the subplot level.

I'm thinking of adding a new `layout.geo` attribute named `fitbounds` which would be `false` by default. When turned on, we would compute the bounds of the data in all traces (i.e. lon/lat pts for `scattergeo`, polygons for `choropleth`) on the subplot and "fit" them (i.e. compute the corresponding `projection.scale` and translation) before first render. This would essentially be an "opt-on" version of our autorange routine. 

That's probably a couple more days of work; nothing substantial. Does that sound ok?

**Comment by etpinard** [comment]
... oops, forget to paste the link to the demo:https://codepen.io/etpinard/pen/zYxOoEB

**Comment by nicolaskruchten** [comment]
> That's probably a couple more days of work; nothing substantial. Does that sound ok?

Yes! Can we default it to `true` for `geo` subplots that contain only `choropleth` in `geojson` mode... somehow?

**Comment by nicolaskruchten** [comment]
Also: this would be `geo`-only right? we would add it to `mapbox` some other day?

**Comment by etpinard** [comment]
> Can we default it to `true` for `geo` subplots that contain only `choropleth` in `geojson` mode... somehow?

We could, but I'd vote against it for consistency with `choroplethmapbox`.

**Comment by etpinard** [comment]
> Also: this would be `geo`-only right? we would add it to `mapbox` some other day?

Yes, that's the plan for `v1.52.0`

**Comment by nicolaskruchten** [comment]
what would `fitbounds` do when not using `geojson` and/or in the presence of `scope`?

**Comment by nicolaskruchten** [comment]
Having thought about this a bit, I think `fitbounds` would need to accept two modes, in addition to "off"... One scoped to the entire geojson, and one scoped to locations-only.

**Comment by etpinard** [comment]
> Having thought about this a bit, I think `fitbounds` would need to accept two modes, in addition to "off"... One scoped to the entire geojson, and one scoped to locations-only.

Sure, good call.
