### ISSUE TITLE
`image` future directions

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4301]
Following the introduction of `image` trace type in https://github.com/plotly/plotly.js/pull/4289, here are a few future directions this trace type could go:
- add support for `x` and `y`
- add new color models
- add optimized rendering pathway in browsers that support it by drawing the image once and rely on CSS `image-rendering: pixelated` to provide a pixelated view of it

**Comment by etpinard** [comment]
- renaming it `pixmap` :smile:

**Comment by archmoj** [comment]
I was wondering it might be of interest to have an option of printing numbers (or other characters) instead of drawing rectangles. Something similar to `pixmap` actually!
https://franz.com/support/documentation/current/doc/cg/cg-pixmaps.htm
Also that reminds me of this article http://www.cs.utah.edu/~gk/papers/vissym04/vissym04kindlmann.pdf which @nicolaskruchten showed me a while ago may be possible using vectors.

**Comment by archmoj** [comment]
Also to metion: 
- supporting typed arrays

**Comment by emmanuelle** [comment]
I have the impression that at the moment nan values are converted to 0. We could instead keep the same behaviour as `Heatmap` where nan regions are transparent and show the background.

**Comment by antoinerg** [comment]
> I have the impression that at the moment nan values are converted to 0. We could instead keep the same behaviour as `Heatmap` where nan regions are transparent and show the background.

I agree we should probably clean things up when we're not receiving numbers and show a transparent color. This is implemented in the following https://github.com/plotly/plotly.js/compare/master...image-nan. Now the question is what to display in the hover for color? A transparent pixel should not exist in `rgb` or `hsl` so there's no way of defining it there. I think not displaying anything would be better. As you know, I'm leaving in vacation tomorrow but feel free to take over the `image-nan` branch!

**Comment by emmanuelle** [comment]
The optimized rendering pathway would be great to display large images (1000x1000 and larger) in reasonable time. I'm a big fan of adding this possibility.

**Comment by antoinerg** [comment]
Commit https://github.com/plotly/plotly.js/commit/d9a17cd8cb9e2798028321f71a101a52d089030a shows an early example using `image-rendering: pixelated`.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
