### ISSUE TITLE
Per-element opacity on Surface plots (opacityscale)

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4331]
Requested in https://github.com/plotly/plotly.py/issues/1859

**Comment by lucapinello** [comment]
I think the problem is related to this function:

https://github.com/plotly/plotly.js/blob/36a48f710c20a51230c11b2ebfad856495ac5d94/src/lib/gl_format_color.js#L79

This function destroy the alpha information and convert the rgba into rgb with the same global opacity for all the colors.

This function is called when parsing the colormap to plot the surface here:
https://github.com/plotly/plotly.js/blob/adf9bee14a8badcb5b2f49065fd594623421c82e/src/traces/surface/convert.js#L408

I am more a Python person, am I on the right track? :)

**Comment by nicolaskruchten** [comment]
I don’t know if “problem” is the word I would use here... At the moment we consciously don’t support alpha in color scales so this is more of a feature request from our perspective today.

There’s also the question of whether or not we can render this correctly and efficiently in webGL with the current code.

**Comment by lucapinello** [comment]
Fair enough. 

BTW this fixed the problem:

function parseColorScale(cont, alpha) {
    if(alpha === undefined) alpha = 1;

    var cOpts = Colorscale.extractOpts(cont);

    var colorscale = cOpts.reversescale ?
        Colorscale.flipScale(cOpts.colorscale) :
        cOpts.colorscale;

    return colorscale.map(function(elem) {
        var index = elem[0];
        var color = tinycolor(elem[1]);
        var rgb = color.toRgb();
		console.log(rgb);
        return {
            index: index,
            **rgb: [rgb.r, rgb.g, rgb.b, rgb.a]**
        };
    });
}

But only if you specify a global opacity <1.0. (0.99 does the trick for me and it works really smoothly)

There must be another setting that overrides this when opacity=1.

![image](https://user-images.githubusercontent.com/1081322/68076992-7b779d80-fd92-11e9-8c5c-db0d59b1bbcb.png)

Thanks again for the quick reply and for the support.

**Comment by nicolaskruchten** [comment]
Great! Feel free to submit a pull request, which should cause the tests to run and we’ll see if that shakes anything loose :)

**Comment by lucapinello** [comment]
Great! Just submitted.

**Comment by lucapinello** [comment]
Hi Nicolas,

After looking at the CircleCI tests I realized that this fixes the per
point opacity but it may break the global opacity.

In the previous version, you forced to have all the points to have the
alpha provided by the users and 1.0 if undefined. This was necessary
probably because internally you always use rgba for colormaps and if the
alpha was undefined, it was set to 0 by tydicolor2 and the surface was not
visible.

Here we may need an additional flag to the method to create the Surface
(for example use_per_point_opacity= True and Fset this to False by default
) to say that we want to use a per point opacity or have a special value of
the global opacity say -1 (this is less clean and  less explicit).

Anyway, this should be trivial for your team to fix and to decide the best
way to allow this. The good news is that this extension doesn't affect
performance, I tried yesterday to overlay 10 surfaces and it was still very
smooth.

Happy to discuss this further.

Thanks again for being so responsive, this was fun :)

Luca

**Comment by archmoj** [comment]
What about implementing `opacityscale` (similar to `volume` trace) for `surface` as well as `scatter3d` plots?

**Comment by lucapinello** [comment]
Thanks @archmoj  for the feedback. Do you have a link with an example?

**Comment by archmoj** [comment]
> Thanks @archmoj for the feedback. Do you have a link with an example?

@lucapinello 
Please view this [demo](https://codepen.io/MojtabaSamimi/pen/wvvyqwL?editors=0010).
At the moment this feature is only implemented for `volume` plots.

**Comment by lucapinello** [comment]
I think this is perfect!

**Comment by archmoj** [comment]
What about renaming the title of this ticket to mention `opacityscale` then?

**Comment by lucapinello** [comment]
Good idea, @nicolaskruchten do you want to change the title in.  Implement opacityscale also in Surface as available in Volume and Scatter3D for consistency.

**Comment by etpinard** [comment]
@archmoj would adding `opacityscale` be a valuable addition to the library in your mind?

If so, please tag this ticket with `type: feature`.

**Comment by etpinard** [comment]
(not to be confused with https://github.com/plotly/plotly.js/issues/4120)

**Comment by archmoj** [comment]
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/jOEZagL) where `opacityscale` is implemented for `surface` plots.

**Comment by nicolaskruchten** [comment]
I'm not sure I understand how this opacityscale works... what is it using as data here, `z`?

**Comment by archmoj** [comment]
In regard with `opacityscale` one could pass an array similar to `colorscale` replacing colors with alpha values.
For example: 
```js
[
[0, 0.2]
[0.5, 0.3]
[1, 0.6]
]
```
would map the opacity of min color to 0.2, the average to 0.3, and the maximum color to 0.6.
There is also strings keys namely "min", "max" and "extremes" to facilitate declaring this.
E.g. the option of "max" maps to [[0, 0.1], [1, 1]] which fades values that are closer to the minimum.

**Comment by nicolaskruchten** [comment]
It feels like it would be a simpler API to accept the A value of RGBA, no?

**Comment by archmoj** [comment]
Well, we could potentially add such an option to `colorscale`.
However it is the way `opacityscale` introduced by `volume` as well as gl-mesh3d webgl module. 
It covers all the cases where one needs to use different opacity levels steps free from various steps defined by any colorscale.

**Comment by nicolaskruchten** [comment]
OK, I guess this makes sense. Seems a bit odd to have two separate scales linked to the same value which doesn't share a name with either i.e. `z` but OK.
