### ISSUE TITLE
Add way to show disputed territories on geo maps

### ISSUE THREAD

**Issue by leigh-plt** [plotly/plotly.js#4345]
Why plotly use russian maps, not internationally recognized maps?

**Comment by alexcjohnson** [comment]
For reference, this came in with #3874 - during which we noticed this change and I commented:

> The only changes I notice are Crimea transferring to Russia (accurate, whatever one thinks of its propriety) and ...

As @nicolaskruchten mentioned we don't make any independent judgments here (feel free to take that up with naturalearthdata), but we would certainly be open to some sort of mechanism for special marking of disputed territories. I'd wait for @etpinard to comment before embarking on a contribution, but presumably this would start with a PR to https://github.com/etpinard/sane-topojson

**Comment by nicolaskruchten** [comment]
Geo maps now accept a `geojson` attribute, so users can specify their own world map.

**Comment by OrchidSoleil** [comment]
So now, after Russia has started the full-scale unprovoked war against Ukraine, is it not obvious to you that Crimea is not a disputed territory, but territory of Ukraine that was occupied by Russia 2014? Why is Crimea still marked as Russia in the default version of the map?

**Comment by Axios0ne** [comment]
@alexcjohnson No, this issue cannot simply be closed, because the territories that you mark on your maps as the territories of the occupying countries are not their territories. 

You could add some additional inscription something like (Crimea is an internationally recognized territory of Ukraine occupied by Russia).

If you discussed the disputed territories for a long time and decided that you will show them as those that are actually controlled by the occupying state. Why don't you mark it on the map so people understand it. Not all map users will read your GitHub explanation.

Also, this applies not only to the occupied territories of Ukraine, other countries have the same situation. For example, Indian territories occupied by China.

**Comment by alexcjohnson** [comment]
@Axios0ne this issue is closed not because we view it as complete (although that was originally why it was closed) but so that we collect all relevant discussions in one place. As I said before, please continue the discussion at https://github.com/plotly/plotly.py/issues/3719, particularly if you'd like to contribute to improving the situation 😄
