### ISSUE TITLE
Grid-graph type (oscilloscope)

### ISSUE THREAD

**Issue by Hadatko** [plotly/plotly.js#4351]
Hi,
is there easy way to have plotly graph working same/similar way as on oscilloscope? That means no axis, only grid. Then describe for each dataset the cell size. This way i can have several different datasets with different values (ranges) in one graph.

Currently what is going on my mind is draw grid "manualy" and describe cell somewhere. But sounds to me as redundant work (workeraund).

**Comment by antoinerg** [comment]
Hello @Hadatko,
First of all, thank you for your interest in plotly.js! I think your question is better suited for the community forum (https://community.plot.ly) since you are not describing a bug or asking for a new feature that we don't have. 

Anyway, I'll try to address it here.

> That means no axis, only grid.

For changing the appearance of the axes, please visit https://plot.ly/javascript/reference/#layout-yaxis to find out a list of all the attributes that will allow you to do so!

> Then describe for each dataset the cell size. This way i can have several different datasets with different values (ranges) in one graph.

One way to achieve this is to have each trace associated with its own y-axis. This way, each y-axis can have a different range which is equivalent to having different cell size. 

Here's an example Codepen: https://codepen.io/antoinerg/pen/zYYmeGY?editors=0010

**Comment by Hadatko** [comment]
Hi @antoinerg, thanks for quick reply and sorry for putting question on wrong page. 
If i may continue here, is there a way to have grid on background staticly initialized? I mean i will set e.g.: grid will have 8columns, 5rows. During zoom the will not changing (their positions).

**Comment by etpinard** [comment]
@Hadatko please use https://community.plot.ly/c/plotly-js so that other users can benefit from the answer. Thank you!
