### ISSUE TITLE
Should we accept 'container' everywhere we have xref and yref?

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4375]
Is there a usecase where we do not want to accept `'container'` for `xref` and `yref`? One possible use would be to draw a vertical line between two columns of subplots, with `x=0.5` and `xref='container'`.

**Comment by alexcjohnson** [comment]
I agree `'container'` would be nice - in this case though I'd think `x` would be `'paper'` (because that's the coordinate space used to position axes - the difference is `'paper'` excludes the margins and `'container'` goes all the way to the edges of the div) but `yref` might be `'container'` with `y` from 0 to 1 so you get a line all the way out including the margins.

**Comment by kaymal** [comment]
Hi, is there any update about this feature?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
