### ISSUE TITLE
difference between live 3-D graph with downloaded PNG 

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4378]
Is this a bug?

![Bunny](https://user-images.githubusercontent.com/33888540/69358330-ad26aa80-0c54-11ea-8694-6a83af66d8ea.jpg)

https://rreusser.github.io/plotly-mock-viewer/#gl3d_bunny

**Comment by alexcjohnson** [comment]
Yes, most definitely a bug. Perhaps something amiss about how we convert the canvas to an image in order to slot it in with the svg pieces? I think that's part of the image generation process in this case anyway...

**Comment by archmoj** [comment]
Also mentioning this one can be helpful.
https://rreusser.github.io/plotly-mock-viewer/#gl3d_rgb_dont_accept_alpha_scatter3d
It appears the live variation is not the correct one since the line with transparency has become completely invisible in the middle!

![gl3d_rgb_dont_accept_alpha_scatter3d](https://user-images.githubusercontent.com/33888540/69359976-ab121b00-0c57-11ea-9740-fb63d5d65ffd.png)

**Comment by archmoj** [comment]
And here is a [demo](https://codepen.io/MojtabaSamimi/pen/JjjzVQZ?editors=1000) illustrating that the results would be identical if `scene.bgcolor` is set to `white` (using the plot on the right).

**Comment by archmoj** [comment]
cc #4360

**Comment by alexcjohnson** [comment]
> And here is a [demo](https://codepen.io/MojtabaSamimi/pen/JjjzVQZ?editors=1000) illustrating that the results would be identical if `scene.bgcolor` is set to `white` (using the plot on the right).

You need to clone `fig` before mutating it, otherwise you get the same actually figure plotted in both cases... but yes, if I do that I see the same thing you do - all screen & downloaded plots look the same except the download with transparent `scene.bgcolor`. But the fix needs to be getting the download to work correctly with transparent background, rather than changing the background to the one that works.

> Also mentioning this one can be helpful.
> https://rreusser.github.io/plotly-mock-viewer/#gl3d_rgb_dont_accept_alpha_scatter3d
> It appears the live variation is not the correct one since the line with transparency has become completely invisible in the middle!

True, but the downloaded one is also not correct - it looks closer to correct, but (a) the one with white bgcolor downloads the same as on the screen, and (b) if you inspect the transparent-bg-download carefully, it appears to be the combination of the two bugs, which in this particular case seems to partially cancel. See for example the gridlines behind the semitransparent trace line - they're lighter than the trace line, but in a correct rendering they would be darker. So I'd consider this a separate bug.

Also perhaps a third bug: giving this plot a white bgcolor makes the semitransparent markers look somewhat more opaque - which I'm not sure I see in the download but you can clearly see it if you create this plot and then toggle the bgcolor in place with `Plotly.relayout(gd, {'scene.bgcolor':'white'})` vs `Plotly.relayout(gd, {'scene.bgcolor':'transparent'})`

Quite a minefield 😅

**Comment by archmoj** [comment]
> > And here is a [demo](https://codepen.io/MojtabaSamimi/pen/JjjzVQZ?editors=1000) illustrating that the results would be identical if `scene.bgcolor` is set to `white` (using the plot on the right).
> 
> You need to clone `fig` before mutating it, otherwise you get the same actually figure plotted in both cases... but yes, if I do that I see the same thing you do - all screen & downloaded plots look the same except the download with transparent `scene.bgcolor`. But the fix needs to be getting the download to work correctly with transparent background, rather than changing the background to the one that works.

Thanks. Above demo is now fixed.
