### ISSUE TITLE
Contour negative valued layer is not visible

### ISSUE THREAD

**Issue by poldz123** [plotly/plotly.js#4415]
Negative numbers within the layer are not that visible, it looks like the symbol it is part of the line.

Adding extra padding should fix this visibility issue only for negative symbols.

![contour-sample](https://user-images.githubusercontent.com/4010507/70355749-e65c3e80-1840-11ea-9d34-8c712d1cfe57.png)

**Comment by etpinard** [comment]
Thanks for pointing this out.

Maybe instead of some vertical adjustment, we could implement https://github.com/plotly/plotly.js/issues/1597 to make the minus sign more visible.

**Comment by etpinard** [comment]
> Adding extra padding should fix this visibility issue only for negative symbols.

Oh you mean some padding between the negative sign and the start of the contour line i.e. tweaking the label bounding box dimensions to "pad" the text of the contour labels. That's actually a great idea with or without https://github.com/plotly/plotly.js/issues/1597 and is probably much easier to implement. 

Thanks for posting @poldz123 !

**Comment by alexcjohnson** [comment]
BTW whenever this gets addressed, looks like contour labels sometimes use the regular hyphen "-", not minus sign "−" like we do for all other negatives

https://github.com/plotly/plotly.js/blob/162afe491bccda9284e7c3b903a45bd9ac5cf836/src/constants/numerical.js#L62

Looking at https://rreusser.github.io/plotly-mock-viewer/#contour_edge_cases - perhaps when `contours.labelformat` is specified we don't fix this character, but we do when auto-formatting? Compare the "-1.0e-6" to "−1µ"
<img width="266" alt="Screen Shot 2019-12-09 at 12 03 11 PM" src="https://user-images.githubusercontent.com/2678795/70456373-fad84b00-1a7b-11ea-91f0-811693ecd656.png">

@poldz123 does your example use `contours.labelformat`? Or is there another case we're missing? We *do* use the correct minus sign for axis ticks with `axis.tickformat`, so seems this issue is just with contour labels.

**Comment by poldz123** [comment]
@alexcjohnson I do use the `contours.labelformat` with the value: `.0f`

**Comment by etpinard** [comment]
@poldz123 I'm attempting to fix this problem in https://github.com/plotly/plotly.js/pull/4540, maybe you could try out this dev bundle:

https://65959-45646037-gh.circle-artifacts.com/0/dist/plotly.min.js

in your use case to see if the results are to your likings. Thanks!

**Comment by poldz123** [comment]
@etpinard 
It looks great, good job. The sign is now visible with the naked eye.

Thanks.

![device-2020-02-03-150710](https://user-images.githubusercontent.com/4010507/73687261-9f9b9100-4697-11ea-8ee1-1e88a3e9f6cf.png)
