### ISSUE TITLE
Plotly basic module much slower than full Plotly for scattergl.

### ISSUE THREAD

**Issue by tboerstad** [plotly/plotly.js#4458]
The only difference between these two pens is which module of Plotly is included:

plotly-latest.min.js is working fine:
https://codepen.io/tboerstad/pen/dyPZoRq

plotly-basic-latest.min.js is slow, especially hovering the mouse over the data points
https://codepen.io/tboerstad/pen/RwNjPgv

**Comment by alexcjohnson** [comment]
The basic module doesn't include `scattergl`, so that codepen will fall back to regular `scatter`.
https://github.com/plotly/plotly.js/tree/master/dist#plotlyjs-basic

**Comment by tboerstad** [comment]
Thank you @alexcjohnson.

As a new user of Plotly.js, it would be helpful to get a warning or error if you try to use a module which is not available. Especially because everything appears to work as normal.

**Comment by alexcjohnson** [comment]
Yeah, I know that can be confusing - it's a decision we made early on to silently ignore unrecognized attributes and attribute values of all kinds, mainly because when you're editing a graph interactively it's easy to end up with leftovers from a previous state (like if you had edited line style but then decide to only display points) and it can even be convenient to get those settings back later if you change your mind.

You can use [`Plotly.validate`](https://plot.ly/javascript/plotlyjs-function-reference/#plotlyvalidate) to ensure all the settings you passed in are used. We've talked about making a debug mode to validate automatically https://github.com/plotly/plotly.js/issues/1741 but this has never quite bubbled up to the top of the queue.

**Comment by tboerstad** [comment]
Thank you, that makes sense. I'll start using `Plotly.validate`.
