### ISSUE TITLE
Feature Req: Edit (drag) plot image positions

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#4512]
I searched to see if there's already an issue for this but couldn't find one. It would be nice to have the ability to edit plot image position via dragging. This would be done by adding a flag to the plot config `edits` object for images, similar to what shapes and annotations already have.

**Comment by sleighsoft** [comment]
Looking for something similar but a little more "generic". I'd like it to be possible to set `editable` or `draggable` on a per element basis.
E.g,
* one shape is draggable because `draggable=true` another isn't because `=false`.
* Title is editable because `editable=true` but axis is not editable because for it default is `editable=false`

I find the current implementation with `editable` quite useless tbh

**Comment by nicolaskruchten** [comment]
You can set some of this stuff in the `config`... https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js#L47

Hopefully this will not be "useless" :)

**Comment by sleighsoft** [comment]
Ah great, missed those. Excuse my "useless" statement but I'd expected element level control right from the get go coupled with a global one

**Comment by sleighsoft** [comment]
But to clarify, there currently is no way to enable e.g. dragging for a single shape?

**Comment by nicolaskruchten** [comment]
I believe this is what `layout.shapes[].editable` is for, no? https://plotly.com/python/reference/layout/shapes/#layout-shapes-items-shape-editable

**Comment by sleighsoft** [comment]
Hmm, maybe documentation should be streamlined. I find it confusing on which combination of settings I need to enable dragging a single shape

**Comment by sleighsoft** [comment]
Also found this related issue: https://github.com/plotly/plotly.js/issues/5463

**Comment by sleighsoft** [comment]
@nicolaskruchten I don't think it works as expected

```html
<head>
	<!-- Load plotly.js into the DOM -->
	<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
</head>

<body>
	<div id='myDiv'><!-- Plotly chart will be drawn inside this DIV --></div>
</body>
```

```javascript
var trace1 = {
  x: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  y: [0, 1, 3, 2, 4, 3, 4, 6, 5],
  type: 'scatter'
};
var trace2 = {
  x: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  y: [0, 4, 5, 1, 2, 2, 3, 4, 2],
  type: 'scatter'
};
var data = [trace1, trace2];
var shapes = [
  {
    type: "line",
    x0: 2,
    y0: 0,
    x1: 2,
    y1: 1,
    yref: "paper",
    line: {color: "RoyalBlue", width:3},
    editable: true
  },
  {
    type: "line",
    x0: 3,
    y0: 0,
    x1: 3,
    y1: 1,
    yref: "paper",
    line: {color: "Red", width:3},
    editable: false
  }
];
var layout = {
  shapes: shapes
};
var config = {
  edits: {
    shapePosition: true
  }
};
Plotly.newPlot('myDiv', data, layout, config);
var myPlot = document.getElementById('myDiv');
```

![image](https://user-images.githubusercontent.com/9438971/133746541-b7f51ae0-46f7-4bcd-9d38-2cdd1e22b3db.png)

* I can now drag both the red and blue line albeit I set `editable=true` for the first one and `editable=false` for the second one.
* When setting `edits>shapePosition=false` then I cannot drag any shape even if `editable=true` for the blue is set.

**Comment by sleighsoft** [comment]
On another topic: Is it possible to obtain an event when clicking on a shape? e.g. when I click on a shape I'd like its color to change

**Comment by nicolaskruchten** [comment]
Hehe, ok, this conversation is going way off topic compared to the original request here, which was to make `layout.images` draggable :) Maybe we can create a new issue or a community forum post or something?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
