### ISSUE TITLE
Accept u, v and w in isosurface and volume APIs similar to cone and streamtube APIs

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4517]
When working with CFD (computational fluid dynamics) simulation the data could be in the form of 3-D vector (u, v, w). To facilitate interfacing with raw data (and adding iso-surface layers on top of stream tube or cone plots), the `value` array including wind speed can be computed internally.

**Comment by jackparmer** [comment]
Hey @peterdsharpe, might be of interest to you 👆

**Comment by empet** [comment]
I'm not familiar with  volumes that can have the attributes u, v, w.
For  a Cone trace (u,v, w) represents the direction of a vector field at the corresponding point (x, y, z).
For volumes I can think at u, v, w  as parameters, similar to parameters in parameterized surfaces,
i.e. u, v, w are derived from a 3d meshgrid, and then
x, y, z are functions of (u,v,w):
 x(u,v,w), y(u,v,w), z(u,v,w).

The values at x, y, z are theoretically defined by a function f:

`vals = f(x(u,v,w), y(u,v,w), z(u,v,w))`

When x(u,v,w)=u, y(u,v,w)=v, z(u,v,w) we can recover the actual definition of a volume.
If this is a case it's a nice extension. Otherwise, please give more details to be able 
to express an opinion.
