### ISSUE TITLE
[FeatureRequest] Allow string functions for modebar buttons

### ISSUE THREAD

**Issue by Batalex** [plotly/plotly.js#4538]
Hi,

It would be quite nice to be able to define `click` function for modebar button from a string. 
Here is the relevant part: https://github.com/plotly/plotly.js/blob/master/src/components/modebar/modebar.js#L170-L172.

This would enable Python, R & co users to add their own modebar buttons and keep Plotly figures serializable.
I have been fiddling with this minimal example in Python:
```python
import plotly.graph_objects as go

icon1 = {
    "width": 500,
    "height": 600,
    "path": "M224 512c35.32 0 63.97-28.65 63.97-64H160.03c0 35.35 28.65 64 63.97 64zm215.39-149.71c-19.32-20.76-55.47-51.99-55.47-154.29 0-77.7-54.48-139.9-127.94-155.16V32c0-17.67-14.32-32-31.98-32s-31.98 14.33-31.98 32v20.84C118.56 68.1 64.08 130.3 64.08 208c0 102.3-36.15 133.53-55.47 154.29-6 6.45-8.66 14.16-8.61 21.71.11 16.4 12.98 32 32.1 32h383.8c19.12 0 32-15.6 32.1-32 .05-7.55-2.61-15.27-8.61-21.71z",
}

config = {
    "modeBarButtonsToAdd": [
        {
            "name": "color toggler",
            "icon": icon1,
            "click": "function(gd) {Plotly.restyle(gd, 'line.color', '#FF00FF')}",
        }
    ],
}

fig = go.Figure(go.Scatter(y=[2, 2, 1], mode="lines"), {})

fig.write_html("custom_button.html", config=config)

```

And it is almost working. I just need to edit the `custom_button.html` file and remove the quotes around the function to get it working.

**Comment by chuck-a-knight-xom** [comment]
Where did this feature request end up? I've been trying to add a custom modebar button in python and can't seem to find anything that works

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
