### ISSUE TITLE
Bar "end" parameter

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4559]
Having `base` and `end` would allow for a lot of flexibility for use-case like timelines.

**Comment by archmoj** [comment]
I was wondering one may use `reversed` horizontal with `base` for that?
Could you please share an image example?

**Comment by nicolaskruchten** [comment]
can you elaborate please?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
