### ISSUE TITLE
Initial draw animations

### ISSUE THREAD

**Issue by jdonnell01** [plotly/plotly.js#4571]
Hello,

Does plotly currently support initial draw animations similar to Highcharts chart.animation?

- https://api.highcharts.com/highcharts/chart.animation
- https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-animation-easing/

Thank you

**Comment by etpinard** [comment]
No, we don't support that at the moment unfortunately.

Thanks for posting!

**Comment by FabricioRHS** [comment]
Alternative we have is to use Animation to (re) load the data.
Sample: https://jsfiddle.net/fabriciorhs/z7hg3se4/

![animation_plotly_fabriciorhs](https://user-images.githubusercontent.com/4131392/78180249-e3610b80-7438-11ea-9cd6-fa54cc0180de.gif)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
