### ISSUE TITLE
Customize BoxPlot Quantiles Labels

### ISSUE THREAD

**Issue by AdnanBoota** [plotly/plotly.js#4587]
Hi Team Plotly @etpinard ,

Thanks for the great library!

Can we please have the option to rename the labels of the quantiles of the box-plot? i.e. change the labels of [min, q1, median, q3, max] to something else using some prop `quantileLabels:['5%', '25%', '50%', '75%', '95%']`
![boxplot-quantiles](https://user-images.githubusercontent.com/14972616/74644239-45f69480-5176-11ea-9548-7004405ad54e.png)

Regards,
Adnan

**Comment by khegewisch** [comment]
I second this request.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
