### ISSUE TITLE
HoverInfo is truncated with long variable names

### ISSUE THREAD

**Issue by AMarthaller** [plotly/plotly.js#460]
There doesn't appear to be a way to specify the hoverinfo width. With longer variable names the strings are truncated with ellipses. I haven't tried any of the samples for providing custom hoverinfo text since I'm using the R API and overriding event handlers is not supported (as far as I can tell).

Duplicate on StackOverflow:
http://stackoverflow.com/questions/36207887/plot-ly-hover-box-size-attribute

It would be nice if the desired tooltip dimensions could be specified.

**Comment by etpinard** [comment]
> There doesn't appear to be a way to specify the hoverinfo width.

Not at the moment.

Here's a workaround: http://codepen.io/etpinard/pen/LNJmeM

**Comment by nothinkelse** [comment]
I think this is not a solution. I would like the text to be same in legend and in hover tooltip. now in your workaround you have trace1, trace2 in legend which is not so informative.

I have to put the same information into text, and into name of trace to achive this, but then in tooltip information is displayed twice.

![image](https://cloud.githubusercontent.com/assets/6547340/16683361/c2ee53f6-44ff-11e6-96fa-02fd1b269524.png)

**Comment by etpinard** [comment]
@nothinkelse you can set the trace `hoverinfo` to `x+y+text` (instead of the default `x+y+text+name`) to remove the trace name from the hover labels.

**Comment by meyermj** [comment]
This is still not very satisfying. I know it seems minor, but from a stylistic standpoint, it's much nicer to be able to use the separation of styling between the number shown and the label. This is automatic with hovertext=name, but the unfortunately truncation happens. Hovertext=text works to display the full label, however, the styling is less satisfying (causes an extra tall hovertext box, no separation between number and label making it harder for the eyes to quickly parse). Furthermore, as others have pointed out, you may want to display separate information in the text field from the name field and display both without truncation: https://community.plot.ly/t/re-size-hover-info-box/955/2

Since the hovertext boxes can already be really wide to accommodate long text fields, why not just allow name fields to also grow the width of the hovertext box in a similar manner? It could even be a simple flag: truncatename: true/false, with true as default so as not to change current default behavior.

**Comment by etpinard** [comment]
> It could even be a simple flag: truncatename: true/false, with true as default so as not to change current default behavior.

If you feel like making a PR, go for it :rocket:

**Comment by SergioCordova** [comment]
I am currently having the same problem and the workaround is not doing it for me. This is my plot

![image](https://user-images.githubusercontent.com/29874726/28182210-987f052e-67c8-11e7-8c7b-ef182b16ef60.png)

If I were to change  `hoverinfo` to `"text"` and change the text to include the name of the trace, then the trace name will appear inside the bar along with the numbers like so.

![image](https://user-images.githubusercontent.com/29874726/28182442-6db03ae2-67c9-11e7-8a2c-a9ae68bbffec.png)

Is there a workaround for this?

**Comment by etpinard** [comment]
@SergioCordova  see https://codepen.io/etpinard/pen/dRaLjb

**Comment by pluskid** [comment]
Same issue here

**Comment by manuelfigueiral** [comment]
> I think this is not a solution. I would like the text to be same in legend and in hover tooltip. now in your workaround you have trace1, trace2 in legend which is not so informative.
> 
> I have to put the same information into text, and into name of trace to achive this, but then in tooltip information is displayed twice.
> 
> ![image](https://cloud.githubusercontent.com/assets/6547340/16683361/c2ee53f6-44ff-11e6-96fa-02fd1b269524.png)

try using using `hoverlabel = dict(namelength = -1)` instead

example:

```
line = dict(type='scatter',
                x = x_vector,
                y = y_vector,
                mode = 'lines+markers',
                name = base.columns[i],
                hoverlabel = dict(namelength = -1)
               )
```

![screenshot 2018-10-04 13 44 59](https://user-images.githubusercontent.com/42811980/46474804-bc8e2e80-c7db-11e8-82c2-eb9bc6915d28.png)

**Comment by RajshekarReddy** [comment]
adding `hoverlabel: {namelength :-1}` into my trace object did the trick.
