### ISSUE TITLE
Long titles for indicator bullet charts are cut off

### ISSUE THREAD

**Issue by mtadams007** [plotly/plotly.js#4600]
Hi,

I'm working on having multiple bullet charts with titles. If the title is too long, then it gets cut off and is unreadable. I didn't see any options to make the titles autofit, but regardless I think it would be better if the titles aren't automatically cut off.

Here's an example with multiple bullet charts: https://codepen.io/mtadams007/pen/VwLPXqe?editors=0010

And here's a simpler example with just one graph: https://codepen.io/mtadams007/pen/zYGNWbQ?editors=0010 

Thanks!

**Comment by antoinerg** [comment]
Hello @mtadams007 and thank you for reporting this problem. Unfortunately, at the moment, margins are not automatically expanded for bullet titles. In the meantime, a quick workaround would be to increase the left margin via the margin layout attribute (ie. `layout = {margin: {l: 200}`).

**Comment by Luiscri** [comment]
Hi, what about if the title is above the gauge? I have the same problem, the title appears quite close (almost overlapping) with the chart and I want to increase the margin of the chart and its title

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
