### ISSUE TITLE
Feature Request: Make data table columns sortable

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.js#4603]
Hey, I was looking through the documentation and see a lot of cool, useful features. I saw the table with the draggable columns which looks great! Is it possible to also have the tables have say, an up and down arrow, to filter by saying ascending or descending row values. Ex: A column with ints of 9, 2, 6 when the arrow is clicked  would return 9, 6, 2 for descending or 2, 6, 9 for ascending.

**Comment by guyts** [comment]
Yeah, this would be a great addition +1

**Comment by Frick-David** [comment]
@guyts I will say that for now, tables in base html are sortable, check out w3 sortable tables.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
