### ISSUE TITLE
hover/texttemplate available keys

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4616]
It would be nice to have a special variable in hover/text-templates like `%{available_keys}` or something that contained all the available keys, for discoverability purposes

**Comment by antoinerg** [comment]
There should be a way to automate the generation (and even the testing) of the list of available keys in hover/text-templates for inclusion in the documentation.

**Comment by nicolaskruchten** [comment]
True, but even then, having it magically/dynamically accessible would be pretty sweet!

**Comment by antoinerg** [comment]
Related to https://github.com/plotly/plotly.js/issues/4139

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
