### ISSUE TITLE
false z data displayed when hovering over scatter3d on gl3d_wolrd-cals mock

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4629]
[Codepen](https://codepen.io/MojtabaSamimi/pen/WNvMyBj?editors=1000)

**Comment by archmoj** [comment]
[Working demo](https://codepen.io/MojtabaSamimi/pen/LYVQBPK?editors=1000) using v1.23.1
Regression since [v1.24.0](https://github.com/plotly/plotly.js/releases/tag/v1.24.0).

**Comment by archmoj** [comment]
The `zcalendar` is `thai` and we get into the `catch` block here:
https://github.com/plotly/plotly.js/blob/be708650801e24a0c9eb56bd6bdc755834cb8daa/src/lib/dates.js#L193.
Are those dates invalid?

**Comment by alexcjohnson** [comment]
This is not a high priority, unless it's blocking someone specific.

The "working demo" isn't actually working either - it's displaying the dates using the input data calendar, but should really be displaying them using the axis calendar. It looks as though the current behavior is trying to take the input data and treat it as though it's already a date from the axis calendar. What it should really be doing is taking the calcdata (milliseconds) value, and converting that back to a date according to the axis calendar, and displaying that. If the calcdata value isn't available, it would need to re-create it - ie first convert from input calendar date to milliseconds, then convert back to an axis calendar date.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
