### ISSUE TITLE
Enable "TMS" tile layer scheme as overlay in scattermapbox. 

### ISSUE THREAD

**Issue by meteoDaniel** [plotly/plotly.js#4658]
There are two different ways of defining `xyz` tile layers for map visualisation. They are differing in the orientation of the naming of the y coordinate:
The TMS specification orders from Bottom Left and the Google/OpenStreetmap (WMS, 'slippy') specification orders from Top Left. So the y naming is inverted. 

Here you can find the required mapbox gl entry point: 
[Vector->Scheme](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#vector-scheme
)

This issue https://github.com/plotly/plotly.py/issues/1610 and this thread https://github.com/plotly/plotly.py/issues/2272 relates to this problem.

**Comment by meteoDaniel** [comment]
Any updates on this issue?

**Comment by nicolaskruchten** [comment]
We'd be happy to integrate a PR for this but as far as I know no one is actively working on it :)

**Comment by aleb** [comment]
Replacing the hardcoded "xyz" with "tms" in `plotly-2.8.3.js` allows using `tms` tiles just fine. There is this piece of code which makes the difference: `scheme === 'tms' ? Math.pow(2, this.z) - this.y - 1 : this.y`. The fix would be trivial, just allow users to specify "scheme"  and pass it further where `"xyz"` is hardcoded.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
