### ISSUE TITLE
missing grid lines and tick labels with range breaks at daily level

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4686]
See https://codepen.io/nicolaskruchten/pen/bGdxaVp

**Comment by archmoj** [comment]
@nicolaskruchten would you please set `width` and `height` in the codepen i.e. to ensure we are looking at identical graphs.
Thanks!

**Comment by nicolaskruchten** [comment]
Done, although this is something you could have done by forking the pen :)

**Comment by archmoj** [comment]
@nicolaskruchten thank you!!

@alexcjohnson I am not 100% sure if missing those lines is a bug. 
But we could try improving that for sure.

On another note - it looks there is a wrong label displayed at that scale for `Nov 15` which should be `Nov 16` maybe?

**Comment by alexcjohnson** [comment]
The issue is with our automatic `dtick` algorithm, which in certain conditions can return either 2 days or 3 days, in addition to 1 day, 1 week, and other values.

https://github.com/plotly/plotly.js/blob/60425d2d3c8f00f20e786bae906e22c9f1b236ca/src/plots/cartesian/axes.js#L760

https://github.com/plotly/plotly.js/blob/60425d2d3c8f00f20e786bae906e22c9f1b236ca/src/plots/cartesian/axes.js#L809

When you remove weekends with `rangebreaks`, 2 or 3 day ticks look bizarre.

Suggestion: if we have `day of week` breaks, run that algorithm but if the result was 2 days reduce it to 1 day, and if the result was 3 days increase it to 1 week.
