### ISSUE TITLE
Unable to import Plotly from 'plotly.js-dist' in webcomponent

### ISSUE THREAD

**Issue by vikjung** [plotly/plotly.js#4706]
When use  
import Plotly from 'plotly.js-dist';  

get error - 
Uncaught SyntaxError: The requested module '../node_modules/plotly.js-dist/plotly.js' does not provide an export named 'default'

When use  
import * as Plotly from 'plotly.js-dist';  

get error  -
plotly.js:24965 Uncaught TypeError: Cannot read property 'document' of undefined
    at plotly.js:24965

**Comment by PipGrylls** [comment]
I have has the same issue when rebuilding a website into Lit from Polymer. 

I considered bundling, but decided to use a script tag import instead withing a lit-html block to keep consistency with the old codebase. 

Repo is private but the file is here:
https://gist.github.com/PipGrylls/94acb3bdef7d7dc611100757cf60c9ac

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
