### ISSUE TITLE
Bar hovers near range breaks

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4713]
Hovering on a bar that's immediately after a range break only works on half the bar: try hovering over the last bar here: https://codepen.io/nicolaskruchten/pen/PoqVBNW?editors=1010

**Comment by archmoj** [comment]
If we set `offset` to 0, the bars are positioned in the right place | [demo](https://codepen.io/MojtabaSamimi/pen/ZEGwqpK?editors=1010). 
Maybe we could/should coerce `offset` when `rangebreaks` are present and then tweek autorange.
cc: @alexcjohnson

**Comment by alexcjohnson** [comment]
Let's not mess with the bar positioning; there may be certain conditions in which that's the "right place" but that's up to the user to decide (with our help 😁)

I bet there's a solution to this where we find the left and right edges of the bar as we do now, but then turn it into pixels (which apparently works correctly today because we draw the bar across the break) and then *back* into data coordinates.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
