### ISSUE TITLE
Write test to validate mocks

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4733]
cc: https://github.com/plotly/plotly.js/issues/4707#issuecomment-609786084

**Comment by alexcjohnson** [comment]
From #4762: before we consider this issue closed, new mocks must automatically be part of the validation test. IMO that's actually more important than making sure we validate all the existing mocks, though both parts would be useful.

> > My primary question is about the hard-coded list in `mocks_test` - seems like we should be able to
> > 
> > * read in the list of _all_ mocks from the filesystem - perhaps if this step is fast enough we can just have `karma.conf.js` do it before every test run and write the results to a file in `tests/jasmine/assets`?
> > * only list a set of mocks or patterns to ignore - and then over time we can reduce that to an empty list.
> 
> @alexcjohnson
> That is a very good idea we could try in another PR.
> At first I did try to adapt our image test for this purpose.
> But it was rather complicated to acess the system files from the jasmine test.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
