### ISSUE TITLE
Using categorical data in parcoords

### ISSUE THREAD

**Issue by AndreHermanto** [plotly/plotly.js#4737]
Dear Plotly team,

I have a question on how to use parcoords with categorical data. I couldn't see it on any of the examples. I want something like 

```
{
    label: 'A',
    values: ['Category A', 'Category B']
}
```

I know you have examples like this one 

```
{
    range: [1, 5],
    label: 'C',
    values: [2,4],
    tickvals: [1,2,3,4,5],
    ticktext: ['text 1','text 2','text 3','text 4','text 5']
}
```
However, the value of those would still be numerical where I need the 'text' as the value. Its something similar like parcats but, I need the selection just like in parcoords. Is this possible?

Thanks

**Comment by archmoj** [comment]
At the moment one could make use of `ticktext` similar to this [demo](https://codepen.io/MojtabaSamimi/pen/yLNmryM?editors=0010).
@AndreHermanto is this a feature request?

**Comment by AndreHermanto** [comment]
@archmoj I see, with `ticktext` is there a direct way to retrieve the `ticktext` value? If not, then yeah it'll probably be a good feature request for parcoords with categorical data

**Comment by archmoj** [comment]
@AndreHermanto 
In terms of roadmap, at the moment we aren't planning on working on this for the next few months, but if anyone here works for an organization that has a software budget, we do accept sponsorship for features, which would enable us to build this feature faster :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
