### ISSUE TITLE
hovermode - x unified and hovertemplate together not working

### ISSUE THREAD

**Issue by akshay-kale** [plotly/plotly.js#4739]
Hi Team,

I'm trying to achieve custom tooltip as shown in screenshot where i need functionality like x unified but with custom html in it.
please help me for the same.

![image](https://user-images.githubusercontent.com/19792888/78664748-413a9b00-78f2-11ea-9f1e-9ac03ac3b99f.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
