### ISSUE TITLE
New feature request: a modeBarButtonsToKeep argument

### ISSUE THREAD

**Issue by davidhodge931** [plotly/plotly.js#4741]
Currently plotly has a function to remove listed mode bar buttons.

It'd be nice if it had a function to keep listed mode bar buttons, and to drop the rest.

Otherwise the code is quite long-winded if a user only wants to keep one button, such as the camera.

This argument could be called `modeBarButtonsToKeep`.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
