### ISSUE TITLE
Highlight a specific point in Violin chart

### ISSUE THREAD

**Issue by salomi9** [plotly/plotly.js#4743]
- I am using Violin chart of PlotylyJS library, and it takes an array of elements and plots it on the chart, Is possible if I want to highlight one point with a different color from that array ?

- Like if my array is as follows :
````javascript
demoViolin = [31.8, 63.5, 65, 59, 71, 72, 79, 68, 66, 89, 71, 67, 77]
````
- I want to plot this on the graph but I want the point 65 to be highlighted with a different color.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
