### ISSUE TITLE
Schema interpretation: multiple layout xaxis and yaxis 

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4747]
In the [bar_multiline_labels.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/bar_multiline_labels.json#L70) I see that we have several `xaxis` and `yaxis` attributes (written in the form "(x/y)axis(%d)").  However the [schema](https://github.com/plotly/plotly.js/blob/master/dist/plot-schema.json) lists a large number of attributes for the single `"xaxis"` and `"yaxis" ` attributes. 

So my question is: how do we know when we have a single attribute as opposed to a list of attributes that follow a specific _naming convention_?

I have seen that we have some attributes that that have a structure akin to this one (splom and sankey). More concretely we have an `"info_array"` of `"enumerate"`, `"subPlotID"` and `"number"`. In the 2 former cases a regular expression is used specify the attribute **value**. Would it make sense to use something of the kind here too?

TIA.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
