### ISSUE TITLE
Schema: unexpected value in layout_metatext.json - layout.xaxis.domain

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4754]
The mock [layout_metatext.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/layout_metatext.json) has a the following [snippet](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/layout_metatext.json#L37):

```json
  "layout": {
    "xaxis": {
      "domain": {"row": 0, "column": 0},
    }
}
```
Same for the `"yaxis"`. 
According to the schema I see: 

```jspn
                "domain": {
                    "valType": "info_array",
                    "role": "info",
                    "items": [
                        {
                            "valType": "number",
                            "min": 0,
                            "max": 1,
                            "editType": "plot"
                        },
                        {
                            "valType": "number",
                            "min": 0,
                            "max": 1,
                            "editType": "plot"
                        }
                    ],
                    "dflt": [
                        0,
                        1
                    ],
                    "editType": "plot",
                    "description": "Sets the domain of this axis (in plot fraction)."
                },
```

Can anyone tell me if this is an incorrect schema issue, an incorrect JSON mock or if I am diagnosing this incorrectly?

TIA.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
