### ISSUE TITLE
Plotly.validate error on transforms mocks

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4759]
<pre>
TypeError: Cannot read property 'length' of undefined
at src/plot_api/validate.js:132:1 
</pre>

When using `Plotly.validate` on these mocks: [
  `transforms`, 
  `gl2d_transforms`, 
  `polar_transforms`
]

**Comment by archmoj** [comment]
https://github.com/plotly/plotly.js/blob/507308b642ce545814dca207118414aff6109d9e/src/plot_api/validate.js#L132

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
