### ISSUE TITLE
Reversed Y-Axis are flipped to none reversed when click and drag with right mouse button

### ISSUE THREAD

**Issue by DamonLuck-BH** [plotly/plotly.js#4761]
Hi,

This appears after version 1.49.5

I'll borrow the following codepen example which shows a reversed Y-Axis
https://codepen.io/plotly/pen/qdGbdL

If you right click in the chart and slightly move the mouse before releasing the mouse button the Y-Axis will be rendered inverted and not in the initial reversed layout.

TIA,

Damon

**Comment by archmoj** [comment]
@DamonLuck-BH thanks for reporting and "minimal" codepen too!
Here is a [demo](https://codepen.io/plotly/pen/qdGbdL) with plotly.js version pinned down.
This appears to be a regression since [v1.50.0](https://github.com/plotly/plotly.js/releases/tag/v1.50.0).

**Comment by DanielTOsborne** [comment]
I noticed this when calling restyle (or update) as well.
I traced it to doextra(axlist.map(rangeAttr), [0, 1], 0) in _relayout.
If I removed that line, my y-axis remains the correct orientation.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
