### ISSUE TITLE
Plotly Event Handlers in Zeppelin 

### ISSUE THREAD

**Issue by xanderwallace85** [plotly/plotly.js#4763]
Hi guys,

I am trying to run some examples in Zeppelin. For example, I tried the double_click_event case shown in
https://plotly.com/javascript/plotlyjs-events/#double-click-event inside the code below

```
<head>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
  <div id="myDiv" style="width: 800px; height: 500px;"><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
    <!-- JAVASCRIPT CODE GOES HERE -->
  </script>
</body>
```
The problem is that after the first “reaction” nothing happens (only the default click event). I noticed that the problem raises after the Plotly.restyle. Is there a better way to do this maybe?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
