### ISSUE TITLE
sankey: node.link.(width|color) does not support arrays

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4766]
As shown in this [Codepen](https://codepen.io/antoinerg/pen/zYvrzJe), `node.link.color` and `node.link.witdh` does not work with arrays even though the schema says there are `arrayOK: true`.

**Comment by archmoj** [comment]
@antoinerg 
Would you mind pinning down the plotly.js version in your codepen to use version `v1.53.0` instead of latest?
Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
