### ISSUE TITLE
sankey: eventData should state if a link or a node was clicked

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4767]
At the moment, there is no clear way to distinguish whether a click was done on a node or a link. I think it should be clearly identified in the eventData.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
