### ISSUE TITLE
Download plot as png button to accept other file formats

### ISSUE THREAD

**Issue by NEGU93** [plotly/plotly.js#4782]
This feature request was motivated after [this](https://community.plotly.com/t/download-plot-as-png-button-to-accept-other-file-formats/38202) question.

 I would like the button "Download plot as png" to actually be able to export all file formats listed [here](https://plotly.com/python/static-image-export/) and not only png.

This may also provide an easier solution for [this](https://community.plotly.com/t/how-to-download-a-pdf-file-generated-from-a-plot/33432) question.

**When is this useful**
This is useful because:

1. It may work as .fig in matlab. That lets you open and edit things in the image before exporting it (HTML lets you change title, rotate image, etc)
PS: [matplotlib](https://matplotlib.org/) does not support this feature yet (saving .fig files) so it may be a big pro for plotly in Python.
2. If one needs many format images, but it's not sure which one will be needed. One can simply export HTML and then export the other formats as needed.

I currently export HTML, svg and png. I try to use svg not to lose quality when zooming (specially for posters) but I also have the png when I need to edit the image (my image editor does not support svg) and of course, HTML figure for jypter notebooks. If I had this tool I could simply export HTML, edit the HTML and then export the svg format. I tried to do that with the current png format but the quality of the generated image is very bad ([Low quality of ‘download plot as png’ in browser](https://community.plotly.com/t/low-quality-of-download-plot-as-png-in-browser/5450)).

**Comment by jdamiba** [comment]
Hi @NEGU93 

After looking into your issue some more, I realized that the behavior you are looking for is likely already possible. I apologize for the confusion!

If you take a look at https://plotly.com/python/configuration-options/#customizing-download-plot-options, you'll see that it is possible to modify your figure's `config` object in order to customize the behavior of the `download plot` modebar button. This includes setting the height and width and the output format. 

Hope this helps!

**Comment by NEGU93** [comment]
Well, this is nice! Thank you. I will use that solution for the moment.
However, this will require to set the extension before exporting the HTML file. I think it's nicer to be able to set this extension AFTER the HTML is created. 
Just let you choose the extension when downloading the figure like this:
![Untitled](https://user-images.githubusercontent.com/9558385/80081517-58fd5a80-8553-11ea-9a89-247026baa6be.png)
And instead of txt file, all the supported formats. Similar to Word's save as file that let you chose docx, doc, pdf, etc.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
