### ISSUE TITLE
Unified hover labels overflow with too many traces

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#4786]
From @jcunhafonte https://github.com/plotly/plotly.js/pull/4620#issuecomment-617065363:

> <img alt="Screenshot 2020-04-21 at 10 27 49" width="944" src="https://user-images.githubusercontent.com/17337794/79849721-c32ec780-83ba-11ea-8c92-59f85e4b4166.png">
> 
> When there are many traces the information gets hidden. Any hint or suggestion to have the legend with scroll or above the graph?

That's a good point - it would be tricky to have this scroll since you can't in general mouse over it; and we don't really want to overflow the graph container, that could have all sorts of negative repercussions. 

One possibility that occurs to me is perhaps when the box is cut off we use the vertical position of the cursor as the scroll bar: when the cursor is near the top of the subplot you see the top of the label, when it's near the bottom you see the bottom.

Another possibility is to find the trace closest to the cursor and make sure the entry for that particular trace is visible; but that would be jittery and anyway if you have two traces exactly on top of each other, you might never be able to see the label for the bottom one. So I think I prefer the first option.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
