### ISSUE TITLE
cursor-pointer persists when a point with annotation clicktoshow: "onoff" is unhovered

### ISSUE THREAD

**Issue by jshleeb** [plotly/plotly.js#4788]
https://jsfiddle.net/Lwqc6hb8/

Hover over the point with the annotation, then move the cursor away. One would expect the cursor to go back to normal after moving it away from the point, but it does not.

Inspecting shows that the class `cursor-pointer` persists on the div with the `nsewdrag` drag class, until a different point with no annotation is hovered.

A similar bug happens with `clicktoshow` is set to `onout`, but only when the annotation is not visible.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
