### ISSUE TITLE
Scatter Plot rendered to HTML flashes blue when clicked on Chrome for Android 

### ISSUE THREAD

**Issue by SimonRosen173** [plotly/plotly.js#4804]
When the scatter plot is clicked on Chrome on mobile the graph flashes blue. 

A potential css fix might be here https://stackoverflow.com/questions/21003535/anyway-to-prevent-the-blue-highlighting-of-elements-in-chrome-when-clicking-quic

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
