### ISSUE TITLE
Add either rel="noopener" or rel="noreferrer" to plotly.com link created with chart

### ISSUE THREAD

**Issue by trycrmr** [plotly/plotly.js#4809]
![image](https://user-images.githubusercontent.com/6002123/80994228-63004280-8e0a-11ea-8256-e0cd032bcf57.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
