### ISSUE TITLE
In relative barmode labels are overlapped when both bars have value 0

### ISSUE THREAD

**Issue by anatoly314** [plotly/plotly.js#4822]
Actually it might be by design, but I decided to raise this question too, maybe it should be fixed by library itself.

I'm using [relative barmode](https://plotly.com/javascript/reference/#layout-barmode) and need to show some customized text when both opposite bars have value `0`. The issue that for value 0 both bars grow in the same direction and labels are overlapped:
[![enter image description here][1]][1]

The only solution which I've thought about is checking when the value is `0` and change it dynamically to something like `-0.009` and manually display the right value despite it's actually wrong. But it's cumbersome solution and chart keep rendering tiny bar for those values which isn't acceptable.

[This is my example on Codepen](https://codepen.io/anatoly314/pen/ExVQJxw)

Can label direction be controlled manually? If not, I guess they should be.
This question has been asked on [StackOverflow too](https://stackoverflow.com/questions/61657786/plotly-js-in-relative-barmode-labels-are-overlapped-when-both-bars-have-value-0).

  [1]: https://i.stack.imgur.com/2Gq6p.png

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
