### ISSUE TITLE
Is it OK to port plotly color palettes into R package?

### ISSUE THREAD

**Issue by dracodoc** [plotly/plotly.js#4830]
I use ggplot and plotly R package a lot, and found plotly color palettes are very good. They are visually pleasing and often good enough out of box for my usage. With ggplot I can only use the default color palette and brewer palette, which is good but not enough.

I looked at the source code of plotly color palettes and RColorBrewer, it seemed not too hard for me to port plotly color palettes into R pacakge and make them available to all R usesr.

I read the license in plotly.js and I think it should be possible to do this, but still want to ask here first.

Is it OK for me to port your great color palettes into R?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
