### ISSUE TITLE
offline map need access token

### ISSUE THREAD

**Issue by 1shaked** [plotly/plotly.js#4833]
hey i am triing to use plotly offline with my own coustom map but i can not use it.
i am using tiff as my map.
i am using my own offline node js server and tried setting all but it is keep asking for intenet connection. 
my code is:
 
`
Plotly.d3.csv(
	"https://localhost:8000/point.csv",
	function(err, rows) {
		function unpack(rows, key) {
			return rows.map(function(row) {
				return row[key];
			});
		}

		var data = [
			{
				type: "scattermapbox",
				text: unpack(rows, "Globvalue"),
				lon: unpack(rows, "Lon"),
				lat: unpack(rows, "Lat"),
				marker: { color: "fuchsia", size: 4 }
			}
		];

		var layout = {
                       layers: [
                           sourcetype: 'image',
                           source: 'localhost:8000/static/image.png'

]
			dragmode: "zoom",
			mapbox: { style: "open-street-map", center: { lat: 38, lon: -90 }, zoom: 3 },
			margin: { r: 0, t: 0, b: 0, l: 0 }
		};

		Plotly.newPlot("myDiv", data, layout);
	}
);
` 

i can not connect to the internet, and run this code on offline computer.
i have a tiff map also and png both can not be set offline

**Comment by archmoj** [comment]
@1shaked What happens when you are connected to the internet? Does your app work?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by 1shaked** [comment]
to long i am not working there ay more thanks anyway
