### ISSUE TITLE
Unable to specify title background color or make it non transparent

### ISSUE THREAD

**Issue by mizeljko** [plotly/plotly.js#4834]
Right now, we are not able to specify background color for y-axis title, it is always transparent and text on text makes it difficult to read either of the values. Is it possible to specify background color or at least to make it non-transparent?

Example:
![image](https://user-images.githubusercontent.com/45470295/81953100-45cf2f00-95d5-11ea-9955-c06e489109d7.png)

Codepen:
https://codepen.io/mizeljko/pen/WNQgoVG

**Comment by archmoj** [comment]
@mizeljko ths is a feature request, right?

**Comment by mizeljko** [comment]
Yes, since I'm assuming there is currently no option for this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
