### ISSUE TITLE
Sankey Diagram canvas scaling distorts node aspect ratio

### ISSUE THREAD

**Issue by leviznull** [plotly/plotly.js#4847]
It seems that the nodes are scaled to the height of the canvas/plotting frame. It seems the plotted diagram is scaling to the size of the canvas. However the sample diagrams listed by Plotly do not seem to struggle with this issue. Is there a way to avoid the distorted node scaling outlined below?

When I limit the canvas size the an ideal aspect ratio `height:50vh;` `width:100vw` the nodes have the correct aspect ration displayed.
![image](https://user-images.githubusercontent.com/31088360/82410427-7403b180-9aa2-11ea-9374-70d5bdec3952.png)

When I set the canvas size to full page using `height:100vh;` `width:100vw` the nodes are elongated and the intended aspect ratio of the nodes are distored.
![image](https://user-images.githubusercontent.com/31088360/82410453-841b9100-9aa2-11ea-8985-c5078fc9b235.png)

There are several examples given on the [plotly page](https://plotly.com/javascript/sankey-diagram/) that are seemingly able to increase the canvas size without distorting the node sizes.
![image](https://user-images.githubusercontent.com/31088360/82410843-2f2c4a80-9aa3-11ea-8c5e-0b380cfe3734.png)

My example can be viewed here:
https://codepen.io/leviz/pen/Vwvqzgv

**Comment by sdbeuf** [comment]
+1

**Comment by endlessbeloved** [comment]
You can set `fig.update_traces(domain_y=list([0,1]), selector=dict(type='sankey'))`  to  `fig.update_traces(domain_y=list([0,0.5]), selector=dict(type='sankey'))` .
It maybe work

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
