### ISSUE TITLE
unable to set tickwidth and tickcolor via template

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4852]
[Demo](https://codepen.io/MojtabaSamimi/pen/RwWvpdW?editors=0010)

**Comment by archmoj** [comment]
@alexcjohnson 
Hmm... not sure if this is a bug?
It goes down to here: 
https://github.com/plotly/plotly.js/blob/bee245587214ed5f1fcc23fcad8006eb75f7cfe2/src/plots/cartesian/layout_defaults.js#L219-L221

Should we support `template` for axes?

**Comment by alexcjohnson** [comment]
I think the problem is a little more subtle than that. We *do* support templating axes, but currently `Lib.coerce2` does not consider a template value to be "non-default."

Consider: just adding empty containers for the axes also doesn't show the ticks:
```js
Plotly.newPlot(gd, {
  data: data,
  layout: {
    template: {layout: layout},
    yaxis: {},
    xaxis: {}
  }
});
```

But if you explicitly turn the ticks on they have the style from the template:
```js
Plotly.newPlot(gd, {
  data: data,
  layout: {
    template: {layout: layout},
    yaxis: {ticks: 'outside'},
    xaxis: {ticks: 'inside'}
  }
});
```

And if you turn ticks on explicitly from the template, that also makes them appear:
```js
var layout = {
  "yaxis": {
    "type": "log",
    "tickwidth": 5,
    "tickcolor": "green",
    ticks: 'outside'
  },
  "xaxis": {
    "type": "date",
    "tickwidth": 50,
    "tickcolor": "red",
    ticks: 'outside'
  }
};
Plotly.newPlot(gd, {
  data: data,
  layout: {
    template: {layout: layout}
  }
});
```

What's happening is in this block:

https://github.com/plotly/plotly.js/blob/bee245587214ed5f1fcc23fcad8006eb75f7cfe2/src/plots/cartesian/tick_mark_defaults.js#L21-L24

`Lib.coerce2` returns `false` because no user value was provided, even though the template provided a value. So `ticks` defaults to `''` rather than `'outside'`.

In this particular case I think it's clear that we want to consider the template value to be "non-default" and to therefore cause ticks to be shown. I _think_ that's a generally true statement, following from the principle that `layout: obj` should produce equivalent output to `layout: {template: {layout: obj}}`, so we should fix that at the level of `Lib.coerce2`, but we should explore some of the other uses of `Lib.coerce2` before deciding that for sure.

**Comment by archmoj** [comment]
Reopening after the revert by #5016.

**Comment by nicolaskruchten** [comment]
is it true that we can't set the tickwidth etc in the template ? or just that we have to also show the ticks from the template?

**Comment by archmoj** [comment]
We were unable to set that before `v1.54.3`. Now moving forward with `v1.54.7`, again we cannot set that.

**Comment by nicolaskruchten** [comment]
I can't agree with "we cannot set that" ... if you also set `ticks: "outside"` in the template then you'll see that the provided tickwidth values in the template are indeed set in the figure. So the problem is not precisely "you can't set it", the problem is that "setting it doesn't also trigger all the other default behaviours it does when it's set in the layout".

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
