### ISSUE TITLE
Scattermapbox built-in styles cause an error

### ISSUE THREAD

**Issue by greenafrican** [plotly/plotly.js#4855]
When setting the `layout.style` to ~`white-bg`~ any of the built-in plotly.js style objects for a `scattermapbox` causes an error.

https://codepen.io/greenafrican/pen/GRpzwdY

**Comment by archmoj** [comment]
No error without mapbox `symbols` & `text`: [demo](https://codepen.io/MojtabaSamimi/pen/ZEbwNaw?editors=0010).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
