### ISSUE TITLE
The `preprocess` is broken.

### ISSUE THREAD

**Issue by cy6eria** [plotly/plotly.js#4863]
**Problem**: The `npm run preprocess` fails with message: "TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object".
**OS**: Mac OS 10.15.4
**Node**:  14.2.0
**Version**: With HEAD on 5010b80dcfdb66a2d6ce8a6650ee7982a5f01a73.

The cause of the problem is in the `tasks/util/update_version.js` The `falafel` package returns an Object, but `fs.writeFile` expect `string`, `Buffer`, `TypedArray` or `DataView`.

**Comment by archmoj** [comment]
That may be related to the node version. Have you tried using node 12 instead?

**Comment by cy6eria** [comment]
@archmoj hi, i almost sure that it is. I tested with 12.16.3 and it works. I've created a simple fix and it doesn't affect the script on 12.16.3, but works with 14.2.0.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
