### ISSUE TITLE
scatter3d line width problem with connectgaps

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4865]
[Demo](https://codepen.io/MojtabaSamimi/pen/eYpoRWq?editors=0010).

**Comment by archmoj** [comment]
Also see https://community.plotly.com/t/connectgaps-skips-over-valid-data-points-in-scatter3d/39437.

**Comment by archmoj** [comment]
Possibly related to https://github.com/gl-vis/gl-line3d/commit/1e423756.

**Comment by archmoj** [comment]
Also there is no line between gaps when using `dash` style for lines | [demo](https://codepen.io/MojtabaSamimi/pen/yLYrvyo?editors=0010).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
