### ISSUE TITLE
Scatter not handling color item when it is an array of numbers

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4868]
This is related to `scatter` trace. `scattergl` & `scatter3d`  traceswork well.
[demo](https://codepen.io/MojtabaSamimi/pen/VwvNxWd?editors=0010)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
