### ISSUE TITLE
Disabled legend item color

### ISSUE THREAD

**Issue by mizeljko** [plotly/plotly.js#4871]
Can we set color of the disabled legend items text? Right now it seems that non disabled get the color directly from layout font color and disabled ones are colored with a bit lighter color. For example, in https://codepen.io/mizeljko/pen/bGVyGaK we set layout font color to green, so "trace 0" is colored gree and disabled "trace 1" is light green.

Is there a way to customize these the same way we can for example customize color for each of the lines next the the legend text?

**Comment by archmoj** [comment]
The current logic, as you mentioned, is based on reducing the opacity by a constant number. And this ratio could potentially be exposed by the API.
Whereas legends can have multiple colours, I am not sure how we could allow users to control all those colours.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
