### ISSUE TITLE
Add minimum gap between axis ticks

### ISSUE THREAD

**Issue by mizeljko** [plotly/plotly.js#4872]
Is it possible to add gap between axis ticks?

Right now I have x axis contains number values as categories, and when the chart size is too small, it would be preferable to display values horizontally. However, when setting the tickangle to 0, values end up too close to each other:
Codepen example with values too close to each other: https://codepen.io/mizeljko/pen/XWmwdNE
With tickangle=0 and without:
![image](https://user-images.githubusercontent.com/45470295/82943567-d871b580-9f67-11ea-8db3-614f4b8973a5.png)

**Comment by archmoj** [comment]
possibly a feature request

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
