### ISSUE TITLE
Plotly.react transition glitch when annotation array length decreases

### ISSUE THREAD

**Issue by aatishb** [plotly/plotly.js#4886]
When I update the annotation array, in certain situations I see glitches with Plotly.react transitions. I believe this issue occurs when the annotation array decreases in length, but still has some elements in common with the previous array. 

Here is a gif of the glitch.

![annotationtransitionglitch2](https://user-images.githubusercontent.com/1878638/83335267-9c956380-a279-11ea-84f3-fadf183d0777.gif)

Here is an example of this: https://codepen.io/aatish/pen/xxwvYGd

Notice that if the new annotation array is longer than the existing array, then this glitch does not occur (which you can see by uncommenting line 40 in the codepen).

Previously I filed #4839 but I believe this is a different (although possible related) bug. Currently this issue is blocking me on a project, so if anyone knows of an easy workaround or fix I'd greatly appreciate any pointers!

**Comment by aatishb** [comment]
In trying to debug this I came across another potential bug. 

https://codepen.io/aatish/pen/ExPoWLK

The expected behavior when I press update is that the annotation should jump to another point on the line, and when I press restart it should go back to the original point being annotated. Instead I find that the annotation jumps off the line and doesn't return.

**Comment by aatishb** [comment]
@archmoj I was just wondering if you happen to know of any workaround for this bug? I have a project that's heavily reliant on plotly.react, and am encountering occasional visual glitches due to this. Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
