### ISSUE TITLE
Feature Request: Sankey cycles

### ISSUE THREAD

**Issue by tkirchm** [plotly/plotly.js#4890]
Hi,

I want to plot the Sankey and therefore link label should be enabled all the time.
Cycle links are drawn the wrong way. b to c looks the wrong way and a to a can be much smaller. b to b could be much smaller.
![image](https://user-images.githubusercontent.com/58719851/83563662-bce44d00-a51b-11ea-9c88-54f8b937d39f.png)

`import plotly.graph_objects as go

fig = go.Figure(data=[go.Sankey(
    node = dict(
      pad = 15,
      thickness = 20,
      line = dict(color = "black", width = 0.5),
      label = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q'],
      x = [0.2,0.3,0.1,0.5,None,None,None,None,None,None,None,None,None,None,None,None,None],
      y = [0.5,0.5,0.5,0.5,None,None,None,None,None,None,None,None,None,None,None,None,None],
      color = "gray"
    ),
    link = dict(
      source = [0,0,0,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,3,3,3,4,4,4,4,4,4,4,4,4,5,0,6,6,6,6,6,6,6,6,6,7,5,5,5,8,8,8,8,8,4,9,6,10], # indices correspond to labels, eg A1, A2, A2, B1, ...
      target = [0,1,11,2,0,5,10,12,13,11,2,0,3,1,10,12,13,14,11,5,11,0,1,0,3,5,1,10,12,13,14,11,6,6,2,0,3,5,10,12,13,14,15,6,16,11,8,0,3,12,14,10,9,8,9,8],
      value = [23,22,2,12,6,16,0,1,2,1,21,14,4,19,72,18,27,3,0,12,2,1,46,12,12,11,1,10,107,0,11,2,142,11,3,23,23,10,45,64,7,11,33,71,15,1,82,8,19,20,60,16,10,25,133,0],
  ))])
fig.show()`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
