### ISSUE TITLE
Negative xaxis values extrapolation

### ISSUE THREAD

**Issue by arsh09** [plotly/plotly.js#4893]
Hello, 

Thank you for the amazing library. 

I read documents for xaxis formatting and I could not find  a way to format date (or linear) such that it will not extrapolate the negative xaxis values. 

Instead of extrapolated values, maybe a '-' (a dash) or something else can be drawn. 

Use case: 

I am plotting data with respect to time, where time for data plotting starts at 00:00 (Minutes : seconds), but if user zoom out, she/he will see "59:00" on negative xaxis. Is there a way to avoid this?

Thank you

**Comment by arsh09** [comment]
Any suggestions on this? 

I am plotting sensor data with time, but I need to show the time from 00:00 to further on positive xaxis (the graph is moving in realtime towards right). Is there a possibility I can avoid showing negative (extrapolated) tick labels? (as pointed in the image below). 

A fig I could think of is to allow a callback function/event whenever the a new tick label is being placed and let user decide the formatting for it? 

![Untitled](https://user-images.githubusercontent.com/16521157/84345574-2cff6c80-abc7-11ea-9ba8-bdde348c44b1.png)

**Comment by arsh09** [comment]
any suggestions on this?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
