### ISSUE TITLE
Scatter plot multiple traces on hover issue in zoomed in view

### ISSUE THREAD

**Issue by ps-1993** [plotly/plotly.js#4894]
In scatter plot for multiple traces while in zoomed view if we hover over any trace it displays hover info of all the traces. It should display the hover info of traces that are available in the zoomed in view

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
