### ISSUE TITLE
overlapping tick labels

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#4899]
`I` have a plot which uses custom labels using `yaxis.ticktext`.

```
yaxis: {
type: "category",
categoryarray: sortedLabelsArray.map((v, i) => i),
categoryorder: "array",
tickmode: "array",
ticktext: sortedLabelsArray,
tickvals: sortedLabelsArray.map((v, i) => i)
}
```

 I dont know if this should be considered a bug or a feature request, but if there are too many values on an axis they tick labels overlap and are unreadable. When labels are auto-generated based on values it skips some labels in order to be readable.

Can there be an option `ticktextpretty: BOOL` to auto-hide labels some labels in between for readability when using 'ticktext' ? 

![Screen Shot 2020-06-04 at 2 50 02 PM](https://user-images.githubusercontent.com/6043499/83809438-a9e49080-a673-11ea-8ca6-a431078d2450.jpg)

**Comment by Alexander-Krause-Glau** [comment]
Did you find any solution to this?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
