### ISSUE TITLE
Can't add a secondary y axis on Plotly with one trace line only

### ISSUE THREAD

**Issue by midapsh** [plotly/plotly.js#4907]
### Issue
I've tried to add a y axis on both sides of the graph using Plotly JS with React JS but it seems that Plotly JS doesn't have the option.

I've tried ```layout.yaxis.mirror ( true | "ticks" | false | "all" | "allticks" )``` and ```layout.yaxis.side  ( "top" | "bottom" | "left" | "right" )``` but it doesn't really work. Maybe Plotly should have a ```layout.yaxis.side "both"```.

### This is what I want:

https://www.andypope.info/tips/tip005c.gif

### This is my ReactJS setup:

https://codesandbox.io/s/beautiful-swartz-3ubxx?file=/src/App.js

Thank you in advance!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
