### ISSUE TITLE
Dynamic changing of colorscale for Surface 3d with restyle function does not work

### ISSUE THREAD

**Issue by Rezakarimi66** [plotly/plotly.js#4916]
Please take a look at this [code](https://jsfiddle.net/reza_karimi76/og96pzLt/17/)
```
// The Folowing two lines works
this.chart.data[0].colorscale = colorScale;
Plotly.react( 'myDiv', this.chart.data );

// This following line does not!
Plotly.restyle( 'myDiv', { colorscale: colorScale } );
```
As you can see restyle function does not do the job and we have to use react function for changing it

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
