### ISSUE TITLE
scattergl + lines bug

### ISSUE THREAD

**Issue by vicn1222** [plotly/plotly.js#4919]
When I use scattergl with lines, none of the mobile browsers show the curve. Desktop works fine. Please use the following code to test on iPhone browsers (chrome, safari, edge, firefox, etc). Using scatter works fine. It used to work, so it must be some recent changes causing the bugs.

<pre>&lt;head&gt;
&lt;script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'&gt;&lt;/script&gt;
&lt;script type='text/javascript' src='https://cdn.plot.ly/plotly-latest.min.js'&gt;&lt;/script&gt;

&lt;script&gt;

$( function() {

  TESTER = document.getElementById('myDiv');
  Plotly.newPlot( TESTER,
    [ {
        x: [1, 2, 3, 4, 5],
        y: [1, 2, 4, 8, 16],
        mode: 'lines',
        type: 'scattergl',
      },
    ],
    { margin: { t: 0 } }
  );

} );

&lt;/script&gt;

&lt;/head&gt;

&lt;body&gt;
        &lt;div id='myDiv'&gt;&lt;!-- Plotly chart will be drawn inside this DIV --&gt;&lt;/div&gt;
&lt;/body&gt;

</pre>

**Comment by archmoj** [comment]
@vicn1222 thanks for the report. 
Latest and previous plotly.js versions work on iPhone7 as well as iPad7.
But it appears there is a problem with newer devices.
If you are sure it used to work on those devices, then could you please investigate which version of plotly.js that caused this problem?

For example by loading different versions: 
```
<script type='text/javascript' src='https://cdn.plot.ly/plotly-1.50.0.min.js'></script>
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
