### ISSUE TITLE
Plotly slow when using bars

### ISSUE THREAD

**Issue by rullymartanto** [plotly/plotly.js#4922]
We are working with datasets with 12 000.
When using bars the entire application gets slow, even zooming out and in is slow, snapshot (toImage) method is very slow and does not render correctly
and sometimes chrome crashes

**Comment by arsh09** [comment]
I faced a similar issue recently, instead of using bars, I used 'scattergl' type and I added '0' between two data points to make them look like bars. It a cheap workaround.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
