### ISSUE TITLE
Multiple realtime data sources with getData()

### ISSUE THREAD

**Issue by compusolve-rsa** [plotly/plotly.js#4923]
Hi Guys

Thanks for the hardwork. I need to access multiple realtime datasources from the document object using javascript.

I can access one data source such as this.
```
function getData() {
				
					//return Math.random();
					return window.myVar;
				
				
				}
```
Works well, but I am struggling to add more traces with getData(). I need something like this;
```
function getData() {
				
					//return Math.random();
					return window.myVar1, window.myVar2, window.myVar3;
				
				
				}
```
Also tried adding a trace like this;
```
var trace2 = {
				  
				  y: [function(getData) { return window.myVar2;}],
				  mode: 'lines'
				};
				
				Plotly.addTraces('chart', trace2);

```
Any help most welcome.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
