### ISSUE TITLE
Integrating discrete-heatmap2d

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4924]
@ordiology has [patched `gl-heatmap2d`](https://github.com/gl-vis/gl-heatmap2d/compare/master...ordiology:discrete-heatmap2d) to implementing discretization, which could be used to resolve https://github.com/plotly/plotly.js/issues/2924 by implementing `zsmooth` on `heatmapgl` (i.e. enabling it to be set to `false`)... Let's help them prepare a PR to get this functionality exposed in Plotly.js.

**Comment by archmoj** [comment]
Thaks @ordiology. Would you mind opening a PR from your fork to this [dev-branch](https://github.com/gl-vis/gl-heatmap2d/tree/init-zsmooth)?

**Comment by archmoj** [comment]
Right now there are conflicts between @ordiology 's `gl-heatmap2d` and `gl-vis` repo. Those should be resolved before merging to master. So I thought one could attempt fixing them on a dev branch by adding commits on top, instead of touching @ordiology's original commits. Once this step is completed we canl publish new `gl-heatmap2d` and could use that to provide `zsmooth` options in the `plotly.js` API.

**Comment by ordiology** [comment]
Thank you @archmoj ,

I have resolved the conflict (it was the package-lock.json). However, I'm not sure you want to just pull in my branch at this point. The version of the heatmap-gl that I have made is to link with our scientists' platform. I chose to make as minimal changes to the plotly source code as possible to get a discretised heatmap to work for our scientists. I considered renaming my version of the gl-heatmap2d code and creating a new npm package that could be sourced using a separate trace tree in plotly, but I wasn't sure this would be a productive way to implement the option. So, instead, I kept the linking to the gl-heatmap2d through plotly.js exactly the same and changed the manner in which the gl-heatmap2d code operated on the data and simply linked to a local version of my edited gl-heatmap2d rather than the default npm package. This wouldn't work for proper implementation purposes as a zsmooth switch is required to choose between each implementation. 

If there's a better way to communicate rather than in github messages, I can send you more information about how I approached the issue and further discuss what would be the simplest way to effect integration of my solution. I'm happy to help any way that I can.

**Comment by archmoj** [comment]
@ordiology thanks for the quick fixup.
I don't think we need a separate package. Instead we need to expand `gl-heatmap2d` to handle both cases (i.e. by passing different options). I am working on other items for a patch release this week. But let's investigate the minimal changes to make that possible.
