### ISSUE TITLE
add id attribution to path of shapes

### ISSUE THREAD

**Issue by orangeSi** [plotly/plotly.js#4931]
hello everyone, my example code is https://codepen.io/orangesi/pen/abdpBaW, and the code generate html code:

```
<path data-index="0" fill-rule="evenodd" d="M81 119 L119 119 L119 101 L81 101 Z" clip-path="url('#clip157432xy')" style="opacity: 1; stroke: rgb(0, 0, 0); stroke-opacity: 1; fill: red; fill-opacity: 1; stroke-width: 2px;"></path>
```
I want to add id attribution to ```<path>```, like this:
```
<path id="mypath" data-index="0" fill-rule="evenodd" d="M81 119 L119 119 L119 101 L81 101 Z" clip-path="url('#clip157432xy')" style="opacity: 1; stroke: rgb(0, 0, 0); stroke-opacity: 1; fill: red; fill-opacity: 1; stroke-width: 2px;"></path>
```
How can I modify the plotlyjs code for this ?

I know the ```data-index``` can be treated as the identifier of ```<path>```, but ``` id ``` attr maybe more directly to access the ```<path>```.

Thanks~
Regard
Si

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
