### ISSUE TITLE
Plotly.validate issue with coloraxis attribute

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4940]
The figure is valid in [this demo](https://codepen.io/MojtabaSamimi/pen/NWxjGBP?editors=0011).
But see the message in the console showing that `Plotly.validate` is unable to handle the case of `coloraxis`.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
