### ISSUE TITLE
Error values don't appear on hover when using scattergl

### ISSUE THREAD

**Issue by levindoneto** [plotly/plotly.js#4954]
If you have a plot with an `error_y`, the _+- values_ only show up for the type **scatter**, not with **scattergl**

With **scatter**:
![image](https://user-images.githubusercontent.com/12832687/85635214-b72de300-b653-11ea-8133-faf5968aff1c.png)

With **scattergl**:
![image](https://user-images.githubusercontent.com/12832687/85635066-5ef6e100-b653-11ea-9c8d-8788b1a3ed11.png)

**Comment by archmoj** [comment]
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/jOWwezx?editors=0010) to illustrate the diff.
@alexcjohnson I am not sure if this a bug or a feature?

**Comment by levindoneto** [comment]
Any news on this one, @archmoj @alexcjohnson ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
