### ISSUE TITLE
plotly-basic.js?d8ae:43786 Uncaught TypeError: Cannot read property 'slice' of undefined     at axRangeSupplyDefaultsByPass (plotly-basic.js?d8ae:43786)

### ISSUE THREAD

**Issue by jwang01** [plotly/plotly.js#4957]
axOut.range = axIn.range.slice(); crashes when click autoscale button when two plots are present.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
