### ISSUE TITLE
Draw region (polygon) on heatmap using a mouse by clicks

### ISSUE THREAD

**Issue by leonardoparada** [plotly/plotly.js#4965]
Could be possible add this funcition (see image atached)
![image](https://user-images.githubusercontent.com/38698615/85965795-da2a0100-b98b-11ea-8875-753552b1e923.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
