### ISSUE TITLE
Using `restyle` method in `updatemenus` button removes the modebar

### ISSUE THREAD

**Issue by HunterMcGushion** [plotly/plotly.js#4974]
This is very similar to #3824, and this bug was first reported in [this comment](https://github.com/plotly/plotly.js/issues/3824#issuecomment-643620847) by @sermeor, but I thought it made sense to open a new issue.

The issue can be reproduced on the Plotly website in [the "Restyle Button Single Attribute" example](https://plotly.com/javascript/custom-buttons/#restyle-button-single-attribute).

On initial load, hovering over the plot brings up the modebar.
![Screen Shot 2020-06-30 at 2 12 29 PM](https://user-images.githubusercontent.com/11300915/86177740-fe94f300-badb-11ea-81d3-eff653508842.png)

However, after clicking the "Heatmap" button, the modebar no longer appears.
![Screen Shot 2020-06-30 at 2 13 19 PM](https://user-images.githubusercontent.com/11300915/86177867-2dab6480-badc-11ea-868f-dadc8ca39b4b.png)

The same thing happens when changing the trace type in other examples on this page. 
This issue can also be reproduced in [this Plotly Python example](https://plotly.com/python/dropdowns/#update-one-data-attribute). Please let me know if I should open a separate issue on [plotly.py](https://github.com/plotly/plotly.py).

Thank you for your time and for making Plotly so awesome!

**Comment by archmoj** [comment]
@HunterMcGushion thanks for the report.

**Comment by Yook74** [comment]
The modebar is removed when switching from any type of 3D plot to any kind of 2D plot, but not vice-versa.

I have not tested every possible combination of 3D and 2D plot types, but I have (programmatically) checked all combinations of 
`bar`, `scatter`, `heatmap`, `scatter3d`, `surface`, and `mesh3d`. The modebar is removed only when switching from a 2D type to a 3D type. 

When I say that the modebar is "removed," I mean that its contents are no longer present in the DOM. The `modebar-container` div is there, but it has no contents. I've looked into the relevant code a little and it looks like when switching between 2D and 3D,  `makePlotFramework` is called. This clears the `modebar-container` div. When going from 2D to 3D, the div is then filled in again, but for some reason it is not populated when switching from 3D to 2D. 

The modebar will remain missing as long as one calls `react`, `restyle` etc. The modebar will show up again when `newPlot` is called or until the config parameter  `displayModeBar` is set to `false` and then `true` again.

@ArtOshchepkov the last paragraph details the only workaround I know of. Just call `newPlot` instead of `restyle`. This does not work for me though, since I'm using Dash and do not have direct control over the Plotly API calls, so a fix would be appreciated!
