### ISSUE TITLE
Empty space between first data point and y-axis

### ISSUE THREAD

**Issue by ceds** [plotly/plotly.js#4976]
I'm busy migrating my web app over to Plotly.  However, I'm having big issues with unproffesional looking graphs.  Specifically big spaces between the first data point and y-axis.  See below for reproducible example as well as pictures.  I've also included how it's supposed to look from a different library.

Any idea how to get past this?

https://codepen.io/ceds/pen/YzwEEQw

**Plotly**
![Plotly 1](https://user-images.githubusercontent.com/10418250/86218467-1c686380-bb81-11ea-8508-6584a24980cb.PNG)
![plotly 2](https://user-images.githubusercontent.com/10418250/86218473-1e322700-bb81-11ea-9e97-ebb9c0f4c7ca.PNG)

**Ideal**
![Other library](https://user-images.githubusercontent.com/10418250/86218477-1e322700-bb81-11ea-8138-fa5cd1b74a63.PNG)

**Comment by alexcjohnson** [comment]
These gaps correspond to 5% of the total plot width. That's currently built into our autorange algorithm and invoked whenever there are scatter markers as well as a few other situations, and at the moment it's not configurable. This is one of the items we're discussing in #1876, which has been around a long time but hasn't made it to the top of the pile yet. We'd gladly accept a PR or [sponsorship](https://plotly.com/consulting-and-oem/) to add the pieces you need.

For now you can set the axis range manually to match the data range, and set [`cliponaxis: false`](https://plotly.com/javascript/reference/#scatter-cliponaxis) in your trace to get the effect where the markers overlap the tick labels.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
