### ISSUE TITLE
Conditional axes date formatting 

### ISSUE THREAD

**Issue by arsh09** [plotly/plotly.js#4983]
Thank you for this amazing library. It works really well. 

I do have a question/feature-request.

Is there a way to format the date on x axis such that I can show date time after a certain date time and before that, the text on xaxis ticks is something else (maybe "-"). This is required as I am plotting a sensor data which needs to start at 00:00:00 ( HH:MM:SS ) and move forward and there shouldnt be anything on negative xaxis ticks when the user zoom out or pan. 

I looked at d3 date formatting but it did not work. 

I think it is important to mention that I am using zoom and pan (on x axis only). 

https://codesandbox.io/s/fervent-zhukovsky-en0uc?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue

If you zoom out on graph, you see the extrapolated date time on xaxis on both sides (positive and negative). Is there a way to turn this off? 

Thank you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
