### ISSUE TITLE
GeoJSON winding causing confusion

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4984]
We're getting lots of questions in Python-land about choropleth maps looking totally broken, because the GeoJSON is wound the wrong way e.g. https://github.com/plotly/plotly.py/issues/2354#issuecomment-638742767 ... can we not auto-detect this and fix it internally?

**Comment by mbkupfer** [comment]
I have experienced and fixed a couple of issues in the world of creating custom GeoJSON maps. If you all are interested, I'm happy to provide some buggy use cases and how they were fixed.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
