### ISSUE TITLE
Plotly.react transition bug: incorrect annotation position

### ISSUE THREAD

**Issue by aatishb** [plotly/plotly.js#4990]
https://codepen.io/aatish/pen/ExPoWLK

The expected behavior when I press update is that the annotation should jump to another point on the line, and when I press restart the annotation should go back to the original point. Instead I find that the annotation jumps off the line and doesn't return. And when I hover over the annotation, it shows me a location on the line, even though the annotated point is not on the line.

I don't think that this issue has to do with mutating the layout object, because if I deep copy layout, the bug remains.

See also: #4886, #4839

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
