### ISSUE TITLE
dtickstops

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4995]
Right now, `tickformatstops` allows you to specify the format of a ticklabel depending on the number of milliseconds between ticks i.e. `dtickrange`. 

I think we need another level of control (tentatively called `dtickstops`?), which would allow us to specify `dtick` as a function of `range` (so this would run before `tickformatstops`).

**Comment by ltuijnder** [comment]
Indeed I would also like to have such a feature.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
