### ISSUE TITLE
idea: when a trace is turned on/off (by double-clicking in legend), grey out the axis too.

### ISSUE THREAD

**Issue by RichardNeill** [plotly/plotly.js#4996]
Consider a case where there are multiple series and multiple y-axes.
Here, it's possible to turn on/off a group of traces by clicking/double-clicking in the legend.
My suggestion is that this should grey-out the corresponding y-axis too, and its labels + text.

For the axis to grey out, all the series plotted on the axis would have to be disabled.
As a heuristic, this should probably only happen if there are > 1 y-axes.

[The chart I'm looking at has 4 axes, and 4 series, each with threshold lines... so it would really improve clarity to have the surplus y-axes suppressed when only one series is visible]

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
