### ISSUE TITLE
Custom tick labels drawn on wrong axis in subplot

### ISSUE THREAD

**Issue by cest-m** [plotly/plotly.js#4998]
When using a second set of x and y axis in a subplot, custom tick labels are drawn on the wrong axis. 
This only occurs when: 
- Subplots are on two rows (works for columns)
- Custom tick labels using `tickvals` and `ticktext`
- The labels should be drawn on x axis (works for y axis)

Reproducible example: https://codepen.io/cest-m/pen/OJMEbwZ
Version used: latest un-minified

![wrongAxisLabel](https://user-images.githubusercontent.com/68110658/87276163-0e4f0700-c4e0-11ea-87a0-0696b7233b36.png)

**Comment by alexcjohnson** [comment]
You just need to tell us to draw `xaxis3` at the end of `yaxis3` (or of `yaxis2`, since the two are overlaying) with `xaxis3.anchor="y3"` https://codepen.io/alexcjohnson/pen/wvMxEaV

We could potentially have deduced that you want `xaxis3` to be drawn on the lower subplot since x3/y3 is the only one you added a trace to, but because of the possibility that a single axis is shared by multiple subplots, and use cases involving adding and removing traces, I think this would have unintended consequences and may not be possible to do robustly.

**Comment by cest-m** [comment]
Thank you very much for the help and clarification.
