### ISSUE TITLE
Dissimilar histogram bins when they should default to all the same

### ISSUE THREAD

**Issue by fparga** [plotly/plotly.js#50]
Histogram charts display some text on hover even when the bins are empty.
This only seems to happen in "Compare data on hover" mode.

JSBin: https://jsbin.com/pamafun/2/edit?js,output

example:
![hover on empty bins 1](https://cloud.githubusercontent.com/assets/2896648/11484339/8133863e-977b-11e5-907e-988feb59f15e.png)
![hover on empty bins 2](https://cloud.githubusercontent.com/assets/2896648/11484369/b19fa564-977b-11e5-9180-c68b15eed938.png)

**Comment by ni-hil** [comment]
Okay I got this wrong, in fact labels does not show because each trace has its own bins. Stacking happens then almost by chance when some bins happens to be the same for several traces.
When only certain types of labels are displayed for a value it means that this bin only exists for this trace.

So it's definitely a bad name for this issue.

Is there a way to have a stacked histogram, with several traces binned in the same way. Where binning wouldn't be set manually but determined by an algorithm using the aggregation of all traces as input?

**Comment by alexcjohnson** [comment]
@ni-hil That's definitely a bug, and leads to a highly misleading chart. If you don't specify bins explicitly, grouped or stacked histograms need to all get the same bins.

**Comment by alexcjohnson** [comment]
@etpinard from https://github.com/plotly/plotly.js/issues/42#issuecomment-162563275:
> Calculating histogram autobins from all traces might break some plots that maneuver around that problem.

Wouldn't any plot maneuvering around this do so by setting manual bins (so altering autobin wouldn't affect them)? You're right that we need to be careful not to change the autobin results much if at all in cases where it gives a decent result... but that should be manageable. And given that the plot step matches bar widths *anyway*, I think it's safe to say it's *always* a bad choice when grouped or stacked histograms use different bins - I'd go so far as to say it mucks up the central metaphor of binning!
