### ISSUE TITLE
3d zoom not preserving with uirevision

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5004]
In this pen, try newPlot@0, then rotate and zoom, then try react@1 ... everything stays the same except the zoom level:

https://codepen.io/nicolaskruchten/pen/YzwdbvR?editors=0010

**Comment by archmoj** [comment]
It seems this only happens when using scroll zoom (using mouse wheel) and not by dragging using zoom modebar.

**Comment by nicolaskruchten** [comment]
hard to tell if this has the same cause as #5012 ... the last known state is not saved, and when scroll-zooming (with a mouse that has notches for discrete zoom increments!) this is just more obvious?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
