### ISSUE TITLE
3d scene disappears if dragging while modebar button event hasn't returned

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5013]
With this codepen: https://codepen.io/MojtabaSamimi/pen/RwrvJQY clicking on the Pan modebar icon takes a long time to return (which is problematic but not the subject of this issue)... if you click and drag on the figure even a tiny bit after clicking on the Pan button but before it returns i.e. while the Pan tooltip is still visible, then after the click event returns, the figure is cleared (presumably the camera is pointing in some insane direction)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
