### ISSUE TITLE
[BUG] Double Click event not working on 3D Surface Plots

### ISSUE THREAD

**Issue by angieto** [plotly/plotly.js#5019]
Hi,

I want to add a double click event listener to a 3D surface plots graph. The doubleclick event is never triggered. I've tried other event listeners like "hover" and "click" they worked just fine.

Below is my sample code
![image](https://user-images.githubusercontent.com/42507452/88340032-e6d21880-ccef-11ea-810d-bf9883e164f2.png)

Browser: Chrome
File Type: HTML

Graph
![image](https://user-images.githubusercontent.com/42507452/88340167-2e58a480-ccf0-11ea-94f1-7bc2124d41de.png)

**Comment by alexcjohnson** [comment]
Thanks @angieto - transferred to the plotly.js repo, I suspect we just didn't implement the doubleclick in 3D because it doesn't already do anything (unlike 2D where doubleclicking resets the axis ranges). But you're right that it would be nicer if we had that. In the meantime you can have your `plotly_click` handler listen for multiple events within a short time period and treat these as a doubleclick.

**Comment by angieto** [comment]
That's what I figured. Having a double click event would be nice!
