### ISSUE TITLE
Mapbox multi-selection bug

### ISSUE THREAD

**Issue by RenaudLN** [plotly/plotly.js#5020]
Hi,

I am using the selection functionalities for mapbox graph which works fine for most cases.

My issue arises with multi-selection (e.g. multi box or lasso select) if I try to zoom or pan the map between two selections.

When I pan the map between two selections, it moves the previous selection boxes:
![multiselect+pan](https://user-images.githubusercontent.com/20662281/88366000-2e79a280-cdcb-11ea-8339-ff9a459f41b2.gif)

When I zoom the map (in or out) and try to add a selection, the previously selected points are lost.

Very simple reproducible example (using the python API but I'm pretty sure the underlying issue is in plotly.js):

```python
import numpy as np
import plotly.express as px

x, y = np.meshgrid(np.arange(100), np.arange(20))
x = x.flatten()
y = y.flatten()
px.scatter_mapbox(lat=y, lon=x, mapbox_style="carto-darkmatter").update_layout(margin=dict(t=0,b=0,l=0,r=0))
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
