### ISSUE TITLE
categoryorder and matches

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5038]
In this pen, which of the two newPlots is correct? https://codepen.io/nicolaskruchten/pen/NWNKvdZ?editors=0010

in both, `categoryorder` is [q,r,s,t] and neither has data for all of those x values. In the first, "t" doesn't appear, in the second both "s" and "t" appear.

**Comment by alexcjohnson** [comment]
"t" doesn't appear in the first one only because it's excluded by autorange. If you zoom out or pan right on the x axes you'll see it's there. If your data had no "q" in it, that would be excluded as well, by the same logic.

I doubt that was a conscious decision, and I think your implication that when `categoryorder='array'` all categories in `categoryarray` should appear regardless of what's in the axis data is probably the right answer - in which case we can simply consider this a bug and include `categoryarray` in the autorange calculation.

**Comment by nicolaskruchten** [comment]
hmmm, ok. This explanation is actually totally coherent to me, and in fact this Pen doesn't actually get at the issue I'm chasing down in any case :) Thanks!
