### ISSUE TITLE
Unclear Documentation For Setting ColorScales

### ISSUE THREAD

**Issue by FA5I** [plotly/plotly.js#5040]
Hi,

I am using the library and came across the following scenario:

I have multiple heatmaps. I want each heatmap to have the same colorscale range, so that they are comparable.

Now I read through the figure reference here:

[https://plotly.com/javascript/reference/#scatter](https://plotly.com/javascript/reference/#scatter)

However it is not clear at all how the colorscale range can be set. My attempt after reading the docs was as follows. As you can see, even though I set cmin and cmax, the actual range for the colorscale does not change.

```
var data = [
  {
    colorbar: {
      title: 'Speed(RPM)<br\><br\>',
      titleside:'top',
      titlefont: {color: 'blue'},
      cmin: 0,
      cmax: 100
    },
    z: [[1, 20, 30], [20, 1, 60], [30, 60, 1]],
    type: 'heatmap'
  },
];

Plotly.newPlot('myDiv', data);
```

Codepen: [https://codepen.io/fkE3/pen/eYZOoPg?editors=0010](https://codepen.io/fkE3/pen/eYZOoPg?editors=0010)

Can someone please explain what is going wrong as I seem to be following the docs to the best of my understanding?

**Comment by bmaranville** [comment]
It looks like setting zmin and zmax achieves your goal, though I can't say why (not in the colorbar section though - in the root of the data section, i.e. at the same level as z).
```
var data = [
  {
    colorbar: {
      title: 'Speed(RPM)<br\><br\>',
      titleside:'top',
      titlefont: {color: 'blue'}
    },
    z: [[1, 20, 30], [20, 1, 60], [30, 60, 1]],
    zmin: 0,
    zmax: 100,
    type: 'heatmap'
  },
];

Plotly.newPlot('myDiv', data);
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
