### ISSUE TITLE
displayModeBar does not recognize false in quotes as a valid value 

### ISSUE THREAD

**Issue by sean-mcleish** [plotly/plotly.js#5049]
Hi,

we have the following issue (LayTec-AG/Plotly.Blazor#34) while using JavaScript-Interop in Plotly.Blazor.

"True" is recognized as a valid value in quotation marks, "False" is not.

Works:
`Plotly.newPlot('myDiv', data, layout, {displayModeBar: "hover"})` --> in quotes
`Plotly.newPlot('myDiv', data, layout, {displayModeBar: "true"})` --> in quotes
`Plotly.newPlot('myDiv', data, layout, {displayModeBar: true})` --> not in quotes
`Plotly.newPlot('myDiv', data, layout, {displayModeBar: false})` --> not in quotes

Does not work:
`Plotly.newPlot('myDiv', data, layout, {displayModeBar: "false"})`  --> in quotes

You can try it [here](https://codepen.io/seanmcl/pen/eYZYVNv).

Would that be easy for you to fix? Otherwise I would have to think of a converter that can serialize enums as booleans, which would be a nasty fix.

Have a nice week!

With kind regards

Sean

**Comment by nicolaskruchten** [comment]
Hello!

So `"true"` is truthy in Javascript because it's a non-empty string, as is `"false"`: we don't have special handling for the string `"true"` basically :) We could maybe add special handling for the string `"false"` but for consistency we'd probably want to add that in everywhere we accept a boolean-or-a-string, not just in `config.displayModeBar`. I don't think we can prioritize this work right now, but we would probably accept a pull-request for it!

Cheers,
Nicolas

**Comment by sean-mcleish** [comment]
Hi Nicolas,

plotly.js does not have to be modified because of such a request. Just thought it might be unwanted behavior. I have managed to get around the problem relatively easily.

Best regards and thanks for the quick answer! 

Sean
