### ISSUE TITLE
Unexpected lines in chart scatter3d

### ISSUE THREAD

**Issue by danyduran** [plotly/plotly.js#5056]
![image](https://user-images.githubusercontent.com/28666420/89695757-b935c380-d8da-11ea-94cd-ffc178e776ed.png)

When I plot a scatter3d chart, show an unexpected , strange rect lines, this lines are not in the data used for the plot.

**Comment by nicolaskruchten** [comment]
Could you share the code that generates this plot so we can better help you? Please note that Plotly draws lines in between points in the order given in the figure, without sorting along any dimension, so it could be that sorting your data would resolve this :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
