### ISSUE TITLE
Automargins + tickformat=",d" bug

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5059]
In this codepen https://codepen.io/nicolaskruchten/pen/PoNqVeL either setting yaxis.automargin=false or tickformat="" fixes the overly-large left margin but using both together is problematic. The problem is much worse with more than one subplot i.e. https://github.com/plotly/plotly.py/issues/2697

**Comment by nicolaskruchten** [comment]
per @alexcjohnson this seems related to the fact that the .5 ticklabels are gone... should we just repeat them like with dates?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
