### ISSUE TITLE
formatting of `base` in hovertemplates differs from `x`

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5066]
In this pen: https://codepen.io/nicolaskruchten/pen/oNxjEMp?editors=0010 you can see that in the hoverlabel, the date formatting for `base` differs from that of `x` leading to start and stop being formatted differently. Ideally `base` would be formatted using the axis' `tickformat` just like `x`

**Comment by chrysillala** [comment]
Hi, I would like to work on this issue. Could you please assign and guide me? Thanks!

**Comment by nicolaskruchten** [comment]
Hi @chrysillala, that would be great!

@antoinerg are there any quick pointers to where the hovertemplate stuff lives?

**Comment by antoinerg** [comment]
> @antoinerg are there any quick pointers to where the hovertemplate stuff lives?

Basically, when `hovertemplate` contains a variable without any formatting, the hover module (in `src/components/fx/hover.js`) will look for a default formatting. For variable `x`, it will look for a formatted value in a key named `xLabel`. Therefore, the fix for the current issue is to simply add a key named `baseLabel` with the appropriately formatted value for `base`. This should be done in the `bar` trace's hover routine.

Because it's a simple one-liner, I proceeded to make the change myself in https://github.com/plotly/plotly.js/pull/5216. Thanks, @chrysillala for offering your help :)

**Comment by chrysillala** [comment]
@antoinerg thanks for the update!
