### ISSUE TITLE
Rangeslider value access inconsistency

### ISSUE THREAD

**Issue by Jack-alope** [plotly/plotly.js#5067]
Hello, 

I've found that when using the rangeslider if you select a region on the graph itself you access the rangeslider values by``eventdata["xaxis.range[0]"]``while if you move the rangeslider itself the xvalues are accessed via``eventdata["xaxis.range"][0]``. The first case is with the strings "xaxis.range[0]" for x1 and "xaxis.range[1]" for x2 while the second is a array location [0] for x1 and location [1] for x2.

I believe this is a bug and they should be consistent as they both modify the range in the same way. I have attached an example in codepen here to better demonstrate. https://codepen.io/jack-alope/pen/MWyaVgj

Case 1 is defined in lines 23, 24 of https://github.com/plotly/plotly.js/blob/master/src/components/rangeselector/get_update_object.js while I believe case 2 is defined in https://github.com/plotly/plotly.js/blob/master/src/components/rangeslider/oppaxis_attributes.js lines 32 onwards. 

Thank you for taking a look

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
