### ISSUE TITLE
investigate upgrade karma-jasmine to v4

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5070]
`karma-jasmine` v4 is out which supports `node v14`. 
We need to investigate why few tests are failing https://circleci.com/workflow-run/802a89bf-ee66-462d-b1d1-507c8d5e82d0 at the moment.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
