### ISSUE TITLE
Allow inverting longitude in scattergeo

### ISSUE THREAD

**Issue by mkounkel** [plotly/plotly.js#5082]
Scattergeo is great for allowing to plot things on a sphere, even if it isn't necessarily the earth map.

The way it is set up, the longitude goes 0 to 360 degrees, increasing from left to right. Maps of the sky though, have the coordinate system set up from right to left, i.e., backwards to the map of the earth.

In principle, all one needs to do is to set up longitude as 360-l instead of l, which works fine visually, but completely messes up the hover coordinates, so it'd be nice to be able to specify the direction of plotting natively.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
