### ISSUE TITLE
How to improve plotly performance

### ISSUE THREAD

**Issue by liuzuweigogo** [plotly/plotly.js#5090]
In my project, I use extendTraces to draw a heat map. As the amount of data increases, the drawing speed becomes slower.

**Comment by liuzuweigogo** [comment]
I can also turn off which features to improve the overall performance？

**Comment by SetarehSalehee** [comment]
We have a similar issue as well, we used Angular-Plotly to draw a Gantt diagram which includes a lot of shapes being drawn on the plot. After adding for example 100 tasks the plot becomes unusable. We cannot drag the plot up and down or back and forward. I tried everything I found on the performance improvement. It is better but not enough.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
