### ISSUE TITLE
There are three heatmapgl in the submap, but only one is shown

### ISSUE THREAD

**Issue by liuzuweigogo** [plotly/plotly.js#5092]
1. There are three heatmapgl in the subplots, but only one is shown
2. Heatmapgl and scattergl cannot coexist in the subplots, heatmap can, but I need to use heatmapgl

**TypeError: Cannot read property 'select' of undefined**

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
