### ISSUE TITLE
X Axis Labels Disappear When Zooming In and Out

### ISSUE THREAD

**Issue by jasonncleveland** [plotly/plotly.js#5107]
I am using plotly.js to represent monthly data. I am using a scatter plot with multiple traces. I'm currently using the latest version (1.54.7). I went through the version history and found it broke as of version 1.54.6.

Below is an example of the structure of the data I'm using:

## Data

| Month | Data 1 | Data 2 |
| ------- | ------- | -------- |
| Jan-2021 | 33229.4717 | 162199.8730 |
| Feb-2021 | 41821.7795 | 204140.6911 |
| Mar-2021 | 45757.4607 | 223351.5587 |
| Apr-2021 | 43718.5669 | 213399.2998 |
| May-2021 | 44608.2127 | 217741.8433 |
| Jun-2021 | 42625.3861 | 208063.2600 |
| Jul-2021 | 43668.4540 | 213154.6884 |
| Aug-2021 | 43562.1913 | 212635.9983 |
| Sep-2021 | 42119.6341 | 205594.5803 |
| Oct-2021 | 43524.9869 | 212454.3958 |
| Nov-2021 | 42146.7681 | 205727.0272 |
| Dec-2021 | 42115.7580 | 205575.6605 |

## Steps to Reproduce

1. Visit http://chart-studio.plotly.com/create
2. Enter the above data in columns A, B, and C
3. Create 2 new scatter traces `Structure -> Traces`
  a. First trace uses column A as the X and column B as the Y
  b. Second trace uses column A as the X and column C as the Y
4. Modify the trace styling `Style -> Traces`

- Modifying whether the display uses points and/or lines using the `individually` tab works fine
- Modifying whether the display uses points and/or lines using the `by type` tab and then zooming causes the x axis labels to disappear

`"data"` and `"layout"` can be found under `JSON -> Tree`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
