### ISSUE TITLE
Proposal: new exponentformat which uses "milli" prefix

### ISSUE THREAD

**Issue by ignamv** [plotly/plotly.js#5111]
Can someone please look over my pull request to see if it's suitable for the main repo?

https://github.com/ignamv/plotly.js/pull/1

**Comment by archmoj** [comment]
Looking good to me.

**Comment by nicolaskruchten** [comment]
I see in the constant array `SIPREFIX` that `k` and `m` are there already... it just seems like a bug to me that `exponentformat="SI"` doesn't use these.

**Comment by nicolaskruchten** [comment]
PS @ignamv thanks for the PR! I'm just wondering if we can't just fix this in `SI` instead of introducing a new mode :)

**Comment by alexcjohnson** [comment]
The existing SI mode is working as intended. Not using the `m` prefix - but using all the others - is pretty typical on log axes because the `m` is too often confusing (vs `M`) and doesn't shorten the labels much (`100m` is _longer_ than `0.1`). For `k` it's a little more subtle, we don't use it for `1k` but we do for `10k`. This I don't feel that strongly about, we could consider it a bug, but I do think there's a logic to the current behavior: the longest pure-power labels you have otherwise are `100k` and `100M` etc, which are exactly as many characters as `1000`, so we defer to readability and use unmodified numbers for just one more power of 10.

All that is to say I think the current behavior makes sense as a default for `SI`. But I can see wanting to change that and always use a prefix - or, for that matter, keeping the numbers unmodified longer (or using prefixes more extreme than `f` and `T`, beyond which we currently switch to `power` notation - because I didn't deem those prefixes sufficiently well known when this feature was originally written - but that probably would need to be a totally separate attribute).

So what if we make a new attribute to substitute in for the `3` here:

https://github.com/plotly/plotly.js/blob/2737bf26019e059f3da63c70545364bc3593474b/src/plots/cartesian/axes.js#L1045

something like `ax.minexponent`? For your use case @ignamv you'd set it to `0`, but someone who doesn't even want to use `k` or `µ` might set it to `6`, or something between even.

**Comment by ignamv** [comment]
> So what if we make a new attribute to substitute in for the 3 here

Sounds cleaner! I'll give it a go.

**Comment by ignamv** [comment]
I've added the new attribute and removed the `eng` `exponentformat`. I'm not familiar with this codebase so I based the new code on what I found for the `exponentformat` attribute.

**Comment by alexcjohnson** [comment]
@ignamv looks good! Feel free to make a PR to the main repo. It'll need a test or two before it's ready to merge, probably one setting `minexponent` to zero (the case you care most about) and another setting it large like in https://github.com/ignamv/plotly.js/pull/1#issuecomment-684779096

This is a good model to start with:

https://github.com/plotly/plotly.js/blob/c437cdf46b775df09d1157087f31d4d5d0a5276e/test/jasmine/tests/axes_test.js#L2811-L2833

**Comment by ignamv** [comment]
Thanks! I've added both tests and they seem to work.
