### ISSUE TITLE
Weird issue with heatmaps with sliders

### ISSUE THREAD

**Issue by Jorgeewa** [plotly/plotly.js#5115]
I have been using plotly for a while now and I must say it meets all our needs. However, we are having some issues especially with null data. Some sensors send data and sometimes they are problematic and send almost no data. We will like to display it this way.

However there are some inconsistent behaviours observed as shown in these two pens:
https://codepen.io/JorgeJavasScripter/pen/jgmoxa (expected behaviour when handling null data mixed with non null)

https://codepen.io/JorgeJavasScripter/pen/qBZXMMW (ugly behaviour when handling data similar to above)

In the second case, the dimensions of 150 by 16 are totally ignored even for days with data making the maps look ugly. Can you give me a heads up on what is going wrong please.

Ps I noticed if I start the data points from day 8 which has some data the plots look as I want.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
