### ISSUE TITLE
Histogram, barmode: overlay bug with groupby transform has a class with a single element in it

### ISSUE THREAD

**Issue by AZaitzeff** [plotly/plotly.js#5128]
When you use a group by transform with a class with a single element in it ("c" in the example below), A histogram with barmode: overlay has unexpected behavior (does not show correct graph).
HTML:
```
<head>
	<!-- Load plotly.js into the DOM -->
	<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
</head>

<body>
	<div id='myDiv'><!-- Plotly chart will be drawn inside this DIV --></div>
</body>

```
Javascript
```
var data = [{
    "x": [1,1,1,2,3,4,4,4,4,3,3,5,5],
    type: 'histogram',
  "transforms": [{"type": "groupby", "groups": ["a","a","a","b","b","b","b","a","a","a","a","c","a"]}],"opacity": 0.5
  }];
var layout = {"barmode": "overlay"};
Plotly.newPlot('myDiv', data, layout);
```
![Screen Shot 2020-09-04 at 12 19 40 PM](https://user-images.githubusercontent.com/2396638/92262755-95e64000-eea9-11ea-960b-2896404969fb.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
