### ISSUE TITLE
[Feature request] - Add segments on plotly graph

### ISSUE THREAD

**Issue by itaishalom** [plotly/plotly.js#5136]
Hi, I'm trying to figure out if it's possible to create segments and edit them after creation just like Peaks.js
http://audiovideo.jeffreyeverhart.com/audio-annotation/peaks.html

Like the image below:
![SIh8x](https://user-images.githubusercontent.com/9066121/92584744-b0029280-f29c-11ea-954c-a11a0ca3b349.png)

Also posted on StackOverflow

[https://stackoverflow.com/questions/63793475/add-segments-to-a-plotly-js-graph](url)

**Comment by andreygolubkow** [comment]
Hi! Can you use annotations for it ?

**Comment by itaishalom** [comment]
Do you have any working demo on jsfiddle?
Anyway i'll check annotation feature now.
Thanks

**Comment by itaishalom** [comment]
AFAIK creating shapes on graph is a feature that only available on python as it's not seen on the documentation page of Shapes javascript

**Comment by emmanuelle** [comment]
Hi @itaishalom the shape-drawing feature is also available in Javascript (the tutorial on Shapes needs to be updated in the JS doc)

**Comment by itaishalom** [comment]
Hi, yeah you right, I checked it (this is why I deleted the comment).
Now, working my way around it, it seems to be a basic feature which is not exists :(

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
