### ISSUE TITLE
[Feature request] Date format axis for Image trace

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#5141]
At the moment using the `dx` and `x0` (or `dy` and `y0`) parameters, it is not possible to change the format of the axis to date for an Image trace.

This could be useful in particular in Python for xarrays represented with an Image trace.

**Comment by antoinerg** [comment]
> At the moment using the `dx` and `x0` (or `dy` and `y0`) parameters, it is not possible to change the format of the axis to date for an Image trace.

@emmanuelle I tried to reproduce this shortcoming but it seems like it does work sometimes: for example, check out the mock in this [branch](https://github.com/plotly/plotly.js/compare/fix-5141).

Could you please send me a JSON of a figure with an image trace on a date axis that does not render properly at the moment so I can make the appropriate modifications?

**Comment by archmoj** [comment]
@emmanuelle wondering if this issue is resolved?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
