### ISSUE TITLE
BUG: Can't adjusting latex label size

### ISSUE THREAD

**Issue by Weugene** [plotly/plotly.js#5144]
Dear Plotly developers!

I am trying to change the size of latex label in plotly:
fig.update_layout(
                  xaxis_title=xlabel,
                  yaxis_title="$V_0 + \Omega$",
                  yaxis = dict(
                      titlefont = dict(
                          size = 50,
                      ),
                  )
                  )
Latex markdown is rendered very well, but the size of it not changable. But if I change latex code to the plain one, it works very well. It would be nice if you fixed this bug.

BR,
Evgenii

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
