### ISSUE TITLE
Allow text overlap on Mapbox

### ISSUE THREAD

**Issue by david-987** [plotly/plotly.js#5145]
I'd like to allow text to overlap in maps, similar to how we can now have overlapping markers with allowoverlap.
![image](https://user-images.githubusercontent.com/1450259/93018132-d5114100-f5cd-11ea-8808-2d251a51a38e.png)

In my use case, a critical requirement is to display all numbers even if they must overlap. The map is exported to a png.

Some things I've tried:
- Reducing text font size (works, but makes the numbers unreadable)
![image](https://user-images.githubusercontent.com/1450259/93018275-d131ee80-f5ce-11ea-8adb-a95fc9183046.png)
- Adjusting zoom. Helps sometimes, but not if the relevant area is large.

Are there any other tricks I could try to make sure all text is visible at all times?

**Comment by Charlesfox1** [comment]
+1 for this. Sad to see it has not got any attention.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
