### ISSUE TITLE
[FEATURE] Mapbox has implemented strokes on circle points

### ISSUE THREAD

**Issue by bandersen23** [plotly/plotly.js#5150]
In mapbox/mapbox-gl-js#3672, the Mapbox team implemented the following parameters:

- `circle-stroke-color`
- `circle-stroke-width`
- `circle-stroke-opacity`

I think exposing these would be greatly beneficial to Plotly users as users could then add a stroke to their points to make them stick out.

I'm working on adding these parameters, but I'm still figuring out everywhere they need to be added and what functions still need to be written. 

So far I've worked on adding them in the following files / places:
https://github.com/plotly/plotly.js/blob/94b31a8bbb8980ccafa23171d43732b386a88b20/src/plots/mapbox/layers.js#L197
https://github.com/plotly/plotly.js/blob/94b31a8bbb8980ccafa23171d43732b386a88b20/src/plots/mapbox/layout_attributes.js#L254

I believe I need to add something here, but am still figuring out what to add:
https://github.com/plotly/plotly.js/blob/94b31a8bbb8980ccafa23171d43732b386a88b20/src/traces/scattermapbox/convert.js#L161

I'd love any guidance you may have to adding these!

**Comment by millercommamatt** [comment]
I too would like to request support for stroke on mapbox circles.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by millercommamatt** [comment]
As best as I can tell from the documentation, stroke support for mapbox circles was never added.
