### ISSUE TITLE
Unable to disable Mapbox pan/tilt and other actions

### ISSUE THREAD

**Issue by JeremyGuinn** [plotly/plotly.js#5153]
Currently, it looks like only scrollZoom can be disabled in mapbox plots by setting the options to include `scrollZoom:false`.
It would be nice to be able to disable the other [handlers](https://docs.mapbox.com/mapbox-gl-js/api/handlers/) used by mapbox.

Returning the mapbox instance on the created plot would be useful in manipulating the internal mapbox. This would be an easier solution than having to add all the options.

https://jsbin.com/gazanayaqe/edit?html,js,output

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
