### ISSUE TITLE
Plotly.update(...) to select points on a graph

### ISSUE THREAD

**Issue by LoganWlv** [plotly/plotly.js#5162]
Hi, 

Use case : 

I have a two axis graph and I want to update it with some **selected points**.
To do that I am using `Plotly.update` function and the `selectedpoints` property to pass the indexes of the points that I want to select. 

Following the documentation :

![image](https://user-images.githubusercontent.com/22358070/94011943-68096280-fda8-11ea-8480-00f2da6face4.png)

It seems to expect a one dimensional array. 
But with a one dimensional array it is not working and with a two dimensional array it works. 

I did debug a bit the code and it seems that in the `_restyle` function (for instance in plotly_basic.js), we do some logic on the property value (to handle multi traces? )

```
for(i = 0; i < traces.length; i++) {
            cont = data[traces[i]];
            contFull = getFullTrace(traces[i]);
            var preGUI = fullLayout._tracePreGUI[contFull._fullInput.uid];
            param = makeNP(preGUI, guiEditFlag)(cont, ai);
            oldVal = param.get();

           //Here if my selectedpoints are '[1, 2, 3, 4, 5]', newVal will always be '[0]'
           // if selectedpoints are '[[1, 2, 3, 4, 5]]', newVal be identical
            newVal = Array.isArray(vi) ? vi[i % vi.length] : vi;
```

In my understanding `selectedpoints` should be defined as a 
_Two dimensional array containing integer indices of selected points for each trace._

Am I wrong?

**Not working example** 

https://codepen.io/loganwlv/pen/jOqXQjN

Working example : 

https://codepen.io/loganwlv/pen/ExKGObP

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
