### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by denissanga** [plotly/plotly.js#5167]
Hi all, I added a node_module in my project but when I try to import in a javascript code the plotly module the following error appears:

`ReferenceError: document is not defined`

Can someone help me to solve this error?

thank you very much
Best Regards

**Comment by archmoj** [comment]
Have you seen
https://stackoverflow.com/questions/32126003/node-js-document-is-not-defined
or
https://plotly.com/nodejs/getting-started/
?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
