### ISSUE TITLE
scattergl blank with 1.5M+ points

### ISSUE THREAD

**Issue by sleighsoft** [plotly/plotly.js#5178]
When creating a `scattergl` chart with 1.5M+ points, it will render transparent lines. On hover, data seems to be available.

No errors are logged to the console.

With 1M points it still works.

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
    <div id="chart1" style="width: 100%; height: 640px;"></div>

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        const el = document.getElementById('chart1');
        const xD = [];
        const yD = [];
        for (let x = 0; x < 5_000_000; x++) {
            xD.push(x);
            yD.push(Math.random());
        }
        Plotly.newPlot(el, [{ x: xD, y: yD, type: 'scattergl'}]);
    </script>
</body>

</html>
```

**Hardware**
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041
Processor	Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz, 1801 Mhz, 2 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	16,0 GB
GPU GeForce GT 750M

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
