### ISSUE TITLE
Transformation matrix attribute in heatmap trace

### ISSUE THREAD

**Issue by pfebrer** [plotly/plotly.js#5188]
Hi!

I was wondering that adding a transformation matrix attribute to `heatmaps` would be of great help. 

I want to display transformed images using `plotly.py` and at the moment all I can do is transform the image myself first and then pass it to `Heatmap`, as proposed in https://github.com/plotly/plotly.py/issues/2635#issuecomment-666408749. However, this has the drawback that the borders of the image don't look nice and the data displayed is really an interpolation, not the real data anymore.

I've been also playing with `contourcarpet`, which allows me to plot the skewed images very easily but only as contours, not heatmaps.

After checking the code of the heatmap trace, it seems trivial to add a line like `context.setTransform(...transmatrix)` to linearly transform all the bricks in the canvas (when `zsmooth` is not used). Handling hover events would maybe be more difficult but it is probably doable. There may be also other implications that I'm not aware of.

If you are interested but don't have the time for it, I'd be willing to create a pull request, although I would need some pointers to have a more clear view of what are the things to take into account, since this is the first time I actually play with `plotlyjs` code and it's a bit overwhelming :)

Cheers!

**Comment by archmoj** [comment]
@pfebrer96 thanks for the offer to submit a PR.
Do you think that using `css` transform could help in this regard?
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/gOMmBXL?editors=0100) that may be of interest.
If that is the case, one could attempt fix the hover positions when `rotation` is present https://github.com/plotly/plotly.js/pull/5193 is merged.

**Comment by pfebrer96** [comment]
Thanks for the answer! 

The `css` approach is interesting. Unfortunately, I believe it is quite complicated to achieve what I want, because:
- I want to apply the transform only to the heatmap, the axes still need to be in the horizontal and vertical directions. 
- If I target only `.heatmaplayer`, the rest of the plot needs to be resized accordingly. The axes labels need also to be recalculated according to the transform.
- By skewing `.hoverlayer`, the hover information can become unreadable.
- I'd like to do these plots in python, can custom css be passed to a single plot through json?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
