### ISSUE TITLE
Maximum value on axis less than largest data point

### ISSUE THREAD

**Issue by s1dsq** [plotly/plotly.js#5194]
![plotly-issue2-github](https://user-images.githubusercontent.com/29670086/95169198-20370200-07d0-11eb-9952-ec63b336451f.jpg)

`yaxis: {
            title: {
                y: "0.05",
                automargin: true,
                font: {
                    family: "Open Sans",
                    style: "normal",
                    weight: "normal",
                    size: "12px",
                    color: "rgba(0, 0, 0, 0.87)",
                },
                text: "INTENSITY",
                standoff: 40,
                width: "left",
            },
            range: [],
            tick0: 0,
            nticks: 10,
            autorange: true,
            rangemode: 'nonnegative',
            showgrid: true,
            showline: true,
            linewidth: 2
        }`

Attached above is the layout for the axis. The behavior can be changed by manipulating _nticks_ but because of dynamic changes in points, there is no way to know how many ticks should be set in advanced. Is there a workaround for this?

**Comment by mojoaxel** [comment]
To clarify: The problem is that the next higher `1.8n` tick is missing on the y-axes!?

**Comment by s1dsq** [comment]
@mojoaxel Yes, that is correct.

**Comment by alexcjohnson** [comment]
@s1dsq that's currently the expected behavior - notice for example that your x axis shows the same thing on both sides, data points beyond the extremal ticks. If we were to implement configurable padding on the autorange (see eg #1876) then you could change the current 5% padding to something like 20%, which would ensure there's always room for another tick.

(You're probably aware of this at least in general terms, but `nticks=10` in fact means "no more than 10" ticks. So based on the largest automatic step in `dtick`, a factor of 2.5 from 2x10^n to 5x10^n, there are occasional cases you may have as few as 4 ticks. Since you have `rangemode='nonnegative'` here though, there's always a tick right at the start so this worst case actually happens when the top of the range is just below 2.5x10^n, where the highest tick shown is 2x10^n, ie 20% below the top. Kind of interesting that it's not quite as bad as `2.5/nticks`, which would be 25%... Pretty sure `2.5/nticks` would work for any `nticks`, and it's possible that `2/nticks` is sufficient but that I'm less confident of.)

I suppose another route would be to add a boolean option "extend autorange to exactly the next tick" although I'm less enthusiastic about this idea, as it would make odd jumpy behavior as new points are added gradually extending the range.

A workaround in the meantime would be to add a phantom trace (transparent with no legend or hover info) duplicating ~15% larger either all the data or some subset that includes the largest point.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
