### ISSUE TITLE
Autorange does not seem to work in certain cases

### ISSUE THREAD

**Issue by s1dsq** [plotly/plotly.js#5197]
[Like this one](https://plotly.com/~siddharth.singh/1/)

The Y axis shows 0 despite setting autorange. Any help would be appreciated.

**Comment by archmoj** [comment]
It seems to work.
Here is a [codepen](https://codepen.io/MojtabaSamimi/pen/xxOqyde?editors=0010).

**Comment by alexcjohnson** [comment]
@archmoj I wouldn't call it a bug, but there may be room to improve the behavior here. The issue is that all the data values are identical, so we don't have a clear idea what range to give the data; so we just use that one value ±1. In this case that one value is very close to zero, so it looks like the range is just -1 to 1 with all the data at 0.

You can get something useful out of this data if you set `yaxis.rangemode = 'tozero'` - then the range you end up with is from 0 to that single value + 5%, which makes it clear that the value is a little below 1e-9. Ideally `yaxis.rangemode = 'nonnegative'` would do something similar, but it doesn't, it ends up giving 0 to 1. But I think even `yaxis.rangemode = 'normal'` (default) could do better by saying that when there's a single value between -1 and 1 (but not 0) the autorange goes from 0 to twice that value.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
