### ISSUE TITLE
plotly_click don't be triggered, in mobile, dragmode select

### ISSUE THREAD

**Issue by skout90** [plotly/plotly.js#5227]
Hello.

plotly_click don't be triggered, in mobile, dragmode select.
in dragmode default, plotly_click works well.
https://codepen.io/skout90/pen/jOrMeZR

Please check log, mobile emulator in chrome dev tools, and you must **REFRESH**

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
