### ISSUE TITLE
Treemap forced root node

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5242]
Semi-related to https://github.com/plotly/plotly.js/issues/5199 ... one difference between sunburst and treemap is that treemap always has a root node even if you don't want it. It would be nice for this to be optional.

**Comment by GeorgeFlorian** [comment]
Have there been any updates on this ?

I also don't need the root element in the treemap chart that I am using.
I have set `hovertemplate: '%{label}<br />%{value}% <extra></extra>'` and since the root doesn't have any labels or values I get warnings in the console 
```
console.trace() WARN: Variable 'label' in hovertemplate could not be found!
console.trace() WARN: Variable 'value' in hovertemplate could not be found!
console.trace() WARN: Too many hovertemplate warnings - additional warnings will be suppressed
```

Also when I hover over the root element it shows the hovertemplate as `%{label} %{value}%` which is not wanted.

**Comment by johncalabrese** [comment]
I also have this problem. I guess its not something I did wrong!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
