### ISSUE TITLE
option to control margin.minfinal(width|height)

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5246]
I like that idea - `layout.margin.minfinal(width|height)` perhaps, with a default of something like 100 (px).

_Originally posted by @alexcjohnson in https://github.com/plotly/plotly.js/pull/5237#discussion_r513588895_

**Comment by archmoj** [comment]
By exposing these two constants: 
https://github.com/plotly/plotly.js/blob/96d75110706d255ead829ba1d0ba18e8e5a0b67e/src/plots/plots.js#L1867-L1868

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
