### ISSUE TITLE
mirroring axis in splom is not consistent

### ISSUE THREAD

**Issue by miketerp** [plotly/plotly.js#5272]
Based on splom examples (https://plotly.com/python/splom/), when someones trying to mirror the x & y axis, only the graph on the bottom left is "mirrored". We would like to have this consistent across all of the graphs.

How to reproduce: 
Take the example from (https://plotly.com/python/splom/), apply "mirroring"

```
num_variables = 16

xaxes = {}
yaxes = {}

for i in range(num_variables):
    xaxes[f'xaxis{i+1}'] = dict(showgrid=False, zeroline=False, showline=True, linecolor='black', linewidth=1, mirror=True)
    yaxes[f'yaxis{i+1}'] = dict(showgrid=False, zeroline=False, showline=True, linecolor='black', linewidth=1, mirror=True)

fig.update_layout(**xaxes, **yaxes)

# OR
# fig.update_xaxes(showline=True, linecolor='black', linewidth=1, mirror=True)
# fig.update_yaxes(showline=True, linecolor='black', linewidth=1, mirror=True)
```

Here's a screenshot:
![splom mirror axis](https://user-images.githubusercontent.com/2692987/99098093-80c31700-25a6-11eb-8fba-73fcc5059027.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
