### ISSUE TITLE
Stacked binary traces

### ISSUE THREAD

**Issue by ciuliene** [plotly/plotly.js#5274]
Hello, I have a problem with Plotly.js. I'm trying to draw some traces which have 0 and 1 as values. They are digital variables and what I want to do is to draw them one above the other one, like this:

![Schermata 2020-11-13 alle 22 15 25](https://user-images.githubusercontent.com/47216590/99122057-e4c4fa00-25fd-11eb-89fc-64a8a603d81b.png)

To do so, I faked each trace values. First trace can be 0 or 1, second trace can be 3 or 4, third trace can be 6 or 7, etc...
The problem is when I remove a trace using the legend. The result is something like this:
![Schermata 2020-11-13 alle 22 17 18](https://user-images.githubusercontent.com/47216590/99122154-19d14c80-25fe-11eb-8e34-e12adcd7bd29.png)

I'd like to have the other lines to be redrawn without the removed one.

So, the question is: is there an easier way to do this? Something like "stacked binary layout"?

Thank you!

**Comment by alexcjohnson** [comment]
You can use a category axis. Might just work exactly as you have it but with `yaxis.type='category'`, but then you don't need to encode the values as numbers, any unique values will do. Here I just used strings to get a category axis automatically:
```js
Plotly.newPlot(gd,
    [{y: ['a','b']},{y:['c','d']},{y:['e','f']}],
    {yaxis:{tickvals:['a','b','c','d','e','f'],ticktext:['OFF','ON     ','OFF','ON     ','OFF','ON     ']}}
)
```
![Screen Shot 2020-11-13 at 5 11 18 PM](https://user-images.githubusercontent.com/2678795/99126080-73705180-25d3-11eb-9396-ad553fb43bd9.png)

That said @archmoj I think there's a bug here when I try to include `categoryorder`, which is necessary to ensure the Off values always come before the On values: Then when I hide a trace via the legend, its categories are still there:
```js
Plotly.newPlot(gd,
    [{y: ['b','a']},{y:['c','d'], visible: 'legendonly'},{y:['e','f']}],
    {yaxis:{tickvals:['a','b','c','d','e','f'],ticktext:['OFF','ON     ','OFF','ON     ','OFF','ON     '], categoryorder: 'category ascending'}}
)
```
![Screen Shot 2020-11-13 at 5 20 08 PM](https://user-images.githubusercontent.com/2678795/99126601-80417500-25d4-11eb-82e2-24c14938cbe4.png)
And worse, if I set a trace to `visible: false` instead of `'legendonly'` an error is thrown. Doesn't seem to be directly related to #5267 / #5268 as I see the problem both before and after that fix...

**Comment by ciuliene** [comment]
> You can use a category axis. Might just work exactly as you have it but with `yaxis.type='category'`, but then you don't need to encode the values as numbers, any unique values will do. Here I just used strings to get a category axis automatically:
> 
> ```js
> Plotly.newPlot(gd,
>     [{y: ['a','b']},{y:['c','d']},{y:['e','f']}],
>     {yaxis:{tickvals:['a','b','c','d','e','f'],ticktext:['OFF','ON     ','OFF','ON     ','OFF','ON     ']}}
> )
> ```
> 
> ![Screen Shot 2020-11-13 at 5 11 18 PM](https://user-images.githubusercontent.com/2678795/99126080-73705180-25d3-11eb-9396-ad553fb43bd9.png)
> 
> That said @archmoj I think there's a bug here when I try to include `categoryorder`, which is necessary to ensure the Off values always come before the On values: Then when I hide a trace via the legend, its categories are still there:
> 
> ```js
> Plotly.newPlot(gd,
>     [{y: ['b','a']},{y:['c','d'], visible: 'legendonly'},{y:['e','f']}],
>     {yaxis:{
>         tickvals:['a','b','c','d','e','f'],
>         ticktext:['OFF','ON     ','OFF','ON     ','OFF','ON     '],
>         categoryorder: 'category ascending'
>     }}
> )
> ```
> 
> ![Screen Shot 2020-11-13 at 5 20 08 PM](https://user-images.githubusercontent.com/2678795/99126601-80417500-25d4-11eb-82e2-24c14938cbe4.png)
> And worse, if I set a trace to `visible: false` instead of `'legendonly'` an error is thrown. Doesn't seem to be directly related to #5267 / #5268 as I see the problem both before and after that fix...

Hey @alexcjohnson , I've done it! I managed to have stacked binaries using, as you told me, type: "category", categoryorder: "array", and categoryarray. Each time the user clicks on the legend the categoryarray property is reloaded. It now works exactly as I wanted

I haven't checked the case with an "invisible" trace (visible : false) because I don't use it. Anyway thank you so much for your help! 1000 points for you! 👍

**Comment by alexcjohnson** [comment]
@ciuliene OK great, glad that worked! There's still a bug here though, so I'll leave the issue open until we address it.
