### ISSUE TITLE
left edge of graph renders without markings first, then re-renders and appears to jump right when using background images

### ISSUE THREAD

**Issue by mohanprasadgutta** [plotly/plotly.js#5276]
Hello,

I am having problem with latest Plotly.js version when using it to plot graphs with background images.  When I am not using "images" attribute in layout my graph renders steadily with out jumping to right. But when I try to use "images" attribute in layout to set a background image for my graph, it first renders left-axis(i.e y axis) jumps right without markings and then re-renders with markings.

I made jsbin example with and without "images" attribute to describe the problem more clearly.

without "images" attribute: https://jsbin.com/cawayep/edit?html,output

with "images" attribute: https://jsbin.com/likuhox/1/edit?html,output

so is there any way we can avoid that jumping issue when using plotly.js with "images" attribute?

Thanks

**Comment by joshrabinowitz** [comment]
It may not be totally obvious in the second, `with "images" attribute` example above, because it happens so quickly in some browsers, but the left y-axis gets drawn to the very left first, and then shifts right to make room for the labels on the y-axis. When we show graphs with a lot more data lines, this is more obvious.

As we show in the first example above, this behaviour does not seem to occur in the `without "images" attribute`.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
