### ISSUE TITLE
Autorange behaves differently for mode='markers' vs mode='lines'

### ISSUE THREAD

**Issue by tboerstad** [plotly/plotly.js#5280]
First of all, thank you very much for Plotly.js. It's helped me out a lot. 

As a developer, I would have expected that the x- and y-range would be stable when toggling the mode. 

See this [codepen example](https://codepen.io/tboerstad/pen/NWPOMde) and observe that the x- and y-range jumps when toggling between a line and scatter plot. 

This is a minor issue, and feel free to close it if it's intentional.

**Comment by alexcjohnson** [comment]
I'm glad plotly.js has helped you!

These differences are intentional - line charts get no padding in the x direction, whereas with markers you get padding in both directions. Exactly why x and y are treated differently is a bit subtle, but I'd say the main thing is different expectations around independent vs dependent variables. Also with markers we need to leave extra room in both directions for the markers themselves, in addition to the padding.

There is however a longstanding open issue to provide more control over this behavior #1876. It has a lot of pieces and for whatever reason none of them have bubbled up to the top of our list, but we'd happily accept a PR or sponsorship to make them a reality.
