### ISSUE TITLE
Hover info offset in Horizontal Bar Charts with low height

### ISSUE THREAD

**Issue by COLLINETTEBastien** [plotly/plotly.js#5281]
Hello !

I am currently working with Horizontal Bar Charts and I noticed a strange offset on the hover info that display the values.
It occurs when the height's value is low and the x-axis values in the middle of the graph are close to each other.

Here's an example : 
https://codepen.io/collinettebastien/pen/XWKGNxW

In the example, hover values for Wed, Thu and Fri have an offset that put a part of the value out of its container but that is not the case for Mon where values are also close to each other.
 
Is this behaviour expected as the height is considered as too low or is it a bug that can be fixed?

I hope that my example is clear enough.

Thank you very much for your hard work!

**Comment by alexcjohnson** [comment]
Thanks for the report @COLLINETTEBastien - to be clear, here's a picture of the misalignment in your codepen:
<img width="116" alt="Screen Shot 2020-11-16 at 9 11 46 AM" src="https://user-images.githubusercontent.com/2678795/99262370-e48a5180-27eb-11eb-93ea-0daca3281f67.png">
It looks like "786" and "Primary" are aligned correctly, but "783" and "Tertiary" are too high and "789" and "Secondary" are too low.

This is happening when the overall plot height is low enough that we can't fit the hover labels either completely above or completely below the objects (bars) being hovered on, so we display the hover labels centered on the bars. That's why we don't see this issue for the top bars (there's enough room for the hover labels below these bars) or the bottom bars (there's enough room for the hover labels above these bars).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
