### ISSUE TITLE
Rangebreaks autorange bug when first point is inside a break

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#5298]
see https://github.com/plotly/plotly.js/pull/5287#discussion_r528234233

> If you look at the baseline for this mock, you can see a bug in the autorange where the left edge gets no padding. This has nothing to do with matching axes, it'll happen on a single axis with rangebreaks, just because the first point is inside a break.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
