### ISSUE TITLE
constrain domain and overlaying axes

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#5299]
See https://github.com/plotly/plotly.js/pull/5287#discussion_r528232359

> This one I haven't tested, but it certainly seems problematic to have overlaying axes and use the domain (which would apply to all of them) to satisfy a constraint on just one.

In principle we could allow this as long as only one of the overlaying axes has a constraint on it. If multiple have constraints there may be some situations where it would still be possible (but complicated) to satisfy all the constraints, but there would be other situations where this becomes self-contradictory. The easy thing to do would be to just disallow `constrain: 'domain'` when the axis is overlaying or has another axis overlaying it.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
