### ISSUE TITLE
Correct license comments in prebuilt libraries

### ISSUE THREAD

**Issue by wald-tq** [plotly/plotly.js#5300]
I am using the file `plotly.js/dist/plotly-basic.js` and I found that the copyright and license information for d3 is missing. 

So everybody who is using plotly is probably violating the terms of the d3 License.

My suggestions: 
* add the license strings to the build output in a format that is respected by webpacks extractComments: https://webpack.js.org/plugins/terser-webpack-plugin/#extractcomments
* Add a note to the documentation of plotly, mentioning the usage, copyright and license information of d3

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
