### ISSUE TITLE
Automatic Determination Of X Axis With 1 Bar Plot and 1 Line Plot

### ISSUE THREAD

**Issue by dhakim87** [plotly/plotly.js#5317]
When I make a line plot and a bar plot on the same page, both show if the bar plot comes first, but only the line plot shows if the bar plot comes second.  This appears to be due to how x axis is set on the second plot:

If bar plot is first:

- Sets categorical for plot 1
- Switches to cartesian for plot 2

If line plot is first

- Sets cartesian for plot 1
- Stays with cartesian for plot 2, even though only trace in second plot is categorical.  This should choose a categorical axis "A" "B" "C" in my example below.  

See example here:
https://codepen.io/dhakim87/pen/BaLKaBJ

**Comment by dhakim87** [comment]
Argh.  The call to newPlot modifies the layout parameter object and adds an xaxis field.  My misunderstanding of the api - if modification of the layout argument to Plotly.newPlot is an intended side effect, close this ticket.  Otherwise bug could likely be fixed by a defensive copy of the layout argument.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
