### ISSUE TITLE
Issue while displaying negative numbers , minus symbol getting displayed as strange character

### ISSUE THREAD

**Issue by jmriyaz84** [plotly/plotly.js#5327]
In our graph y values may have negative numbers , but those negative numbers getting displayed as special characters.

Please help us on this. 
<img width="813" alt="negative-issue" src="https://user-images.githubusercontent.com/8514576/101461014-c2e83a00-3953-11eb-8149-8d23e870532c.PNG">

**Comment by archmoj** [comment]
Which font are you using?

**Comment by jmriyaz84** [comment]
Thanks Issue Resolved UTF-8 Issue

**Comment by jmriyaz84** [comment]
Dear Team ,
Thanks for your response , issue resolved before my jsp page was using some other charset after changing to UTF-8 issue got resolved

**Comment by 5j9** [comment]
In my case, the problem was that I was copy-pasting the contents of https://cdn.plot.ly/plotly-2.25.2.min.js into a file manually. Apparently, some encoding issue was happening there (I'm using windows 10). Saving/downloading the file fixed everything.

I found the link on https://plotly.com/javascript/getting-started/ . Interestingly the link does have a `download` attribute to force the file to be download, but I believe it fails to do so due to [same-origin restriction for download attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes).

**Comment by YasirKusay** [comment]
Hi @5j9, I did try your solution (and made sure I was specifying the encoding) but I still had the same issue. Do you have any other recommendations?
