### ISSUE TITLE
Missing labels on the RangeSlider

### ISSUE THREAD

**Issue by fairking** [plotly/plotly.js#5333]
I searched the github and your docs but I cannot find any example with showing labels on the RangeSlider?

It would be nice to add some example to the https://plotly.com/javascript/range-slider/

![image](https://user-images.githubusercontent.com/13495631/101772179-eb526e80-3ae2-11eb-846b-e020f13459e1.png)

Thanks for any help.

**Comment by fairking** [comment]
Another missing thing I am looking for:
![image](https://user-images.githubusercontent.com/13495631/101774281-cca1a700-3ae5-11eb-99e5-0900390b95e9.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
