### ISSUE TITLE
subplots do not work correctly with visible: 'legendonly' plots

### ISSUE THREAD

**Issue by mmakrzem** [plotly/plotly.js#5347]
I want to create a subplot similar to the first one shown in the documentation here: https://plotly.com/javascript/subplots/ with one important change.  When a user clicks on the legend to hide a trace, I don't just want to hide the trace line but still keep the plot axis and grid lines visible, I want to hide that as well.  

I created this code pen that demonstrates the bug: https://codepen.io/mmakrzem/pen/mdrmvyR

In my example, I create 4 plots rendered in 1 row and 4 columns.  

Notice that if you click the 'Blue' legend, the first plot disappears, leaving only the Orange, Green and Red traces as desired.
Everything works fine with this example, so long as you hide the traces from top to bottom without skipping any.

To see the bug, turn all the traces on, and then click on 'Green' in the legend to hide the 3rd plot.  This should result in the Blue, Orange and Red traces to be visible.  

What I'm seeing instead is that the Blue and Orange plot axes are visible but there are no traces drawn.  The Red plot is perfectly fine.

If you turn all of the traces on, and then click on 'Red" to hide the last plot, now the Red one is gone (correct) but the other 3 do not render in their appropriate spots.

**Comment by mmakrzem** [comment]
Just updated my codepen to use https://cdn.plot.ly/plotly-2.4.2.min.js and the problem still exists in plotly v2.  Any suggestions on how to fix this issue?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
