### ISSUE TITLE
Plotly Modal touchpad scroll works on chrome but does not work in mozilla

### ISSUE THREAD

**Issue by bhosaleanagha** [plotly/plotly.js#5352]
I have used plotly historam. Upon clicking the histogram graph a modal opens. But when i try to open my webpage in chrome the modal touchpad scroll works fine. Whereas opening the webpage in firefox it shows modal with scrollbar. But the scrollbar is not touchpad scrollable.

Please guide!

**Comment by alexcjohnson** [comment]
Thanks @bhosaleanagha - but I'm not quite sure what modal you're referring to. Can you post a screenshot and relevant code example? (ideally online like https://codepen.io/fkE3/pen/eYZOoPg?editors=0010)

**Comment by alexcjohnson** [comment]
I'm sorry, I still can't tell what functionality you're referring to with this description. Is this modal something that plotly.js created? Or is it something you made in some other way inside the handler for a plotly.js event? We'll need some sort of reproducible code example - doesn't need to be your code, in fact it's better if it's pared down to the bare minimum required to demonstrate your issue.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
