### ISSUE TITLE
[Request] Support Server-side rendering

### ISSUE THREAD

**Issue by alanpurple** [plotly/plotly.js#5361]
need mechanism for server-side rendering

for example, angular, they can inject DOCUMENT object for SSR, to component

plotly.js should handle build options like "--use_custom_documentObj"

**Comment by dawadam** [comment]
It would be handy to be able to render a static image on the server side, with NodeJS.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
