### ISSUE TITLE
newPlot doesn't respect layout.height unless layout.autosize is explicitly true

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#537]
I know this should really be done with relayout, but nevertheless, I found the behavior surprising.

http://codepen.io/cpsievert/pen/yOrQya

**Comment by etpinard** [comment]
I would definitively call this a bug. Thanks for bringing this up.

The root of the problem is in this [block](https://github.com/plotly/plotly.js/blob/5601e69790d0fd1c9e9f4f5ded956f8c2230891f/src/plot_api/plot_api.js#L2559-L2561) where layouts with incomplete size specifications (denoted by `autosize: 'initial'` [internally](https://github.com/plotly/plotly.js/blob/5601e69790d0fd1c9e9f4f5ded956f8c2230891f/src/plots/plots.js#L729-L730)) go through the `plotAutoSize` routine which overrides the user layout spec by the computed size of the graph div.

I believe the aforementioned block should instead be:

```js
computedStyle = window.getComputedStyle(gd);
newHeight = fullLayout.height || parseFloat(computedStyle.height);
newWidth = fullLayout.width || parseFloat(computedStyle.width);
```

**Comment by n-riesco** [comment]
@etpinard While looking into #106 and #272 I came across [this TODO](https://github.com/plotly/plotly.js/blob/b5331e391957278059eac89a77e2d7a74575f181/src/plots/layout_attributes.js#L50) and I'm looking into removing `'initial'` from `autosize`. Since it touches the same code, I could address this issue in the same PR.

**Comment by n-riesco** [comment]
I've also found that `autosize: true` isn't honoured in the following cases:
-  when `Plotly.plot(Tabs.fresh(), [{ x:[1,2,3], y:[3,2,1]}], {autosize: true})` is run, the graph is given the default dimensions `700x450` regardless of the dimensions of the container. Only after `Plotly.relayout(gd, {autosize: true})` is run, the graph takes the dimensions of the container;
-  `Plotly.relayout(gd, {})` has no effect.

In the PR I'm preparing, I'm planning to ensure that:
- `Plotly.plot(Tabs.fresh(), [{ x:[1,2,3], y:[3,2,1]}], {autosize: true})` creates a graph with the dimensions of the container;
- and that `Plotly.relayout(gd, {})` triggers `plotAutoSize` if `autosize` is set.

**Comment by cpsievert** [comment]
It looks like the issue I originally reported still persists, no?

**Comment by etpinard** [comment]
> It looks like the issue I originally reported still persists?

Correct. Will be done in https://github.com/plotly/plotly.js/pull/635
