### ISSUE TITLE
Allow user annotations

### ISSUE THREAD

**Issue by alexandergerber** [plotly/plotly.js#5385]
As far as I know it is possible for a user to add shapes to a plot as in the last example on this page https://plotly.com/python/shapes/ .
![image](https://user-images.githubusercontent.com/19466818/103871602-897b2980-50cd-11eb-9960-a8f3065b795c.png)

It would be a cool feature, if the user could also annotate the graph, e.g. similar how you would do it in Power Point by adding 
a text field.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
