### ISSUE TITLE
3d graph export

### ISSUE THREAD

**Issue by afang223** [plotly/plotly.js#5390]
Currently, when trying to build an external button to export a 3d scatter graph as a png, the graph is never able to be downloaded. The same function call to the modebar to image button's click function works for 2d graphs. How can this be resolved?

**Comment by DobsX** [comment]
I have the same use-case and ultimately the same problem.  We have a bunch of other components/html around the Plotly plot that we want to include in the image, so we are using our own external button.

From what I can tell, 3d charts are using webgl, and so there's some extra stuff that needs to be considered.  I think calling `toImage` or `downloadImage` externally is somehow not providing the right context to the subsequent native Plotly image functions.

**Comment by DobsX** [comment]
@afang223 your situation seems so eerily similar to mine so perhaps my solution will work for you.  We're using next.js SSR for our project, and webgl/3d Plotly plots were having an issue with screenshots.  Just like you, it was fine with 2d.

So what we had to do was to import Plotly.js [dynamically](https://nextjs.org/docs/advanced-features/dynamic-import) so the functions are running in the browser.

```
const Plotly = (await import('plotly.js/dist/plotly.js')).default;
...
await Plotly.toImage(...);
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
