### ISSUE TITLE
Heatmap Colorscale Feature Request

### ISSUE THREAD

**Issue by JMiller63** [plotly/plotly.js#5392]
My project uses the Heatmap and accompanying Colorscale object to represent our data. We have implemented a slider component that dynamically updates the zmin and zmax values of the Colorscale object. The data we present is in the 0 to 100 range and the issue we are seeing is that when the zmax value changes between having 2 digits to 3 the Colorscale tick mark labels update and cause a minor graph resize based on the transition from 2 digits to 3 (and vice versa). Is it possible to add a boolean property that would enable/disable this resize? I understand that this is somewhat of an edge case hence the bool defaulted to enabled. If there's a better way of handling this please advise.

**Comment by alexcjohnson** [comment]
That's happening because by default the margins expand automatically to fit their contents, in this case the colorbar. But you can disable that behavior by turning off `layout.margin.autoexpand` and setting an explicit `layout.margin.r` (assuming your colorbar is on the right) that leaves enough space for all situations.

**Comment by JMiller63** [comment]
This fixed our issue exactly, thanks so much!
