### ISSUE TITLE
Colorbar scale on Mapbox doesn't update after callback

### ISSUE THREAD

**Issue by Raimondo-M** [plotly/plotly.js#5397]
Hi everyone,
 I am having the following issue using px.scatter_mapbox to show some values from a dataframe.
The issue appears when I change with a callback the value to plot.
"Value A" has a lower scale than "Value B".
When I move from A to B with the callback, everything is fine. 
When I come back to "value A" from "value B",  the colorbar keeps the biggest scale of "value B".
This is happening with also other scales, it always keeps the biggest scale it has seen.

![bug_immage](https://user-images.githubusercontent.com/53900506/104352787-06a80380-54ff-11eb-98ba-7406e9c698e1.png)

I think this issue could be related to this one #4337, but I haven't been able to fix it 

```
def mapbox(df = df, value = 'Human health', colors = color_scales):
    fig = px.scatter_mapbox(df, lat = "lat", lon = "lon", color = value, size = value,
                            color_continuous_scale = colors[value], size_max = 25, zoom = 12, hover_name=df.Label)
    ...
    return fig
```
and

```
@app.callback([Output('mapbox', 'figure'), Output('info_box', 'children')],
    [Input("map_impact", 'value')])
def update_need_table(value):
    return mapbox(value = value), info_box_text[value]
```

Thanks a lot for any help, I hope I had explained the issue clearly

(Apologies if I made mistakes in reporting this issue, it is the first time I report one)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
