### ISSUE TITLE
[Feature Request] New Sizing Option to Repeat Source Image in Area Defined in layout.image Object 

### ISSUE THREAD

**Issue by frankwalentowski** [plotly/plotly.js#5403]
I tried to draw a pattern below a trace to highlight specific areas within the trace.
For reasons of beauty it is no option for me to use layout.shapes to draw a monotonous color area. I want to draw a pattern with small tiles which are repeated within drawn area.

I thought one option could be to use layout.images. But while testing this feature I realized that the parameter layout.images[].sizing has only three possible values ("fill", "contain", "stretch"). Each value stretching my tile its own way.

It would be nice to have a fourth type of layout.images[].sizing (https://plotly.com/javascript/reference/layout/images/#layout-images-items-image-sizing) named "repeat" which repeats the given image within the given area in x and y direction.

P.S.:
I also tried to use a SVG-File as image but Plotly seems not to accept the file because image layer remains empty with the SVG file.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
