### ISSUE TITLE
Physically square plots with automatically matching ranges

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5405]
@alexcjohnson's idea here would be a `matchlength` boolean attribute which would ride on top of `matches` and force the domains to match as well as the ranges. Maybe `matchdomainlength` ?

This would enable physically-square all-ranges-match facetted plots like this:

* `xaxis1: matchlength=true, anchor=y1, matches=y1`
* `xaxis2: matchlength=true, anchor=y2, matches=x1`
* `yaxis1: matchlength=true, anchor=x1, matches=x1`
* `yaxis2: matchlength=true, anchor=x2, matches=y1`

in the graphic below A=anchor and M=matches+matchlength=true:

![image](https://user-images.githubusercontent.com/203523/104611492-2f411200-5653-11eb-967a-9ae0b892a046.png)

**Comment by nicolaskruchten** [comment]
Presumably, having all four axes (x and y) have `matches=x, matchlength=true` would also do it.

**Comment by alexcjohnson** [comment]
> Presumably, having all four axes (x and y) have `matches=x, matchlength=true` would also do it.

`xaxis: {matches: 'x'}` would be ignored during `supplyDefaults` so yes that would work. Redundant and would be flagged by `Plotly.validate`, but if that makes upstream logic simpler then go for it.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
