### ISSUE TITLE
Last xaxis tick tooltip is misaligned (only with custom xaxis ticks)

### ISSUE THREAD

**Issue by aliaksandr-dzemchanka** [plotly/plotly.js#5417]
In this pen https://codepen.io/aliaksandr_dzemchanka/pen/zYKerPr last point xaxis tick tooltip is misaligned. It should be rendered at the same place where xaxis line ends.
This is not reproduced if I remove custom ticks (ticktext and tickvals).
![image](https://user-images.githubusercontent.com/7568452/104854367-49127b80-5917-11eb-8261-943842f60cde.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
