### ISSUE TITLE
Click one point by javascript instead of mouse

### ISSUE THREAD

**Issue by orangeSi** [plotly/plotly.js#5431]
Hello， I try to click one point (example: the point which x=5) by javascript instead of mouse， but I don't know how to do it or can't find the API of Plotlyjs. 

My test code is  as below:  
```
<head>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>  
  <div id="myDiv" style:width: 100%><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
    <!-- JAVASCRIPT CODE GOES HERE -->
  </script>
</body>
```
and
```
var myPlot = document.getElementById('myDiv'),
    d3 = Plotly.d3,
    N = 16,
    x = d3.range(N),
    y = d3.range(N).map( d3.random.normal() ),
    data = [ { x:x, y:y, type:'scatter',
            mode:'markers', marker:{size:16} } ],
    layout = {
        hovermode:'closest',
        title:'Click on Points'
     };

Plotly.newPlot('myDiv', data, layout, {showSendToCloud: true});

myPlot.on('plotly_click', function(data){
    var pts = '';
    for(var i=0; i < data.points.length; i++){
        pts = 'x = '+data.points[i].x +'\ny = '+
            data.points[i].y.toPrecision(4) + '\n\n';
    }
    alert('Closest point clicked:\n\n'+pts);
});

```
then get the plot:
![image](https://user-images.githubusercontent.com/12126846/105434944-6dfc4b00-5c97-11eb-9007-43aa7e5715a0.png)

The above code also be in [codepan](https://codepen.io/plotly/pen/QbZmZY).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
