### ISSUE TITLE
Rendering to a browser from a python script?

### ISSUE THREAD

**Issue by DaveSprague** [plotly/plotly.js#5441]
Is it correct that plotly will not render in a browser when you're just running it using python from the command line or inside vscode. That it will only render in a browser when running from inside a jupyter notebook or if you build your own webserver as part of your python code?

When running a python script (not a notebook) I can get it to generate an html file and display that in a browser but it appears that it won't just render, interactively, in a browser. Is that expected?

My goal is to have a python script that renders interactive plots that generate events, on hover for example, with corresponding callbacks in my python script. Is that not possible unless I'm working in a notebook?

Thanks,
Dave

**Comment by alexcjohnson** [comment]
Sounds like [Dash](https://github.com/plotly/dash)

**Comment by DaveSprague** [comment]
I'll look into that Thank you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
