### ISSUE TITLE
allow boolean mask for selectedpoints

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5445]
Right now if I have a scatter plot with 5 points and I want to mark the first three as selected, I have to pass `selectedpoints: [0,1,2]` but in certain contexts it would be easier to provide `selectedpoints: [true, true, true, false, false, false]`.

**Comment by alexcjohnson** [comment]
Seems reasonable, accept either form and switch based on the type of the first array element?

**Comment by nicolaskruchten** [comment]
sgtm

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
