### ISSUE TITLE
Huge difference between polar plot in plotly.js and plotly.js-basic-dist

### ISSUE THREAD

**Issue by TheLogan** [plotly/plotly.js#5450]
So I've created the following codepen, in the left side I've got the cdn for both plotly.js and the basic dist, one is commented out, switch them around to see the difference. The basic one to me looks like it's broken
[https://codepen.io/tim-logan/pen/GRNKGZJ](https://codepen.io/tim-logan/pen/GRNKGZJ)

**Comment by archmoj** [comment]
Thanks for the report.
Here is a [minimal codepen](https://codepen.io/MojtabaSamimi/pen/RwobBvM?editors=1000) showing the diff between two.

**Comment by alexcjohnson** [comment]
That's not expected to work. The [basic bundle](https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-basic) is only supposed to contain `scatter`, `bar`, and `pie` trace types. I think what's happening is the basic version is falling back to the very old (and about to be removed in v2) legacy polar charts, because `type: 'scatterpolar'` isn't recognized, so you end up with `type: 'scatter'` but then the `r` attribute invokes legacy polar.

**Comment by archmoj** [comment]
And if I substitute with the v2 candidate builds on master there is no `polar` on `basic` | [codepen](https://codepen.io/MojtabaSamimi/pen/mdObjNj?editors=1000).

@alexcjohnson isn't this the correct behaviour given the fact `basic` bundles should not contain `scatterpolar`?

**Comment by TheLogan** [comment]
Do any of the partial bundles contain polar coordinates? (I tried looking at creating my own bundle, but can't get the software to run, so I left a comment on the gist)
