### ISSUE TITLE
Logarithmic axis support for indicator charts.

### ISSUE THREAD

**Issue by eniv** [plotly/plotly.js#5453]
Hi,
Is it possible to set the axis type to logarithmic for these charts?
I've tried to set the type attribute in xaxis and yaxis of the layout to 'log', but it had no effects:
```
var layout = {
  xaxis: {
    type: 'log'
  },
  yaxis: {
    type: 'log'
  }
};
```

my data trace is a simple bullet which looks something like:
```
  {
    type: "indicator",
    value: 0,
    delta: { reference: 0.5 },
    domain: { x: [0.25, 1], y: [0.08, 0.25] },
    mode: "gauge+number+delta",
    gauge: {
      shape: "bullet",
      threshold: {
        line: { color: "black", width: 2 },
        thickness: 0.75,
        value: 0.5
      },
      axis: { visible: true, range: [0, 1] }
    }
```

I've also tried setting the `type` attribute to `'log'` under `gauge.axis`, but it also had no effect.

**Comment by nicolaskruchten** [comment]
We do not have log support for indicators at the moment, no.

**Comment by eniv** [comment]
ok, thanks for the quick response.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
