### ISSUE TITLE
Polar charts don't respect the hovermode feature that enables multiple tooltips

### ISSUE THREAD

**Issue by TheLogan** [plotly/plotly.js#5464]
https://codepen.io/tim-logan/pen/zYovxmr

The first 3 charts work as expected, but the last one should to my understanding should show both tooltips at the same time, similar to how [Nivo handles tooltips on their radar chart](https://nivo.rocks/radar/) (except for the tooltips not being combined), where you get all values from a single point on the axis.
I've tried a few different values, and I can't get it to work like that.
P.s. I'm curious, is it possible to combine the tooltips into a single tooltip?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
