### ISSUE TITLE
Trace text can disappear when gaps are present

### ISSUE THREAD

**Issue by tcummin2** [plotly/plotly.js#5493]
This is a bit of an odd case. Here's a working example: https://codepen.io/tcummin2/pen/yLVadzB

1. Open the codepen
2. Pan on the plot at least once
3. One of the texts will disappear
4. Pan again
5. The other text will disappear but the first one will reappear
6. The texts will neither appear nor disappear from then onward.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
