### ISSUE TITLE
Plot component shows fallback component on every render

### ISSUE THREAD

**Issue by wamoha** [plotly/plotly.js#5495]
Thanks for your interest in plotly.js!

**Environment -** 
react-plotly: 2.5.0
plotly: 1.51.3
react: 16.12.0
react-dom: 16.12.0

**Sample code**

`
const LazyPlot = React.lazy(() => {
  return Promise.all([import("react-plotly.js"), new Promise(resolve => setTimeout(resolve, 5000))]).then(([m]) => ({
    default: m.default
  }));
});

export const BaseChart = <RowType extends {}>(props: IBaseChartProps<RowType>): React.ReactElement => { 
  const d: Plotly.Data[] = [
    {
      type: "scatter",
      mode: "lines",
      x: [1, 2, 3],
      y: [2, 6, 3],
      marker: { color: "red" }
    },
    {
      type: "bar",
      x: [1, 2, 3],
      y: [2, 5, 3]
    }
  ];
  return (
    <>
      <React.Suspense fallback={<div>Loading...</div>}>
        <LazyPlot
          data={d}
          layout={{
            width: 450,
            height: 350,
            title: "A Fancy Plot"
          }}
        />
      </React.Suspense>
    </>
  );
};
`

Wrap the above code in some parent component which maintains state. When the parent and baseChart components render, the plot component renders lazily, displaying the fallback component. When there's any update to the state of the parent component, and the baseChart component re-renders, the fallback is displayed.

**Expected**: The fallback should not be displayed on re-renders as the module/component import has succeeded.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
