### ISSUE TITLE
How to show hover with a vertical moving line in a line chart?

### ISSUE THREAD

**Issue by YongxinZz** [plotly/plotly.js#5507]
I have a line chart with a vertical moving line that moves along with the slider as the picture shows. 
![image](https://user-images.githubusercontent.com/62288008/108097642-ae769b00-7082-11eb-8800-4274b6c5e506.png)

I am wonder if the hover function can be added to this moving line, as the picture shows below.
So it will continually show the data where the line indicates while the line is moving (without using the mouse hovering on the line).
![image](https://user-images.githubusercontent.com/62288008/108098172-5a1feb00-7083-11eb-9c5a-ab104b752fe9.png)

How can I achieve this function using plotly?

I saw the plotly.fx.hover on this page https://plotly.com/javascript/hover-events/#triggering-hover-events
Is that something I can use in my case? If yes, how does this plotly.fx.hover works? (there is no explanation how plotly.fx.hover works)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
