### ISSUE TITLE
Plotly library fails to load silently

### ISSUE THREAD

**Issue by danielfrunza** [plotly/plotly.js#5509]
Plotly javascript library fails to load silently if ArcGIS library is added before it. This issue is blocker for me because I can not use both of them in the same time...

Steps to reproduce on Chrome or Firefox on Windows10:
1. Open any website that does not have already ArcGIS or Plotly loaded.(ex: google.com)
2. Open Chrome developer tools
3. Add FIRST ArcGIS in console drawer by copy/paste following lines:
```
var acrGISlib = document.createElement("script");
acrGISlib.setAttribute("type", "text/javascript");
acrGISlib.setAttribute("src", "https://js.arcgis.com/4.18/");
document.getElementsByTagName("head")[0].prepend(acrGISlib);
```
4. Add the Plotly lib from CDN in console drawer by copy/paste following lines:
```
var plotlyLib = document.createElement("script");
plotlyLib.setAttribute("type", "text/javascript");
plotlyLib.setAttribute("src", "https://cdn.plot.ly/plotly-latest.min.js");
document.getElementsByTagName("head")[0].prepend(plotlyLib);
```
5. Check if global variable 'Plotly' is available.
`Uncaught ReferenceError: Plotly is not defined`

Note: If step 3 is skipped everything is working as expected. If step 4 is done before step 3 they will both work but this does not help me...

![Plotly](https://user-images.githubusercontent.com/14039720/108195170-1af3a780-7120-11eb-8ff7-b71749ecc8a0.png)

**Comment by danielfrunza** [comment]
I've tried also with 2.0.0-rc.0 and the issue is still reproducing...

**Comment by alexcjohnson** [comment]
This is certainly an interesting one - The ArcGIS JavaScript library sets `window.define`, which confuses our UMD header. If you delete that in between loading ArcGIS and loading Plotly, with something like:
```
<script>delete window.define;</script>
```
Then Plotly loads just fine. https://codepen.io/alexcjohnson/pen/wvoeJRY?editors=1000

I've never seen another library that leaks `define` onto the global scope like that. It's not clear to me whether that's intentional or not, but I believe our header is pretty standard so this must be a problem with a lot of JS packages.

**Comment by danielfrunza** [comment]
Thank you for the quick answer! I didn't thought a second that this could be the problem... I thought it was some event that is shared and prevents the lib to load...
