### ISSUE TITLE
Orthographic zoom should adjust center

### ISSUE THREAD

**Issue by jobh** [plotly/plotly.js#5510]
The problem is visible in [this pen](https://codepen.io/luthaf/pen/oNgmavz) from another issue.

If you zoom in until no red dots are visible, then pan to center a red dot, then zoom out again, the whole plot drops out of view. 
 The further you zoom in, and the further you pan, the worse the problem becomes. Counter-intuitively, you have to zoom in to locate the plot again.

I _think_ the problem is that `camera.center` is in aspectratio coordinates, so when the aspect ratio is scaled (which is how orthographic zoom is implemented), the center should also be scaled accordingly.

Ideally, I think the center should be adjusted so that the zoom appears to be around the mouse position, like in 2D plots. But I don't know how hard it would be to achieve, and this simpler fix will go a long way.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
