### ISSUE TITLE
3d camera center in data coordinates

### ISSUE THREAD

**Issue by CarlAndersson** [plotly/plotly.js#5524]
In many cases it would be useful to allow setting the camera center in "data units". This would for example allow the scene to initially be centered at a point of interest so that rotations can occur around that point.
From what I can tell there is no easy way to do this at the moment.

Related:
- https://github.com/plotly/plotly.py/issues/1778
- https://github.com/plotly/plotly.js/issues/579

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
