### ISSUE TITLE
Interactions with choropleth plot inside elements with `transform: translate` don't work in Firefox

### ISSUE THREAD

**Issue by LucaVazz** [plotly/plotly.js#5525]
When applying a css-transform with `translate` or `translate3d` to the parent element, interactions with a choropleth chart inside of that element unfortunately don't work in Firefox.
This applies to hovering over data points and zooming with the mouse wheel. Hovering doesn't display the label, while zooming happens to an offset point.

Tested in Firefox 86.0 and 87.0b3 (Aurora / Developer edition).

**Example**: https://codepen.io/lucavazz/pen/mdOpgMY

possibly related: #5193

**Comment by LucaVazz** [comment]
Unfortunately the PR mentioned above only addresses the hover part of the problem.

Zooming with the mousewheel is still offset when the parent has a translate transform applied.  
From my investigation the simplest fix for this would be to wait for the Firefox bug to be fixed, since it happens due to some inter-connected details inside D3's zoom handling.

**Comment by LucaVazz** [comment]
The hover interactions are fixed now with #5607.
However, zooming with the mouse wheel into a map in Firefox still doesn't work / zooms to a wrong point on the map.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
