### ISSUE TITLE
Yaxis values remain in rangeslider after plotly.react call is made to modify the data of a chart

### ISSUE THREAD

**Issue by cpascale43** [plotly/plotly.js#5526]
With `plotly.newPlot`, the chart renders correctly both times but `plotly.React` renders both new and old yaxis values in rangeslider the second time it's called. 

![rangeslider](https://user-images.githubusercontent.com/52431501/109196279-7ef21d80-7769-11eb-95f8-eea166b12d15.gif)

[codepen of rangeslider that reproduces the issue](https://codepen.io/cpascale43/pen/ExNozGY)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
