### ISSUE TITLE
android webview useragent and isSafari

### ISSUE THREAD

**Issue by hjiayz** [plotly/plotly.js#5528]
https://github.com/plotly/plotly.js/blob/d0ddf03850ccfc5e625da0735b6dcea8e1d61a05/src/lib/index.js#L707

```
/Version\/[\d\.]+.*Safari/.test("Mozilla/5.0 (Linux; U; Android 4.4.4; zh-cn; M351 Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30")
```
`true`

**Comment by hjiayz** [comment]
https://github.com/lancedikson/bowser/blob/master/src/parser-browsers.js

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
