### ISSUE TITLE
Change mask color for range slider

### ISSUE THREAD

**Issue by SimonSimCity** [plotly/plotly.js#5530]
Since it already was asked on Stackoverflow without any proper solution, I now request it here as a feature-request.

I want to change the constant `rangeMask`: https://github.com/plotly/plotly.js/blob/8c5b7253879e8069bc789953430d63d54f7ae36d/src/components/rangeslider/constants.js#L31

If this is already possbile, please point me at an example of how to do it.

The only way I've found is a rather ugly work-around in which I have to use the `!important` CSS term (https://stackoverflow.com/questions/51885481/customize-mask-color-of-range-slider).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
