### ISSUE TITLE
Scatter plot with filled area breaks Y scale

### ISSUE THREAD

**Issue by alessandropisu** [plotly/plotly.js#5540]
In a scatter plot, when fill area is enabled, the scale of the Y axis changes and starts from 0 instead the reduced range (in this case from 122 to 134) when the plot area is not filled.

This is the example with **FILL ON**
[CODESANBOX](https://codesandbox.io/s/morning-moon-qnf0c?file=/index.html)

This is the example with **FILL OFF**
[CODESANBOX](https://codesandbox.io/s/clever-leakey-gb5oi?file=/index.html)

As we can see, the values of two charts are the same but the way to show them is absolutely different cause of this different representation of Y axis

**Comment by alexcjohnson** [comment]
This is intentional - when you fill to zero, the implication is that the absolute size of the data is important to represent visually. This is the same reason we always extend the axis to zero on bar charts.

You're right though that it could be useful to be able to disable this. So while not a bug, we'd be open to adding a feature to control it.
