### ISSUE TITLE
Sunburst Transitioning Issue

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.js#5559]
Not sure if anyone else has come across this (and I tried searching for a similar problem but couldn't find anything). If you are building web-based dashboards with plotly.js and are using the sunburst chart, the following css will prevent the sunburst from transitioning:

* {
    height: 100%;
}

(note: the bullet is supposed to be a star but for some reason the formatting won't allow a star)

I'm not sure why, but when this css is applied, the sunburst chart becomes unresponsive and does not allow you to click the parent elements. Anyways, if you're having this issue, it's likely because of the above.

Also... using the above css will cause problems with your chart legends as well. For me, it was causing the chart legend to be greyed out. Again, not sure why this one line of css causes these problems but maybe others have experienced these same issues. Anyways, if you have, just remove the above code from your file and everything should work fine. Cheers!

**Comment by Kully** [comment]
```
* {
  height: 100%;
}

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
