### ISSUE TITLE
Add support for adding anchor on Pie Chart Data

### ISSUE THREAD

**Issue by harsh201** [plotly/plotly.js#5561]
Hi,

We are trying to create a pie chart with annotation similar to this.
![image](https://user-images.githubusercontent.com/2502711/111950261-097b3200-8b08-11eb-90f2-270a7badb2c7.png)
But since there is no anchor point when we resize the graph, the lines get misaligned. Is there a possibility to add a definition of anchor point to pie chart, similar to what we have in line charts?
![image](https://user-images.githubusercontent.com/2502711/111950591-81e1f300-8b08-11eb-8b81-e2b9966d36c7.png)

**Comment by nicolaskruchten** [comment]
Right now annotations can be anchored to X or Y axes, or to the paper itself, but there is no coordinate system for Pie charts. Implementing such a system would be a fair amount of work and I'm not sure that we'd be up for it right now :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
