### ISSUE TITLE
Multicategorical axis label is misplaced when `showticklabels: false`

### ISSUE THREAD

**Issue by tcummin2** [plotly/plotly.js#5569]
Reproducible Example: https://codepen.io/tcummin2/pen/gOgwgON
When `showticklabels` is `false`, the x-axis label in this example is placed at the top of the plot. 

Seems to be a regression of `v1.50.0`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
