### ISSUE TITLE
should setting clickmode to select change the double click behaviour to plotly_deselect (similar to setting dragmode to select does)?

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/plotly.js#5574]
when `dragmode`  is `'select'` or `'lasso'` , `plotly_deselect` is emitted when you double click but that doesn't seem to be the case if `clickmode` is `'select'` or `'event+select'` (and `dragmode` is`'zoom'`). 

At the moment, if I select a point in a graph where clickmode='select' and dragmode='zoom', the only way to deselect is to change the dragmode in the modebar and the double click after that.

https://codepen.io/michaelbabyn/pen/LYxxOLQ

**Comment by nicolaskruchten** [comment]
I think this is the behaviour even outside of clickmode=select ... i.e. if you set the dragmode to select, drag-select some points, then set the dragmode to pan, you can't double-click-to-deselect. In general, double-clicking has dragmode-specific behaviours like recentering after panning and stuff like that IIRC.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
