### ISSUE TITLE
Issue - White space top and bottom in plotly bar char

### ISSUE THREAD

**Issue by rajkumars22** [plotly/plotly.js#5575]
I’m having a **White space top and bottom** using a Plotly bar chart of more than 80 bars. Please fix the issue as soon as possible.
Please Refer: https://codepen.io/rajkumars22/pen/jOyyMeZ

**Comment by nicolaskruchten** [comment]
What's happening here is that your `scatter` trace (for the vertical line) is causing some automated 5% padding to be added at the top and bottom of your chart, and since your chart is so tall, that 5% really adds up. There's no way right now to disable this padding unfortunately, so the best workaround I can suggest is to swap out your scatter trace for a `layout.shape` object to draw the line you've got there.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
