### ISSUE TITLE
Switch from Mapbox GL JS to MapLibre GL

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5578]
MapLibre (https://github.com/maplibre/maplibre-gl-js) is the community-supported "drop-in" successor to Mapbox GL JS... worth looking at whether or not we should switch.

**Comment by birkskyum** [comment]
Feel free to reach out if you need guidance on this migration, or just have questions on the topic. Compatibility in this case really should be fine - I'd imagine a renaming things mapbox->maplibre to get you quite far, but there might be some details to account for since MapLibre GL JS has progressed significantly since the v1 fork years back but for the most part in non-breaking ways.
