### ISSUE TITLE
Adding plotly_click event handler to surface 3d chart that calls window.open causes weird camera changes

### ISSUE THREAD

**Issue by Madman600** [plotly/plotly.js#5590]
I'm trying to open a new browser window when I click on a plotly 3d surface chart. When the chart is clicked and the new window opens, however, the chart does some crazy rotation moves. You can see in this codepen, just click around on the chart a few times.

https://codepen.io/APRRT/pen/YzNvVvW

**Comment by Madman600** [comment]
I think what's happening is sometimes when you click you might drag a little which does some weird things when the focus is lost. But shouldn't "plotly_click" be fired after a mouse up? It's firing on the mouse down.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
