### ISSUE TITLE
Parcoords : incorrect selection with constraint range 

### ISSUE THREAD

**Issue by vdgodse** [plotly/plotly.js#5593]
I am trying to select a single line in the parallel co-ordinates plot programmatically. So I use constraint range in the following way - {constraintRange: [y1,y1] ,label:'axis 1'} , {constraintRange: [[y2,y2]] ,label:'axis 2'}. 
This way we expect only the lines passing through value y1 on axis1, and through values y2 on axis2 be selected but plotly doesn't update the selection. It's the same UI as before setting up constraint range.
In other case with multiple lines selection(as in example 2)  plotly selects the lines, but a few extra unexpected lines as well.

Reproducible examples
Example 1(single line selection)      : https://codepen.io/vdgodse/pen/wvgEPZx
Example 2(multiple lines selection) : https://codepen.io/vdgodse/pen/poROpXb

Workaround : add a very small value delta d eg:- [y1,y1 +d1] and [y2,y2 + d2] eg: [5,5.00001] instead of [5,5] 

Would you like to add other ways to select lines programmatically like by using index as in other plots like scatter? That way plotly could handle the special case of single selection in the library code itself.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
