### ISSUE TITLE
Tooltip/Hover text for the lines in scatter plot

### ISSUE THREAD

**Issue by danielfrunza** [plotly/plotly.js#5594]
Is it possible to display hover text on the lines(not only on markers) of the same trace in a scatter plot?

![image](https://user-images.githubusercontent.com/14039720/115420619-f5f4e100-a203-11eb-9cdd-8b69550c006b.png)

**Comment by nicolaskruchten** [comment]
Not at the moment, no, but it's a good idea!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
