### ISSUE TITLE
Overrideable `padding` on cartesian axes

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5599]
I think this idea can easily be broken out of https://github.com/plotly/plotly.js/issues/1876 independently...

Cartesian traces right now have non-overridable behaviour around how much padding they add to auto-range, that differs for x/y, and whether or not markers are present etc etc. We could add a `padding` attribute to `(x|y)axis*` whose "auto" behaviour would be the current one, but that users could override to e.g. set to 0 or set to some fraction.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
