### ISSUE TITLE
Scene generated with duplicated canvas element

### ISSUE THREAD

**Issue by amaralc** [plotly/plotly.js#5608]
Scene tag is generated with duplicated canvas element. 

I am not sure if the problem occur during the first render of the component or if it is during the rerender, but the effect result is the following DOM tree:

![image](https://user-images.githubusercontent.com/32170099/115883671-6c702980-a424-11eb-841c-8b1721fd5242.png)

![duplicated-canvas-within-scene](https://user-images.githubusercontent.com/32170099/115885574-785ceb00-a426-11eb-9163-86f61f6a9a3d.gif)

The error is not repetitive, and I still didn't figure out the exact conditions reproduce it. Is there something I could do about it?

Im using plotly.js ^1.58.4, with react-plotly.js ^2.5.1, to render a scatter3d plot that

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
