### ISSUE TITLE
Feature request: Allow groupby nameformats to reference trace properties other than 'name'

### ISSUE THREAD

**Issue by devonbush** [plotly/plotly.js#5612]
We are using groupby transformations on scatter plots, and would like to have legend entries of the form '[[name]] ([[X]] points)', where [[name]] is the string from the 'groups' attribute, and X is the count of values in the group.  So e.g. "group A (3500 points)".  We could (and currently do) accomplish this by specifying each name manually in the transform.styles property, but our plots can be large (>1MM points), and so I'd rather avoid the overhead and complexity of having to also count group memberships ourselves. 

It looks like the limiting factor is lines 204-207 of [groupby.js](https://github.com/plotly/plotly.js/blob/32d46313a6c7dcdd46ebb608f7a18ce70201645a/src/transforms/groupby.js#L204), where only `trace.name` is passed into `Lib.templateString`.  If the whole trace was also passed in as, e.g., 'traceObj', then I could accomplish what I want by using a `nameformat` of `"%{trace} (%{traceObj.x.length})"`.    The method might have to get reordered somewhat to make this possible, since the trace isn't fully created yet on line 204.   Also, it would be kind of odd to have both 'trace' and 'traceObj' passed, but that seems like the only way to avoid breaking existing nameformats that use the 'trace' property (and any better naming suggestions would be most welcome!). 

I'm happy to attempt to develop and submit the PR for this myself if there's agreement that this is a desirable feature.    Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
