### ISSUE TITLE
Draggable x and y axis lines with axis points(axis ticks)

### ISSUE THREAD

**Issue by pavananand** [plotly/plotly.js#5617]
Hello All,

I was trying to add draggable axis lines and axis points on the Plotly graph. I can drag the axis line but not able to drag the axis points present on the axis lines(x-axis and y-axis). Please help me with this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
