### ISSUE TITLE
Glitches on scroll zoom when displaying (fast) real time data

### ISSUE THREAD

**Issue by federicomassa** [plotly/plotly.js#5631]
I'm using plotly.js for a real time data monitoring application. While using "scroll zoom" on a fast refreshing plot (~25 Hz), the zoom becomes very glitchy. Try this out: https://codepen.io/federicomassa/pen/rNyBRzQ.
Any ideas? Thanks!

**Comment by federicomassa** [comment]
Update: I fixed it manually by not using plotly's scrollZoom functionality and changing the layout x/y axis range on mouse wheel: https://codepen.io/federicomassa/pen/oNZvRwM

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
