### ISSUE TITLE
Scroll-zoom on macOS Safari 14.1 doesn't work anymore

### ISSUE THREAD

**Issue by giorgiomarcias** [plotly/plotly.js#5640]
Hi, from Safari 14.1 (on macOS) the scroll-zoom option (`{ scrollZoom: true }`) doesn't work anymore. It does work on Firefox, though, thus I suppose it's related to some change on the Safari API, maybe?

See https://plotly.com/javascript/configuration-options/#scroll-and-zoom.

**Comment by nicolaskruchten** [comment]
Possibly related: https://github.com/plotly/plotly.js/issues/5551

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
