### ISSUE TITLE
two traces are not sharing the same yaxis(y2) 

### ISSUE THREAD

**Issue by rhb57438** [plotly/plotly.js#5672]
Here is the link of the example:

https://codepen.io/fyx78329/pen/KKWNyWo

Issue1: 
I set yaxis 2 has the "range": [0,279]
But the input/output area charts are shown in very lower place.

Issue2:
When we disable percentage trace by clicking the legend, and click autoscale icon , we can see input & output are not sharing the same yaxis2.

**Comment by alexcjohnson** [comment]
yaxis2 has `type: 'category'` - was that intentional? If I remove that, I think this graph behaves as you would expect.

**Comment by rhb57438** [comment]
Thanks. I am using some contructor to build data & layout.

There is no defination on yaxis type on  myConfigStr 
But after JSON.Parse, ```type: 'category'```  is added.
```
        console.log('b4 JSON Parse',myConfigStr)       << Not include any type setting for yaxis2
        myNewConfig = JSON.parse(myConfigStr);
        console.log('after JSON Parse',newConfig)      << found ```type: 'category'```  is added, sometime, ```type: 'linear'```  is added, looks like it depends on my data. 
```

Then just found type: 'category'

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
