### ISSUE TITLE
tickformat not accept multiple new line?

### ISSUE THREAD

**Issue by rhb57438** [plotly/plotly.js#5689]
`xaxis: {
      tickformat: '%m-%d \n NewLine \n NewLineAgain' // `

second(or more) new line is not working

**Comment by nicolaskruchten** [comment]
The correct syntax is `<br>` I believe instead of `\n`.

**Comment by rhb57438** [comment]
OK, thank you. @nicolaskruchten    <br> works.
I was referring  https://plotly.com/javascript/tick-formatting/
And I saw there is an example using \n.

**Comment by alexcjohnson** [comment]
This is indeed confusing and AFAICT undocumented: Date axis ticks have special handling of a single `\n` character: They will split the label there, and if the second part matches the second part of the previous tick we drop it. That's how you get ticks like:
```
Jan    July   Jan    July   Jan    July
2010          2011          2012
```

Feels to me like (a) we should document this behavior, and (b) we may want to generalize it: do the same with `<br>`, and possibly treat `\n` and `<br>` the same in all text.
On the other hand I suppose if people DON'T want this automatic pruning of date labels, the `\n`/`<br>` distinction gives them a way to opt out of it. That's a pretty abstruse feature though...

**Comment by alexcjohnson** [comment]
FWIW this special handling is here:

https://github.com/plotly/plotly.js/blob/4759b7e6dfda3aae1d7246b67bed5ed942fa5a49/src/plots/cartesian/axes.js#L1425

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
