### ISSUE TITLE
Surface plots opacity less one do not color correctly for negative x and y camera positions.

### ISSUE THREAD

**Issue by GriffinHatchery** [plotly/plotly.js#5699]
To illustrate the issue here is a copy of the code pen from https://plotly.com/javascript/3d-surface-plots/ with the cameras position changed:
https://codepen.io/suin3g/pen/PopEdXg
Now here is the same code but with the opacity set to 0.999. Pay special attention to the tall peak.
https://codepen.io/suin3g/pen/xxqpyxW
The expectation is that the two graphs would look almost identical (0.999 being really close to 1). Instead the surfaces with the most positive x and y values are shown on top of the surfaces that are nearer.  If you rotate the figure back to the positive quadrant for x and y it works as expected.

**Comment by Apivan** [comment]
I experienced this issue too.  Adding opacity to this surface shape from https://plotly.com/javascript/3d-surface-lighting/, the bug is more noticeable.  

![image](https://user-images.githubusercontent.com/8325019/120430609-767d3480-c3a1-11eb-9d76-b2e964995796.png)


I think these links explain the problem.
https://stackoverflow.com/questions/4305911/opengl-depth-sorting 
https://blender.stackexchange.com/questions/182646/odd-transparency-or-normal-issues

**Comment by suin3g** [comment]
If that is the case a simple depth sort should fix 95% of the issue for surface plots. The only time depth sorting should have strange behavior, if I understand right, is when the depth order of the triangles is not easily defined, (for example when the triangles intersect each other). A surface plot should not usually have intersecting triangles.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
