### ISSUE TITLE
[Feature, Prototype, Code] Word-wrap for the Axis Title

### ISSUE THREAD

**Issue by m-podlesny** [plotly/plotly.js#5700]
There are already ongoing discussions about related topic: 
https://github.com/plotly/plotly.js/issues/2053 and https://github.com/plotly/plotly.js/issues/382
First one stays open since 2017. Second - since 2016.

While we are waiting for the **Unification of text rendering and wrapping**, maybe it's worth to update `convertToTspans()` and `buildSVGText()` functions a bit, to have the text wrapping for the axes titles working.

### Prototype solution
It needs improvements and some testing.
Proposed API:
```ts
layout.xaxis.title.wrap?: boolean
layout.yaxis.title.wrap?: boolean
```
If `true` - it's going to work like a `word-break`.
Default: `undefined`.

Here you are the code comparison: https://github.com/plotly/plotly.js/compare/master...m-podlesny:master

Localhost test for a simple string:
```js
str = 'Lorem Ipsum is simply dummy text of the printing and typesetting.';
```

![image](https://user-images.githubusercontent.com/17722512/120333730-47f35100-c2f0-11eb-9fff-5cd692e12433.png)

ToDo: Improve the word wrapping if the string has `<br />`.
```js
str = 'First line.<br />Second line that is very loooong.';
str = 'First line that is very loooong.<br />Second line.';
```
Let me know if it's worth to continue this way.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
