### ISSUE TITLE
Uncaught TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by vinnitu** [plotly/plotly.js#5714]
import Plotly from 'plotly.js-dist';

Uncaught TypeError: Cannot read property 'document' of undefined

How to handle it?

**Comment by vinnitu** [comment]
trying use plotly with vue3 (+vite)

npm install plotly.js -S

**Comment by nicolaskruchten** [comment]
if you're importing from `plotly.js-dist` you'll likely need to `npm install plotly.js-dist` rather than `npm install plotly.js` :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
