### ISSUE TITLE
Scatter3D WebGL maximum portability warnings

### ISSUE THREAD

**Issue by jxu** [plotly/plotly.js#5720]
Example: Open console in Firefox 86 from https://plotly.com/javascript/3d-scatter-plots/

I get many warnings: 

     WebGL warning: checkFramebufferStatus: Using format enabled by implicitly enabled extension: WEBGL_color_buffer_float. For maximal portability enable it explicitly.

Is there a way to hide this warning? I didn't see any in plotly docs.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
