### ISSUE TITLE
Filled area plots ignore NaNs

### ISSUE THREAD

**Issue by sergiykhan** [plotly/plotly.js#5722]
Filled area plots do not show gaps for NaNs.

## Example 1
```
import plotly.graph_objects as go
fig = go.Figure()
fig.add_scatter( x=[0,1,2,3,4], y=[10,10,None,10,10],
    fill='tozeroy',
)
fig.show()
```
![1](https://user-images.githubusercontent.com/25179211/121412879-8796ea00-c93b-11eb-8e18-094d9f5d0653.png)

## Example 2
```
import plotly.graph_objects as go
fig = go.Figure()
fig.add_scatter( x=[0,1,2,3,4], y=[10,10,None,10,10],
    stackgroup='one',
)
fig.show()
```
![2](https://user-images.githubusercontent.com/25179211/121412911-8ebdf800-c93b-11eb-9a0d-044b615da958.png)

**Comment by Irantwomiles** [comment]
I'm having the same issue. I can't get the lines to draw where a NaN is between the two points. Did you buy chance find a way around this?

**Comment by sergiykhan** [comment]
I think I ended up using `px.area`
```
fig = px.area(
    x=[0,1,2,3,4],
    y=[10,10,None,10,10],
)
fig.update_traces(
    line_shape='hv',
    line_width=0,
)
fig.show()
```

![newplot](https://user-images.githubusercontent.com/25179211/212964805-8fff469e-a33a-4c4b-9886-11e03ada2ff3.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
