### ISSUE TITLE
Rollup tree shaking not working

### ISSUE THREAD

**Issue by gavinr** [plotly/plotly.js#5723]
When using just a small portion of Plotly.js API, Rollup should use tree shaking to reduce the bundle size, correct? When I run Rollup, it just includes the entire contents of `node_modules\plotly.js-dist-min\plotly.min.js`

## Reproducible test case:

```
mkdir plotly-rollup-testing-2
cd plotly-rollup-testing-2
npm init -y

npm install rollup --save-dev
npm install @rollup/plugin-node-resolve --save-dev
npm install @rollup/plugin-commonjs --save-dev

npm i --save plotly.js-dist-min
```

create file `rollup.config.js`:

```
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";

export default {
  input: "main.js",
  output: {
    file: "bundle.js",
    format: "iife",
  },
  plugins: [nodeResolve(), commonjs()],
};

```

create file `main.js`:

```
import Plotly from "plotly.js-dist-min";

var trace1 = {
  x: [1, 2, 3, 4],
  y: [10, 15, 13, 17],
  mode: "markers",
  type: "scatter",
};

var trace2 = {
  x: [2, 3, 4, 5],
  y: [16, 5, 11, 9],
  mode: "lines",
  type: "scatter",
};

var trace3 = {
  x: [1, 2, 3, 4],
  y: [12, 9, 15, 12],
  mode: "lines+markers",
  type: "scatter",
};

var data = [trace1, trace2, trace3];

Plotly.newPlot(domNode, data);
```

Run:

```
.\node_modules\.bin\rollup -c rollup.config.js
```

- **Expected**: `bundle.js` output file should be very small (< 1MB)
- **Actual**: `bundle.js` output file is very large (~3.4 MB) - basically the same size as `node_modules\plotly.js-dist-min\plotly.min.js`

**Comment by nicolaskruchten** [comment]
This is probably more of a Rollup issue than a Plotly.js issue to be honest... Maybe you can try the same thing on the `plotly.js` module instead of `plotly.js-dist-min`, to see of Rollup has any better results?

The alternative would be to use [our built-in custom-bundle generator](https://github.com/plotly/plotly.js/blob/master/CUSTOM_BUNDLE.md) to build the bundle you need (i.e. one with just `scatter` traces) or to use our smallest [officially-distributed partial bundle](https://github.com/plotly/plotly.js/tree/master/dist) (`basic`) which weighs in at 1 meg unzipped...

**Comment by gavinr** [comment]
Thank you for your prompt response - I really appreciate it.

I did a quick try to use `npm install plotly.js` instead - if I add a few more rollup plugins, it runs without error but I'm not sure it's creating a valid bundle. Will have to do some more investigation.

```
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import json from '@rollup/plugin-json';
import { terser } from "rollup-plugin-terser";

export default {
  input: "main.js",
  output: {
    file: "bundle.js",
    format: "iife",
  },
  plugins: [json(), nodeResolve(), commonjs(), terser()],
};
```

Thanks for the link to the bundle generator. 

If anyone else has figured out how to properly build with Rollup, would love to hear

**Comment by keul** [comment]
I tried the same today using vite (which automatically used compression and three-shaking), but I've a similar result of the author of this issue. I also tried with terser.
My output chunk is still 3.5+ Mb

I know there's a custom build system, but this is not always the easiest option. With (very) older version of Plotly I was able to load required features one by one, but now this seems disappeared from the documentation.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by MrEarle** [comment]
I think this is still a concern. If we need plots from two different partial bundles, we either need to install both bundles, install the full plotly bundle or create a custom bundle. Having it so that we can only include specific plots would definitely be a huge improvement for the use of plotly.

**Comment by gvwilson** [comment]
Thaks @MrEarle - would you be willing/able to help us build a solution? (We're hoping to release plotly.js 3.0 this week, and then focus on process/build improvements for 3.1, so it would be very timely.) thanks - @gvwilson

**Comment by ignatz** [comment]
Very sorry to ping such an old closed bug (happy to open a new one). Empirically and after skimming the changelog as well as open issues, plotly still doesn't seem very shakeable. Is there any update or other issue I could follow? 🙏
