### ISSUE TITLE
Unwanted lines appear on ultra-zoomed line charts in FF

### ISSUE THREAD

**Issue by dineshu07** [plotly/plotly.js#573]
when i zoom i can see extra lines in line chart. 
initial chart looks like this 
![newplot 1](https://cloud.githubusercontent.com/assets/13025236/15604327/6a2af72c-241d-11e6-9d9c-3bbf1773fcce.png)

![newplot](https://cloud.githubusercontent.com/assets/13025236/15604242/edb71ce8-241c-11e6-80cc-c07ff8d1e92f.png).
after zooming it looks like the above image
 I’m i wrong? or did i misunderstand anything? can any one tell me please?

**Comment by etpinard** [comment]
Yikes. Thanks for reporting.

Can you share a reproducible code snippet to help us debug?

**Comment by dineshu07** [comment]
Thanks for quick response. strange problem. here is my code pen [http://codepen.io/plotly/pen/oXmJoz](url) . now i tested on windows pc with chrome, ff. i'm not able to reproduce it. but when i open it in ubuntu ff , chrome i can see the above problem. you can reproduce this problem on ubuntu firefox.

**Comment by etpinard** [comment]
Thank you very much for this bug report.

With http://codepen.io/etpinard/pen/GqRpEO the bug is noticeable in `Mozilla Firefox 46.0.1` but not in `Google Chrome 51.0.2704.63` on Ubuntu 16.04.

**Comment by dineshu07** [comment]
Is there any fix for this ?

**Comment by mdtusz** [comment]
Working fine in both `Google Chrome 51.0.2704.63` and `Mozilla Firefox 46.0.1` on OSX 10.10.5.

**Comment by alexcjohnson** [comment]
A quick check on Browserstack shows:
- on win 7+ this fails with FF 51 and below but was fixed in FF 52.
- on win XP the latest FF (49) does not show the bug.
- on various mac OS's all FF versions seem OK.

Debugging in FF is nearly impossible for our code, for some reason (really hoping Quantum fixes this)... @etpinard or @dineshu07 can you confirm that in recent linux FF versions this is fixed? And if so can we close this issue?

**Comment by etpinard** [comment]
Not noticeable for me on FF55 on Ubuntu 16.04.

**Comment by alexcjohnson** [comment]
> Not noticeable for me on FF55 on Ubuntu 16.04.

Great - I'm going to close then, as "fixed by Firefox."
