### ISSUE TITLE
Annotation Font size overwritten by css when html is added

### ISSUE THREAD

**Issue by maximilian0311** [plotly/plotly.js#5735]
Hi,
I think I found a bug which cost me like forever to find and I hope it can be fixed or at least this helps others.

I did the following:
1. Have a css class called "line" which defines a font-size in the project
2. Create a plotly chart with an annotation in it
3. As soon as e.g. "br" is added to the annotation the font size is no longer defined by plotly but by the css class "line"

https://codepen.io/maximilian0311/pen/poeGQxx?editors=1111

I don't have a problem anymore in my project because I renamed the "line" class and everything is fine, but I think it is worth mentioning for others

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
