### ISSUE TITLE
box plot gives wrong number？

### ISSUE THREAD

**Issue by dongxiaotian** [plotly/plotly.js#5736]
I am using plotly's box plot, however the upper fence and lower fence seems not right.

the Q3 = 8, Q1 = 3, IQR = Q3-Q1 = 8-3 =5
then upper fence = Q3+1.5\*IQR = 8+1.5\*5 = 15.5, while the plot shows 10?
is there anything wrong?
the code belows:

import plotly.express as px
px.box([-20,1,2,3,4,5,5,5,6,7,8,9,10,20])

![image](https://user-images.githubusercontent.com/12750937/122351930-390fce00-cf81-11eb-926c-8e16bed65ed1.png)

**Comment by nicolaskruchten** [comment]
@archmoj @alexcjohnson do you see anything here?

**Comment by alexcjohnson** [comment]
What we display as the upper or lower fence is actually the last data point within 1.5 IQR past the quartile. So the upper fence could have been as high as 15.5 but since there are no data values between 10 and 20 it gets pushed down to 10.

Some packages do it this way, some use a fixed 1.5 IQR; what I like about this way is that it gives you extra information about where there actually are data points in the distribution (you know there's one exactly at the fence value), which then allows you to see more clearly the gap to the outliers. The disadvantage is you don't see precisely "beyond this point we mark points as outliers."

**Comment by nicolaskruchten** [comment]
Ah right. We gotta update the docs to that effect!

**Comment by dongxiaotian** [comment]
> What we display as the upper or lower fence is actually the last data point within 1.5 IQR past the quartile. So the upper fence could have been as high as 15.5 but since there are no data values between 10 and 20 it gets pushed down to 10.
> 
> Some packages do it this way, some use a fixed 1.5 IQR; what I like about this way is that it gives you extra information about where there actually are data points in the distribution (you know there's one exactly at the fence value), which then allows you to see more clearly the gap to the outliers. The disadvantage is you don't see precisely "beyond this point we mark points as outliers."


that's very helpful, now i understand the detail of box plot, great thanks!
