### ISSUE TITLE
Document hovertext default behavior

### ISSUE THREAD

**Issue by jxu** [plotly/plotly.js#5749]
It appears hovertext default of empty string makes hovertext take on the value of text. However if it is not an empty string then it uses the value given. This is not documented at https://plotly.com/javascript/reference/#scatter-hovertext

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
