### ISSUE TITLE
Plotlyjs  Treemap chart is not rendering

### ISSUE THREAD

**Issue by mannkumar19** [plotly/plotly.js#5756]
I am trying to create Treemap chart using below link 

[Plotly Treemap][1]

  [1]: https://plotly.com/javascript/treemaps/

Now I am trying to generate Treemap which shows revenue for same companies in different years

index.js:

        data = [{
          type: "treemap",
          labels: ["company 1","company 2","company 3","company 1","company 2","company 3"],
          parents: ["2017","2017","2017","2018","2018","2018"],
          values: [15,20,30,23,45,56]
       }]
    
       Plotly.newPlot('myDiv', data)

Index.html

    <head>
    	
    	<script src='https://cdn.plot.ly/plotly-2.1.0.min.js'></script>
    </head>
    <body>
    	<div id='myDiv'></div>
    </body>

But it is not rendering any chart. Please suggest if i am making any mistake in constructing data

**Comment by mannkumar19** [comment]
Please suggest on this team

**Comment by mandy6610** [comment]
maybe you can try this

 data = [{
      type: "treemap",
      labels: ["2017company1","2017company2","2017company3","company1","company2","company3","2017","2018"],
   text:["company1","company2","company3","company1","company2","company3","2017","2018"],
   
      parents: ["2017","2017","2017","2018","2018","2018","",""],
      values: [15,20,30,23,45,56,0,0],
      texttemplate:'%{text}'
   }]

   Plotly.newPlot('myDiv', data)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
