### ISSUE TITLE
Investigate fixing scroll zoom handler after switching to more recent d3-geo

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5787]
OK, I guess this makes sense. The map is still in a somewhat broken state at that point: if you scroll-zoom until you can see the map appear from above, you can drag it up and down but not left/right. If you then (or instead) use the zoom out button, now you can drag left/right. Can we detect and fix this in the scroll zoom handler perhaps?

_Originally posted by @alexcjohnson in https://github.com/plotly/plotly.js/pull/5112#discussion_r638112695_

**Comment by archmoj** [comment]
In respect to above comment, this particular case used to lead to NaN map bounds which would be no longer the case after merging #5112.
```js
        Plotly.newPlot(gd, [{
            type: 'scattergeo',
            lon: [0],
            lat: [0]
        }], {
            geo: {
                projection: {
                    type: 'kavrayskiy7',
                    rotation: {
                        lat: 38.794799,
                        lon: -81.622334,
                    }
                },
                center: {
                    lat: -81
                },
                lataxis: {
                    range: [38.794799, 45.122292]
                },
                lonaxis: {
                    range: [-82.904731, -81.622334]
                }
            },
            width: 700,
            heigth: 500
        })
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
