### ISSUE TITLE
Legend line spacing of graph with hidden legend in a legend group is too big

### ISSUE THREAD

**Issue by gilles-crealp** [plotly/plotly.js#5795]
I understand that legend group (`legendgroup`) trigger a bigger line spacing (in vertical or horizontal mode) to be able to distinguish group from the list (1<sup>st</sup> screenshot) but when you set a group to have only one legend (by hidding other legends, `showlegend = false`, 2<sup>nd</sup> screenshot) the result sould not have a bigger line spacing (should be like 3<sup>rd</sup> screenshot).

![newplot 1](https://user-images.githubusercontent.com/29562925/124237155-83638400-db17-11eb-93d1-5ba76b742b83.png)
![newplot 2](https://user-images.githubusercontent.com/29562925/124237162-852d4780-db17-11eb-9784-6bb9c21d2765.png)
![newplot 3](https://user-images.githubusercontent.com/29562925/124237171-878fa180-db17-11eb-9ea5-ff54ffc76079.png)

https://jsfiddle.net/m8zf7pvr/

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
