### ISSUE TITLE
Tooltip/Description for legends added in a plot

### ISSUE THREAD

**Issue by Chirag-Khanna** [plotly/plotly.js#5798]
With extensive usage of plots in one of our applications, we have come across use-cases wherein providing extra information (description) for the legends is a must. One of the UX pattern to fulfill this requirement is to use tooltips. 

Can we enhance the charts to have tooltips over the legends for all traces types in the manner below

![image](https://user-images.githubusercontent.com/33049290/124444895-aeaad500-dd9c-11eb-99b0-f897a52f0c7f.png)

Done a POC and seems we can achieve this. What are your suggestions?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
