### ISSUE TITLE
Double click on legend doesn't work properly with 2 pie chart displayed at different times

### ISSUE THREAD

**Issue by Heexos** [plotly/plotly.js#5799]
Hi,
I got 2 pie chart that has some shared data. I display one or the other with buttons. When the second one is displayed, double clicking on the legend don't work and `hiddenlabels` take the value `[undefined]`
Here is a working exemple of the issue : https://codepen.io/heexos/pen/Pomwmbq

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
