### ISSUE TITLE
Range Slider - Slider handles gets overlapped by the plot lines

### ISSUE THREAD

**Issue by shehan-mark** [plotly/plotly.js#5800]
Overall this is a good library. This have been most useful to me and my team. Recently I found a bug where the range slider handles gets overlapped by the plot representation when a re-render has happened on a chart with multiple Y axis. This become a huge issue when the range slider is filled with multiple plot representations. Like 5 or more.

I have created a detailed issue regarding this here - https://github.com/plotly/react-plotly.js/issues/249

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
