### ISSUE TITLE
How can implement strip plotly chart with facet 

### ISSUE THREAD

**Issue by jitendraP-ashutec** [plotly/plotly.js#5809]
can we create [this](https://plotly.com/python/strip-charts/#strip-charts-with-plotly-express) kind of chart with plotlyJS?
I want to create a chart using facets in plotlyJS like they have created using plotly express? Is there is example exist?

**Comment by rheinheimer** [comment]
Second this! The current JS subplots don't appear to do true faceting. The Python version is great. I'll investigate, but will probably end up rolling my own, since I don't think it would be too hard to simply create a wrapper to parse out data (via React...)

**Comment by rheinheimer** [comment]
I second this! Having such an ability, as in Python (https://plotly.com/python/facet-plots/) would be super helpful for more useful data analytics. I'll investigate a little but in the meantime probably roll my own, sans nice integration as in the Python version.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
