### ISSUE TITLE
[BUG] updating layout of 3d plot throws error

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#5811]
When using 3d plot , Function [Plotly.relayout]( https://plotly.com/javascript/plotlyjs-function-reference/#plotlyrelayout) throws error if we update layout for 2D proeprties.
```js
// this will throw following error becuase it is update for a 2D graph while graph is 3D at the moment
Plotly.relayout(graphDiv, {
    'xaxis.range': [0, 5]  // off course it should be 'scene.xaxis.range': [0, 5]  becuase its 3d chart
});
```

**Error:**
```Uncaught TypeError: Cannot read property '_inputDomain' of undefined```
          
**Solution** 
Pleaase update this line so that 
instead of 
```js
if(axFull._inputDomain) {
                // if we're autoranging and this axis has a constrained domain,
                // reset it so we don't get locked into a shrunken size
                axFull._input.domain = axFull._inputDomain.slice();
}
```

it should be 
 ```if(axFull && axFull._inputDomain) {```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
