### ISSUE TITLE
Wind Rose not showing some ModBar buttons

### ISSUE THREAD

**Issue by StephaneAdeso** [plotly/plotly.js#5812]
I am using the [wind rose graph](https://plotly.com/javascript/wind-rose-charts/).
From what I have read, it is normal that some graphs do not have all the buttons. 

But what I don't understand is that if you can zoom in and out on the wind rose graph, why the Zoom in, Zoom out, AutoScale and Reset Axes buttons don't come out?
 Is there a way to show those buttons? 
Because in the documentation I have not found anything about it.

![image](https://user-images.githubusercontent.com/55595063/124892619-4ea17200-dfda-11eb-852e-5b1cca80ea46.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
