### ISSUE TITLE
Plotly will overlap lines when zoom if working with Sizzle

### ISSUE THREAD

**Issue by CraigMeng** [plotly/plotly.js#5821]
minimum reproducible codes here:
[codepen](https://codepen.io/CraigXue/pen/jOmVdPG)

if you use mouse to zoom the line chart, you will see there will always be a line right in the middle of graph.
This bug will happen only when:

1. there is Sizzle available in WIndow
2. the data includes null value

**Comment by CraigMeng** [comment]
Update: It is due to D3 will use Sizzle as selection engine. We switched type: scatter to type: scattergl, this problem is resolved.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
