### ISSUE TITLE
Circular Flows in Sankey plot

### ISSUE THREAD

**Issue by ese-jdm418** [plotly/plotly.js#5829]
Hi everyone,

I am wanting to use plotly sankey to be able to visulise stocks and flows data. However, I would like to have nodes that can flow into themselves. Is this possible?

I have attached a crudely annotated picture of what I would like to do and the code I have used. Any help would be very greatly appreciated.

![Plotly Sankey](https://user-images.githubusercontent.com/57348351/125988965-dfa2f9b6-ae64-4a8a-8f67-eacee4d68828.png)

Code:

fig = go.Figure(go.Sankey(
    arrangement = "freeform",
    node = {
        "label": labels,
        'pad':40,
        "color": ['rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)', 'rgb(0, 0, 255)'],
        },

    link = dict(
      source = source_array,
      target = target_array, 
      value = value_array,
      color = colour_value,
      label = name_array
  )))

John.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
