### ISSUE TITLE
Snowpack and plotly

### ISSUE THREAD

**Issue by pmkroeker** [plotly/plotly.js#5840]
I have created a [discussion in snowpack](https://github.com/snowpackjs/snowpack/discussions/3596), but I figured I would ask here as well.

Has anyone had success in using plotly with snowpack? I'm getting errors when trying to run in dev mode as it says some files are missing.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
