### ISSUE TITLE
Heatmap legend layout breaks on Safari under specific circumstances

### ISSUE THREAD

**Issue by JobLeonard** [plotly/plotly.js#5847]
Steps to reproduce:

- have a heatmap with a few `null` values 
- set a custom `tickvals` and `ticktext` array for the legend

Broken heatmap legend:
https://codepen.io/JobLeonard/pen/XWRaarG
![image](https://user-images.githubusercontent.com/259840/126520687-750ba439-f858-40fc-bbc9-20175d5d740a.png)

Working heatmap legend:
https://codepen.io/JobLeonard/pen/oNWGXop
![image](https://user-images.githubusercontent.com/259840/126520559-58b04fb1-6cb2-422b-8a20-f2bdba28300e.png)

It works fine in every other browser/platform that I've tested this on.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by JobLeonard** [comment]
I can confirm that this is no longer a concern for us because we moved away from using Plotly after we decided that working around this and other bugs was not worth the hassle.

As for whether the bug is still valid, I linked two codepens above, one with a minimal repro of the bug, and one with a slight variation that doesn't break to make it easier for whomever decides to debug this to figure out what causes the breakage. Opening these links with any modern Safari browser will demonstrate that the bug does indeed still exist. I leave the decision of whether that means this bug should remain closed or not up to you.
