### ISSUE TITLE
ggplot2 stacked barplot, reorder its y-variables...different output when using ggplot and ggplotly

### ISSUE THREAD

**Issue by tanthiamhuat** [plotly/plotly.js#5850]
Please see the link here:
https://community.rstudio.com/t/ggplot2-stacked-barplot-reorder-its-y-variables/110591/6

Data is available for download here for reproducible output:
https://extendsclass.com/csv-editor.html#bf64de4

Code is available here:
`OEE_Outputs_ByLine_Daily$Metrics <- as.factor(OEE_Outputs_ByLine_Daily$Metrics)
OEE_Outputs_ByLine_Daily$Metrics2 <- relevel(OEE_Outputs_ByLine_Daily$Metrics,'OEE')

  g <- ggplot(OEE_Outputs_ByLine_Daily, 
              aes(fill=Metrics2, y=Percent, x=Date)) +
    geom_bar(position="stack", stat="identity") +
    geom_col(position = position_stack(reverse = TRUE)) +
    facet_wrap(~Line, strip.position = "bottom") +
       labs(title="Different Metrics (%) vs Date",x="",y="")
  ggplotly(g)`

You can see here, if we plot g alone from ggplot, there is no issue on Line 1. 
![image](https://user-images.githubusercontent.com/9988941/126595032-0fa68eb7-4ba4-4c36-82e5-9a2c500ff309.png)

However, when using ggplotly(g), Line 1 shows the issue that its OEE does not start from 0%.
![image](https://user-images.githubusercontent.com/9988941/126594964-73cb866a-47ff-4a7f-ada4-acd6b576b5cb.png)

I hope I am clear in explaining the issue.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
