### ISSUE TITLE
Add touch support to sliders

### ISSUE THREAD

**Issue by keul** [plotly/plotly.js#5855]
Related to #1098.

Workaround described in the related issue and fixed in https://github.com/plotly/plotly.js/pull/5025 can also be applied to the slider component. Right now it's not possible to drag&drop the slider using a touch device.

See https://xf4qe.csb.app/ for an example: using a smartphone it's not possible to drag&drop the slider. Just click works.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
