### ISSUE TITLE
ModeBar Cartesian missing

### ISSUE THREAD

**Issue by LukasHoettecke** [plotly/plotly.js#5866]
The cartesian ModeBar options have been in the default settings till plotly.js 1.58. In the newest version, they are removed from default and cannot be added any more. Howver, they are descripted in the documentation (https://plotly.com/javascript/configuration-options/).

var trace1 = {
  x: [0, 1, 2, 3, 4, 5, 6],
  y: [1, 9, 4, 7, 5, 2, 4],
  mode: 'lines+markers',
  type: 'scatter'
};
var trace2 = {
  x: [0, 1, 2, 3, 4, 5, 6],
  y: [2, 10, 5, 17, 15, 12, 14],
  mode: 'lines+markers',
  type: 'scatter'
};

var data = [trace1,trace2];

Plotly.newPlot('myDiv', data,{modeBarButtonsToAdd: ['hoverCompareCartesian']});

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
