### ISSUE TITLE
Allow custom percentiles in box plots

### ISSUE THREAD

**Issue by ClementFeltin** [plotly/plotly.js#5867]
Hello !
Current box plots make use of computed q1 median and q3, but I am interested in replacing q1 (quantile 25%) and q3 (quantile 75%) with another 2-tuple of quantiles (possibly 5% and 95%), or even better : a 2n-tuple of quantiles (e.g. 5% 10%, 90% 95%).
Thanks :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
