### ISSUE TITLE
Scattergl freezes on hover when y values have lots of zeros

### ISSUE THREAD

**Issue by karosc** [plotly/plotly.js#5881]
I recently noticed that the scattergl trace freezes and gets very slow when hovering over traces with lots of consecutive zero values. You can mitigate the issue by either:
1. zooming in on small area to show only a portion of the data,
2. downgrading to plotly.js v2.0.0-rc.1 or earlier, or
3. not including so many consecutive zeros

I am more of a dash user than plotly.js and posted about this issue [over there](https://github.com/plotly/plotly.js/issues/6792), but when I discovered this issue crops up only when using versions of plotly.js after plotly.js v2.0.0-rc.1, I figured I post here. 

I am not good enough of a js developer to track down the commit that might be causing this slowdown and for now I am going to stick to plotly.js 1.58.4 if I need to use scattergl. Nevertheless, I was able to pull together a [codepen example to reproduce the behavior](https://codepen.io/karosc/pen/ZEKqmOK).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
