### ISSUE TITLE
3D Chart Axes

### ISSUE THREAD

**Issue by Kevin-Rush** [plotly/plotly.js#5887]
Hello Plotly.js and Github community,

I am currently writing a project using Plotly and I need to display data points in 3D. I am currently using scatter3d but the display always shows the point within the 3D cube. For my purposes I was hoping to display the data points in relation to a centralized axis instead of within the 3 walls of the cube. Currently I am displaying 3 lines (x, y, and z) within the 3D space but this causes the 3 lines to appear in the legend. 

Is there a feature to Plotly to display the axes within the 3D space for scatter3d? If not is there an alternative that would better suit my needs.

Hoping to hear back soon.

Kevin Rush

**Comment by jxu** [comment]
turn off grid lines?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
