### ISSUE TITLE
Add drawing 3D arrows

### ISSUE THREAD

**Issue by jxu** [plotly/plotly.js#5891]
The current workaround in 3D is to use a line and then a cone for the arrow head https://stackoverflow.com/a/63316665

It should be possible to draw a 2D triangle directly onto the OpenGL view?

**Comment by th0ger** [comment]
A suggestion would be to render the cone as a reduced cone + cylinder.
We would need two new parameters, something like (details up to you):
- Cylinder length, relative to the total length (of the original cone).
- Cylinder width, releative to to the width (of the original cone).

![image](https://github.com/plotly/plotly.js/assets/26322144/5392a75a-ec49-48b9-b49f-edc3f3bcc884)

Then we could render:
- Cone: `cylinder_length=0, cylinder_width=0` (default)
- Arrow: `cylinder_length=0.5, cylinder_width=0.25`
- Line:  `cylinder_length=1.0, cylinder_width=0.1`
 
The total length of the shape would be unchanged, and determined by current logic for cone size.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
