### ISSUE TITLE
Histogram display ranges on x-axis.

### ISSUE THREAD

**Issue by erick-umc** [plotly/plotly.js#5893]
Hi, 

I'm creating a histogram using the nbinx property to set the number of bins. Instead of displaying the ranges when I hover a specific bar, I would like to display them on the x-axis, like this: 

![histogram-example-1 1](https://user-images.githubusercontent.com/62611550/129604136-f3bf7f38-2737-4d16-9815-f928f5e77483.jpg)

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
