### ISSUE TITLE
Further reduce the number of `noCI` tests by installing the required fonts and adjust the tests

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5923]
We did reduce the number of `noCI` test when compared to pre-v2 era.
I hope in near future we could spend some time to bring that down to zero. 
This is I think possible by ensuring the needed fonts installed in the jasmine containers.
So if you don't mind I keep this flag and instead open an issue to track it?

_Originally posted by @archmoj in https://github.com/plotly/plotly.js/pull/5922#discussion_r702127826_

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
