### ISSUE TITLE
Cannot scroll down the chart legend by the mouse wheel scroll.

### ISSUE THREAD

**Issue by kei51e** [plotly/plotly.js#5926]
I cannot scroll down the chart legend by the mouse wheel scroll. It works on Chrome. 

I use Safari on Intel Mac, Version 14.1.1 (16611.2.7.1.4). You can reproduce it on the following pen.

https://codepen.io/kei51/pen/BaZQwQG

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
