### ISSUE TITLE
parcoords Select, hover and click on a single line

### ISSUE THREAD

**Issue by EsamAhmed77** [plotly/plotly.js#5932]
I have ran in an issue with **React-plotly** where I want to **select** or hover on click on a single line in the **parcoords** and then i get the data or make some changes to a single line like change color onHover and so on  but the problem is that the event handlers doesn't work properly and some of them doesn't work at all for example the onHover event work just when I hover in the blank bottom area and the onUnhover as well, the onClick and any event depends on a mouse click like onSelected and so on.
I have been searching for 5 days with no progress at all the example that i have found on codepin are not **parcoords** diagrams they are deferent types of plot so is there any way that i can do those events with Reactjs ?
and if there a props i should add to the Layout, data ot the config to make it work ?

the way i pass the events is like this :
<Plot
   onClick={() => "do something"}
   onHover={() => "change line color"}
 />

but the behavior is not what i want and it doesn't look like it works as it suppose to.

**Comment by husnaintahir1** [comment]
have you found the answer for this ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
