### ISSUE TITLE
Add "zoom z axis only" icon to surface plot toolbar

### ISSUE THREAD

**Issue by bg23** [plotly/plotly.js#594]
If z-data contain many small "peaks" in the presence of a very big peaks, viewing the small peaks is practically not possibly because the surface plot is z-scaled according to the biggest peak (see example image).
Suggestion: Add an icon "zoom z axis only" to the toolbar. When active, the mouse wheel would expand only in z direction while not changing the x-y-view. Big peaks would overflow in z, and small peaks would become visible.
Z-zooming would be around zero if the z values contain positive and negative numbers. If only positive numbers are there, z-zooming would be from the minimum. For negative-only data respectively.

![image](https://cloud.githubusercontent.com/assets/19235708/15713278/15a99184-2816-11e6-9171-8bfe9fec9fc7.png)

**Comment by etpinard** [comment]
Thanks for the suggestion!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
