### ISSUE TITLE
Surface : Rendering issue with large values

### ISSUE THREAD

**Issue by vdgodse** [plotly/plotly.js#5949]
Plotly is unable to render **surface** plot correctly for large values. 
Please take a look at the codepen here: https://codepen.io/vdgodse/pen/OJgoLex

![image](https://user-images.githubusercontent.com/82810640/134627730-80500d83-9775-47ed-a4d8-e63871451588.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
