### ISSUE TITLE
Radarchart/ scatterpolar issue when adding ids conflicting with the whole chart

### ISSUE THREAD

**Issue by AtienzaHD** [plotly/plotly.js#5972]
Hello, 

I am new to plotly and I am adding a new radar chart to my page. I am experimenting with plotly and discovered that whenever I add the ids trace to my chart, this would create a conflict with the looks of my chart. Can anyone help me please? 

https://codepen.io/atienzahd/pen/LYjPjKr (Without IDS trace)
![image](https://user-images.githubusercontent.com/19652352/136527892-e4ca2c3d-efd7-481c-8d1e-739dd0a977ee.png)

https://codepen.io/atienzahd/pen/vYJBJob (With IDS trace added) 
![image](https://user-images.githubusercontent.com/19652352/136527851-d4227388-48e8-496a-8142-a9c26cfd777e.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
