### ISSUE TITLE
I have noticed that plotly doesn't show its plots when using create-react-app. 

### ISSUE THREAD

**Issue by sean-mcclure** [plotly/plotly.js#5978]
It's not just the react version of plotly; regular ploty.js also does not show the plot when using create-react-app. If you hover over where the plot should be the tooltips appear, so the plot is loaded somewhat. Any idea why create-react-app would cause a conflict with plotly.js?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6061157/136665904-07f74e79-5d24-4357-935d-850b1f29f7df.gif)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
