### ISSUE TITLE
Plotly line dashes look blurry and are barely distinguishable in scattergl trace type

### ISSUE THREAD

**Issue by valentinstn** [plotly/plotly.js#5979]
I detected that there is a significant difference between the line dashes (especially for `dot`) between `scatter` and `scattergl` trace type. It can always be seen (with any type of data) but it is especially clear for traces with many data points.

This minimal example shows pretty well what I mean: https://codepen.io/valentinstn/pen/abyzObW

The issue can also be seen in this screenshot: The plots should look the same, only difference is the trace type (scatter vs. scattergl).

![grafik](https://user-images.githubusercontent.com/3725906/136791178-0b85a14c-4926-4338-9478-bb5c5810653b.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
