### ISSUE TITLE
Expose info about attribute coercion and/or way to validate user data/layout

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#598]
Two ways of doing this come to mind:

1. Add a few `Lib.log` in [`coerce.js`](https://github.com/plotly/plotly.js/blob/master/src/lib/coerce.js) notifying users if a given attribute is set to an invalid value. Post https://github.com/plotly/plotly.js/pull/590, these logs would be hidden by default. This method has one drawback: it would only warn user about invalid values, **not** about invalid attributes (which never reach `coerce.js`.

1. Add a `Plotly.validate(data, layout)` method that runs the full `supplyDefaults` chain, compare input and full data/layout and logs the info.

**Comment by cpsievert** [comment]
As mentioned in #619, having a `required` meta tag for attributes would be quite useful for generating informative error messages in our client APIs

**Comment by etpinard** [comment]
I just pushed some Proof-of-Concept commits for a `Plotly.validate` method to [`plotly-validate`](https://github.com/plotly/plotly.js/compare/plotly-validate).

I wouldn't mind getting opinions from @cpsievert @mdtusz @alexcjohnson @chriddyp @cldougl

**Comment by etpinard** [comment]
Note that the idea of providing an error code comes from the [`deep-diff`](https://github.com/flitbit/diff#differences) package.

I'm imagining that for some applications e.g. the [`unsettable`](https://github.com/plotly/plotly.js/compare/plotly-validate#diff-aebcd90cecf267e2a9daf630428aad1bR27) validate error code would not matter.

**Comment by alexcjohnson** [comment]
@etpinard I love the strategy and the structure of the response. Aside from a few comments I made on the commits, I would just try and make the error codes look more like errors than benign "differences" like those returned by `deep-diff`. So instead of "visible", use "invisible" or even "aborted" because that's likely what happened - coercion was aborted because something crucial was missing. "unsettable" I might just call "unused", and it needs more explanation like "key XXX is valid but was not used because other values made it irrelevant"

**Comment by mdtusz** [comment]
Looks pretty good. Github won't let me comment on the code for some reason, but it may be nice to pass a list of the path keys rather than just `root` to crawl. E.g. `['xaxis', 'rangeslider', 'range']` so that if there arises any _specific_ validation based on the nest, we can test it.

**Comment by alexcjohnson** [comment]
You can't comment on the combined diff until it's in a PR I guess... But you can comment on individual commits
