### ISSUE TITLE
[Feature] Lazy-Load style rendering of charts to improve performance with many charts on one website

### ISSUE THREAD

**Issue by maximilian0311** [plotly/plotly.js#5982]
Hello together,
I have a website where I'm using a lot of charts therefore initial loading takes a lot of time.

I built a wrapper for plotly.js at work and I think this may be a good feature for more people so I want to share the idea here:
The idea is the following:
 - Put the data and style objects into a variable and each time the plot is updated just update the variable.
 - Track if the plot is within the viewport with the scroll event
 - Render/Update the chart only when it is visible or becomes visible

That way initial loading is very fast as only initially visible charts will be rendered right at page load.
Also updating the charts is getting very fast as not visible charts will not be rendered immediately if they are not visible.

If e.g. a chart is updated many times but is not visible a lot of unnecessary renders are not done anymore.
**(sorry can't share code as I did it at work and I'm not allowed to share code)**

Ideally just a boolean in the layout to activate this functionality would be great.

If its not possible or wanted to implement this in the original plotly.js library maybe this idea helps some of you to improve performance on your projects :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
