### ISSUE TITLE
"last" `textmode`

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5990]
If one wants to create a line graph with a label at the end of each trace, it is possible to use `text` as illustrated in [this codepen](https://codepen.io/MojtabaSamimi/pen/ExvymWJ?editors=0010).
However it is rather complicated to set text for all other points to blank.
What if we add a new attribute e.g. `textmode` with options e.g. *false* and *last* to help simplify creating such graphs?
Also `autorange` could be improved to accommodate extra space for those labels.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
