### ISSUE TITLE
horizontal legend undesirable positioning

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5997]
[codepen 1](https://codepen.io/MojtabaSamimi/pen/qBXqRYZ)
[codepen 2](https://codepen.io/MojtabaSamimi/pen/oNeYMQY)

**Comment by alexcjohnson** [comment]
@archmoj can you say more about the problems here? I can't tell just from looking at those codepens whether it's just that our automatic positioning algorithm isn't smart enough, or we're actually doing something explicitly wrong.

**Comment by archmoj** [comment]
@alexcjohnson if you look at codepen number 2 and play with the width of the editable graph (e.g. by resizing the viewport), you'll notice the positioning problems.

**Comment by bigmike36c** [comment]
Here's a screenshot of what @archmoj is describing:
<img width="704" alt="Screen Shot 2021-12-13 at 2 41 05 PM" src="https://user-images.githubusercontent.com/81941044/145877389-b07efad8-feae-4fd9-8fbb-7dc23f7fb8a5.png">
I've had similar, potentially related, issues with horizontal legends as [detailed here.](https://community.plotly.com/t/psa-scaling-graphs-in-dash/57437/7?u=bigmike)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
