### ISSUE TITLE
Drawing shape performance 

### ISSUE THREAD

**Issue by toams69** [plotly/plotly.js#5998]
Hi all,

I have a project with multiple charts display on the same page.
All charts have the same xAxis. I would like to create a common vertical line showing the mouse position on each charts.

To achieve this I am playing with mousemove event and shapes. 
The mousemove event and x calculation is working well. If for example I am updating the title of each chart by displaying the x position it is great.

But if I am updating or creating a new shape (the vertical line) when I am moving the mouse very fast, I have a delay...

![plotly](https://user-images.githubusercontent.com/814788/138417943-cb24f647-dd77-40fe-80ec-8ae003411414.gif)

Do you have any suggestion to help me to improve this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
