### ISSUE TITLE
ECDF graphs in Plotly JS

### ISSUE THREAD

**Issue by brandongohwh** [plotly/plotly.js#6000]
I've used Plotly in Python and Matlab for the longest time and have been very satisfied with it, however the features supported by the JS version are lacking and are not consistent with the Python, Matlab or R counterparts. 

Is it possible to have ECDF graph function implemented? I very much would like to refrain from using other graphing libraries just for this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
