### ISSUE TITLE
Common hover label for hovermode = 'closest'

### ISSUE THREAD

**Issue by valentinstn** [plotly/plotly.js#6005]
For scatter plots with `hovermode` == `closest`, the current default behavior for hover labels is to only show one hover label near the data point, representing the X and Y data information. However, me (and maybe others?) think that this behavior doesn't look good. The labels is too cluttered and shows too much information, which makes it difficult to interpret. 

At the moment, the hover label is rather complex and visually, the labels are much easier to understand if they'd work similarly to `hovermode` == `x`, meaning that the X value is shown as hover label near the X axis and the Y value is shown in the hover label near the data point.

I already implemented this locally, but I wanted to bring this back upstream, as I think it is generally desired. I found multiple threads around the internet where people wanted to have this behavior.

### As-is

![grafik](https://user-images.githubusercontent.com/3725906/139402567-abda97dc-4a76-4cf2-8770-36aa7538b223.png)

### To-be

![grafik](https://user-images.githubusercontent.com/3725906/139402629-8a698442-8046-4bd8-a7bc-5a55a501b77b.png)

(Screenshots taken from this interactive version: https://stackoverflow.com/a/39259137/6156346)

### Benefits

* Better consistency with other plot types, most of them (like bar plots, boxplots, etc.) show a common label on the x axis.

### Discussion

* Do you think this could be a meaningful default behavior? 
* Or should we add an option for it?
* Is there another way to achieve common x label without modifying the plotly library?

**Comment by valentinstn** [comment]
@nicolaskruchten if there are multiple traces with similar X value, then the `x` mode becomes rather difficult to use, as too many labels are shown at the same time. The `closest` mode does exactly what we expect, just we are not a fan of the current hover labels.

**Comment by nicolaskruchten** [comment]
OK, makes sense. We're not going to change the default behaviour for now, but if you're interested in submitting a PR that adds a new attribute (default false) that would activate the x/y axis hoverlabels even in `closest` mode, that seems like it would meet your needs, right?

**Comment by alexcjohnson** [comment]
Could this be treated as a new hovermode? It also occurs to me it may be nice to have formatting like x unified mode, but with point selection like closest, like "closest unified" or something...

**Comment by valentinstn** [comment]
I'll think about a meaningful option, thank you!

**Comment by Lxstr** [comment]
@nicolaskruchten would be great! My thoughts: 

As you said, I believe it would make sense to have new attribute to independently control which labels are highlighted on hover.

It is possible to want to use hovermode "closest" but need to highlight a particular tick label that helps the user better grasp the position of the datapoint.

Conversly, there is no assumed reason you would need the tick label highlighting that automatically comes with hovermode "x" or "y". This was you could turn them off when not wanted.

Without this feature one might opt to print the x or y values into the hover template itself, however I think this detracts from the user experience by adding clutter when there is already significant hovertemplate information to digest. (my current situation)

Attribute use:
```
hoverticklabel = "y"
hoverticklabel = "x"
hoverticklabel = "x+y"
hoverticklabel = "none"
hoverticklabel="automatic"
```
Perhaps by having a default option as automatic/inherit we can avoid having to break any existing expected behaviour.

@valentinstn How did you go with your previous implementation? Are you able to share the code please?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
