### ISSUE TITLE
Plotly bug when doing cursor tracking

### ISSUE THREAD

**Issue by vicn1222** [plotly/plotly.js#6009]
Hi,

I create a demo at https://jsfiddle.net/vicn1222/04qpouc1/4/ for cursor tracking.

If you comment out createTrackingCursor(), the tracking values are correct. If you add createTrackingCursor() the values are wrong.

Also zoom doesn't work with createTrackingCursor() on...

Can anyone give a hint?

Many thanks and great work!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
