### ISSUE TITLE
Customize axis value in `unified` hover tooltip

### ISSUE THREAD

**Issue by junjiewu-mtl** [plotly/plotly.js#6012]
Issue: Tooltip of `x unified` hover mode always has an x-axis value at the top, many users already expressed interest to adjust or hide the value in the tooltip. [https://community.plotly.com/t/customizing-text-on-x-unified-hovering/39440/8](url)

Potential Solution: Include a new attribute to hide or customize the x or y-axis value shown at the top of the hover tooltip using`unified` hover mode
<img width="1024" alt="Screen Shot 2021-11-04 at 5 37 00 PM" src="https://user-images.githubusercontent.com/53387300/140559621-f599447c-9fa4-4e25-98e7-d33d992601e7.png">

**Comment by ReenigneArcher** [comment]
I would like this feature as well, specifically the ability to customize it. I think a `hovertemplate` that applies only to the title would work perfectly.

I've attempted some options but all have downfalls.

Using `xaxis.hoverformat` does not seem to allow appending or prepending text so this is a no go.

Using `xaxis.tickmode=array`, `xaxis.ticktext`, and `xaxis.tickvals` does sort of work; however in order for the customized value to show in the hover label it also needs to show on the axis... that means if you want the customized value to show for every value, you have to have a tick on the axis for every single value, which gets ugly.

**Comment by nicolaskruchten** [comment]
`xaxis.tickprefix` and `xaxis.ticksuffix` do work, but it's not always convenient to have the same text on the axis as in the hovers, indeed.

**Comment by ReenigneArcher** [comment]
> `xaxis.tickprefix` and `xaxis.ticksuffix` do work, but it's not always convenient to have the same text on the axis as in the hovers, indeed.

I did think about using that method as well, but I'm guessing that could cause problems with localization where some languages may reverse the order.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
