### ISSUE TITLE
If I hover a box on a Boxplot chart, it shows hover balloons for a different box too.

### ISSUE THREAD

**Issue by kei51e** [plotly/plotly.js#6016]
If I hover a box on a Boxplot chart, it shows hover balloons for a different box too.

![image](https://user-images.githubusercontent.com/68080/141239135-34f14033-d9ec-4074-a084-bc475523f366.png)

Reproducible example on codepen: https://codepen.io/kei51/pen/eYEjVaB

You can hover the most left box, then it shows hover balloons for the left and center boxes.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
