### ISSUE TITLE
feature request: custom gridlines

### ISSUE THREAD

**Issue by CrepeGoat** [plotly/plotly.js#6020]
Gridlines on 2D line plots are currently restricted to straight vertical & horizontal lines. I would like to have more flexible gridline options available, like, for example, 4-coordinate-paper (4CP) gridlines (see examples in [this paper](https://info.endaq.com/hubfs/gaberson-shock-severity-estimation.pdf) and [this blog post](https://blog.endaq.com/shock-analysis-response-spectrum-srs-pseudo-velocity-severity)): ![](https://blog.endaq.com/hubfs/pseudo-velocity-srs-4cp-gun-stock2.svg)

Other options may be desirable, but this is the one I can think of that I know would have a practical application.

*Edit - these are apparently known more commonly as "tripartitie plots"*

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
