### ISSUE TITLE
[FR] surface plot: add attibutes to projection

### ISSUE THREAD

**Issue by putianyi889** [plotly/plotly.js#6023]
Currently I could use `contours_z_project_z=true` to enable projection. However, the projections and the contours on the surface share the same appearance. For example, if I want to show the projection without showing z contours on the surface, i can't do it. Adding independent attibutes to projection will solve the problem.
Same problem asked by another user: https://stackoverflow.com/questions/67154362/surface-plot-with-contours-only-plot-projection-contours-traces-in-3d-plot

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
