### ISSUE TITLE
Mesh3d initerpolation rendering of out-of-range colors

### ISSUE THREAD

**Issue by CarlAndersson** [plotly/plotly.js#6027]
Came across this issue while working in python, but I suspect that the problem is in javascript since it's rendering related.
If a number of points in a mesh is way outside the chosen color range, there are very strange graphical glitches in the surface.
I would expect the following to give me a flat blue in the center, since the "modified" data points are much lower than the chosen color range.

It also happens for other colorscales, and with values outside on the positive side.
Sometimes, but not always, it goes away if you zoom in very close in the plot. It doesn't in my toy example, but it did in a plot for my research.
I can easily work around it, so it's not a huge issue for me personally now that I know that it's just a rendering issue.

```
import plotly.graph_objects as go
import numpy as np

x = np.linspace(-1, 1, 101)
X, Y = np.meshgrid(x, x)
Z = np.zeros_like(X)

value = np.where(X==0, -500, (np.sin(X) * np.sin(Y))**2)
go.Figure(go.Mesh3d(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    intensity=value.flatten(),
    cmax=1, cmin=0
)).show()
```

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/20397548/142479163-cdb08782-00d3-4238-a723-a76c83e36d77.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
