### ISSUE TITLE
Plotly Js Bar chart bars cut off for time duration display type

### ISSUE THREAD

**Issue by jmaheshkumar** [plotly/plotly.js#6029]
https://codepen.io/jmaheshkumar/pen/eYEXYEX
We are trying to display values in a duration format but the Bar chart bars get cut off.
This issue is happening only in Chrome & Firefox in Windows & Ubuntu.

![image](https://user-images.githubusercontent.com/41112856/142590243-cc7bcc51-c7fc-4dd6-b2cd-063328360dac.png)

**Comment by jmaheshkumar** [comment]
@etpinard This is happened in chrome and firefox of windows & ubuntu. In Mac safari, This working as expected. Please help me to resolve it soon.......

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
