### ISSUE TITLE
Heat-map Error for Specific Data/Layout

### ISSUE THREAD

**Issue by cagantomer** [plotly/plotly.js#6033]
I encounter an issue with heatmap visualization - with specific data / layout, the heat map is not drawn and the following error is raised:

> plotly-latest.js:26976 Error: <image> attribute width: Expected length, "NaN".
> attrConstant @ plotly-latest.js:26976

Immediately followed by:

> plotly-latest.js:26976 Error: <image> attribute x: Expected length, "NaN".
> attrConstant @ plotly-latest.js:26976

[Here](https://codepen.io/cagantomer/pen/GRvBzjy) is a minimal codepen example that reproduces the error. 

I am suspecting it has to do with interpreting the X values as numeric. If I change the first item from a number-like (i.e. "1310") to a string (i.e. "1310_") the heat map is rendered properly.

**Comment by archmoj** [comment]
Please see [this codepen](https://codepen.io/MojtabaSamimi/pen/zYdVdQY?editors=0010) which illustrated the notes bellow:
1. You could use `autotypenumbers: 'strict'` in the layout or axis level (cc: #5240) to disable axis auto type which was implemented in v1.58.0.
2. The `plotly-latest.js` stayed at the last v1 release. You need to load specific v2 version to load the "latest" release.
3. `Plotly.plot` is no longer part of the v2 API. So `Plotly.newPlot` is used in the codepen.
Hope this could help closing the issue.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
