### ISSUE TITLE
Too many digits displayed on Y axis

### ISSUE THREAD

**Issue by mmakrzem** [plotly/plotly.js#6048]
I have noisy data that bounces around between 0 and 1.  When the values are around 0 the y axis displays reasonable results for the y axis.  However when the values are around 1, the yaxis display is too long as too many digits are showing and getting cut off by other things on the page.  I created a simple code pen that demonstrates the problem here:

https://codepen.io/mmakrzem/pen/ZEbBENK

How can the y axis labels be fixed so they don't show so many digits?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
