### ISSUE TITLE
scatter3d-textposition behaves differently when passed string vs. array

### ISSUE THREAD

**Issue by sthoch** [plotly/plotly.js#6049]
See [jsbin](https://jsbin.com/wularaw/edit?html,output).

In a `scatter3d` trace, passing `textposition: "top center"` positions all texts at the desired position. Passing an array, e.g. `["top center", "top center"]` doesnt behave as I expected. In the jsbin, one text is positioned at what would be `top left`, while the other is positioned at what would be `middle center`.

I hope I am not just misunderstanding the [reference](https://plotly.com/javascript/reference/scatter3d/#scatter3d-textposition).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
