### ISSUE TITLE
scrollZoom performance issues since 2.0.0-rc.2

### ISSUE THREAD

**Issue by secretwpn** [plotly/plotly.js#6054]
I don't have rights to reopen the #5912 so creating a follow-up issue

Here's a demo: https://codesandbox.io/s/plotly2-performance-hovermode-0hf9z?file=/src/index.js

It is set to run with `Plotly 2.0.0-rc.1` and the zoom is smooth like butter
But change it to `rc.2` or any fresher version and try zooming in with mouse wheel some good amount - after certain point it will become unusably sluggish

**Comment by archmoj** [comment]
Please note that the default `hovermode` is *'closest'* in v2.
Could you please try setting `hovermode: 'x'` in the layout?

**Comment by secretwpn** [comment]
@archmoj Yes, I'm aware of that and `hovermode` is explicitly defined in layout properties of my demo.
The demo also has an illustration on how performance differs with newer plotly version on different kind of data - randomized vs sampled from test system.

**Comment by shreeramk** [comment]
@secretwpn With `scattergl` and `hovermode` set to `closest`, I m seeing slowness as well. 
@archmoj please help us here.

**Comment by archmoj** [comment]
Here is changelog diff between rc1 and rc2: 
https://github.com/plotly/plotly.js/commit/c74be057255e9be25430bf8bb358af9a521eb81c

Could you please investigate if this is a side effect of #5632?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
