### ISSUE TITLE
Bar graph textposition: 'auto' does not work correctly when constraintext is 'none'

### ISSUE THREAD

**Issue by tcannon686** [plotly/plotly.js#6059]
<https://jsfiddle.net/zrwdbx13/>

From the above jsfiddle, some of the text is overflowing to the left of the graph, when it should be positioned to the right of the bar. I think this issue is caused by [this line](https://github.com/plotly/plotly.js/blob/abbfa7baf480ebc00d007fdc77e22b901ee1ab10/src/traces/bar/plot.js?utf8=%E2%9C%93#L365) which checks if the plot will fit if it is shrunk, but does not check if shrinking is possible.

This looks like a bug to me, but please let me know if this is just me misunderstanding something.

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
