### ISSUE TITLE
In some cases plotly doesn't report about wrong data

### ISSUE THREAD

**Issue by lana-k** [plotly/plotly.js#6064]
I use `plotly.js` and `react-chart-editor` in my project where data for chart building are controlled by user. Sometimes users provide wrong data (usually for tricky cases like 3D surface or heatmap). In some cases `plotly.js` logs warnings or errors and they are shown to users as notifications (because in my plotly config `notifyOnLogging: 1`). But in other cases `plotly.js` silently does nothing however in dev tools I can see errors like `Error: <rect> attribute height: Expected length, "NaN".`

I prepared an example: https://codepen.io/lana-k/pen/qBPjpEa

In the example there are two functions: `createTreeMap` and `createHeatMap`. Data for both of them are wrong. But if you call `createTreeMap` you will see the notification with a message and if you call `createHeatMap` plotly says nothing about wrong data and in dev tools I can see errors like `Error: <rect> attribute height: Expected length, "NaN".` 

![image](https://user-images.githubusercontent.com/24638357/146690284-d45eab3f-c952-42fc-8ff1-384149ad9d8d.png)

If you see that a height is NaN, why not log a warning or error like "Can't build the chart. Check your data please."?
So, I see that actually plotly supports data validation and reporting errors and warnings to users (tree map), but not for all chart types.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
