### ISSUE TITLE
Weird behaviour in table when using html links instead of text on firefox

### ISSUE THREAD

**Issue by thepycoder** [plotly/plotly.js#6071]
Hi! Thank you so much for your awesome library :)

This is a very specific one. Plotly table on Firefox works normally, but when I make one of the columns a html `<a>` instead of normal text, it gets all messed up.
![image](https://user-images.githubusercontent.com/11781950/146952707-bc45f010-fb01-4edd-bcff-9d6b398605f7.png)
![image](https://user-images.githubusercontent.com/11781950/146952749-bce3fda0-d583-4402-a16d-9e33a63d0cc7.png)

Oddities include: missing link text altogether, overlapping text, jumping in and out of existence when scrolling...
I've made a codepen (https://codepen.io/thepycoder/pen/wvrqyML) with a simple reproducible example. Just remove the `<a>` and `</a>` tags from the date column to see the difference. 

Firefox and system info:
Firefox 95.0.1 (64-bit)
Manjaro Linux

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
