### ISSUE TITLE
Multiple axis side doesn't change after added to the layout

### ISSUE THREAD

**Issue by aanilyildiz** [plotly/plotly.js#6074]
I have a program that controls multiple axes, I want to change the axis side after the axes have been added to the layout but changing the side property doesn't do anything. Using the latest plotly.js-dist-min and plotly-angular

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
