### ISSUE TITLE
Bar multi category axis ordering is incorrect

### ISSUE THREAD

**Issue by jamieflorence** [plotly/plotly.js#6075]
Hi all. Hope you're having a great start to the new year.

I'm experiencing an unusual bug with multiple axis ordering, [which can be reproduced on CodePen](https://codepen.io/jamieflorence/pen/KKXoXme)

I have a major category x axis as a string (the date) and a minor category x axis as a number, incrementing upward from 1. I provide the dates and numbers in the correct order, but the when the plot is displayed it is in the incorrect order. There is no sorting going on from my end; the example linked is adapted direct from the Multi Category axis example in the docs, except with a single trace and new data.

Can anyone shed some light on what might be causing this?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
