### ISSUE TITLE
Fill to max x value on a scatter plot

### ISSUE THREAD

**Issue by CarlosAmaral** [plotly/plotly.js#6085]
Hi,

Thank you for the work done to keep this library alive and well.

I came across a problem: I can't seem to find an option at which I would be able to fill from the scatter line until the max of an axis, in this case X. Illustration follows. 

Thank you.
![plotly-fill](https://user-images.githubusercontent.com/12385793/150353193-5c294b1a-810f-4609-ab86-9b17886647bf.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
