### ISSUE TITLE
Chrome gives RESULT_CODE_KILLED_BAD_MESSAGE on loading a local html from a network shared folder.

### ISSUE THREAD

**Issue by kei51e** [plotly/plotly.js#6086]
Plotly version: 2.8.3
Platform: Windows 10
Chrome: 97.0.4692.99

If you open a local HTML file on a Windows network shared folder with Chrome, it shows  RESULT_CODE_KILLED_BAD_MESSAGE. 

Looks like it happens if you open an HTML file with a network shared folder path like `\\machine-name\folder\index.html`. This issue doesn't happen if you copy the HTML file to the local drive like "C:\folder". 

It has been working fine until last week. The difference between last week and this week is the Chrome version. Seems like it happens on the recent Chrome. 

The other HTML pages are still working fine. Only pages with Plotly fail with this error. If you know how to workaround this problem, please let me know. 

![image](https://user-images.githubusercontent.com/68080/150472621-d70d65dc-d5bd-4869-9466-409c3399b022.png)

![image](https://user-images.githubusercontent.com/68080/150472634-0b30cd82-b734-4b89-a41a-12e5a8dfc873.png)

### How to Reproduce

* Prepare a network shared folder.
* Copy plotly-2.8.3.min.js in the folder.
* Create an index.html in the folder with the following contents. I prepared a [zip file](https://github.com/plotly/plotly.js/files/7910764/Archive.zip) also for convenience. 
```
<head>
        <script src='./plotly-2.8.3.min.js'></script>
</head>
<body>
        <div id='myDiv'><!-- Plotly chart will be drawn inside this DIV --></div>
  <script> 
    var data = [
      {
        x: ['giraffes', 'orangutans', 'monkeys'],
        y: [20, 14, 23],
        type: 'bar'
      }
    ];
    Plotly.newPlot('myDiv', data);
  </script>
</body>
```
* Open the shared folder from the a different Windows box using `\\machine-name\folder` path syntax and open `index.html` on Chrome.

Related topic on Forum:
https://community.plotly.com/t/chrome-edge-give-result-code-killed-bad-message-on-loading-local-html-from-network-drive/59902

**Comment by gabrieldsaugusto** [comment]
Hi. It seems like every html file based on a code AND stored in a network drive, is giving the result of "RESULT_CODE_KILLED_BAD_MESSAGE" error in the window instead of the usual graphics, it happens with Google Chrome and also with Microsoft Edge. It is interesting to clarify that Internet Explorer, a way more outdated app is working just fine. In my case specifically, I'm having problems while trying to run .html based in a Python code while using the Plotly library, just as you said. I'm accompanying day by day to see if any solution has been developed for this specific error...

Have you tried to open it with Mozilla Firefox? It seems like it works there. But it is annoying to have to install another browser just for this. Maybe it is an error which showed up after the latest updates based on chromium... Are you still having this issue, like me?

**Comment by kei51e** [comment]
It actually works on the latest Chrome (98.0.4758.82). I think they silently fixed it. I'm closing it. Thanks for your help.
