### ISSUE TITLE
Custom Checkbox in updatemenus

### ISSUE THREAD

**Issue by steven-nicolaou** [plotly/plotly.js#6099]
Currently, if I want a custom button that toggles in `updatemenus`, I need separate True and False buttons. For toggle behavior, it would be more elegant if a custom toggle component existed, perhaps rendered as a checkbox.

**Comment by StasSpawn** [comment]
Hello. Is there any news about checkbox?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
