### ISSUE TITLE
alignments in horizontal legend groups 

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#6102]
There is still some behavior that strikes me as odd though when some groups share a line. I would have expected us to end up with a consistent column width so that (a) the nth group on the first line is horizontally aligned with the nth group on subsequent lines, and (b) all the groups on one line are evenly spaced. I guess the current behavior makes sense without legend groups - it's like you're just writing out the legend as a paragraph - but when you have groups involved it creates some weird effects like this:
![Screen Shot 2022-01-31 at 5 55 55 PM](https://user-images.githubusercontent.com/2678795/151886857-991cbfb6-82b0-4929-8ce9-39104fa5d8c9.png)
That I think would look much better with consistent horizontal spacing. Not exactly sure if we should consider this a bug or just a feature request for a new mode that does what I'm suggesting, but can you make an issue where we can follow up on this?

_Originally posted by @alexcjohnson in https://github.com/plotly/plotly.js/pull/6094#pullrequestreview-868512830_

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
