### ISSUE TITLE
On hover custom tooltip position

### ISSUE THREAD

**Issue by hanatharesh2712** [plotly/plotly.js#6104]
Creating a custom hover template using the `plotly_hover `event and displaying as below screenshot. the position of the custom tooltip is not proper. Ideally, it should display the custom tooltip in the same position as currently, the original tooltip is showing. I am using the x and y positions as below:

![image](https://user-images.githubusercontent.com/17156331/152136424-fbe05060-4b73-4cc3-8076-af79f9f54ad2.png)

```
  gd.on('plotly_hover', function (eventData) {
            Plotly.Fx.unhover(gd);
            const point = eventData.points[0];
            const labelcount = point.data.labels.length;
            var PointY = eventData.points[0].bbox.y1;
            if (labelcount / 2 > point.i) {
                PointY = eventData.points[0].bbox.y1 / 2;
            }
```

Fiddle demo - https://jsfiddle.net/yv8nqb9s/

1) Implemented a tooltip showing all labels and the active labels will be bolder
2) Hover template position is not accurate when I set the transform value.

How to fix the position of the tooltip and display it at the correct position?

Thanks!

**Comment by purvamistry97** [comment]
I am also facing the similar issue and looking for some solution

**Comment by gouranga-devit** [comment]
I am looking for solution position of custom tooltip.

**Comment by alexcjohnson** [comment]
You're close - I'm not sure what you're going for with `y1 / 2`, but the main issue is when you set `position: absolute` it doesn't automatically move the element out of the flow until you give it a new position, so as is it's going to appear below the plotly div. Put your x and y into `left` and `top` instead of `transform`. https://jsfiddle.net/90g8vtrj/1/

Also be aware: `bbox.x0, y0, x1, y1` are the bounds of the region being hovered on - in this case I believe it's the largest circle you can fit inside the pie slice you're hovering on, which is why the hover label isn't always pointing quite to the edge of the slice but at least it's never pointing to empty space outside the slice!. We then do some additional calculations to determine where to put the Plotly hover label so that it's outside but pointing to that region, but in the event data you just get the bounds so you can choose for yourself where to position the label with respect to that.

@archmoj I notice something weird here: if I set `hoverinfo: 'none'` in that particular graph (which you normally want to do in exactly this case since you're creating your own hover box), `bbox` disappears from `eventData.points[0]`. That seems like a bug, would you agree? But it behaves correctly if I try this on the `pie_simple` mock... any idea what's going on?

**Comment by hanatharesh2712** [comment]
@alexcjohnson Thank you so much for the detailed info!

so, You mean in the event data do not have such info for tooltip positions? How can I calculate based on `bbox.x0, y0, x1, y1`?

**Comment by alexcjohnson** [comment]
Most of the time we put the tooltip either to the left or right of the bbox, depending on the tooltip size and the available space on either side. We don’t know how big your tooltip will be, nor whether you will allow it to spill out of the graph div, so can’t make that decision for you. 

When the tooltip ends up on the right, that means its left edge is at `x1` and it is vertically centered on `(y0+y1)/2`. When it ends up on the left its right edge is at `x0`, vertical alignment is the same.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
