### ISSUE TITLE
Axis thickness is inconsistent

### ISSUE THREAD

**Issue by anvitha-bhge** [plotly/plotly.js#6112]

**Comment by anvitha-bhge** [comment]
Whenever the window containing plot is resized, even though the linewidth of all axes is configured to be same,
there is a visual difference in widths of axes.
codepen link : [https://codepen.io/anvitha_bh/pen/WNXjJYZ?editors=1010](url)

As shown below in the images, the width of second y axis is changing as plot width changes.

![IncorrectAxis](https://user-images.githubusercontent.com/90032080/153449768-04cd9c82-21cb-453d-b073-9820b12dbff1.png)
![IncorrectAxis2](https://user-images.githubusercontent.com/90032080/153449785-5cc3f797-d510-4e7c-aee0-2bc07b6d4ea4.png)

**Comment by alexcjohnson** [comment]
Thanks @anvitha-bhge - I'm not able to reproduce this behavior. What browser (specific version) and OS are you seeing this on?

**Comment by anvitha-bhge** [comment]
OS: Windows 10 Enterprise, version : 1909, OS Build : 18363.1977
Chrome version: 98.0.4758.82  (Official Build) (64-bit)
Microsoft edge version: 98.0.1108.43 (Official build) (64-bit)

**Comment by anvitha-bhge** [comment]
Yes, the inconsistency is observed when the page is zoomed in.

**Comment by alexcjohnson** [comment]
I'm not aware of a workaround for this issue, and unfortunately the assumption that `devicePixelRatio` is an integer is made implicitly in tons of places in our codebase. You can see for example that gridlines also have this problem in your codepen, and if you make other types of plots I bet you'd see this with ticks, colorbars, annotation boxes, and legend boxes, to name just the ones that come to mind quickly. So it would be a pretty sizable effort to fix, and as I said before the fix is likely not going to be 100% robust anyway due to CSS transforms. I'll label it a bug, but it's probably not one we'll be able to address any time soon unless someone is able to sponsor the fix. But if you're interested in making a PR we'd be happy to help get it across the finish line!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
