### ISSUE TITLE
sankey: prevent dragging but allow arrangement != "fixed"

### ISSUE THREAD

**Issue by hottwaj** [plotly/plotly.js#6114]
Hi there.  Issue, proposed solution and notes on implementation below.

I'm happy to implement a solution and submit a PR, but need guidance on whether using "dragmode == False" setting is suitable way of implementing this.
- Sankey diagrams allow their "nodes" to be dragged around by the user, unless they have "arrangement" == "fixed"
- However, "arrangement" also controls whether any automatic arrangement of nodes is done by plotly.  
- If arrangement is set to fixed, plotly will i) prevent user dragging, ii) not automatically arrange placement of any nodes.

So, can we add an option to separately control user dragging of nodes (without changing automatic layout as specified by "arrangement" setting)?

e.g. check for layout.dragmode == False and if so prevent user dragging nodes?

I believe dragging could be disabled by preventing call to attachDragHandler here:
https://github.com/plotly/plotly.js/blob/master/src/traces/sankey/render.js#L931

Caveat: I can't work out what existing sankey code for "dragmode" is meant to be doing here:
https://github.com/plotly/plotly.js/blob/master/src/traces/sankey/base_plot.js#L48

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
