### ISSUE TITLE
zoom to mouse pointer in 3D diagrams

### ISSUE THREAD

**Issue by JoergTie** [plotly/plotly.js#6117]
Hi all,
when I zoom into a 3D-Diagramm it zooms to the center of the diagram.
Is it possible to zoom into the position where the mouse pointer points to?

**Comment by alexcjohnson** [comment]
Not a mode we have right now. You can ctrl-drag or right-button-drag to pan, then zooms and rotations are based on the new center position.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
