### ISSUE TITLE
tooltip hover example freezes

### ISSUE THREAD

**Issue by 4b11b4** [plotly/plotly.js#6122]
https://plotly.com/javascript/hover-events/#combined-click-and-hover-events
the codepen for this example causes browser to freeze

https://codepen.io/plotly/pen/eJOyej

**Comment by alexcjohnson** [comment]
Yikes, thanks @4b11b4!
That pen is using `plotly-latest` so stuck on v1.x... dunno if anything we've done since then would have fixed this behavior but the pen needs adjusting before we can test that, because it depends on `Plotly.d3`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
