### ISSUE TITLE
[Bug] Choosing PNG title for saved plot from figure

### ISSUE THREAD

**Issue by mdylan2** [plotly/plotly.js#6123]
Repost from [my post on the Dash forum](https://community.plotly.com/t/bug-choosing-png-title-for-saved-plot-from-figure/59304)
Hi, for some reason when I download plotly figures from Dash on Safari or Chrome (clicking the little camera icon on a plot), it downloads the file as newplot.png. However, when I download images on Brave browser, I get a window that pops up, allowing me to choose the file name (as in image attached). Can this issue be fixed on Safari/Chrome?

![image](https://user-images.githubusercontent.com/47123837/154477789-25770ec1-35a7-41b7-92dc-00a9aa9e242c.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
