### ISSUE TITLE
Feature request: scatter plot with pie chart

### ISSUE THREAD

**Issue by kkollsga** [plotly/plotly.js#6126]
Using plots with multiple pie charts is a great way to highlight trends complex data sets. Matplotlib supports plotting pie charts in maps and scatter plots, but falls short in being interactive, and everything else plotly does incredibly well.

Would it be possible to add functionality to add pie charts in scatter plots?
An example and use case from matplotlib can be found below:
https://www.geophysique.be/2010/11/26/matplotlib-basemap-tutorial-06-real-case-pie-charts/

The easiest way to implement would be to have an additional pie or data tag to import additional data (something like this):
`fig = go.Figure(data=go.Scatter(x=t, y=y, pie=(labels=['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen'], values=[[4500,2500,1053,500]]), mode='pie'))`

or simply:
`fig = go.Figure(data=go.Scatter(x=t, y=y, labels=['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen'], values=[[4500,2500,1053,500]], mode='pie'))`

Thanks =)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
