### ISSUE TITLE
Feature request: ability to add pattern fills to pie chart

### ISSUE THREAD

**Issue by DoctorNo124** [plotly/plotly.js#6134]
Is there a way to add pattern fills to pie chart slices similar to how the pattern attribute is available in the marker object for bar chart? If not, is this something that could be implemented? Showing an example of this below: 

![image](https://user-images.githubusercontent.com/29240797/157286832-2a68f8df-df76-4a06-9f43-3fc97faef6d9.png)

**Comment by archmoj** [comment]
Tagging @s417-lama here who implemented `pattern` feature.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
