### ISSUE TITLE
Sankey - Customize link opacity when hovering on nodes

### ISSUE THREAD

**Issue by mattiatantardini** [plotly/plotly.js#6142]
Hi,

I'm currently working on a large sankey diagram with many links and nodes. I have already lowered the base opacity of the links, but what will be really helpful for the plot legibility is to make possibile the customization of the opacity for links when the mouse hovers on nodes.

From what I understand, currently the link opacity when hovering on nodes is set to 0.4 (see rows 63-89 of [sankey/plot.js](https://github.com/plotly/plotly.js/blob/623fcd1fea9d9bfb86e5e0d44d8047cd8636881c/src/traces/sankey/plot.js)).

I would like to set it to full opacity (equal to 1). Is there a way to do so or a change in the library code is needed?

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
