### ISSUE TITLE
feature: Rangeslider on yaxis

### ISSUE THREAD

**Issue by aukeschaap** [plotly/plotly.js#6148]
Right now it is not possible to add a rangeslider on the yaxis. One example usage of this is in a horizontal bar chart, as seen in the first picture below. It would look something like the second picture, a plot I am trying to recreate.
![image](https://user-images.githubusercontent.com/23525223/159018452-4a35615d-240b-4795-816c-55b2525d462f.png)
![image](https://user-images.githubusercontent.com/23525223/159019157-8147d292-48b4-41cf-b914-7ed2385bc9b5.png)

Are there more people that would like to have this as a feature? I found one community post about it: https://community.plotly.com/t/can-i-have-rangeslider-in-yaxis/1359

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
