### ISSUE TITLE
Scattter Type Text styling

### ISSUE THREAD

**Issue by devv3899** [plotly/plotly.js#6157]
I am trying to plot a chart of alarms generated by the machines on a time series scale and I have been able to do it successfully.

The thing I am not able to able to find is how can I have a border or change the background color of the scatter text that has been plotted? Is there any predefined tool for it? or is there a way do achieve it.

The only available styling options are family, size and color.

It would be really helpful to have the way to Border out or change background color of the plotted text so that we can plot boxes directly without using markers and it looks aesthetic.

![Current](https://user-images.githubusercontent.com/35231294/160167547-6da79eb8-4546-4554-932e-0dfdf50ac0c6.png)

![ Required Output](https://user-images.githubusercontent.com/35231294/160167654-f9a09b6e-fd45-463e-a179-66ea35170a4c.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
