### ISSUE TITLE
Ability to modify existing selections

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#6168]
Another part of #1851 to discuss separately: we want to be able to modify an existing selection, either by dragging the whole thing around or by moving one point / corner / edge.

We have a couple of examples already where we draw handles on things: zoom boxes have corners when you're zooming in 2D, or rectangles when you're zooming in 1D:
![Screen Shot 2022-04-07 at 17 05 37 (2)](https://user-images.githubusercontent.com/2678795/162309846-fc2b977e-16aa-4e1c-bf25-280c02301c9b.png)
![Screen Shot 2022-04-07 at 17 06 46 (2)](https://user-images.githubusercontent.com/2678795/162309852-51450374-af7c-414b-812f-b66404a34a26.png)
Rangesliders also have rectangular handles:
![Screen Shot 2022-04-07 at 17 09 48](https://user-images.githubusercontent.com/2678795/162310603-d184a561-c654-488f-a8da-68c0ed2e4205.png)
Whereas editable shapes have draggable circles at their corners:
![Screen Shot 2022-04-07 at 17 10 59](https://user-images.githubusercontent.com/2678795/162312215-e45229cf-e424-4844-aa75-823988ec220e.png)

I think we should use rectangles on the edges and L shapes at the corners for adjusting rectangular selections, and circles at each vertex of a lasso. And if you drag the middle of any selection it translates the whole thing.

By default all of these handles can be white with black border, but let's make attributes to control the colors, sizes, and line widths.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
