### ISSUE TITLE
Tooltip does not display on a bar chart with a single data point

### ISSUE THREAD

**Issue by sudha-varanasi** [plotly/plotly.js#6170]
Sample code: https://codepen.io/sudha-varanasi/pen/VwyqEew

- While using the hovermode "x" or "x unified" we are unable to display a tooltip when there is only a single bar to plot
- This does not occur when there are 2 or more bars in the graph
- Our scenario is specific to using hover mode "x unified" and autorange as "false"
- The data property shows the details on the tootip to be displayed, but it does not show up on the graph.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
