### ISSUE TITLE
Double click does not zoom out in any graph on Macbook

### ISSUE THREAD

**Issue by sudha-varanasi** [plotly/plotly.js#6171]
Sample Code: https://codepen.io/sudha-varanasi/pen/VwyqEew
(This issue is reproducible on any graph in the [Plotly.js](https://plotly.com/javascript/) website)

- Create any graph with the zoom options enabled.
- Zoom-in on a certain part of the graph
- You get a pop up message saying "Double click to zoom-out"
- Double click
- The graph intermittently zoom out, mostly doesn't on a Macbook Pro 15-inch, 2018 (OS version: 12.2.1, )

**Comment by Kully** [comment]
> * The graph intermittently zoom out, mostly doesn't on a Macbook Pro 15-inch, 2018 (OS version: 12.2.1, )

Interesting, I thought I had experienced a similar thing.

I cannot replicate while using your example, do you mind attaching a GIF/movie to see the problem in action?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
