### ISSUE TITLE
zoom rubberband behaviour

### ISSUE THREAD

**Issue by mzechmeister** [plotly/plotly.js#6176]
The zoom modes I have seen in plotly are based on drawing rectangles and boxes by the user.
In qt applications I have experienced another nice zoom behaviour; it seems it is called "rubberband drag".
It works like that:
A right click creates a virtual center and when moving the mouse with the right button hold pressed, the zoom depends on the relative coordinates with respected to the virtual point.
It is a smooth zoom and feels similar to mousewheel zoom, but in two dimensions and symmetrically.

Can this be implemented as zoom mode option in plotly, too? Is there a quick hack to get it now?

Added: It just come to my mind that it also similar to a two finger zoom, also called pinch zoom (e.g. https://github.com/plotly/plotly.js/issues/480). That might be starting point.

**Comment by mzechmeister** [comment]
@alexcjohnson Thanks for consideration.

Meanwhile, I found a way to hack it in. Thus I can demostrate it:
https://gist.github.com/mzechmeister/c3f0557b0bb87f6b410d6d49e1124bda
https://gistpreview.github.io/?c3f0557b0bb87f6b410d6d49e1124bda
https://jsfiddle.net/7rskne05

Unfortunately, there is no native support in javascript for drag with right mouseclick. Thus it needed to be emulated.
Also, there is a zoom bug in plotly (#5311), which I worked around via toggling `fixedrange`.
And there is a little short coming due to imprecise p2c conversion (#1548).

Enjoy

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
