### ISSUE TITLE
Plotting fails silently when handed bad data, or produces confusing error messages

### ISSUE THREAD

**Issue by phx-mkoninckx** [plotly/plotly.js#619]
For example: http://codepen.io/anon/pen/ZObgwz
No error messages are produced, even at the console, when running this code (attempting to plot scatter3d with no z-axis data). It would be more developer-friendly if an error message was produced that indicated why no data was plotted.

**Comment by etpinard** [comment]
I wouldn't call this _failing_ really. 

`scatter3d` needs `z` array in order to be considered visible. 

We could make it clearer in our docs (maybe by adding `required` meta tag in our attribute [declarations](https://github.com/plotly/plotly.js/blob/9ee53c9af2c516d4c5fd4e80d1cba6e7bab95e48/src/traces/scatter3d/attributes.js#L63-L66)) and/or expose some other way to inform users about attribute coercion. 

In any case, this is a duplicate of https://github.com/plotly/plotly.js/issues/598
