### ISSUE TITLE
How to represent these areas on world map 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [plotly/plotly.js#6190]
```
au
cn-east
cn-northeast
cn-southeast
eu-central
in
kr
sa
sg
us-east
us-west
```

How to represent these areas on world map with corresponding index(column) in my case a number count

<img width="200" alt="count" src="https://user-images.githubusercontent.com/8083613/168230222-e065aa59-19d8-4724-b4f6-1596d7c9c6d9.png">

Each count(number) corresponds to the region? Something like plot shown below or even better with different colors

Below is an example of: https://plotly.com/javascript/choropleth-maps/

![area](https://user-images.githubusercontent.com/8083613/168229360-3f45b9cc-9ef6-483f-b014-db8e1f02e0b1.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
