### ISSUE TITLE
Bars in the same `alignmentgroup` should have the same width

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#6198]
Followup from https://github.com/plotly/plotly.py/issues/3715 ... In this pen https://codepen.io/nicolaskruchten/pen/RwQxYJK we see that the upper subplot has a bar, but it's auto-width'ed to 1ms or something because there are no other bars in the subplot. But it's in an `alignmentgroup` with the traces on the other subplot so they should have the same width.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
