### ISSUE TITLE
Problem with 3d animation with ios 15.4

### ISSUE THREAD

**Issue by Miraha02** [plotly/plotly.js#6201]
OK, here's the problem, when i launch the animation i've made on this [website](https://uartois-lml.github.io/gait-app.html)
The animation bugs and this appear: 
![unknown](https://user-images.githubusercontent.com/92987783/171396683-7f5f754f-6b0c-47ba-b89f-cbdd5c33321b.png)

then i updated my ipad on ios 15.5 and it worked well

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
