### ISSUE TITLE
How can i numerate all cells? 

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6208]
1) I want to see the particualr number of each cell (screenshot) 

![2022-06-03_132640](https://user-images.githubusercontent.com/56681850/171837278-8ed7ae47-46f4-47fa-b28e-ef8cf377c827.png)

Does this library can do this? 

2) Also, how can i make them clickable? So i can check what cell was clicked?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
