### ISSUE TITLE
The custom format fot the tooltip with the parameter "textinfo"

### ISSUE THREAD

**Issue by Dusan-Krehel** [plotly/plotly.js#6221]
If the user have the graph, so the user can read the information's from the tooltip. I know about the actual format for "textinfo", but the actual format is not good, if i wanna using the value with the suffix, as the value as "15 €".

**Comment by nicolaskruchten** [comment]
You can use the `hovertemplate` attribute for this :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
