### ISSUE TITLE
[BUG] go.Heatmap y axis labels misaligned when using mathjax

### ISSUE THREAD

**Issue by geislpxs** [plotly/plotly.js#6226]
Good evening, 
I'm not sure if this is a bug or somehow wanted behavior. 

dash                 2.5
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-renderer        
dash-table           5.0.0

    - Browser [chrome]
    - Version [102.0.5005.63]

**Describe the bug**

When I use strings for y in go.Heatmap with leading and trailing Dollar-signs, the y axis labels lose the alignment (neither left, nor center, nor right. Somehow random). When I remove the Dollar-signs, everything is fine.

**Expected behavior**

Consistent alignment

**Screenshots**

![image](https://user-images.githubusercontent.com/55396253/173215488-c108db93-e080-4950-9b71-2f21aeb99a19.png)

**Comment by alexcjohnson** [comment]
Thanks @geislpxs - we'll investigate, but in the meantime I'll mention if you just need subscripts & superscripts you can do that without MathJax, just eg `"T<sub>Lys1Air</sub>mean"`. The allowed tags, that are supported across most elements of a graph, are listed in eg https://plotly.com/python/reference/layout/annotations/#layout-annotations-items-annotation-text. They look like HTML but we in fact reinterpret them into SVG while drawing the graph.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
