### ISSUE TITLE
how to change legend shape in plotly.js 

### ISSUE THREAD

**Issue by viramjain13** [plotly/plotly.js#6240]
I want to change the shape of the legend to circle how I can change the legend shape. Is there is any way to change  ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
