### ISSUE TITLE
editable property on layout.shapes does not work

### ISSUE THREAD

**Issue by aanilyildiz** [plotly/plotly.js#6245]
Hi all, I'm trying to limit the shape editing to individual shapes. But when I set editable true on any shape it doesn't work as intended.
I was using config.editable before and yes I disabled that setting when I tried to make shapes editable.

Here's the example code: [https://codepen.io/aanilyildiz/pen/WNzNvPw](https://codepen.io/aanilyildiz/pen/WNzNvPw)

**Comment by archmoj** [comment]
You need to set `shape.editable: false`.
Also please note that `plotly-latest` does not load the latest v2.
Here is the [working codepen](https://codepen.io/MojtabaSamimi/pen/YzazGaQ?editors=0010).

**Comment by archmoj** [comment]
In your codepen one could activate the shape for editing by clicking on the edge.
[The automatic logic](https://github.com/plotly/plotly.js/blob/fefa11cbd533d11dea7db55d5dbed76c6359cf89/src/components/shapes/draw.js#L163-L165) also depends on the opacity of the `shape` & `fillcolor` as well as `line.width`.
So, if you want to keep the minimal line width, you could adjust the color and opacity as shown in [this codepen](https://codepen.io/MojtabaSamimi/pen/poLoezO?editors=0010).

**Comment by aanilyildiz** [comment]
Thank you so much for your help, I didn't know that the fill color opacity could affect the editable status of the shape as it wasn't documented properly.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
