### ISSUE TITLE
Gauge chart: Multiple thresholds

### ISSUE THREAD

**Issue by ramneet-persistent** [plotly/plotly.js#6270]
I am using Plotly to draw gauge chart in Reactjs project. 
I am trying to display multiple thresholds on gauge bar but its not possible as threshold is not array.
I tried steps key in gauge object also but again output is not similar as threshold object. 
Any suggestions

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
