### ISSUE TITLE
React-plotly event needed forRangeSelector RangeSlider inside plot to fire when range is selected?

### ISSUE THREAD

**Issue by czanbaka** [plotly/plotly.js#6271]
I have a sample chart: https://codepen.io/czanbaka/pen/MWVpeMX

I would like to fire an external event when the user is done selecting a date range. I know that slider fires a relayout event, but that is too many, I would like only the final event to trigger. Any ideas?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by vedvalsangkar** [comment]
When using Blazor interop, this would become a better alternative to relayout event which is triggered multiple times in a single drag. The delay/repeat firing is more noticeable in server-side rendering.
