### ISSUE TITLE
Move only background image with mouse

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6278]
Is there a posibility to move ONLY background image with mouse?

Now we have Pan function, which moves whole plotly (images, coordinates, …)

![2022-07-21_124756](https://user-images.githubusercontent.com/56681850/180964984-36aa7c8c-c243-4507-b17d-a6b6afd92350.png)

But I want to move only background image without influence on coordinates, layout, grid, etc.)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
