### ISSUE TITLE
3d chart doesn't work with extendTraces() if all traces are set to 0 points first

### ISSUE THREAD

**Issue by andrewhodel** [plotly/plotly.js#6280]
It does work if the points are not removed from the existing traces though.

https://jsfiddle.net/v4mghLd5/1/

**Comment by andrewhodel** [comment]
It shouldn't require doing something like this to `extendTraces()`, it should be possible to `extendTraces()` while there is no data in the 3d chart.

<img width="635" alt="Screen Shot 2022-07-28 at 2 39 53 PM" src="https://user-images.githubusercontent.com/741705/181422029-40d1a68f-a3da-48f7-95e6-91ae6c18549a.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
