### ISSUE TITLE
lasso and box-select fail with cross filter when number of points N > 1000

### ISSUE THREAD

**Issue by gszep** [plotly/plotly.js#6282]
Selection tools break when cross-filtering with more than 1000 points? I'm using the [generic cross-filtering example](https://dash.plotly.com/interactive-graphing) in the docs and when I set the number of points to be higher `N=3000` the cross filtered update does not show and the page title states `Updating...`

Could this have something to do with inefficient JSON serialization?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
