### ISSUE TITLE
Is there anyway to zoom to/from one side of an axis.

### ISSUE THREAD

**Issue by paris0120** [plotly/plotly.js#6283]
When zoom in or out, can one side of the axis is fixed. For example, when zoom in can the right side of x axis range is locked?

**Comment by alexcjohnson** [comment]
You can drag one end of an axis - put your mouse over the axis labels near one end and you'll see the cursor as a single-ended arrow, whereas it's double-ended when your mouse is over the middle of the axis.

This kind of question will get a quicker answer on https://community.plotly.com/ 😄

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
