### ISSUE TITLE
Reduce size of an HTML file with a lot of plotly graphs in Rmarkdown ( R )

### ISSUE THREAD

**Issue by Auronus92** [plotly/plotly.js#6286]
Hello, first of all I want to thank you for this amazing package. I use it daily for my reports and it's great. 

I'm trying to create an HTML Rmarkdown that runs many plotly graphs... The issues in the HTML file is too big and can't open it. 

I found out that I can use "partial_bundle" function to reduce the size of my file. On my home computer it works great.

I created the following file: 
```
```{r pressure, echo=FALSE, error=TRUE}
dta  = data.frame(x= rnorm(1000), y = rnorm(1000))

plot_ly(dta, x=~x,y=~y) 
```

The Rmarkdown HTML file size is ~5Mb and when I add the funtion "partial_bundle" like this:

```
```{r pressure, echo=FALSE, error=TRUE}
dta  = data.frame(x= rnorm(1000), y = rnorm(1000))

plot_ly(dta, x=~x,y=~y)  %>%
  partial_bundle() 
```

The size of the Rmarkdown HTML file reduces to ~2.5Mb which is great. 

The issue is in my work environment the function doesn't work because it seems like it needs to access internet to download the scripts but it's blocked in my work:

```{r pressure, echo=FALSE, error=TRUE}
Error in curl::curl_download(paste0("https://cdn.plot.ly/",bundle_script), : Could not resolve host https://cdn.plot.ly
```

It there a way to use it offline? There is a description [here](https://github.com/plotly/plotly.js/tree/master/dist#partial-bundles) of the function but I dont get how to use it offline in Rmarkdown..

I use R version 4.1.2 and plotly_4.10.0

Thanks for you help.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
