### ISSUE TITLE
How can I create an addition to Plotly.js so it will allow me to create this kind of multi layered markers?

### ISSUE THREAD

**Issue by HackPoint** [plotly/plotly.js#6289]
​​
![image-20220802153818-1](https://user-images.githubusercontent.com/6758579/183897903-0e1d5cd1-6375-4e73-aeaf-d2e116de0c3a.png)

**Comment by HackPoint** [comment]
@benjeffery

**Comment by benjeffery** [comment]
You've tagged me here, but I'm afraid I stopped doing JS several years ago. Sorry!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
