### ISSUE TITLE
Multi-categorical grouped bar chart with hovermode: 'x' has only the first trace in hover

### ISSUE THREAD

**Issue by tbitai** [plotly/plotly.js#6290]
Only the first trace is displayed in the hover of a multi-categorical grouped bar chart if `hovermode` is set to `'x'`: https://codepen.io/tbitai/pen/NWYBEWJ

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
