### ISSUE TITLE
Warnings while selecting with 2.13

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#6295]
When making selections in https://plotly.github.io/plotly.js-crossfilter.js/ I see the following warnings in the console:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/203523/184183733-17f7778f-317a-4ced-98a4-da4b38b7d107.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
