### ISSUE TITLE
Sync graphs to playback bar #Question

### ISSUE THREAD

**Issue by BlenderItUp** [plotly/plotly.js#6302]
Hi all
I have been looking for an example of syncing graphs. I found the link below, which syncs how I need it to. Make sure you turn on adv to see the graphs  
https://dash.gallery/dash-avs-explorer/

I have been looking through the code but have had no luck figuring out how it works. So i was wondering if there were any examples for something like this that standalone (like one file) so I can better understand what is happening.

**Comment by BlenderItUp** [comment]
I am pretty much looking for anything that allows me to do this. I just need to be able to set its postion by time
![image](https://user-images.githubusercontent.com/61500446/188453492-1831e7d9-f5b3-4d51-8e1d-75dffc34894f.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
