### ISSUE TITLE
Add Transition Easing options to `treemap`, `icicle` and `sunburst`

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#6303]
It would be interesting to select the easing method for transitions.
https://bl.ocks.org/d3noob/1ea51d03775b9650e8dfd03474e202fe

Right now for `treemap` & `icicle` we have 
https://github.com/plotly/plotly.js/blob/8206eb50805b248327573b0ea8d2514c5375b06d/src/traces/treemap/constants.js#L5

And for `sunburst`:
https://github.com/plotly/plotly.js/blob/8206eb50805b248327573b0ea8d2514c5375b06d/src/traces/sunburst/constants.js#L5

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
