### ISSUE TITLE
How to mock randstr for snapshots

### ISSUE THREAD

**Issue by bozdoz** [plotly/plotly.js#6311]
Wondering how I can use jest snapshots while plotly is using its own randstr function (i.e. there's nothing to mock out)

**Comment by alexcjohnson** [comment]
I don't know of a way, unless you've included plotly.js from source in which case you should be able to directly import `plotly.js/src/lib` and replace `Lib.randstr` with whatever you want. Anyway the function is defined [here](https://github.com/plotly/plotly.js/blob/55f86ea9661afeb4bff1e4a0d0b22fb3679c29cb/src/lib/index.js#L326), we'd be happy to accept a PR to make it easily mockable.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
