### ISSUE TITLE
 Plotly js (React) add checkbox as custom button

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6313]
Is there a possibility to add checkbox just like we can add custom button or select?

[Button events in JavaScript](https://plotly.com/javascript/custom-buttons/) here we can fint only buttons and select.

But I need to add there simple html checkbox.
Option with position: absolute is not very good.'

![2022-09-08_143840](https://user-images.githubusercontent.com/56681850/189221528-d391200a-6afc-40a1-9977-b37dba9848a2.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
