### ISSUE TITLE
Add button to layout.updatemenus with my own custom function

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6314]
Can I add button as on screenshot, but with my js function?
For example I want to add alert or just console.log()

![2022-09-09_150328](https://user-images.githubusercontent.com/56681850/189346851-fb2fc8eb-c4e9-4308-a863-e560627c0dc7.png)

**Comment by alexcjohnson** [comment]
For security purposes we don't allow any JS inside the figure spec, since figures don't always come from trusted sources. You could hack something to achieve your purpose by creating a `restyle` or `relayout` call that does nothing, ie set a nonexistent attribute, then listen for that event with that attribute.

We could advance that concept into a real feature by allowing you to just emit an event of your choosing, but do nothing else to the graph. For example, we could make it so this button:
```js
{ args: ['party', 'like it\'s 1999'], label: 'Party Time!', method: 'event' }
```
would emit a `plotly_party` event with data `"like it's 1999"` when clicked. Then you could attach whatever handler you want:
```js
gd.on('plotly_party', e => { console.log(e) })
```

This feature is probably pretty straightforward to implement, if you'd like to make a PR. It's not likely to be worked on by Plotly staff in the near future but we'd happily help review and merge a PR 😄

**Comment by wayne-christopher-ansys-com** [comment]
> You could hack something to achieve your purpose 

@alexcjohnson Do you have an example of how to do this?

**Comment by alexcjohnson** [comment]
I was thinking I'd have to write an example but then I stumbled on [this codepen](https://codepen.io/ajoposor/pen/vmePBp?editors=0010) (from 2017!) that does exactly what I was imagining. 🙇 @ajoposor

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
