### ISSUE TITLE
 How to tilt the axles

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6316]
Is there is a possibility to tilt the X and Y axles?
I’m using scatter plot [Scatter plots in JavaScript](https://plotly.com/javascript/line-and-scatter/)

Need something like this:
![2022-09-14_143647](https://user-images.githubusercontent.com/56681850/190143842-499112cd-f5c2-467d-84ec-535f7bf634cc.png)

**Comment by alexcjohnson** [comment]
No - perhaps you can use a carpet plot? https://plotly.com/javascript/carpet-scatter/

**Comment by archmoj** [comment]
Alternatively you may try adding `rotate` CSS transform similar to this [codepen](https://codepen.io/MojtabaSamimi/pen/yLjEMNW?editors=0100).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
