### ISSUE TITLE
[Feature request] Add EXIF metadata to exported image

### ISSUE THREAD

**Issue by Laurentvw** [plotly/plotly.js#6321]
On export, would be nice to have an option to add EXIF metadata/tags to the image.

Or would there be another way (outside of plotly) to achieve this?

Thank you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
