### ISSUE TITLE
How to draw subplots?

### ISSUE THREAD

**Issue by longranger2** [plotly/plotly.js#6322]
I want to draw subplots, but it did't work
![carbon](https://user-images.githubusercontent.com/52858395/191467591-d26e0ebd-80d1-4a7b-886d-663c18401afa.png)

<img width="1166" alt="截屏2022-09-21 16 59 03" src="https://user-images.githubusercontent.com/52858395/191462135-9e8aded2-8789-4c26-85f6-283cd7190312.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
