### ISSUE TITLE
Right click for Pie and Donut is not working.

### ISSUE THREAD

**Issue by emshakir** [plotly/plotly.js#6329]
plotly_click for right is not working for pie and donut chart, but the same is working for all other charts.
Other charts are using mousedown to trigger this event, whereas pie and donut are using click event, it would be very helpful if you add mousedown for pie and donut too, thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
