### ISSUE TITLE
Wrong color for markers with scattergl

### ISSUE THREAD

**Issue by nhtrvn** [plotly/plotly.js#6330]
Hi all, I'm having problem with scattergl, I have around 1k7 data points and it renders fine with scatter but with scattergl, lots of data points are white and hence not visible on the chart unless I hover over it and look at the tooltip. Here's the issue: https://jsfiddle.net/u58s4p9c/8/

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
