### ISSUE TITLE
Style zoom box (color etc.)

### ISSUE THREAD

**Issue by Elfram** [plotly/plotly.js#6342]
There are questions at different places about configuration of the zoom box (e.g. remove the grey overlay and instead use a colored highlighted box for the zoom region) but I could not find any way to do that.

https://github.com/plotly/plotly.py/issues/835

https://stackoverflow.com/questions/63349023/change-the-color-of-the-zoom-window-in-plotly

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
