### ISSUE TITLE
ggplotly colorbar and colorscale do not display in plotlyjs

### ISSUE THREAD

**Issue by ntran-somalogic** [plotly/plotly.js#6352]
I've got a plot produced by ggplot2, which then gets converted to plotly with ggplotly, that displays properly in the backend but not with plotly. 
Here is my codepen: https://codepen.io/ntran-sl/pen/OJELewV

I have seen the plots produced by ggplot and ggplotly shown correctly in Rstudio, there is a colorbar with the correct custom colorscale, which has a custom start and end color. However, these are completely absent when displayed with Plotlyjs. I've tried changing some properties, such as showscale:true or the color values, but have not had any luck. I have not seen any other reports of this issue between ggplotly and plotly.js.

Expected plot:
![Rplot](https://user-images.githubusercontent.com/111808803/197599092-00258b6b-ff54-4e3e-81fb-524191695085.png)

Any help would be appreciated.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
