### ISSUE TITLE
Mapbox maps rendering issue with multiple worlds

### ISSUE THREAD

**Issue by safroze-plotly** [plotly/plotly.js#6354]
When the view of the map is centered on 180. For example in the attached image, only the section from -180 east is rendered. The problem is the filter of the data set which does not include data from the west edge of the map to 180.

Issue recreated from [dash world centers app](https://dash.gallery/dash-world-cell-towers/) below;
![Screenshot 2022-10-24 101023](https://user-images.githubusercontent.com/116090610/199086134-f7db1945-892f-430a-bfc0-de8883295829.png)

The workaround is to set [mapbounds](https://plotly.com/python/mapbox-layers/) so that multiple worlds are not created.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
