### ISSUE TITLE
Show ticksuffix on hover even when showticksuffix = none

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#6361]
Hello everyone;

I'd like to propose a different behaviour when

`ticksuffix` is set to something and `showticksuffix = "none"`.

Currently ticksuffixes are not shown in that case at all, but I need them to be shown on hover, while not being shown on the axis.

Maybe we could add `showticksuffix = "hoveronly"`?

**Comment by alexcjohnson** [comment]
Thanks @Braintelligence - TBH I'm not sure what the purpose of `showticksuffix = "none"` (also for `showtickprefix`) is. It's there at least for symmetry with `showexponent = "none"`, and THAT has two purposes I know of: (1) reinterpreting the data without the extra exponent, for example if your data was in milligrams but you want the plot to look like it's in grams, or (2) to simplify the tick labels when you have another way to indicate the exponent to users, such as in the axis title. For use case (1) it's important that hover NOT show the exponent in hover, but for use case (2) it's probably mostly better if you DO show it in hover.

So yeah, I think in order to maintain this symmetry, the best solution would be to add `"hoveronly"` to all three of these attributes.

In the meantime though, could you get the effect you want just from `hovertemplate`? I guess that may be more awkward as it's a trace-level attribute and you want something that applies to all traces on the axis, but I'd think it should give the same final result.

**Comment by Braintelligence** [comment]
For my next project I'll try to use `hovertemplate` again; but it would be cool if `"hoveronly"` would be a thing :). Thank you for your helpful answer!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
