### ISSUE TITLE
Uncaught TypeError(d3_selectPrototype.text)

### ISSUE THREAD

**Issue by Jehoshaphat-kr** [plotly/plotly.js#6368]
Hi.

I am using Treemap function for Korean stock market map [https://the-day-after-tomorrow.tistory.com/50]
I have been using it for almost 2 years.

From a while ago, hovering and click-to-zoom is not working.
(click-to-zoom :: I am not sure I address it right... This is the function that you click on particular treemap object, it becomes large)

Error message is shown below.. 
Is there any way I can fix this?

In advance, Thank you for your kind feedback.

+) I am using "https://cdn.plot.ly/plotly-latest.js"

![image](https://user-images.githubusercontent.com/83201178/202395046-49176e6f-d553-4a13-a0ca-231aa9a1d3dd.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
