### ISSUE TITLE
bad link in getting started

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.js#6370]
the link to download plotly.js does not download. it opens the cdn in raw text.

my browser has no option to right click and save destination as file.

also, i couldn't copy the raw text, probably because it was too big.

where is the file i should use?

**Comment by cubetronic** [comment]
![Screenshot_20221119-114542_Firefox](https://user-images.githubusercontent.com/11820866/202868743-723312e5-e8e5-463c-9326-b9d765263a3c.png)

there is the link i am talking about. it says "Download plotly.js" but tapping the link does not download plotly.js

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
