### ISSUE TITLE
Touchscreen drag-and-drop to resize a selection box ("Box select")

### ISSUE THREAD

**Issue by josephernest** [plotly/plotly.js#6374]
Let's say you have made a selection with "Box select" tool.
Then you "touch and drag" (= drag and drop with touchscreen) the border to resize the selection box.

Problem: the drag-and-drop only resizes of a few pixels, and then stops.

**How to have a normal drag-and-drop behaviour to resize the selection box with a touch screen?**

Platform: PC Windows, Chrome, Samsung touchscreen

![image](https://user-images.githubusercontent.com/6168083/203293448-37004df3-42ec-492e-9a12-0f603d701ded.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
