### ISSUE TITLE
Slow rendering of image + slider with Plotly JS

### ISSUE THREAD

**Issue by josephernest** [plotly/plotly.js#6377]
Once an image/heatmap is rendered, no computation should be done, and moving a slider should be instantaneous. Instead, moving the slider here is *very slow* (1 second lag between each position), and uses max CPU %. Live demo: https://jsfiddle.net/nc7jLy1x/

**How to make a faster slider rendering with Plotly JS?**

[![enter image description here][1]][1]

    <script src="https://cdn.plot.ly/plotly-2.16.2.min.js"></script>
    <div id="myDiv"></div>
    <script>
    var z = [], steps = [], i;
    for (i = 0; i < 500; i++) 
        z.push(Array.from({length: 600}, () => Math.floor(Math.random() * 100)));  
    for (i = 0; i < 100; i++)
        steps.push({ label: i, method: 'restyle', args: ['line.color', 'red']});
    var data = [{z: z, colorscale: 'YlGnBu', type: 'heatmap'}];
    var layout = {title: '', sliders: [{
        pad: {t: 5},
        len: 1,
        x: 0,
        currentvalue: {
          xanchor: 'right',
          prefix: 'i: ',
          font: {
            color: '#888',
            size: 20
          }
        },
        steps: steps
      }]};
    Plotly.newPlot('myDiv', data, layout);
    </script>

  [1]: https://i.stack.imgur.com/XOHx0.png

---

PS: Idea: can we move the slider to a separate div, with no plot/graph ? we would use two Plotly.newPlot, one for the heatmap, and the other without any data, but just the slider. Is this possible? I couldn't make the latter.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
