### ISSUE TITLE
[Feature Request] Limit resize and move directions of persistent selection like selectdirection

### ISSUE THREAD

**Issue by maxmitti** [plotly/plotly.js#6378]
For creating selections with `dragmode: 'select'` it is possible to limit possible directions using the `selectdirection` attribute.
It would be useful to have a similar attribute to limit the directions in which a persistent selection (as added with #6243) can be resized and moved.

At the moment persistent selections are not useful when `selectdirection` is limited to one direction, since undesirable selections can be created by resizing or moving the selection box.

I have created an example with the mentioned settings: https://jsfiddle.net/9a083t75/
I would like to be able to change the example, such that after creating a selection by dragging, the resulting selection can also only be resized or moved horizontally.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
