### ISSUE TITLE
Question: Recreate shiny plotly chart

### ISSUE THREAD

**Issue by ndoulgeridis** [plotly/plotly.js#6380]
Hello,

I have an old chart from plotly on shiny. I am trying to recreate this on plotlyJS

![image](https://user-images.githubusercontent.com/3415953/204155161-10b0c633-b203-4450-8bcc-f43de02563f4.png)

Is there a way to add these labels with lines? The only I found is to add text over the bubbles but I need to be like in the photo, bubble, and then a line to the label on the left or right of it.

Thanks.

**Comment by alexcjohnson** [comment]
@ndoulgeridis are you able to recreate this chart in shiny and find the figure JSON? You can pull this out from the JavaScript console by selecting the div with class js-plotly-plot and then `JSON.stringify({data:$0.data, layout:$0.layout})`. I’m not sure what it’s doing to create these features.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
