### ISSUE TITLE
Exporting png or jpg from Safari does not work the first time

### ISSUE THREAD

**Issue by rlreamy** [plotly/plotly.js#6388]
We have an application that allows users to create scatterplots of gene expression across cells. We have enabled download of the resulting plot and in all browsers but Safari, this works beautifully. In Safari, you need to download it twice in order to get all of the points on the plot. The first time, you get the x and y axes, and the legend, but no points, the second time you get everything.

You can see this by going to http://atlas.kpmp.org/explorer, then search for a gene (APOL1 is a good gene name to try) and then select either the Single-cell or Single-nucleus dataset from the next screen. Give the app a few moments to retrieve the data and display the results, then try to download the right image from Safari and you will see it does not work the first time, but it does the second time.

Another way to reproduce is to simply download plotly.js and do the npm start and select something like gl2d_scatter-subplot-panel you can see that it will behave the same way.

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
