### ISSUE TITLE
vertical range slider

### ISSUE THREAD

**Issue by reasley-com** [plotly/plotly.js#6390]
Hello! I'm using a very good library well.

I want to use the vertical range slider function, but I can't find it, so I'm asking you a question.
Please let me know if I didn't find it or if there's any other way to use it!
Thank you very much.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
