### ISSUE TITLE
[Scatter3D/modeLine] Line not displayed correctly -> distorting the lines causing the visualization not to be like the expected

### ISSUE THREAD

**Issue by Quost** [plotly/plotly.js#6400]
### 3D Line is distorting the lines causing an ERROR to the expected visualization

I wrote more about it and also added an example [here](https://community.plotly.com/t/3d-line-is-distorting-the-lines-causing-an-error-to-the-expected-visualization/70886).

![image](https://user-images.githubusercontent.com/19558461/207921163-5272d0d8-b5ec-4fed-a9be-d0f4c0585f36.png)

https://user-images.githubusercontent.com/19558461/207941647-22042f1e-e1ca-4788-9e05-8a640afba350.mp4

**Comment by alexcjohnson** [comment]
Thanks @Quost - I also see the distortion and shaking you're describing in https://codepen.io/matheus-wc/pen/LYrwmbO
FYI `plotly-latest` is misleading, it's the end of the v1 releases, but if I upgrade to the real latest release (`plotly-2.16.5`) the issue is still present.

Since there's an indication this is machine-dependent (@archmoj?) I'm seeing this on an Intel MacBook Pro regardless of browser. @Quost what system are you using?
