### ISSUE TITLE
How to setup responsive chart with multiple axes?

### ISSUE THREAD

**Issue by Morritz** [plotly/plotly.js#6405]
The official example [https://plotly.com/javascript/multiple-axes/](url) shows how to setup multiple axes, but it doesn't go well with property "responsive" set to true in config, then when the width of the chart changes the axes may overlap each other.
Is there way to do it properly?
![image](https://user-images.githubusercontent.com/12800230/208134032-bed60ed8-2152-498a-a23c-a10a0350a6bc.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
