### ISSUE TITLE
Very slow heatmap color scale change with slider

### ISSUE THREAD

**Issue by josephernest** [plotly/plotly.js#6410]
The following code works to change the "min" of the color scale of a heatmap with a slider

[Live demo](https://jsfiddle.net/5wymr8aq/)

But it is very slow. How to have a more responsive / faster change of the color scale with a slider?

```
<script src="https://cdn.plot.ly/plotly-2.16.2.min.js"></script>
<div id="myDiv"></div>
<script>
var z = [], steps = [], i;
for (i = 0; i < 500; i++) 
    z.push(Array.from({length: 800}, () => Math.floor(Math.random() * 100)));  
for (i = 0; i < 100; i++)
    steps.push({ label: i, method: 'restyle', args: ['zmin', i]});
Plotly.newPlot('myDiv',  [{z: z, colorscale: 'Jet', type: 'heatmap'}], {sliders: [{steps: steps}]});
</script>
```

**Comment by GeorgeFlorian** [comment]
Hello.
Any luck with this ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
