### ISSUE TITLE
Xaxis changes when frame changed with sliders

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6421]
You can see it by lines. They change their position. (in json axis numbers also changes)
![2022-12-28_153734](https://user-images.githubusercontent.com/56681850/209813744-e744f828-8606-4574-87a4-675d141699c7.png)
![2022-12-28_153756](https://user-images.githubusercontent.com/56681850/209813752-bea3e6ea-7060-48ce-94b6-f4d623a4efda.png)

As you can see, lines changed their positions. So, axis changes it according to each frame axis. For example, if there will be frame with 1 marker, this plot will became so small. 

But how can I make stable Plotly, without that movement when I change frames?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
