### ISSUE TITLE
Get the current colorscale range (zmin, zmax)

### ISSUE THREAD

**Issue by josephernest** [plotly/plotly.js#6425]
How to get the currently computer colorscale range of a `heatmap`?

I haven't found anything in `document.getElementById("myDiv").layout`, in particular I haven't found a getter for `zmin`, `zmax`.

How to do it?

    <script src="https://cdn.plot.ly/plotly-2.16.2.min.js"></script>
    <div id="myDiv"></div>
    <script>
    var data = [{z: [[1, 2, 3, 4], [5, 6, 7, 8]], colorscale: 'YlGnBu', type: 'heatmap'}];
    Plotly.newPlot('myDiv', data, {}, { modeBarButtons: [['autoScale2d'], ['select2d']]});
    </script>

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
