### ISSUE TITLE
Passing slider tick values and positions as arguments

### ISSUE THREAD

**Issue by bonskotti** [plotly/plotly.js#6447]
Hi,

As far as I understand, it is not possible to give slider tick values or positions as arguments. The values and positions are currently defined based on the number of steps and the length of the slider. If the number of steps is a large number, it can result in a slider with unwanted tick values and positions.

![plotly_slider_example_1](https://user-images.githubusercontent.com/55254241/214836297-156e5f69-57b3-4781-a86d-a9f30bb7c04c.PNG)

There is a workaround for this, but it would be nice to be able to pass tick values and positions as arguments, like with Dash Slider ([https://dash.plotly.com/dash-daq/slider](url)).

Desired output would look something like this:
![plotly_slider_example_2](https://user-images.githubusercontent.com/55254241/214837664-9ace85db-1d01-4102-a897-14a1e0764139.PNG)

If this feature sounds good, I would be interested in developing it.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
