### ISSUE TITLE
Add resampling option to mapbox layers sourcetype "image"

### ISSUE THREAD

**Issue by gperaza** [plotly/plotly.js#6455]
Dear all, 

I am trying to load a local raster (as a png image) to a mapbox map using the "image" layer as instructed here:
https://plotly.com/python/datashader/

The image is loaded successfully and displays well on the map, but pixel edges appear blurred.
<img width="661" alt="image" src="https://user-images.githubusercontent.com/8594468/215596998-7dfc0549-9821-4bc1-936d-e2b74111f91f.png">

As far as I understand, this is caused by linear resampling being the default in mapbox as explained in the following link: 
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-raster-raster-resampling

I would like to use "nearest" resampling to recover the pixelated appearance of raster images.
As per https://github.com/plotly/plotly.js/issues/4490 this doesn't seem too difficult, since Mapbox already support this, but it still escapes my ability for a pull request.

Is there any change the option can be added?
Thanks

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
