### ISSUE TITLE
Scatter3d animation frames overwriting the data in frame[0].

### ISSUE THREAD

**Issue by TomBlackwoodTTM** [plotly/plotly.js#6460]
Plotting a scatter3d with an animation bar, frame[1] overwrites frame[0] in the _transitionData so you can never return to frame[0].

I also wrote about this problem in the plotly forum.

[CodePen](https://codepen.io/TomBlackwood/pen/GRBwWeg) example.

Is it overwriting the memory-space or something?

**Comment by TomBlackwoodTTM** [comment]
Solved the problem by 'cloning' the first frame for data and then adding the frames.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
