### ISSUE TITLE
zsmooth doesnt work with null values

### ISSUE THREAD

**Issue by mslvr40** [plotly/plotly.js#6468]
Given the following heatmap this will show a white square in the middle of the heatmap
```
var data = [
  {
    z: [[1, 20, 30], [20, null, 60], [30, 60, 1]],
    type: 'heatmap',
    zsmooth: 'best',
    colorscale: 'Jet'
  }
];
Plotly.plot('myDiv', data, {}, {showSendToCloud: true});
```

I want null values to be represented on the heatmap as white, However having a square in the middle of the map makes it look not smooth. 
Is there away to round the edges of the colors surrounding the null value so it doesn't stand out as much?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
