### ISSUE TITLE
Plotly JS selection issue

### ISSUE THREAD

**Issue by yujun2017** [plotly/plotly.js#6477]
This is a really good library. We are using Plotly JS in our project and planing to use this library in another projects. 
We do notice an issue for selection feature. When  When we selected using box select and lasso select, selection box will be kept and all other points became to dim. we have to double click to back to normal model.  This makes user confused. The double click only works well in small data and doesn't work in large data (greater than 1000 points). Also there is no way to reset Plotly screen to initial status. The selection box will keep until we refresh screen. 

John

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
