### ISSUE TITLE
Grouped legend has a large gap if it is the first item on the next line;

### ISSUE THREAD

**Issue by Tttaras1** [plotly/plotly.js#6482]
I noticed that the grouped legend has a considerable margin depending on the number of grouped elements if it is the first element in the next line.

https://jsfiddle.net/Tttaras/jz645dr2/13/

![image](https://user-images.githubusercontent.com/43076444/218728684-06ba2e9b-bd92-4f21-b90b-179249f3d391.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
