### ISSUE TITLE
Type definition error: nbinsx does not exist in type 'Partial<PlotData>'

### ISSUE THREAD

**Issue by evoinea** [plotly/plotly.js#6502]
Hi,

I'm getting this typescript error when trying to set nbinsx for a histogram chart:
![image](https://user-images.githubusercontent.com/89025096/221839065-7f22fc38-daa1-4be0-8364-ab44c0ce4f86.png)

I'm using ` "plotly.js": "^2.18.2"'

Thank you for the support!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
