### ISSUE TITLE
When i use Web Worker, i get 'window is not defined'.

### ISSUE THREAD

**Issue by Quska45** [plotly/plotly.js#6506]
Hi. i really enjoy your work in plotlyjs. Thank you.

But i have some ploblem use web worker.

When i use Web Worker, i get 'window is not defined'.

You have some idea this situation?

If i made a mistake in writing code, give some advice.

I use vite.

here is my code
```
import Plotly from 'plotly.js-basic-dist';

function addZero( time ){
    if( time < 10 ){
        time = '0' + time;
    };
    return time;
};

onmessage = async function( event ){
    const { data, layout } = event.data;

   Plotly.newPlot('myChart', data, layout);

    setInterval(() => {
        let date = new Date();
        let hour = addZero(date.getHours());
        let min = addZero(date.getMinutes());
        let sec = addZero(date.getSeconds());
        for(let i=0; i<count; ++i){
            data[i].x.push(`${hour}:${min}:${sec}`);
            data[i].y.push(Math.random()*100);
        }
        Plotly.redraw('myChart');
    }, 1000);

};
```

and error code is here.
```
var FIREFOX_VERSION_REGEX = /Firefox\/(\d+)\.\d+/;
lib.getFirefoxVersion = function () {
  var match = FIREFOX_VERSION_REGEX.exec(window.navigator.userAgent);
  if (match && match.length === 2) {
    var versionInt = parseInt(match[1]);
    if (!isNaN(versionInt)) {
      return versionInt;
    }
  }
  return null;
};
```

**Comment by Quska45** [comment]
Thank you for reply.
I hope  it will possible someday.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
