### ISSUE TITLE
event firing multiple times unnecessarily

### ISSUE THREAD

**Issue by skidvd** [plotly/plotly.js#6509]
I am noticing that at the time of chart creation/initialization various events, including plotly_afterplot and plotly_relayout, are being triggered multiple times (7 or more times each) without any changes to plot configuration nor data. Why are these being triggered so often? I had assumed that each would be triggered only once, but that does not appear to be the case?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
