### ISSUE TITLE
Support text templates for shape labels

### ISSUE THREAD

**Issue by emilykl** [plotly/plotly.js#6511]
Add support for text templates in shape labels.

Add a text template property to `shape.label`, with support for displaying variables which are updated automatically based on the shape's properties -- for example, the x/y coordinates of a rectangle or the slope of a line.

This feature depends on #6454 (Support adding text labels to lines and shapes).

## Proposed API

* Add a `shape.label.texttemplate` property
* Template string format identical to [`hovertemplate`](https://plotly.com/python/hover-text-and-formatting/#customizing-hover-text-with-a-hovertemplate) / [`texttemplate`](https://plotly.com/python/text-and-annotations/#customize-displayed-text-with-a-text-template), where variables can be included in the string using the syntax `%{variable}`.
  * Number format can be specified using [d3-format's syntax](https://github.com/d3/d3-3.x-api-reference/blob/master/Formatting.md#d3_format)
* A limited number of variables are supported, including at least:
   * Shape properties `x0`, `x1`, `y0`, `y1`
   * Calculated value `slope`
   * Possibility to include other variables
* Displayed text is updated in real time as values change, including during drag 

## Partnership

Development of this feature is sponsored by Volkswagen's Center of Excellence for Battery Systems.

<p float="left" align="center" >
<img src="https://user-images.githubusercontent.com/42301846/207075484-2c77d1e1-f0b5-43da-89bf-66ac73c50007.png" width=40% aspect-ratio=3/10 >
</p>

**Comment by emilykl** [comment]
Good point @JulianWgs . 

@alexcjohnson Any thoughts on how unit conversions could be achieved? For timeseries, is it possibly covered by d3 time formatting? https://github.com/d3/d3-3.x-api-reference/blob/master/Time-Formatting.md ?

More generally, could it make sense to support applying a multiplication factor to the slope value?

**Comment by emilykl** [comment]
Looping in @ndrezn here as well

**Comment by alexcjohnson** [comment]
I think the multiplication / division solution is the best here. Right now IIRC we support format strings in text templates, like `%{x:.3f}`, let's just put the operation before the colon (if there is one) so `%{slope*60000:.3f}`.

Does it make sense what numbers you'd want to use here? `60000` is msec/min, so would be used if you want your data in units of <y data>/min, since internally date data is represented as msec. We could try and come up with ways to name the units of ∂x and ∂y so you don't have to figure out the numbers, but that feels like it may be more confusion than it's worth, and we'll need arbitrary numbers anyway in order to cover all the edge cases people might think of.

@emilykl if we're just doing `<field><operation><value>:<format>` we can easily write a purpose-built parser from scratch. But if we ever want to do anything more flexible there's a relatively lightweight one we built for Dash Table [here](https://github.com/plotly/dash/tree/dev/components/dash-table/src/core/syntax-tree) and [here](https://github.com/plotly/dash/tree/dev/components/dash-table/src/dash-table/syntax-tree) that could be ported over. It looks more complex than it is 😉 - if we get to that point I can help.

**Comment by alexcjohnson** [comment]
@JulianWgs that's great, thanks for the feedback. Sounds like we're in agreement. `<field><operation><value>:<format>` where `<operation>` can either be `*` or `/` and `<value>` is a literal number.

For `slope` I can't think of any use case for more complex transformations. I could imagine for coordinate values maybe you want scaling and offset, like to convert between ºC and ºF, but there's no need to add that now.

**Comment by emilykl** [comment]
I agree, `<field><operation><value>:<format>` sounds like the sweet spot in terms of effort vs. payoff and covers @JulianWgs 's use case. Not sure we want to open the can of worms of supporting arbitrary calculations.

**Comment by mosaikme** [comment]
Hello thanks for this implementation,  i wonder if its possible to add percent calculation ?

I wanted to try to add this function. But the codebase is way to profesional for me, No way i can make a good PR for this.

I started to try to add this , but i dont even get , to the testing this. Becaus like i said the codebase is way over my programming skills.

[https://github.com/plotly/plotly.js/compare/master...mosaikme:plotly.js:mosaikme-patch-1](url)

I think the best would be be allowing this in direct in the texttemplate for example : "xPCT: %{ ( (x0 / x1) -1 ) * 100}"   this would give us so much freedom.

**Comment by alexcjohnson** [comment]
@mosaikme that's certainly a nice use case, but it seems to me a little too specific to add a dedicated field for `((x0 / x1) - 1) * 100` or even `((x0 / x1) - 1)` and let the user multiply by 100 with the existing capability. This would be better done with a more general syntax parser as I mentioned in https://github.com/plotly/plotly.js/issues/6511#issuecomment-1462937672.

Certainly not a simple addition, and unfortunately this isn't really on our roadmap any time soon but if you or anyone else is interested in sponsoring it we'd be happy to discuss.
