### ISSUE TITLE
No information on how to debug

### ISSUE THREAD

**Issue by crawlchange** [plotly/plotly.js#6520]
After drawing my first plot, it is empty, no data in it.

There is no warning or error on the console.

Absolutely no way to debug.

Absolutely no information on the docs on debugging. In fact, the in-built documentation search returns nothing for "debug".

Is this a half-serious project?

**Comment by alexcjohnson** [comment]
Our biggest user community by far is Python users, and [plotly.py](https://github.com/plotly/plotly.py) is more vocal about errors. Whereas the original JS consumer of plotly.js was [Chart Studio](https://chart-studio.plotly.com/) that's a bit more constrained but also intentionally flexible about ignoring invalid input because it's easy to get in a situation there that some settings are useless but the user doesn't care.

https://community.plotly.com/ will be happy to help with specific questions. But if you want a programmatic description of what we didn't recognize in your input, try [`Plotly.validate`](https://plotly.com/javascript/plotlyjs-function-reference/#plotlyvalidate)

**Comment by crawlchange** [comment]
Thanks @alexcjohnson .

Plotly.validate seems promising. My issue was solved by guessing, so I'll try it next time, unhopefully :)

Wouldn't it be the case to add mention to Plotly.validate somewhere in the documentation where it is easier to find? For example, the search for "debug" should probably land there. It is not usual that there is a separate function for validating function arguments (instead of the function throwing an exception) so most people probably have no idea about this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
