### ISSUE TITLE
YAxis title is horizontal

### ISSUE THREAD

**Issue by wanghe199512** [plotly/plotly.js#6523]
Recommendation: Line chart YAxis title can be displayed horizontally
![image](https://user-images.githubusercontent.com/38382084/225055552-7f3313cd-e23a-4dfe-950e-3547e1b9053f.png)

**Comment by 28raining** [comment]
I've never seen a graph with the y-axis title written horizontally. 
Could you share an example?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
