### ISSUE TITLE
Question / Docs: Hovertemplate for Datetimes

### ISSUE THREAD

**Issue by kfina91** [plotly/plotly.js#6525]
Minimalexample:
```
var dates = [1,2,3,4,5].map(x => `202${x}-01-01 0${x}:00:00`);
var data = [
    {
        type: 'scatter',
        x: dates,
        y: [5,2,3,1,4],
        hovertemplate: '%{x}',
    },
];
Plotly.newPlot('myDiv', data);
```

Hovertemplate gets shown as "Jan 1, 2021".
How to create a custom datetime format for hovertemplate? (e.g. 'dd.mm.yy hh:ii' or 'mm/dd/yy hh:ii')

**What I tried**
`hovertemplate: '%{x:de}'` For german locale (did not work)
`hovertemplate: '%{x:%d.%m.%Y %H:%M}'` using [d3 api-referecnce ](https://github.com/d3/d3-time-format/blob/v4.1.0/README.md#locale_format) (did not work)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
