### ISSUE TITLE
[Feature request] Wordcloud

### ISSUE THREAD

**Issue by pulien** [plotly/plotly.js#6526]
Hello,

While searching for word clouds with plotly I found that there was documentation for the matlab version but not the others. 
Is there a way to do it with the javascript version?
If not, is this type of plot planned to be supported?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
