### ISSUE TITLE
Scrolling browser window causes crazy zooming and spinning of surface plots

### ISSUE THREAD

**Issue by oscarrutt** [plotly/plotly.js#6539]
Scroll through a browser page containing a Plotly surface plot. Two-finger trackpad scroll on MacBook Pro, Firefox. When a normal scrolling action causes the surface plot to go under the cursor, the scrolling action is interrupted and immediately applied to the surface plot. This causes either unwanted zooming or unwanted rotation of the image, both of which are normally activated by a two-finger trackpad scroll _when the surface plot is under the cursor_. This is an extremely annoying bug. This problem is sometimes dealt with correctly in browser windows (not necessarily plotly) that have a scrolling window within the normal scrolling window. DO NOT TRANSFER A SCROLLING ACTION INTENDED FOR THE BROWSER WINDOW TO THE SURFACE PLOT UNTIL (1) THE SCROLLING IS OVER AND (2) THE SURFACE PLOT IS UNDER THE CURSOR. This might be a little tricky given inertial scrolling behavior but others have solved it.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
