### ISSUE TITLE
Better handling for hover of "missing" points in stacked charts

### ISSUE THREAD

**Issue by ldorigo** [plotly/plotly.js#6541]
When stacking two lines with unequal numbers of points, traces that have missing points get an ugly `%{val}` displayed in their hover text.

Repro: https://jsbin.com/yimadabece/edit?html,output

This is related to https://github.com/plotly/plotly.py/issues/3515 , but remaking it here since 1. it's really a plotly.js issue and 2. the workarounds there don't work, since for stacked plots there is no data for which it's possible to make dummy hover texts.

![Screenshot_20230329_151750](https://user-images.githubusercontent.com/8631181/228550452-7605c14f-e8dc-4c40-a724-6f7bb90b92c1.png)

**Comment by Sinnaeve** [comment]
I agree that option to ignore missing point in custom hover would be good.
`But doesn't the workaround still work ? Can't you create dummy value at 0 on your missing points, then associate dummy hover text to them.

Like that in you're example:
````
x1 = [0, 1, 2, 3, 4, 5];
y1 = [0, 1, 2, 4, 8, 16];
x2 = [0,1,2,3, 4, 5];
y2 = [0,0,0,4, 3, 2];
texts_1 = ["A", "B", "C", "D", "E", "F"];
texts_2 = ["", "", "", "G", "H", "I"];
````

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
