### ISSUE TITLE
Feature Request: Remove contours and spikelines if hoverinfo="none"/"skip" or hovermode=False in go.Surface

### ISSUE THREAD

**Issue by celia-lm** [plotly/plotly.js#6545]
Context: https://github.com/plotly/plotly.py/issues/4133

I think it makes sense that, if a user has specified `fig.update_layout(hoverinfo="none")` or `hoverinfo="skip"` or `hovermode=False` they won't want any type of hoverevents. By default, making these changes in a go.Surface figure don't change the behaviour of contours or spikelines.

So, I would want something like:
```
if hoverinfo in ["none", "skip"] or not hovermode : 
    fig.update_traces(contours_x_highlight=False, contours_y_highlight=False, contours_z_highlight=False,)
	fig.update_scenes(xaxis_showspikes=False, yaxis_showspikes=False, zaxis_showspikes=False)
```

There might be other property changes where it would make sense to apply these changes, or other properties that should be changes, but those are the ones I could think of!

Thank you!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
