### ISSUE TITLE
Why we use d2l in annotation

### ISSUE THREAD

**Issue by tanujdrivetech** [plotly/plotly.js#6550]
Hi,
can anyone explain why we use d2l in annotation. For ex:- "point.xaxis.d2l(point.x)"
because when we use this and our data point is a date, add annotation not working as expected.
d2l converting date into epoch time and when we relayout for adding annotation this time converting according to local timezone and that causing annotation to place on unwanted data point.

thanks in advance

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
