### ISSUE TITLE
Update updatemenus with updatemenus 

### ISSUE THREAD

**Issue by VePaKo** [plotly/plotly.js#6558]
Hello everone!
I have following problem with updatemenus on python:
Shortly I want to make two drop down menus visible/invisible with another (third) drop down menu.
Not shortly: Let's imagine I have 2 minutes d and m, one of which represents scatters with day periodicity another with month. At the same time I want to see only one of them. So I want to create the third button which relayout or update previous two and make one of them visible another invisible. And in this case in updatemenus I have a list of 3 updatemenus_dicts
Is it possible to do it on python? 
I have already tried different options and one of my favorite (but not workable) is create the third button as:
dict(
active =1,
buttons = [
{method = ”relayout”,
args = [{'updatemenus':{'visible':[True,False,True]}}]},
{method = ”relayout”,
args = [{'updatemenus':{'visible':[False,True,True]}}]}
]
)
But when I do so the buttons don`t switch their visibility

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
