### ISSUE TITLE
Colours painting between animated frames when transition duration is set to 0

### ISSUE THREAD

**Issue by jshallow90** [plotly/plotly.js#6562]
Hi Plotly team!

I have an issue in one of my plots, I'm using a stacked horizontal bar chart to display a lot of varying price quantities. I'm using a custom callback to move from one frame to the next. 

The issue I'm seeing is that when there are a lot of stacked bar charts present, moving between the 2 frames repaints the colours of the graph and makes it tricky to track individual bars.

I've created and example in https://codepen.io/some_random_username/pen/rNqOJQE and the "next" button (changeFrame function) will simulate the behaviour. Also attached is a video showing the behaviour. I'm not sure if this is related to length of the array I'm presenting / the colours I'm using on each bar, so any advice to get this transitioning smoothly without animations would be appreciated. 

Thanks!
[screen-capture.webm](https://user-images.githubusercontent.com/31829840/231403108-f08e4446-da3b-4eb8-a203-c6faa0b51147.webm)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
