### ISSUE TITLE
Support multiple labels for shapes

### ISSUE THREAD

**Issue by emilykl** [plotly/plotly.js#6568]
Modify `shape.label` property to accept either a single label or an array of labels. This will allow multiple labels to be attached to a single shape.

For example:

```
        "shapes": [
            {
                "label": [
                    {
                        "text": "Top left label",
                        "textposition": "top left"
                    },
                    {
                        "text": "Bottom right label",
                        "textposition": "bottom right"
                    }
                ],
               ...
          },
     ],
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
