### ISSUE TITLE
Support different `newshape` defaults for different shape types

### ISSUE THREAD

**Issue by emilykl** [plotly/plotly.js#6569]
Allow the user to define different `newshape` defaults depending on whether the drawn shape is a line, rectangle, circle, etc.

For example, new rectangles could be drawn with a red outline but new lines drawn in black. This would also support adding a label to new lines, but not other shapes.

One way to implement could be adding additional `layout` keys like `newshape-line`, `newshape-rect`, etc., but not sure if this is the most elegant -- any thoughts @alexcjohnson ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
