### ISSUE TITLE
Hover placement issue on coupled hover(overlap)

### ISSUE THREAD

**Issue by yRmog** [plotly/plotly.js#6577]
Hello !

I'm trying to sync hover on subplots and it works perfectly but I'm facing with one issue that the hoverbox overlap on other graph like in the screenshot , the bloack outlined hoverbox is on the third grahp and also there is a gap between the green and blue one 

![Screenshot from 2023-04-20 17-07-56](https://user-images.githubusercontent.com/124313840/233409647-dc0122d9-73b3-4921-a0e8-458364aadbfd.jpg)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
