### ISSUE TITLE
3d charts do not support automargin in axis settings

### ISSUE THREAD

**Issue by jumbox-cz** [plotly/plotly.js#6578]
I would need long labels on the axes in 3d charts. However, these are centered in the space between the chart and the title. I can't control the distance of the title from the graph though.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
