### ISSUE TITLE
Bar marker is hidden for log axis

### ISSUE THREAD

**Issue by elv1s42** [plotly/plotly.js#6585]
When using a bar chart with non-zero marker lines, it is possible to see the bars with zero values, here is an example: 
![image](https://user-images.githubusercontent.com/6689884/235363998-e148e2f9-f324-45b8-b26d-f3f19ccc85e9.png)
```javascript
var data = [
  {
    x: ['A', 'B', 'C'],
    y: [40, 1, 0],
    type: 'bar',
    marker: {line: {width: 3}}
  }
];

layout = {
  hovermode: 'x',
  autosize: true,
  margin: { l: 20, r: 20, t: 20, b: 20 }
}

Plotly.newPlot('myDiv', data, layout);
```
But the marker lines are no longer visible when switching to log axis type:
```javascript
layout = {
  hovermode: 'x',
  yaxis: {
    type: "log"
  },
  autosize: true,
  margin: { l: 20, r: 20, t: 20, b: 20 }
}
```
![image](https://user-images.githubusercontent.com/6689884/235364076-e26828ee-9fec-461f-98ec-cdf3126369f8.png)

Is this an expected behaviour?
Please see the codepen example [here](https://codepen.io/elv1s42/pen/KKGqgaa)

**Comment by alexcjohnson** [comment]
Yes, that’s expected. On a log axis zero is infinitely far away from 1, so you could zoom out as far as you want and you still wouldn’t reach zero.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
