### ISSUE TITLE
Radarchart/scatterpolar don't always seem to fit labels to a constrained space 

### ISSUE THREAD

**Issue by thongchatbananacoding** [plotly/plotly.js#6587]
Hello this is my chart happened, it should `automargin`

<img width="512" alt="Screen Shot 2566-05-02 at 16 52 46" src="https://user-images.githubusercontent.com/76507510/235638374-66b07f61-b1b7-4151-9673-25d60a2b0ffc.png">

Here is my layout that i add `automargin` as much as i can BUT still doesn't work
```
layout = {
  polar: {
    angularaxis: {
      rotation: 90,
      direction: "clockwise",
      ticks: "",
      linecolor: grey60,
      gridcolor: grey60,
      tickfont: {
        family: "Lato",
        color: grey140,
        size: 16,
      },
      automargin: true,
    },
    radialaxis: {
      ticklen: 2.3,
      tickcolor: grey120,
      tickfont: {
        color: grey120,
      },
      linecolor: grey120,
      gridcolor: grey60,
      automargin: true,
    },
  },
  showlegend: false,
  margin: {
    t: 40,
    b: 40,
    l: 40,
    r: 40,
  },
  autosize: true,
  xaxis: {
    automargin: true,
  },
  yaxis: {
    automargin: true
  }
}
```

Do the `plotly.js` not supported the Radar chart for `automagin` to fit labels ?

Can someone please give me suggestion thanks !

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
