### ISSUE TITLE
Single date trace not showing in heatmap when range is specified

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.js#6594]
A heatmap trace is not visible when the trace defines only one date and an x-axis range is specified (date lies within the specified range).
https://jsfiddle.net/41aecz9q/ (trace1 not visible)

If there are two or more dates in that trace, it will rendered rendered.

Is there any workaround I can use besides adding artificial dates?

Thanks,
Matthias

**Comment by alexcjohnson** [comment]
The problem here is that we don't know how wide you want a brick to be if there's only one brick. With two or more we can infer that from the next coordinate. With only one we use a default width of 1, which for dates means 1ms because that's the internal representation of dates. It's not a great default but it's not clear what would be better.

There's an alternative form for heatmaps where instead of providing the center positions of the bricks (for `x` or `y`) you provide the edges - ie if your z matrix has dimension MxN, instead of using length M for the `x` array you can use M+1. That removes this ambiguity.

Another way to do this is instead of an x array, use the attributes `x0` (the center of the first x brick, as a time string) and `dx` (the width of each brick, in milliseconds). That only works if all the bricks have identical widths.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
