### ISSUE TITLE
layout legend.itemclick and legend.itemdoubleclick should get radio-button behavior option

### ISSUE THREAD

**Issue by schlatterbeck** [plotly/plotly.js#6617]
Feature request:
Currently legend.itemclick and legend.itemdoubleclick can be configured to 'toggle' or 'toggleothers'.
For some applications -- where only one trace at a time should be shown -- a third option 'radio' (I'm unsure of the name) should be added. The semantics is radio-button-like behavior: When clicking on a legend item only that item is shown, all others are turned off. This is especially interesting for showing one of several 3D-Plots at a time.

For a use-case see my antenna plot program: This shows an antenna gain pattern as 3D. Frequencies are selectable in the legend. Only one 3d plot is shown at a time.

https://blog.runtux.com/content/2022/12-el-1deg-plot3d.html
source is https://github.com/schlatterbeck/plot-antenna

[Note that currently a 3D plot makes it almost impossible to use the legend feature, I had to use the legendgroup feature to tie the (invisible) legend items of the 3D plot to a scatter plot used only for switching the 3D plots.]

I'm currently simulating radio-button behavior with my own custom javascript:
```
            var myPlot = document.getElementById('{plot_id}')
            myPlot.on ('plotly_legendclick', function(clickData) {
                         var xlen = clickData.data.length;
                         //console.log (clickData);
                         for (var i = 0; i < xlen; i++) {
                            clickData.data [i].visible = 'legendonly';
                         }
           });
```
This disables all currently-selected legend items and the configure legend action then makes the clicked item visible as the only item. Having a third option in addition to 'toggle' and 'toggleothers' for legend.itemclick and legend.itemdoubleclick would make this use-case much easier.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
