### ISSUE TITLE
Inaccuracte margin spacing for container-referenced legends and colorbars

### ISSUE THREAD

**Issue by hannahker** [plotly/plotly.js#6624]
As discussed [in this comment](https://github.com/plotly/plotly.js/pull/6616#discussion_r1211840299), plots where the `xaxis` domain is constrained and where there is a container-referenced legend or colorbar may end up with inaccurate plot width and margin area. With a container-referenced legend we force the right margin to be at least as wide as the legend, even if there’s nothing as far right as paper-position=1.

**Comment by hannahker** [comment]
cc @alexcjohnson as you have some detailed thoughts on how to address this.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
