### ISSUE TITLE
How can I disable zoom without disabling pan - dragmode: "pan" does not disable zoom

### ISSUE THREAD

**Issue by GeorgeFlorian** [plotly/plotly.js#6650]
I am interested in disabling only zoom on a Choropleth Map but keep the pan feature.

The only way to disable `zoom` is to use `dragmode: false` which also disables `pan`.

Using `dragmode: "pan"` does not disable `zoom`.

I am using the following types of maps:
- `type: "scattergeo"`
- `type: "choropleth"`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
