### ISSUE TITLE
Double click does not work on Mesh3D

### ISSUE THREAD

**Issue by ReinderVosDeWael** [plotly/plotly.js#6658]
Hi, I'm trying to add a double click event to a mesh3D plot. This plot seems to register single clicks just fine, but double clicks are not registered (see attached code pen). Am I doing something wrong? Is this a bug? Is there a workaround? 

https://codepen.io/ReinderVosDeWael/pen/PoxmOmZ?editors=1011

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
