### ISSUE TITLE
Histogram does not correctly display trace with single X value (when another trace has more than one X value)

### ISSUE THREAD

**Issue by sgalla** [plotly/plotly.js#6661]
From what I can tell, this specifically happens when the histogram has more than one trace where one trace has more than one X value and the other trace has one X value.

Here is a codepen that demonstrates the bug: https://codepen.io/Shannon-Gallagher-the-bold/pen/XWyRVar

It appears that "Results B", the dataset with a single result, renders as a line at the exact X value, rather than the bar overlay that is the full width of the bin. Adding an X value to trace2 ("Results B") results in expected behavior (uncomment line 25 in the codepen and comment line 24).

Below are photos for reference. The first shows the broken behavior when the trace has a single X value. The second shows expected behavior that is seen when a second X value is added to the trace data.

(Note: I do see this working as expected up until version 1.41.3.)

<img width="1781" alt="Screen Shot 2023-06-30 at 11 49 39 AM" src="https://github.com/plotly/plotly.js/assets/8962302/332437fc-d805-4004-b3a3-201d37994807">

<img width="1780" alt="Screen Shot 2023-06-30 at 11 49 50 AM" src="https://github.com/plotly/plotly.js/assets/8962302/bb1b2f12-24b6-47f1-bc88-5992a592cf48">

**Comment by 28raining** [comment]
Created PR to fix this https://github.com/plotly/plotly.js/pull/6725

The PR does fix this issue. But, like I said in PR, because May is 31 days and June is 30 then using a single point in May ends up making the bar slightly wider. Fixing that would be a much bigger code change... and could break other stuff.

**Comment by 28raining** [comment]
Note you can use bingroup to fix this. 
I think you should be using bingroup anyway, but the fix I made removes that requirement
https://codepen.io/28raining/pen/OJrxjBo

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
