### ISSUE TITLE
How to import plotly extendTraces in a react app? 

### ISSUE THREAD

**Issue by nikelborm** [plotly/plotly.js#6662]
I tries many differrent examples of imports, I even tried to import it with `import { extendTraces } from 'plotly.js/src/plot_api/plot_api';` but it allways throws different kinds of errors. Most of them related to failed bundle of somethin `buffer/ image`. Import from plot_api fails with different error that some categories not found

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
