### ISSUE TITLE
Feature or Bug: Resize plot on parent-div resizing (responsive)

### ISSUE THREAD

**Issue by eqvis** [plotly/plotly.js#6688]
Hi, 

we use plotly with typescript on a SPA. It works very good. But we have some space problems and we try to solve them hiding some parts of the UI (maximize/minimize view) or adding splitter (primeng) to let the user decide what to show. There is a tree with files that contains the data, some input in forms to choose what to show an how and then a part for the plot itself.
But hiding the tree or changing the panel sizes with the splitter doesn't change the size of the plot automatically - And we want this!

Here is an example:
[codepen](https://codepen.io/eqvis/pen/zYMmxzM)

Resizing the div container, the plot remains same size as before (resizing the iframe using the splitter on codepen does the trick!). We did a workaround with a MouseOver event on `var plotlyReactObj = divContainer.querySelector("svg.main-svg>g.draglayer>g.xy>rect.nsewdrag.drag")` But this is very fragile!

Please fix this!

Best regards,
Mayra

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by Jdruwe** [comment]
@eqvis did you end up finding something better?
