### ISSUE TITLE
TypeError: Cannot assign to read only property 'color' when loading a graph returned from Redux API

### ISSUE THREAD

**Issue by miklcct** [plotly/plotly.js#6710]
The Plot component generates an exception and returns an empty div when a graph returned from Redux API is used:

```
<Plot {...graph}/>
```
It generates an exception `TypeError: Cannot assign to read only property 'color'` inside the library code.

The graph is returned from a Redux API endpoint defined something similar to the below:
```
builder.query<PlotParams, {}>({
      query: (args) => `api/generate_graph`,
    })
```

For state management, Redux protects all returned objects preventing modification to be made inside them.

The same graph can be displayed if a deep copy of the graph is made:

```
<Plot {...structuredClone(graph)}/>
```

**Comment by Nageshwararaov** [comment]
I am also facing the same error.

**Comment by Nageshwararaov** [comment]
This fixed my issue, Object has its own reference in memory to destroy it you can use JSON.parse(JSON.stringify(object)).

Link - [Reference Link ](https://stackoverflow.com/questions/48710797/how-do-i-deep-clone-an-object-in-react#:~:text=can%20use%20JSON.-,parse%20(JSON.,deep%20copy%20or%20deep%20clone.)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
