### ISSUE TITLE
Bar chart rendering issues

### ISSUE THREAD

**Issue by TR-fengxing** [plotly/plotly.js#6715]
When I wanted to use a bar chart to achieve this straight line effect, I found that some of the columns in the picture were not rendered
![image](https://github.com/plotly/plotly.js/assets/124949725/1fdcfdf4-f56c-4f74-b570-57145a20ef3f)
I tried setting the line width to 0.5, but at this point the lines don't look smooth enough
![image](https://github.com/plotly/plotly.js/assets/124949725/8e48011a-4a3f-4ebd-b7db-9862bbfa822f)

**Comment by TR-fengxing** [comment]
![image](https://github.com/plotly/plotly.js/assets/124949725/6b09e230-c890-4feb-811f-369403ab96fa)

**Comment by alexcjohnson** [comment]
The bars in bar charts have antialiasing disabled, but we do try to adjust them so that at least one pixel is always visible. Giving your bars a width of 0 and a line width of 0.001 is pushing our algorithm to its edge though. Is it fixed if you increase that line width to something like 0.5? Can you share a link ot that codepen?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
