### ISSUE TITLE
TypeError: next is not a function at Object.viteServeStaticMiddleware when inserting iframe

### ISSUE THREAD

**Issue by linustws** [plotly/plotly.js#6717]
As the title says, when i try to insert an iframe with the src attribute being the absolute filepath, i get the error in a black box:
![image](https://github.com/plotly/plotly.js/assets/97421565/9e03694f-9764-42b6-8970-c2149823d4fc)

The iframe i'm trying to insert is a .html file that has a plotly graph. I'm trying to do this with SvelteKit.

```
<div class="output_html rendered_html output_subarea ">
     <iframe scrolling="no" width="100%" height="545px" src="src/lib/model/model_iframe_figures/figure_4.html" frameborder="0" allowfullscreen=""></iframe>
</div>
```

I'm pretty sure that it can find the iframe files and it seems that the next() function cant be found. I've searched online and havent found similar issues that has to do with inserting iframes.

I tried inserting this script tag: <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/3.32.1/minified.js" integrity="sha512-ZvqqKs1oYkDfMwsIQTpW2OnKhSsTjMvIch9JbsNti/odAAe3B88WyZc8XIVDK9wNN/+sI58v7HUVHhnKaZ2yHg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

in the html file but it didn't work also...

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
