### ISSUE TITLE
how to download the plot in pdf format in chrome browser using plotly.js

### ISSUE THREAD

**Issue by honghh2018** [plotly/plotly.js#6729]
Thanks for your interest in plotly.js!

Before opening an issue, please search for existing and closed issues. If your problem or idea is not addressed yet, [please open a new issue](https://github.com/plotly/plotly.js/issues/new).

Bug reports **must** be accompanied with a reproducible example. We recommend using [codepen](http://codepen.io/), [jsfiddle](https://jsfiddle.net/) or [jsbin](https://jsbin.com) to share your example. Please use the [latest un-minified version](https://cdn.plot.ly/plotly-latest.js) of plotly.js in your report unless not applicable.

If you don't know JavaScript and still want to help us by reporting a bug, please attach the `"data"` and `"layout"` attributes that describe your graph and updates (if required to detect the bug). One way to retrieve your graph's data and layout attributes is by exporting your graph to [Plotly Cloud](http://plot.ly/). To do so, click on the _Edit in Chart Studio_ mode bar button (the 2nd one from the left by default) and follow these [instructions](https://help.plot.ly/save-share-and-export-in-plotly/), or watch this [screencast](https://community.plot.ly/t/mega-sharing-graphs-with-chart-studio/8869).

Issues found on the example pages from https://plot.ly/javascript/ should be filed in our [documentation repo](https://github.com/plotly/documentation/issues) with the exception of https://plot.ly/javascript/reference which should be filed here.

Note that GitHub issues are reserved for bug reports and feature requests only. Implementation questions should be asked on community.plot.ly (tagged [`plotly-js`](http://community.plot.ly/c/plotly-js)) or on Stack Overflow (tagged [`plotly`](https://stackoverflow.com/questions/tagged/plotly)).

Comments on GitHub issues or pull requests should add content to the discussions. Approbation comments such as *+1* or *I would like this feature to be implemented as well* will be deleted by the maintainers. Please use [GitHub reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead.

Thanks to develop the great tool for graphic visualization,
     I wonder the browser to download the pdf when using the plotly.js to plot a bar or other type of graphic,
     I saw the download format just only contain the png, svg jpeg but pdf,   in my opinion, the svg would be large than pdf when using the big data to draw a big graphic to download. so i want to turn to pdf format download to minimize the file size.

so,  in this case, i can not find the documentation of this solution case, so how can i convert the plotly.js plot into pdf to download
 any advice would be appreciated.
Best, 
hanhuihong

**Comment by 28raining** [comment]
Does this help?
https://png2pdf.com/

If not, could you share an example .svg file, and an example .pdf file that you would like Plotly to create.

**Comment by alexcjohnson** [comment]
PDF generation is awkward within the browser, unfortunately - we haven't found a workable way to build this in like you can with the other formats. If you're just concerned about file size I don't think SVG should be much worse than PDF if at all. The issue with SVG typically is in fact the opposite: it does NOT include fonts, which can make it smaller but causes it to render differently in different environments (even on the same computer) which not only makes it look different, but can make the text overflow its container, since we use the as-rendered size of the text in the browser to decide how much margin to add, how big a box to put around legends and annotations, etc.

Browsers can generally print to PDF, but this isn't available programmatically. So the best I can suggest is to save as SVG, reopen that in the browser, and print to PDF. You should be able to remove the step of saving the SVG, and just open a new window/tab with only the plot in it, which the user can then save as a PDF directly - which should also enable you to ensure the right fonts are loaded.
