### ISSUE TITLE
Feature: Country colour coding according to filter

### ISSUE THREAD

**Issue by droberts-ctrlo** [plotly/plotly.js#6731]
We have a specific use-case we are using plotly.js for within the company I work for; we sometimes need to colour-code countries according to specific criterion within a geo map - for example, we may need all predominantly English speaking countries to be Blue, all  predominantly French to be green, predominantly Spanish to be yellow, etc.

We have implemented this for our use-case, and wonder if it would be useful for the community; should it be as such, we can open a pull request of our code, and work from there.

**Comment by 28raining** [comment]
Have you tried Choropleth maps?
https://plotly.com/javascript/choropleth-maps/

**Comment by alexcjohnson** [comment]
Thanks @droberts-ctrlo - I'm curious to hear about what you implemented. From the sound of it I'm guessing you already have a choropleth, and I think what you're adding is a flavor of categorical colorscales https://github.com/plotly/plotly.js/issues/1747. The alternative for this kind of data is to break it into different traces, one per category, and give each trace a fixed color. This is what `plotly.express` does from the Python side, but we don't have a clean way to construct traces like this purely in JS.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
