### ISSUE TITLE
Timestamp '1970/01/01 00:00:00' formats as 'undefined' in hovertext

### ISSUE THREAD

**Issue by adamjhawley** [plotly/plotly.js#6751]
I tried to customise the hovertext format of some timestamp data and found that the timestamp '1970/01/01 00:00:00' formats as 'undefined'.

**_Note: please hover over the first data point in the example below to see the issue I am describing._**

Minimal example to recreate the issue ([CodePen here](https://codepen.io/adamjhawley/pen/oNJKYYa)):
```javascript
var dates = [0,1].map(x => `1970-01-01 00:00:0${x}`);

var data = [
  {
    type: 'scatter',
    x: dates,
    y: [5,2,3,1,4],
    hovertemplate: "%{x}, %{y}"
  }]

var layout = {
  xaxis: {
    tickformat: '%H:%M:%S',
    hoverformat: '%H:%M:%S'
  },
}

Plotly.newPlot('myDiv', data, layout);
```

I am happy to try and fix this issue myself but could benefit from someone pointing me in the right direction. I presume that the issue is caused by something like "0 seconds since epoch" is wrongly resolved as falsey at some point.

Thanks in advance for any pointers/help!

**Comment by archmoj** [comment]
Nice find :1st_place_medal: 
After long investigation, 
it looks like the bug is coming from this block:
https://github.com/plotly/plotly.js/blob/630b092a3878942a61f8fd7b08ac1b98a1abe86e/src/plots/cartesian/axes.js#L1770-L1779

Perhaps we should modify the first if statement to be something like:
```js
if(headStr !== undefined && (dateStr === '00:00:00' || dateStr === '00:00')) {
```

I am looking forward to reviewing your pull request.
FYI - Our contributing information is at https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md
