### ISSUE TITLE
How to use background-color and opacity for hovertemplate Plotly.js 3D Scatter

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.js#6764]
I'm using the Plotly.js library to create 3D Scatter Plots. I'm using the bgcolor attribute in hoverlabel to adjust the color of the template when hovering. I have specified the opacity in that attribute as rgba(188, 20, 26, 0.5), but it seems that the opacity is not working. Can you please guide me on how to correctly use bgcolor and opacity on hoverlabel in Plotly.js 3D Scatter plots? Thank you!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
