### ISSUE TITLE
Should traces with hovermode: 'none' impact hover radius for other traces?

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#678]
I am using a trace as an error interval around a main trace. I don't want the user to be able to hover over the error interval, so I've marked it as hovermode: 'none'. However, this makes it very difficult to hover over the trace which it surrounds.

In the example, the dark green trace labeled "Fair" is difficult to hover over due to its interval. The blue trace labeled "Premium" is easy to hover over.

http://codepen.io/john-soklaski/pen/vKyxNQ

This seems like it is a bug, or is there a better way to accomplish this?
Thanks!

**Comment by etpinard** [comment]
I wouldn't call this bug because we -- on purpose -- consider `hoverinfo: 'none'` traces in the hover picking routine in order to fire `plotly_hover` events from them. See PR https://github.com/plotly/plotly.js/pull/385 for more info.

But, this is a limitation of our API. I think we should add a `hoverinfo` flag (something like `'hide'`) to handle the case where a user wants to hide the hover labels but still be able to grab event data from them. Correspondingly, `hoverinfo: 'none'` would effectively remove the trace from the hover picking routine all together and thus remove its impact on the hover radius, like you desire here.

**Comment by etpinard** [comment]
> [...], or is there a better way to accomplish this?

I can't think of an easy way to accomplish this unfortunately.

**Comment by john-soklaski** [comment]
@etpinard Is this along the lines you were thinking? https://github.com/plotly/plotly.js/compare/master...john-soklaski:hoverinfo_hide

**Comment by etpinard** [comment]
@john-soklaski looks like you're on the right track. 

In its current form, we can't merge your patch in the `v1.x` branch, because we're effectively changing the `hoverinfo: 'none'` behaviour. In other words, what `'none'` currently does is transferred to `hoverinfo: 'hide'`. 

Instead, maybe we should keep `hoverinfo: 'none'` the way it is and add e.g. `hoverinfo: 'skip'` - which would make the picking routine completely skip over the trace in general.

Thoughts?

**Comment by john-soklaski** [comment]
@etpinard I think that is a good solution, I'll updated my branch and send a PR.

**Comment by etpinard** [comment]
@john-soklaski Great. 

Make sure to test out the behaviour in `gl3d` traces (which I think don't have `hoverinfo: 'none'` hover test at the moment).

**Comment by etpinard** [comment]
closed via https://github.com/plotly/plotly.js/pull/851
