### ISSUE TITLE
Implement resize on editable drag on 'path' type layout shapes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#682]
Follow up issue after @n-riesco 's https://github.com/plotly/plotly.js/pull/660.

Foundations in https://github.com/plotly/plotly.js/pull/660#issuecomment-227716924

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
