### ISSUE TITLE
Plotly fails when using "scattergl" and value greater than 2^24 [Only on M1]

### ISSUE THREAD

**Issue by ravikirankhareedi** [plotly/plotly.js#6820]
When plotting using Plotly.newplot() and type scattergl on M1 machine, the plotting fails if the value of x-axis is greater than 2^24. 
Example: 

```
var data = [
  {
    x: [16777217],
    y: [1],
    type: "scattergl",
  }
];

Plotly.newPlot('myDiv', data);
```
![Screen Shot 2022-03-01 at 9 27 12 PM](https://user-images.githubusercontent.com/7555400/156300999-383d4502-030b-42bc-8da3-1c47e7fe5837.png)

 The data gets plotted on the margin which cannot be zoomed/panned. (16777217 is 2^24 + 1)
Attached screen shot. The issue only happens on M1 machine. On Intel hardware everything works well.

**Comment by Coding-with-Adam** [comment]
hi @justinjhendrick 
Thank you for confirming the solution. Would you be able to create a pull request with the fix?

**Comment by justinjhendrick** [comment]
@Coding-with-Adam, yes, I'll give it a shot!

I have a couple questions about how to do this:
1) I'm going to try to fix this for all the relevant shaders, but I'm not totally sure how to find all the affected shaders and a good test case for each one. I might need to start by just fixing this on just scattergl. And fix each webgl plot type, one at a time with multiple PRs.
2) Some of the affected shaders are in dependent packages (such as https://github.com/gl-vis/regl-scatter2d). Are the maintainers of these dependencies as motivated to fix this as plotly devs are?
3) [Related to point 2] is there a performance penalty? If so, how big? According to [this comment](https://github.com/plotly/plotly.js/issues/6820#issuecomment-1858396828), plotly is likely not bottlenecked on webgl render. But if I'm making changes to dependencies, other packages might have be bottlenecks in different places. Are there benchmarks I can use to quantify the performance penalty?

**Comment by archmoj** [comment]
> @Coding-with-Adam, yes, I'll give it a shot!
> 
> I have a couple questions about how to do this:
> 
> 1. I'm going to try to fix this for all the relevant shaders, but I'm not totally sure how to find all the affected shaders and a good test case for each one. I might need to start by just fixing this on just scattergl. And fix each webgl plot type, one at a time with multiple PRs.
> 2. Some of the affected shaders are in dependent packages (such as https://github.com/gl-vis/regl-scatter2d). Are the maintainers of these dependencies as motivated to fix this as plotly devs are?
> 3. [Related to point 2] is there a performance penalty? If so, how big? According to [this comment](https://github.com/plotly/plotly.js/issues/6820#issuecomment-1858396828), plotly is likely not bottlenecked on webgl render. But if I'm making changes to dependencies, other packages might have bottlenecks in different places. Are there benchmarks I can use to quantify the performance penalty?

@justinjhendrick we also maintain `gl-vis` modules. Let's start by the minimal PR to `regl-scatter2d` and provide a link to this issue in its description. After that we will could have a look at rendering times on CircleCI, etc. But at this point I'm not too worried about the performance side effect.
Thank you!

**Comment by justinjhendrick** [comment]
In response to point 1 from [my earlier comment](https://github.com/plotly/plotly.js/issues/6820#issuecomment-1868014189), I went looking for other affected WebGL trace types in addition to scattergl. I couldn't find any others that are affected by this same bug. I checked the following trace types:

```
        type: "streamtube",
        type: "cone",
        type: "mesh3d",
        type: "heatmapgl",
        type: "surface",
        type: "parcoords",
        type: "scattergl",
        type: "scatterpolargl",
        type: "scatter3d",
        type: "splom",
  ```
  
I found precision issues generally with x-values near 1e9. Some of them seem like the integers are being converted to float32s and we're losing precision that way (similar to the scatter3d example from [this comment](https://github.com/plotly/plotly.js/issues/6820#issuecomment-1858396835). But I couldn't find any issues that were M1 Mac specific.

Somewhat surprisingly, splom was not fixed by this change, despite also depending on regl-scatter2d. But I can repro that on Windows, so I guess that's being caused by something else.
 
Can anyone else find M1 mac specific precision issues that aren't fixed by https://github.com/gl-vis/regl-scatter2d/pull/36? If not, I recommend closing this ticket and tracking down the non-platform-specific precision issues in another issue.
