### ISSUE TITLE
Support for SolidJS

### ISSUE THREAD

**Issue by thedanchez** [plotly/plotly.js#6823]
Just wanted to plant this seed as food for thought and was curious if this is something that is on the radar. I feel like it would be cool to have a SolidJS adapter for Plotly (i.e `solid-plotlyjs`) considering how close it resembles React (and potentially mirror `react-plotlyjs`). It is also a much more performant piece of technology by comparison across many metrics.

Would something like this ever be considered as a possibility?

**Comment by alexcjohnson** [comment]
Interesting, thanks for bringing this up! I don't personally have any experience with SolidJS, but the good news is `react-plotly.js` and other related wrappers are generally very stable - you can plug in new versions of plotly.js without needing any updates to the wrapper. So I suspect the best route here would be for you or another community member who actively uses SolidJS to create and publish the wrapper, modeled off `react-plotly.js`, and we would happily promote it among our user community.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
