### ISSUE TITLE
Hover events over trace instead of datapoint

### ISSUE THREAD

**Issue by omrihaber** [plotly/plotly.js#6873]
I would like to be able to highlight traces when the user hover on the trace, i tried to make it work with current implementation and couldn't get it to work unless hover was on a specific datapoint.

Would it be possible to add these hover events?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
