### ISSUE TITLE
hovermode='x-unified' hover info contains data point with a different x-value

### ISSUE THREAD

**Issue by wangxy98** [plotly/plotly.js#6921]
When I used hovermode='x-unified', the hover info displayed the data point with a different x-value like below. Even if I set hoverdistance=1. How do I make the hover info only display the data point with the same x-value. Thanks!
<img width="769" alt="image" src="https://github.com/plotly/plotly.js/assets/50725856/203509e9-fed6-477f-8c46-4122668107a4">

version: 2.26.0

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog; a short reproducible example would be very welcome too. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by floriancargoet** [comment]
I too would like to disable the "closest" mode that comes implicitly with "x unified". 
I only want to show points with the exact x value. Setting hoverdistance to 0 disables the hover entirely.

**Comment by CarinaI** [comment]
I would also like to display only infos about points with the same x value. I use version 3.3.0
