### ISSUE TITLE
Reference line for nominal values

### ISSUE THREAD

**Issue by alon-aviv-ni** [plotly/plotly.js#6934]
Hi all,
I would like to add two traces - one of type 'box' and the other of type 'line'.
Line width is controlled whenever I plot numerical values - simply using the min/ max values to select my lint starting/ ending point.
However, I'm trying to get my line start/ end according to the nominal value I have (e.g., 'T1') so I cannot use x0 and x1 as numerical values.
When trying to set: x0: 'T1' and x1: 'T1' I get a dot and not a line.
Is there a way to set the start/ end point according to the box plot width?
Following an image of what I'd like to achieve - a box plot with two reference lines/ limit lines:

![image](https://github.com/plotly/plotly.js/assets/104836955/2c71b31e-2bf8-4b54-b5c7-84387e0cf175)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
