### ISSUE TITLE
Handle empty data in heatmaps

### ISSUE THREAD

**Issue by Sanjay-Sahu-Bandla** [plotly/plotly.js#6968]
Is there any way to handle the empty data like showing "_No data is available_" when there's no data given for the heatmap

**Example:** 

```js
var data = [
  {
    z: [],
    type: 'heatmap'
  }
];

Plotly.newPlot('myDiv', data);
```

Instead of showing an empty heatmap with x-axis, y-axis lines, it should show a label text like "_No data is available_"

If this feature is not available, it would be great to add such feature.

**Comment by sidharth-05** [comment]
Hi @Sanjay-Sahu-Bandla ! I would love to take on this issue!

**Comment by gvwilson** [comment]
Hi @Sanjay-Sahu-Bandla @sidharth-05 - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review. Thank you - @gvwilson
