### ISSUE TITLE
Shape labels not working anymore - since v2.33.0 

### ISSUE THREAD

**Issue by sean-mcl** [plotly/plotly.js#7013]
Hi,

the shape labels are not working anymore since v2.33.0 (upgraded from v2.32.0).

https://plotly.com/javascript/shapes/#adding-labels-to-shapes 

Expected (v2.32.0)

![image](https://github.com/plotly/plotly.js/assets/64470948/f17dbc56-5c7b-4aa8-879c-384c339c622e)

Actual (v2.33.0)

![image](https://github.com/plotly/plotly.js/assets/64470948/a60cd6c3-d9d4-473d-be34-364f748ac635)

If there is a breaking change, please let me know.

**Comment by emilykl** [comment]
Hi @sean-mcl , thanks for reporting.

The docs example seems to render properly in v2.33.0: https://codepen.io/emilykl-code/pen/MWdRZaP

Could you provide a minimal example demonstrating the issue? I wonder if perhaps something else in the figure definition is interfering with the shape label.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
