### ISSUE TITLE
Change single point color

### ISSUE THREAD

**Issue by AhmedBasem20** [plotly/plotly.js#7022]
Hello,
I'm trying to add custom color for a particular point on a box plot, I used `Plotly.restyle` here https://codepen.io/AhmedBasem20/pen/xxNXoad 
to change the point with value 16 to green for example, but it changes the whole plot color.
I'm not sure if I'm using wrong syntax or there is a different API for this use case.
Thanks.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
