### ISSUE TITLE
Histogram Redraw: replace numeric array with string array breaks redraw function

### ISSUE THREAD

**Issue by scottwittenburg** [plotly/plotly.js#710]
I'm using plotly.js 1.12.0, and in my browser console I type:

```javascript
container = document.querySelector('.plotly-container')
Plotly.newPlot(container, [{type: 'histogram', x: [1,3,1,1,2,3,1]}])
```

this works as expected.  Now, according to the [documentation](https://plot.ly/javascript/plotlyjs-function-reference/#plotly-redraw) I can completely replace the data and then redraw, so I do:

```javascript
container.data = [{type: 'histogram', x:['one', 'two', 'one', 'one']}]
Plotly.redraw(container)
```

Which does not update the plot, but generates the following console error:

```
Error: ax.dtick error: NaN
```

For me, this is happening on Ubuntu 14.04 in both Chrome (51) and Firefox (47).

Perhaps it is expected that if you replace the numeric data values with strings, then `redraw` will not work?

Thank you for maintaining an open source project!

**Comment by etpinard** [comment]
Here's the solution: http://codepen.io/etpinard/pen/Vjbpbz

In brief, plotly.js mutates a few parts of the user data during a `.plot` call in order to skip a few auto-type routines in subsequent plot / restyle / relayout calls.

For example, `layout.xaxis.type` if not set by the user during the first `.plot` call gets filled to its auto-type value. Therefore subsequent `.plot` call won't have to dive into the data arrays to try to figure out what axis type the user is trying to plot.

This user data mutation is confusing, not ideal or even flat-out wrong, but it will stay us until at [`v2.0.0`](https://github.com/plotly/plotly.js/issues/420). So I will close this issue. Our apologies.

**Comment by scottwittenburg** [comment]
No worries, thanks for the workaround!
