### ISSUE TITLE
Studying the evolution of Ploty.js's project

### ISSUE THREAD

**Issue by gustavopinto** [plotly/plotly.js#712]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. Ploty.js was in my list. 

To further analyze the impacts of Ploty.js' migration, we analyzed the git log commit history of your project in terms of _number of contributions_, _number of newcomers_, and _number of contributors per month_. The following figure presents a temporal perspective regarding these three measures. 

![plotly-com-con](https://cloud.githubusercontent.com/assets/235062/16536341/9e7beb02-3fc6-11e6-9e6a-bef5f1b80a06.png)

Given the numbers presented in the graphic, we would like to ask Roslyn developers the following questions:

1. What motivated the project to open its source code at Github? How do you evaluate the benefits of this migration?
2. Does this snapshot make sense? Did you find any inconsistency on the data?
3. Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?
4. Why did the number of active contributors decrease after the project became open-source?
5. Why did the project attracted so few new source code contributors, after its transition to open-source?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by etpinard** [comment]
Hi, thanks for your interest in our project

----

> What motivated the project to open its source code at Github? How do you evaluate the benefits of this migration?

This [post](https://plot.ly/javascript/open-source-announcement/) is probably a good place to start.

> Does this snapshot make sense? Did you find any inconsistency on the data?

For the most part, yes. But, the number of _real_ contributors pre open-source is significantly less than what's shown. Most pre-open-source [contributors](https://github.com/plotly/plotly.js/graphs/contributors) are present only due to merge commits in the plotly private repo that plotly.js used to be a part of.

> Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?

For the most part, we targeted potential contributors (e.g. discovered on twitter) and ask them to team up with us for specific projects.

> Why did the number of active contributors decrease after the project became open-source?

> Why did the project attracted so few new source code contributors, after its transition to open-source?

As mentioned in my answer to question 2, the number of _real_ contributors pre open-source is significantly less than what's shown on your graph. Removing all contributors with merge commits only should tell a different story.

----

I hope this help.

**Comment by gustavopinto** [comment]
Hi @etpinard, if you dont' mind, we have additional questions about the motivations for going open-source.  

For example, was the main motivation of the companies to attract and retain new contributors?  Or was the main motivation perhaps to promote a profile of open-source-friendliness and get goodwill from the community? 

Could you please elaborate a bit over it?

Additionally, were there instances that companies recruited people from the community after they contributed to the (now open-sourced) project? 

Were there discussions between the companies and the community that indicate a communication between them? 

Finally, what are the recommendations for policies to create a sustainable community?

**Comment by etpinard** [comment]
cc @jackparmer @chriddyp @alexcjohnson @bpostlethwaite
