### ISSUE TITLE
Drop support of setting `title` to string (instead of `title.text`) as well as `titlefont` in v3?

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#7177]

**Comment by gvwilson** [comment]
@archmoj what's the background for this one?

**Comment by archmoj** [comment]
When `title` is added in plotly.js it only accepted a string e.g. `title: 'The titlte'`.
Later on more options were needed to control the `title` e.g. `font`.
Therefore `title` could be an object with multiple keys e.g. 
```js
title: {
  text: 'The title',
  font: ...
  ...
}
```
The proposal here is to drop the deprecated form, when `title` is set to a string e.g. `title: 'The titlte'`.

**Comment by alexcjohnson** [comment]
Several years ago we expanded all the `title` attributes from strings to dicts, with the original string moved to the `text` field inside the dict. But we kept it backward compatible, so a figure supplied with a string gets converted to the dict form automatically. This leads to confusion, both because people will see examples done both ways and because anyone using the old one will then inspect their graphs and see something else in them, so it’s probably time to remove this compatibility layer.

**Comment by emilykl** [comment]
@archmoj @gvwilson We should make these changes to `colorbar` as well, correct? I.e. drop support for setting `colorbar.title` to a string, and remove `colorbar.titlefont` and `colorbar.titleside`.

**Comment by gvwilson** [comment]
:+1:

**Comment by archmoj** [comment]
> @archmoj @gvwilson We should make these changes to `colorbar` as well, correct? I.e. drop support for setting `colorbar.title` to a string, and remove `colorbar.titlefont` and `colorbar.titleside`.

It is not only colorbars but also several other components including axes, pie, etc.

**Comment by archmoj** [comment]
@emilykl  You may search for `titlefont` attribute which is deprecated too.
