### ISSUE TITLE
https://cdn.plot.ly/plotly-latest.min.js does not appear to be latest

### ISSUE THREAD

**Issue by TomasHubelbauer** [plotly/plotly.js#7315]
Hi, when I access https://cdn.plot.ly/plotly-latest.min.js, I get this:

```
/**
* plotly.js v1.58.5
* Copyright 2012-2021, Plotly, Inc.
* All rights reserved.
* Licensed under the MIT license
*/
```

According to https://github.com/plotly/plotly.js/releases/latest, I should get this instead:

```
/**
* plotly.js v2.35.3
* Copyright 2012-2024, Plotly, Inc.
* All rights reserved.
* Licensed under the MIT license
*/
```

It appears as though the `-latest` CDN path is maybe bumped manually or it used to work automatically but the automation for it broke at some point.

**Comment by alexcjohnson** [comment]
That's correct, as of v2.0 we are no longer updating `plotly-latest`. It's stuck at the end of v1.x, so that breaking changes in new major versions don't impact users of `plotly-latest`. We considered creating a new bundle that tracks the latest release (`plotly-latest-v2` or some such) but ultimately decided against it on the grounds that it's better to update explicitly so that you get a chance to test the new version.

@archmoj at some point we discussed adding a console warning or some such to `plotly-latest` describing this behavior... @LiamConnors is this documented anywhere else?

**Comment by LiamConnors** [comment]
> [@archmoj](https://github.com/archmoj) at some point we discussed adding a console warning or some such to `plotly-latest` describing this behavior... [@LiamConnors](https://github.com/LiamConnors) is this documented anywhere else?

It's documented in this repo here https://github.com/plotly/plotly.js?tab=readme-ov-file#un-minified-versions-are-also-available-on-cdn

**Comment by TomasHubelbauer** [comment]
Sorry, I didn't look at the repository readme, I just used the latest URL automatically because usually that's all there is to it. I think this issue can be closed, it should at least help with issue search as my issue search previously didn't surface anything relevant. Thank you for clearing this up for me.
