### ISSUE TITLE
Plot running slow when many points are displayed

### ISSUE THREAD

**Issue by ifll** [plotly/plotly.js#741]
I have noticed that the more points you are displaying in a scatterplot the more computing power it requires to interact with the plot, and there could appear some lagging while using plotly...

In my case I have to plot over 50k points in a scatter plot, which makes it necessary not to be so "laggy"...

Is there any solution to increase the performance of the plot?

i have realised that when I hover my cursor over an area from the plot with high point density (lets say 10000 points per cm2) it is more "laggy" than when I hover the mouse in an area with lower point density (100 points per cm2). At the time I am hovering the mouse over there is some information which appears on the "text" field of the marker. Is there any way to fire this option only at the moment that the cursor is steady for "X" seconds instead of always? (I guess that with this solution plotly would run much smoother, as it would only refresh the information when the cursor is steady and not always)

If anyone have any other ideas on how to plot over 50k points in a scatter plot with plotly and make them run smooth please help me.

Thank you

**Comment by etpinard** [comment]
Thanks for writing in.

> In my case I have to plot over 50k points in a scatter plot, which makes it necessary not to be so "laggy"...

Yep. That's an known issue, mainly cause by our svg implementation.

> Is there any solution to increase the performance of the plot?

Use the `scattergl` trace type which is designed for large datasets. See example with 1 million points: http://codepen.io/etpinard/pen/XXrzBe

> Is there any way to fire this option only at the moment that the cursor is steady for "X" seconds instead of always?

You can try different values of the [`HOVERMINTIME`](https://github.com/plotly/plotly.js/blob/ead4bc51f2c7b6ba25d49be36eb6dbe6451d7884/src/plots/cartesian/constants.js#L69) constant we use to determine the delay between calls to the pick-on-hover routine. Note that this constant isn't configurable via the API; you'll have to build your own plotly.js bundle in order to use custom values.

----

@ifll I'm going to close this issue as it is mostly an implementation question. Please use our community [forums](http://community.plot.ly/) for questions of the likes in the future.

**Comment by ifll** [comment]
Thank you very much Etienne! I will try to implement all this to see how it looks like!

sorry for having posted here, I didn't know there was a forum to ask questions about this.

**Comment by ifll** [comment]
Is there the possibility to have "click" events on the "scattergl" plot type?
