### ISSUE TITLE
Minor inconsistency in config

### ISSUE THREAD

**Issue by mdfederici** [plotly/plotly.js#839]
In plotly_config, configs are camel case except for 'displaylogo'. Sorry i'd just fix it but there is a backwards compatibility question you may want to sort out.

**Comment by etpinard** [comment]
Very true. We'll fix all of those in `v2.0.0`.

**Comment by etpinard** [comment]
Thanks for the headsup.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
