### ISSUE TITLE
Spacing between bricks in a heatmap

### ISSUE THREAD

**Issue by CalvinFernandez** [plotly/plotly.js#858]
![image](https://cloud.githubusercontent.com/assets/2644420/17705695/451199c2-63a7-11e6-9754-c95d3668520a.png)

I'm trying to add spaces between bricks in my plotly heatmap to make it look like the above image. The closest workaround I've found to solving this is to implement something like http://codepen.io/etpinard/pen/dMQrKN. Would it be possible to add a `padding` field to the heatmap api that will specify padding for bottom, left, top and right of each heatmap brick?

**Comment by CalvinFernandez** [comment]
( @etpinard / not sure who to ping ) would someone mind taking a look here 

https://github.com/plotly/plotly.js/compare/master...CalvinFernandez:heatmap-padding

**Comment by etpinard** [comment]
@CalvinFernandez great initiative. We've been wanting to add this feature for a while now. :beers: to that!

There a few things we should clear up before making your PR though.

- Is `padding`, with `l`, `t`, `r` and `b` items really necessary? I'm thinking that two attributes: one controlling horizontal padding and another for vertical padding _should be_ enough. Unless you can convince me otherwise.
- a few other minor points that I'll make on your https://github.com/plotly/plotly.js/commit/a508d2882d468433367fd078249eef2567c67a4a commit

**Comment by CalvinFernandez** [comment]
@etpinard 👍 to horizontal and vertical.

**Comment by etpinard** [comment]
> :+1: to horizontal and vertical.

@CalvinFernandez Great. In this case, I would prefer a _flat_ attribute set instead of `padding` container.

plotly.js has alrady a few `gap` attributes like `bargap` and `boxgap` So, I'd vote for `hgap` and `vgap`. But, that might not be verbose enough. @cldougl  what do you think?

**Comment by CalvinFernandez** [comment]
alternatively `xgap` `ygap` is terse and clear?

**Comment by etpinard** [comment]
>  xgap ygap is terse and clear?

+1

**Comment by CalvinFernandez** [comment]
hey, @etpinard I addressed the comments; mind taking another look?

**Comment by etpinard** [comment]
@CalvinFernandez looks great! PR away :rocket: 

One thing though, when you'll make your PR, the image tests fail on CI because your newly added `heatmap_brick_padding.json` mock has no corresponding baseline image. If you're feeling adventurous, you can try generate that baseline image locally using our image-test docker container. See docs [here](https://github.com/plotly/plotly.js/blob/master/test/image/README.md). If you find that too much of a pain, I'll upload the CI artefact to the PR thread.
