### ISSUE TITLE
Data array attributes should support Typed arrays (e.g. Float32Array)

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#860]
http://codepen.io/anon/pen/wWOmNQ

**Comment by monfera** [comment]
@joshua-gould Thanks for your report, iirc @etpinard answered but I don't see it here, just wanted to mention that typed arrays are not yet supported except for `pointcloud` (typed array demo [here](http://codepen.io/monfera/pen/BLjJVZ)). 

However there are plans to introduce this option. The approach isn't to just not fail when a typed array is supplied, but also, to handle things efficiently with typed arrays in mind, at least for plots where performance matters. For this reason there's no imminent plan to map typed arrays into untyped arrays just to make it work, because the API might change somewhat, similar to how `pointcloud` has an `xy` typed array attribute instead of a separate `x` and `y` attribute.

**Comment by etpinard** [comment]
Initial support for typed arrays got added for https://github.com/plotly/plotly.js/pull/2388/

Discussion on JSON-serializable typed array data should continue in https://github.com/plotly/plotly.js/issues/1784
