### ISSUE TITLE
Marker/line opacity unaffected by restyle when fill=toself

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#884]
http://codepen.io/cpsievert/pen/ZOdVOk

**Comment by rreusser** [comment]
Not fixed by the big changes in animations: http://codepen.io/rsreusser/pen/ozNkEv

**Comment by rreusser** [comment]
Seems like perhaps an issue with `restyle` figuring out what needs to update, in which case this shouldn't be affected by the animation PR.

**Comment by etpinard** [comment]
After some investigation:

- this issue has nothing to do with `toself`, all `fill` values behave the same
- I believe this is the desired behavior. Trace `opacity` does not impact `fillcolor`. See the current logic `fillcolor` default logic [here](https://github.com/plotly/plotly.js/blob/f07a274fe7c215c06d3827f2a589f17421f72ce1/src/traces/scatter/fillcolor_defaults.js#L32-L36).

In brief, `fillcolor` defaults to:

- `line.color` with 0.5 alpha channel, 
- if `line.color` isn't set, `marker.color` with 0.5 alpha channel, 
-  if `line.color` and `marker.color` aren't set, `marker.line.color` with 0.5 alpha channel,
-  if `line.color`, `marker.color` and `marker.line.color` aren't set, the default trace color with 0.5 alpha channel.

But, as discussed with @cpsievert , trace opacity should really impact the fill color. The fact that plotly.js doesn't do that at the moment is a design flaw - that unfortunately cannot be easily fixed in a backward-compatible way. 

We should consider making `opacity` impact  fill color in the `v2.0.0` release. Changing the issue title accordingly.

**Comment by etpinard** [comment]
Oops. I didn't read the issue title correctly. 

There is in fact a bug [here](https://github.com/plotly/plotly.js/blob/f07a274fe7c215c06d3827f2a589f17421f72ce1/src/traces/scatter/clean_data.js#L25) - where we explicitly remove trace opacity from traces that have a non-`none` fill value to avoid edge-case inconsistencies. Please refer to this 2015 [issue](https://github.com/plotly/streambed/issues/1369) for the details.

But, the aforementioned inconsistency does not apply to `toself` traces. Fix is coming up.

**Comment by tsando** [comment]
Sorry, I was a bit lost by the thread comments and links but is there a workaround or fix for this yet? I wan to make the opacity apply to the fill area color. Is there any way to do this using `toself`? Thanks.
