### ISSUE TITLE
Purged gd still passes Lib.isPlotDiv

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#908]
If `gd` was ever a plot, then `Lib.isPlotDiv(Plotly.purge(gd)) === true` still passes. The solution would be for `Plotly.purge()` to remove the `js-plotly-plot` class added [here](https://github.com/plotly/plotly.js/blob/master/src/lib/index.js#L388).

The conclusion at the moment is not to fix this with a breaking change, but it seems to be a bug nonetheless.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
