### ISSUE TITLE
Add option to not leave gaps in grouped bar chart

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#930]
See http://community.plot.ly/t/grouped-bar-chart-leaves-gap-when-a-trace-has-missing-element-for-a-one-or-more-xaxis-tick/2078 for more context info.

Maybe we should add a new `barmode` e.g. `'grouped-no-gaps'` ?

**Comment by yniknafs** [comment]
+1

**Comment by yniknafs** [comment]
![screen shot 2018-04-10 at 12 41 11 pm](https://user-images.githubusercontent.com/7563948/38570709-8035f3c8-3cbc-11e8-985f-1d5167f7e2d1.png)

**Comment by dogrultan** [comment]
Any updates on this issue?

Thanks and have a nice day.

**Comment by sourcecode369** [comment]
Please fix this issue.

**Comment by Numeri** [comment]
I'd also love a new mode for this!

**Comment by Braintelligence** [comment]
If anyone found a solution to ignore bars with empty values so they don't group invisibly it would be cool to share.

**Comment by Braintelligence** [comment]
Sorry for necroing this a bit but I'm still looking for a solution here. Did anyone find one in the meantime?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
