### ISSUE TITLE
Animate trace entrance/exit

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#932]
[This stackoverflow question](http://stackoverflow.com/questions/39415791/using-plotly-js-animation-feature/39457872) makes it clear that people may expect `Plotly.animate` to animate the _entrance_ of traces. It wasn't the focus, so right now it only animates _existing_ traces. I think it's a reasonable thing people will definitely expect though, so opening this for discussion as a feature request.

See also: possible connection to #920 regarding entrance/exit of traces.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
