### ISSUE TITLE
customize notifier

### ISSUE THREAD

**Issue by markbrown4** [plotly/plotly.js#939]
Can't see a way to customize / monkey patch the notifier.

Apps often have their own notification style and it would be nice to be able to patch the notifier to use something else like https://github.com/CodeSeven/toastr as an example.

A config option that passes a `style`(info / error), `message` and `delay` would be ideal.

``` js
notifier: (style, message, delay) {
  toastr[style](message);
}
```

**Comment by etpinard** [comment]
That would be nice. But it won't be a priority for us in the foreseeable future.

Feel free the sent a PR our way.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
