### ISSUE TITLE
Color mapping discontinuity in `surface` surfacecolor

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#940]
See http://codepen.io/etpinard/pen/xEVOwZ 

where odd looking line appear on the surface e.g.

![image](https://cloud.githubusercontent.com/assets/6675409/18518411/e0178c2e-7a6d-11e6-90f0-4a46379fbd9e.png)

I believe this issue is related to how [`colormap`](https://github.com/bpostlethwaite/colormap) is handling custom colorscale. The `colormap` package is a dependency of the [`gl-surface3d`](https://github.com/gl-vis/gl-surface3d) gl-vis module.

**Comment by etpinard** [comment]
@dfcreative would you be interested in looking into this?

**Comment by dfcreative** [comment]
@etpinard ok, sure

**Comment by rreusser** [comment]
Interesting. I've been wondering about how to do complex colormaps and ruled out this approach because of this artifact. Presumably it's because the argument loops around from 359˚ back to 0˚. My only thought is that, given two arguments `θ1` and `θ2`, to interpolate between `θ1` and `θ2 + n * 360˚`, for whatever `n` minimizes `|θ1 - θ2 + n * 360˚|`. That way it will be smart enough to know that 359˚ -> 0˚ is a small change, not a large change.

**Comment by rreusser** [comment]
In thinking about it though, this might need to be a configuration option. Sometimes you might really just want to capture the whole colormap range between two adjacent points…

**Comment by dfcreative** [comment]
If I get it right, the function has discontinuity in the place of "lines", in terms of linear space:
![image](https://cloud.githubusercontent.com/assets/300067/18527183/931e832c-7a91-11e6-81e8-d62a581466ca.png)
Not sure what exactly happens in `gl-surface3d`, but it seems to build verteces based on passed samples, connecting all the values by verteces. Therefore some verteces connect the opposite sides of that discontinuous "jump", which is a proper behaviour (low-res):
![image](https://cloud.githubusercontent.com/assets/300067/18527022/018da3f2-7a91-11e6-9705-dffffa7bdceb.png)
Possible solution to that would be make verteces avoid discontinuities, how exactly make it - oh.

**Comment by rreusser** [comment]
Sorry to stick my nose in, but I've been trying to get a better handler on shaders. Yeah, I get it now. The definition of vertex vs fragment shaders means there's really no way to handle this. The fragment shader would need to know about the pre-interpolated values, which, unless I'm wrong, it just doesn't.

[Here's an example](http://stackoverflow.com/questions/25434419/glsl-custom-no-interpolation-of-triangles-with-vertex-colors/25508724#25508724) that uses a geometry shader to accomplish something like this and pass the values at each vertex to the fragment shader. That would make it possible to detect and fix this case in the shader, except… geometry shaders.

So yeah, seems like a feature and not a bug that the colormap is applied in the fragment shader itself.

**Comment by rreusser** [comment]
Again, pardon my interest… last thing: Moved the colormap eval to the vertex shader instead. Works perfectly, but in general colors are then interpolated and don't necessary lie on the color wheel itself, depending on the density of the points. But does work… pretty difficult to have cake and eat it too though…

<img width="560" alt="2016-09-14 18 30 49" src="https://cloud.githubusercontent.com/assets/572717/18551943/9510c9dc-7b28-11e6-9473-79b5fac39776.png">

**Comment by dfcreative** [comment]
@rreusser oh, that is nice solution, all we have just to pick color in vertex shader indeed.
![image](https://cloud.githubusercontent.com/assets/300067/18593932/9f0602c0-7c0b-11e6-90e0-344d5393001b.png)

I’ll make a PR to gl-surface3d

**Comment by rreusser** [comment]
The only downside is that it might not always be desired. Like you might want a single quad to span the whole colormap gamut. With evaluation in the fragment shader you get a whole rainbow. With evaluation in the vertex shader, you get a single flat color (red at both ends?).

It might be reasonable to create a switch to opt for one or the other since short of some wild shader trickery, I don't think the choice can be avoided. I don't love the idea of low-level switches, but I just don't know how else to handle a colormap on a variable that repeats.

It feels almost like a [hairy ball theorem](https://en.wikipedia.org/wiki/Hairy_ball_theorem) sort of conundrum…

**Comment by dfcreative** [comment]
Ok I’ve made a [PR](https://github.com/gl-vis/gl-surface3d/pull/8) with mode switch.

**Comment by etpinard** [comment]
@dfcreative 

TODO:

- [ ] bump and `npm publish` gl-surface3d (you might need @mikolalysenko to get you publish rights for that)
- [ ]  resolve this comment: https://github.com/gl-vis/gl-surface3d/pull/8#r79242061
- [ ] add logic to [`src/traces/surface/convert.js`](https://github.com/plotly/plotly.js/blob/master/src/traces/surface/convert.js)
- [ ] add image test mock and baseline in [`test/image/`](https://github.com/plotly/plotly.js/tree/master/test/image)

**Comment by rreusser** [comment]
Not for this since it's complex-aware and so is a bigger project, but I made a glslify shader, [glsl-domain-coloring](https://github.com/rreusser/glsl-domain-coloring) that tries to really do complex colormaps the right way:

![unknown](https://cloud.githubusercontent.com/assets/572717/18654813/07309d58-7eb2-11e6-9cea-cad6b70a0de1.jpeg)
