### ISSUE TITLE
Lint with standardjs

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#950]
The [standard](https://github.com/feross/standard) set of linting rules are becoming the standard :laughing: for open-source JS libraries. 

We should follow suit.

**Comment by rreusser** [comment]
Strong choice! See also: [standard-format](https://github.com/maxogden/standard-format)

**Comment by etpinard** [comment]
I believe plotly.js should remain a ES5-only repository for the foreseeable future. I also believe that `npm run lint` should catch all non-ES5 slip-ups.

Eslint is configured with ES5-only parser by default ([ref](http://eslint.org/docs/user-guide/configuring#specifying-parser-options)), but standard now uses an ES8 parser :astonished:  ([ref](https://github.com/feross/eslint-config-standard/blob/85872703713090cd84bc80f3b6d2076cc5769ed0/eslintrc.json#L3)) meaning that running the stock `standard` in plotly.js will not catch non-ES5 tokens.

So, I propose using [`standard-own`](https://github.com/o2team/standard-own) which uses that same [engine](https://github.com/flet/standard-engine) as standard but allows uses to specify which ECMA script to parse. I think adding:

```json
{
  "standard-own": {
    "eslintConfig":  {
       "parserOptions": {
          "ecmaVersion": 5
        }
     }
  }
}
```

to the package.json should do the trick.

Alternatively, we could publish an es5 version of [`eslint-config-standard`](https://github.com/feross/eslint-config-standard) and use that?

**Comment by rreusser** [comment]
Interesting. Agreed on keeping it ES5 for the sake of consistency. (though [es2020](https://github.com/yoshuawuyts/es2020) hits the nail on the head, IMO.)

Related discussion: https://github.com/feross/standard/issues/159

**Comment by rreusser** [comment]
Though I'm mostly trying to understand the consequences of the parser vs. the set of rules and what that means for simply enforcing style.

**Comment by rreusser** [comment]
Testing out `./node_modules/.bin/standard --fix` now, just to watch things burn…

**Comment by etpinard** [comment]
To enforce ES5, we could use [`use-es5-only`](https://github.com/azu/use-es5-only) which simply errors out when trying to parse non-es5 tokens (w/o listing detail about the error) or try to write something better using [`esutils`](https://www.npmjs.com/package/esutils#keyword) to provide better info about the non-ES5 token found.

**Comment by rreusser** [comment]
Ah, looks like that maybe just sets the parser version of eslint. Separate steps seem nice since they're two different things, but if it's really as simple as setting the parser version, maybe it's not worthwhile to separate it.

**Comment by etpinard** [comment]
> Ah, looks like that maybe just sets the parser version of eslint.

As far as I know, I don't think one can set the parser version within `standard`.

**Comment by alexcjohnson** [comment]
FWIW @etpinard and I had a slack chat about styles a few weeks ago... we talked about how I'm freaked out by the restrictions imposed by no `;`, how there are things like [semistandard](https://github.com/Flet/semistandard) but it doesn't have much traction, etc etc... it concluded with me saying:

> I could still be convinced to go with standard if someone can convince me it really is becoming the standard throughout the js dev community… until then I feel like we should stick with what we have.

So let me generalize that statement: if we change styles, it had better be because the community is truly coalescing around a style AND we're convinced it's going to last many years that way. My gut reaction is that we shouldn't switch styles at all unless and until we move to ES6+ (but please don't open that can of worms here!)

Also for the record I completely agree with the outcome of #1629 - while enforcing completely automated style has its advantages, if it stops you from doing things that - rules be damned - make your code more readable (extra parens, d3 half-indents, etc etc) - then it's going too far.

And of course @rreusser 's https://github.com/plotly/plotly.js/pull/1629#discussion_r113708332 is spot on:
> The golden rule of conventions: Convention `<insert convention you use here>` is aesthetically superior to `<insert proposed alteration here>`. 😉

So there's really no point arguing about what's superior on the merits. Unless you can start the discussion with "all the major active projects (in ES5) are using this style so it'll be easier for new people to adapt to our project," lets leave our style as it is now.

**Comment by monfera** [comment]
Entering the room, realizing that I missed the bikeshedding :-) Please therefore ignore my self-healing attempt :-) 

I started liking no-semicolons with ES2015, as its streamlined syntax made the semicolons stick out, [indeed](https://bytearcher.com/articles/plea-for-semicolons/#comment-2410069459) it's subjective. I admittedly haven't considered majority share due to switching back and forth anyway eg. between plotly.js and [gl-vis](https://github.com/gl-vis). Looks like standard.js is the [most starred](https://github.com/showcases/clean-code-linters) style but semi still leads in large libs. Maybe everybody is waiting for some other large libs to switch 😆 

The sample list is [neat](https://github.com/feross/standard#who-uses-javascript-standard-style) and there are non-standardjs libs which omit semis eg. [regl](https://github.com/regl-project/regl/blob/gh-pages/regl.js) or [bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/button.js). Standard.js announced recently to audacity/ridicule, and revisiting now, I'm impressed to see a lot of [libraries](https://raw.githubusercontent.com/feross/standard-packages/master/all.json), `react-`: 322, or `react-`: 94 hits. It looks grassroots, and FB/React itself hasn't tipped over, though they just tipped over to `rollup` which was only used by D3 4.0 a short while ago. Subjective choices have more inertia than objectively better stuff :-)

A couple times I've run into a superficial and immediately obvious issue with an iife in ES5. With ES2015 there's hardly ever a need for an iife because of the block scoping of `let`/`const` that replace basically all `var`s. We avoid iife-s even with ES5 but if there's _still_ a need I don't mind the preceding semi as it's also a warning sign (yeah Stockholm syndrome).

Re the `D3` indentation convention, I used it when learning D3 but my editor kept destroying it, and I found it confusing to maintain . So I don't _fluent_ down levels, just [assign a variable](https://github.com/plotly/plotly.js/blob/master/src/traces/parcoords/parcoords.js#L610-L621) to new scenegraph levels, it'll be compact uglified, but much easier to add a new 'enter'/'update'/'exit'/'filter'/'transition' without accidentally breaking a long chain. It adds maintainability with the large scenegraphs we have but a tad longer.

**Comment by monfera** [comment]
To add an example for overbearing format rules, we already have some constraints that feel a bit arbitrary, compare this, what I think would be nice but not allowed:
```
    var missing = function(n, i) {
        return traceIn.link.source.indexOf(i) === -1 
            && traceIn.link.target.indexOf(i) === -1;
    };
```
with this, as allowed by our current linter:
```
    var missing = function(n, i) {
        return traceIn.link.source.indexOf(i) === -1 &&
            traceIn.link.target.indexOf(i) === -1;
    };
```
Aside from nice vertical alignment, I like important things to not be at the line end if they can be at the beginning, as it shows intent and structure faster. I know most shops put their ternary operators to the end like this, and we have no intention to revisit it:
```
    tinycolor(layout.paper_bgcolor).getLuminance() < 0.333 ?
        'rgba(255, 255, 255, 0.6)' :
        'rgba(0, 0, 0, 0.2)';
```
but this shows the ternary nature more directly:
```
    tinycolor(layout.paper_bgcolor).getLuminance() < 0.333
        ? 'rgba(255, 255, 255, 0.6)'
        : 'rgba(0, 0, 0, 0.2)';
```

**Comment by rreusser** [comment]
Have to agree with @alexcjohnson. I still prefer some of the standard/semistandard conventions, but short of something drastic like prettier that I think does have merits beyond the aesthetic, I think bikeshedding is best avoided, especially if it involves hundreds of manual variable declaration reworkings just to get it off the ground.

**Comment by etpinard** [comment]
`eslint@4` is out: http://eslint.org/docs/user-guide/migrating-to-4.0.0

Note the changes to the indent rule. Running `eslint .` with `v4` from the root of `plotly.js/` spits out more than 4000 errors and unfortunately `eslint --fix .` doesn't do a great job fixing our code base.

**Comment by rreusser** [comment]
Could just disabled…

> To address: We recommend upgrading without changing your indent configuration, and fixing any new indentation errors that appear in your codebase. However, if you want to mimic how the indent rule worked in 3.x, you can update your configuration:

```json
{
  rules: {
    indent: "off",
    "indent-legacy": "error" // replace this with your previous `indent` configuration
  }
}
```

**Comment by etpinard** [comment]
Probably won't happen anytime soon, closing.
