### ISSUE TITLE
data text position is not refreshed on zoom or pan

### ISSUE THREAD

**Issue by Matz13** [plotly/plotly.js#952]
Hi all,
I was toying around with the layouts and different display options and found this issue.
When I display text over a marker, it works properly, but whenever I zoom or pan, the text doesn't move.

An example here: http://codepen.io/anon/pen/zKoKag

Keep up the good work!

**Comment by etpinard** [comment]
Thanks very much for the report.

This bug was introduced in `1.17.0` - most likely in https://github.com/plotly/plotly.js/pull/802

cc @rreusser

**Comment by rreusser** [comment]
I don't think there's a fundamentally complicated technical problem here, but the best-case scenario would be to work through regressions like this by adding the proper easing and transitions as we go so that animations and element persistence work their way into more corners of plotly.js. That said, getting it fixed is obviously the top priority.
