### ISSUE TITLE
Strange behavior with missing values in scattergeo 

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#963]
http://codepen.io/cpsievert/pen/ZpLbxJ

I discovered this problem when using scatter to make a map of canada:

![screen shot 2016-09-21 at 7 28 16 pm](https://cloud.githubusercontent.com/assets/1365941/18733590/e72be1c6-8031-11e6-9274-e4c89fd6b592.png)

Supplying the same data to scattergeo gives me this:

![screen shot 2016-09-21 at 7 29 26 pm](https://cloud.githubusercontent.com/assets/1365941/18733597/f837a914-8031-11e6-8275-e1c810befd96.png)

Thus, it seems like [0, 0] is being inserted before (or possibly after) `null`?

**Comment by cpsievert** [comment]
Also, this seems to work fine with scattermapbox

**Comment by etpinard** [comment]
I changed my mind. Instead of simply making sure that non-numeric values are skipped in `scattergeo` traces (as in https://github.com/plotly/plotly.js/pull/964), I'll refactor combine some of the `scattermapbox` logic into `scattergeo` should make it easy to add `connectgaps` to and `fill: 'toself'` support to `scattergeo` traces - and maybe also hover text for `scattergeo` lines in 1.18.0.
