### ISSUE TITLE
The annotation arrow isn't rendered properly on load

### ISSUE THREAD

**Issue by fresheneesz** [plotly/plotly.js#992]
Annotations seem to be missing the arrow head when the graph is first rendered. Strangely, once I either change the zoom, or click on one of the axes, the arrowhead changes to the correct display.

Here's what it looks like onload:
![plotly annotation bug](https://cloud.githubusercontent.com/assets/149531/18947570/860580f2-85e8-11e6-9d8a-05e18844bdbd.png)

This is what it looks like after doing one of those actions I mentioned:
![plotly annotation bug correct](https://cloud.githubusercontent.com/assets/149531/18947574/8763db56-85e8-11e6-9435-b03bcf3aaba2.png)

**Comment by etpinard** [comment]
Yikes.

Can you share a reproducible example via codepen / jsFiddle /jsBin to help us debug? Thanks.

**Comment by fresheneesz** [comment]
Here you go: http://codepen.io/anon/pen/XjakQy

**Comment by etpinard** [comment]
Strange. If the graph `div` is appended to the DOM before calling `Plotly.newPlot`, the arrow head is coloured properly as in http://codepen.io/etpinard/pen/vXajVP

**Comment by etpinard** [comment]
Also to not, http://codepen.io/anon/pen/XjakQy works perfectly fine in FF 49.

The bug persists in `Google Chrome 53.0.2785.143`.

**Comment by alexcjohnson** [comment]
Ha crazy - you can't call `d3.select(node).style('stroke-width')` or any other attribute for that matter before the element is part of the DOM. I guess it makes sense that d3 can't call `getComputedStyle` in this case (though apparently FF and Chrome disagree on whether it makes sense) even though `node.style['stroke-width']` is available. Oh well, it was only a shortcut to read styles back anyway rather than just pass the style info in from above.
