### ISSUE TITLE
scattergl can't resolve date with sub-minute precision

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#995]
See http://codepen.io/etpinard/pen/ORjbkR

Probably because time stamps that long can't fit on the GPU. We'll probably have to rescale to data arrays about the xy axis range.

**Comment by monfera** [comment]
@etpinard I see sub-minute precision (in this case, seconds) on both versions in the codepen example:
![image](https://cloud.githubusercontent.com/assets/1548516/19065242/b9d49c14-8a12-11e6-8828-4a709ca0b826.png)

**Comment by etpinard** [comment]
This is what I'm seeing

![image](https://cloud.githubusercontent.com/assets/6675409/19138795/4563f866-8b4d-11e6-9d9c-4376c0bb913a.png)

The top figure (which is a `scattergl` trace) has no drawn marker points.

**Comment by monfera** [comment]
Indeed, I initially misinterpreted it as a tick label rendering issue.

**Comment by monfera** [comment]
@jackparmer a question for you at the end: having a PR for https://github.com/plotly/plotly.js/issues/413, we now have a PoC solution for this issue. The root cause was that the data path from the `plotly.js` through `gl-vis` to the GPU is of a 32 bit resolution, and

`new Date('2016-10-10').valueOf()` i.e. time from the epoch as an integral multiple of milliseconds is much larger than `Math.pow(2, 24)`

I broadened the pipeline to 64 bits up till the (32-bit) `WebGL` renderer, where an offset is introduced. This works well for arbitrary start dates (e.g. in 2016) as long as the span of time domain is not too long, for example, 10/29/2016 to 10/30/2016 can be represented with very fine resolution. But the current PoC can't cover e.g. 2016 ... 2026 with a _fine_ temporal resolution, as we still have a 32 bit (actually 24 bit) representation. Examples:

- At an exact `millisecond` resolution, this covers 4.66 hours `(2 ** 24) / 1000 / 3600`
- At a `second` resolution, this covers half a year (*)
- At a `minute` resolution, this covers 32 years (*)

_(*) with the last two examples, there's some dithering - eg. at the `second` resolution, maybe we don't get an exact `10/10/2016 21:58:47` but more like `10/10/2016 21:58:47.23429` - which may not matter in practice if values are shown with precision that's limited to `second` (I don't think we automatically have such resolution-aware truncation though)._

This 32 bit resolution limit is *native to* WebGL. With more work, it'd be possible to pass on two 32 bit arrays and combine them in the vertex shader. It slows down the vertex shader a bit, though it's very unlikely to be a bottleneck.

I'd add that this resolution limitation isn't inherent to dates/times. It applies for plain numbers as well.

What do we know about the expected combination of the span of time domain *and* the expected temporal resolution, should we shoot for a software based 64 bit solution in the shader or let's get feedback first?

**Comment by monfera** [comment]
Example: millisecond resolution over one second
![image](https://cloud.githubusercontent.com/assets/1548516/19328209/e217ad44-90d2-11e6-85db-9de3e42d69e8.png)

**Comment by etpinard** [comment]
Slightly unrelated, but looking at the above screenshot, we should try to address gl2d date axis ticks formatting as discussed [here](https://github.com/plotly/plotly.js/blob/f7a8afa3eb122755e4497581bb11faf772465c71/src/plots/gl2d/scene2d.js#L242-L243).

**Comment by monfera** [comment]
@etpinard @jackparmer doubling the available WebGL precision has worked out, giving us a millisecond-level resolution even over years or millennia: https://github.com/gl-vis/gl-scatter2d/pull/1

Besides adding test cases, the other WebGL renderer needs to be refactored as well (`scatter2d-fancy`).

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/issues/1079
